image: pc218:5000/debpack

variables:
  PKG_REPO: 'linacgui_deb'
  PKG_REPO_URL: 'https://git.cells.es/ctpkg/$PKG_REPO'

# Is performed before the scripts in the stages step
before_script: 
  # just for debugging the artifacts
  - cd /packaging
  - rm -rf /packaging/linacgui_deb
  - git clone https://git.cells.es/ctpkg/linacgui_deb 
  - cd linacgui_deb
  - git checkout upstream && git checkout pristine-tar && git checkout master

# Defines stages which are to be executed
stages:  
  - build
  - test
  - deploy

# Stage "build"
run-build:  
  stage: build
  script:
    - gbp import-orig --uscan --merge-mode=replace --pristine-tar --no-interactive --postimport='gbp dch -N$GBP_UPSTREAM_VERSION-0~bpo9+0~alba+1 -R -c --debian-branch=$GBP_BRANCH --spawn-editor=never'
    - cat debian/changelog
    - cowbuilder --update
    - gbp buildpackage
    # just for debugging the artifacts
    - pwd
    - ls
    - ls /packaging/
    - ls ..
    - ls ../build-area/
    - /packaging/build-area/

  # This stage is only executed for new tags
  only:
    - tags

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - /packaging/build-area/*

# lintian: 
#  stage: test
#  script:
#    - TODO
#    
#piuparts: 
#  stage: test
#  script:
#    - TODO
#    
#dput:
#  stage: deploy
#  script:
#   - TODO
