image: localhost:5000/debpack:ci

variables:
  PKG_REPO: 'linacgui_deb'
  PKG_REPO_URL: 'https://git.cells.es/ctpkg/$PKG_REPO'
  
# Is performed before the scripts in the stages step
before_script:  
  - build_chroot

# Defines stages which are to be executed
stages:  
  - build
  - test
  - deploy

# Stage "build"
run-build:  
  stage: build
  script:
    - mkdir artifacts
    - cd /packaging
    - git clone $PKG_REPO_URL 
    - cd $PKG_REPO
    - git checkout upstream && git checkout pristine-tar && git checkout master
    - gbp import-orig --uscan --merge-mode=replace --no-interactive --pristin-tar
    - cat debian/changelog
    - gbp buildpackage --git-export-dir=$CI_PROJECT_DIR/artifacts/
    # list the artifacts dir
    - ls -la $CI_PROJECT_DIR/artifacts/

  # This stage is only executed for new tags
  only:
    - tags

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - artifacts/*

lintian: 
  stage: test
  script:
    - lintian -i -I --suppress-tags-from-file=/root/lintian-tags.txt artifacts/*.changes
  allow_failure: true
  only:
    - tags
    
piuparts: 
  stage: test
  script:
    - piuparts -d stretch -m http://httpredir.debian.org/debian --extra-repo 'deb [ trusted=yes ] http://controls01.cells.es/testrepo debian9/' artifacts/*.changes
  allow_failure: true
  only:
    - tags
    
deploy_to_staging:
  stage: deploy
  script:
    - echo 'TODO this would call dput to the staging repo with appropriate credentials'
    - ls artifacts/*
  only:
    - tags
    
deploy_to_production:
  stage: deploy
  script:
    - echo 'TODO This would call dput to the production repo with appropriate credentials'
    - echo 'TODO This would push the local git repo to $PKG_REPO_URL'
  when: manual
  only:
    - tags