image: pc218:5000/debpack

variables:
  PKG_REPO: 'linacgui_deb'
  PKG_REPO_URL: 'https://git.cells.es/ctpkg/$PKG_REPO'

# Is performed before the scripts in the stages step
before_script: 
  - cd /packaging
  - git clone $PKG_REPO_URL 
  - cd $PKG_REPO
  - git checkout upstream && git checkout pristine-tar && git checkout master

# Defines stages which are to be executed
stages:  
  - build
  - test
  - deploy

# Stage "build"
run-build:  
  stage: build
  script:
    - gbp import-orig --uscan --merge-mode=replace --pristine-tar --no-interactive --postimport='gbp dch -N$GBP_UPSTREAM_VERSION-0~bpo9+0~alba+1 -R -c --debian-branch=$GBP_BRANCH --spawn-editor=never'
    - cat debian/changelog
    - cowbuilder --update
    - gbp buildpackage --git-postbuild='echo BUILD FINISHED:$GBP_CHANGES_FILE; export PKG_CHANGES_FILE=$GBP_CHANGES_FILE' # do not run checks now
    # just for debugging the artifacts
    - pwd
    - ls
    - ls /packaging/
    - ls ..
    - ls ../build-area/
    - ls /packaging/build-area/

  # This stage is only executed for new tags
  only:
    - tags

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - /packaging/build-area/*

lintian: 
  stage: test
  script:
    - lintian -i -I 
    
piuparts: 
  stage: test
  script:
    - piuparts -d stretch -m http://httpredir.debian.org/debian --extra-repo 'deb [ trusted=yes ] http://controls01.cells.es/testrepo debian9/' $PKG_CHANGES_FILE
    
dput:
  stage: deploy
  script:
    - echo 'TODO: this would call dput to the staging repo with appropriate credentials'

deploy_to_production:
  stage: deploy
  script:
    - echo 'TODO: This would call dput to the production repo with appropriate credentials'
  when: manual
