# Is performed before the scripts in the stages step
before_script:  
  - cd /packaging
  - rm -rf /packaging/linacgui_deb
  - git clone https://git.cells.es/ctpkg/linacgui_deb 
  - cd linacgui_deb
  - git checkout upstream && git checkout pristine-tar && git checkout master

# Defines stages which are to be executed
stages:  
  - build

# Stage "build"
run-build:  
  stage: build
  script:
    - gbp import-orig --uscan \
      --merge-mode=replace \
      --pristine-tar \
      --no-interactive\
      --postimport='gbp dch -N$GBP_UPSTREAM_VERSION-0~bpo9+0~alba+1 -S --debian-branch=$GBP_BRANCH --no-interactive'
    - cat debian/changelog
    - git status

  # This stage is only executed for new tags
  only:
    - tags

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*
