image: pc218:5000/debpack

variables:
  PKG_REPO: 'linacgui_deb'
  PKG_REPO_URL: 'https://git.cells.es/ctpkg/$PKG_REPO'

# Defines stages which are to be executed
stages:  
  - build
  - test
  - deploy


debugging1:  
  stage: build
  script:
    - echo 'foo' > /tmp/kk
    - cat /tmp/kk
    - KK=$(cat /tmp/kk) 
    - echo $KK
    - cp /tmp/kk kk2
    - cat kk2
    - ls kk2
  artifacts:
    paths:
      - /tmp/kk
      - kk2
  

debugging2:  
  stage: test
  script:
    - echo $KK
    - cat /tmp/kk
    

# Stage "build"
run-build:  
  stage: build
  script:
    - cd /packaging
    - git clone $PKG_REPO_URL 
    - cd $PKG_REPO
    - git checkout upstream && git checkout pristine-tar && git checkout master
    - gbp import-orig --uscan --merge-mode=replace --pristine-tar --no-interactive --postimport='gbp dch -N$GBP_UPSTREAM_VERSION-0~bpo9+0~alba+1 -R -c --debian-branch=$GBP_BRANCH --spawn-editor=never'
    - cat debian/changelog
    - cowbuilder --update
    - gbp buildpackage --git-postbuild='echo $GBP_CHANGES_FILE > /tmp/GBP_CHANGES_FILE' # do not run checks now
    # just for debugging the artifacts
    - cat /tmp/GBP_CHANGES_FILE
    - PKG_CHANGES_FILE=$(cat /tmp/GBP_CHANGES_FILE) 
    - echo $PKG_CHANGES_FILE
    - pwd
    - ls
    - ls /packaging/
    - ls ..
    - ls ../build-area/
    - ls /packaging/build-area/

  # This stage is only executed for new tags
  only:
    - tags

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - /packaging/build-area/*

lintian: 
  stage: test
  script:
    - lintian -i -I $PKG_CHANGES_FILE
  allow_failure: true
  only:
    - tags
    
piuparts: 
  stage: test
  script:
    - piuparts -d stretch -m http://httpredir.debian.org/debian --extra-repo 'deb [ trusted=yes ] http://controls01.cells.es/testrepo debian9/' $PKG_CHANGES_FILE
  allow_failure: true
  only:
    - tags
    
deploy_to_staging:
  stage: deploy
  script:
    - echo 'TODO this would call dput to the staging repo with appropriate credentials'
  only:
    - tags
    
deploy_to_production:
  stage: deploy
  script:
    - echo 'TODO This would call dput to the production repo with appropriate credentials'
    - echo 'TODO This would push the local git repo to $PKG_REPO_URL'
  when: manual
  only:
    - tags