all: communication startup mainscreen

communication:
	echo -n "N\n" | taurusuic4 -x linacOverview.ui -o ui_linacOverview.py ; echo -n "\n"
	echo -n "N\n" | taurusuic4 -x linacPlcWidget.ui -o ui_linacPlcWidget.py ; echo -n "\n"

startup:
	echo -n "N\n" | taurusuic4 -x linacStartupSynoptic.ui -o ui_linacStartupSynoptic.py ; echo -n "\n"
	echo -n "N\n" | taurusuic4 -x coolingLoop.ui -o ui_coolingLoop.py ; echo -n "\n"
	echo -n "N\n" | taurusuic4 -x eGunLV.ui -o ui_eGunLV.py ; echo -n "\n"
	echo -n "N\n" | taurusuic4 -x klystron1ictk.ui -o ui_klystron1ictk.py ; echo -n "\n"
	echo -n "N\n" | taurusuic4 -x klystron2ictk.ui -o ui_lystron2ictk.py ; echo -n "\n"
	echo -n "N\n" | taurusuic4 -x klystronLV.ui -o ui_klystronLV.py ; echo -n "\n"

mainscreen:
	echo -n "N\n" | taurusuic4 -x linacMainscreenSynoptic.ui -o ui_linacMainscreenSynoptic.py ; echo -n "\n"
	echo -n "N\n" | taurusuic4 -x klystronHV.ui -o ui_klystronHV.py ; echo -n "\n"
	echo -n "N\n" | taurusuic4 -x attenuator.ui -o ui_attenuator.py ; echo -n "\n"
	echo -n "N\n" | taurusuic4 -x phaseShifter.ui -o ui_phaseShifter.py ; echo -n "\n"
	echo -n "N\n" | taurusuic4 -x magnet.ui -o ui_magnet.py ; echo -n "\n"
	echo -n "N\n" | taurusuic4 -x eGunHV.ui -o ui_eGunHV.py ; echo -n "\n"
