# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/klystronHV.ui'
#
# Created: Thu Feb 27 15:23:33 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_klystronHV(object):
    def setupUi(self, klystronHV):
        klystronHV.setObjectName(_fromUtf8("klystronHV"))
        klystronHV.resize(170, 240)
        self.gridLayout = QtGui.QGridLayout(klystronHV)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.highVoltageGroup = TaurusGroupBox(klystronHV)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.highVoltageGroup.setFont(font)
        self.highVoltageGroup.setObjectName(_fromUtf8("highVoltageGroup"))
        self.gridLayout_2 = QtGui.QGridLayout(self.highVoltageGroup)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.hvLabel = QtGui.QLabel(self.highVoltageGroup)
        self.hvLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.hvLabel.setFont(font)
        self.hvLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.hvLabel.setWordWrap(True)
        self.hvLabel.setObjectName(_fromUtf8("hvLabel"))
        self.gridLayout_2.addWidget(self.hvLabel, 0, 0, 3, 1)
        self.hvStatusValue = TaurusLabel(self.highVoltageGroup)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.hvStatusValue.setFont(font)
        self.hvStatusValue.setObjectName(_fromUtf8("hvStatusValue"))
        self.gridLayout_2.addWidget(self.hvStatusValue, 0, 1, 1, 2)
        self.hvVoltageValue = TaurusLabel(self.highVoltageGroup)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.hvVoltageValue.setFont(font)
        self.hvVoltageValue.setObjectName(_fromUtf8("hvVoltageValue"))
        self.gridLayout_2.addWidget(self.hvVoltageValue, 1, 1, 1, 2)
        self.hvCurrentValue = TaurusLabel(self.highVoltageGroup)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.hvCurrentValue.setFont(font)
        self.hvCurrentValue.setObjectName(_fromUtf8("hvCurrentValue"))
        self.gridLayout_2.addWidget(self.hvCurrentValue, 2, 1, 1, 2)
        self.hvRamp = QtGui.QLabel(self.highVoltageGroup)
        self.hvRamp.setMaximumSize(QtCore.QSize(60, 16777215))
        self.hvRamp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.hvRamp.setObjectName(_fromUtf8("hvRamp"))
        self.gridLayout_2.addWidget(self.hvRamp, 3, 0, 1, 1)
        self.hvRampEnableLed = TaurusLed(self.highVoltageGroup)
        self.hvRampEnableLed.setMinimumSize(QtCore.QSize(15, 15))
        self.hvRampEnableLed.setMaximumSize(QtCore.QSize(15, 15))
        self.hvRampEnableLed.setObjectName(_fromUtf8("hvRampEnableLed"))
        self.gridLayout_2.addWidget(self.hvRampEnableLed, 3, 1, 1, 1)
        self.hvRampEnableCheck = TaurusValueCheckBox(self.highVoltageGroup)
        self.hvRampEnableCheck.setShowText(False)
        self.hvRampEnableCheck.setAutoApply(True)
        self.hvRampEnableCheck.setForcedApply(True)
        self.hvRampEnableCheck.setObjectName(_fromUtf8("hvRampEnableCheck"))
        self.gridLayout_2.addWidget(self.hvRampEnableCheck, 3, 2, 1, 1)
        self.hvRampStepValue = TaurusLabel(self.highVoltageGroup)
        self.hvRampStepValue.setObjectName(_fromUtf8("hvRampStepValue"))
        self.gridLayout_2.addWidget(self.hvRampStepValue, 4, 1, 1, 2)
        self.hvRampStepTimeValue = TaurusLabel(self.highVoltageGroup)
        self.hvRampStepTimeValue.setObjectName(_fromUtf8("hvRampStepTimeValue"))
        self.gridLayout_2.addWidget(self.hvRampStepTimeValue, 5, 1, 1, 2)
        self.hvRampThresholdValue = TaurusLabel(self.highVoltageGroup)
        self.hvRampThresholdValue.setObjectName(_fromUtf8("hvRampThresholdValue"))
        self.gridLayout_2.addWidget(self.hvRampThresholdValue, 6, 1, 1, 2)
        self.klystronLabel = QtGui.QLabel(self.highVoltageGroup)
        self.klystronLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.klystronLabel.setFont(font)
        self.klystronLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.klystronLabel.setWordWrap(True)
        self.klystronLabel.setObjectName(_fromUtf8("klystronLabel"))
        self.gridLayout_2.addWidget(self.klystronLabel, 7, 0, 3, 1)
        self.pulseStatusValue = TaurusLabel(self.highVoltageGroup)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pulseStatusValue.setFont(font)
        self.pulseStatusValue.setObjectName(_fromUtf8("pulseStatusValue"))
        self.gridLayout_2.addWidget(self.pulseStatusValue, 7, 1, 1, 2)
        self.klystronVoltageValue = TaurusLabel(self.highVoltageGroup)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.klystronVoltageValue.setFont(font)
        self.klystronVoltageValue.setObjectName(_fromUtf8("klystronVoltageValue"))
        self.gridLayout_2.addWidget(self.klystronVoltageValue, 8, 1, 1, 2)
        self.klystronCurrentValue = TaurusLabel(self.highVoltageGroup)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.klystronCurrentValue.setFont(font)
        self.klystronCurrentValue.setObjectName(_fromUtf8("klystronCurrentValue"))
        self.gridLayout_2.addWidget(self.klystronCurrentValue, 9, 1, 1, 2)
        self.label = QtGui.QLabel(self.highVoltageGroup)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.highVoltageGroup)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.highVoltageGroup)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 6, 0, 1, 1)
        self.gridLayout.addWidget(self.highVoltageGroup, 0, 0, 1, 1)

        self.retranslateUi(klystronHV)
        QtCore.QMetaObject.connectSlotsByName(klystronHV)

    def retranslateUi(self, klystronHV):
        klystronHV.setWindowTitle(QtGui.QApplication.translate("klystronHV", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.highVoltageGroup.setTitle(QtGui.QApplication.translate("klystronHV", "klystron high voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.hvLabel.setText(QtGui.QApplication.translate("klystronHV", "High Voltage Power Supply", None, QtGui.QApplication.UnicodeUTF8))
        self.hvRamp.setText(QtGui.QApplication.translate("klystronHV", "HV Ramp", None, QtGui.QApplication.UnicodeUTF8))
        self.klystronLabel.setText(QtGui.QApplication.translate("klystronHV", "klystron electron pulsed", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("klystronHV", "step", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("klystronHV", "time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("klystronHV", "threshold", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusLabel, TaurusLed
from taurus.qt.qtgui.container import TaurusGroupBox
from taurus.qt.qtgui.panel import TaurusWidget
from taurus.qt.qtgui.input import TaurusValueCheckBox
