# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/ui/linacMainscreenSynoptic.ui'
#
# Created: Fri Jun  6 11:33:36 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_linacMainscreenSynoptic(object):
    def setupUi(self, linacMainscreenSynoptic):
        linacMainscreenSynoptic.setObjectName(_fromUtf8("linacMainscreenSynoptic"))
        linacMainscreenSynoptic.resize(1250, 825)
        linacMainscreenSynoptic.setMinimumSize(QtCore.QSize(1250, 825))
        linacMainscreenSynoptic.setMaximumSize(QtCore.QSize(1250, 825))
        font = QtGui.QFont()
        font.setPointSize(7)
        linacMainscreenSynoptic.setFont(font)
        self.tbGunLevelValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.tbGunLevelValue.setGeometry(QtCore.QRect(386, 62, 70, 22))
        self.tbGunLevelValue.setObjectName(_fromUtf8("tbGunLevelValue"))
        self.tbNumberValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.tbNumberValue.setGeometry(QtCore.QRect(308, 107, 50, 22))
        self.tbNumberValue.setObjectName(_fromUtf8("tbNumberValue"))
        self.tbWidthValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.tbWidthValue.setGeometry(QtCore.QRect(238, 107, 55, 22))
        self.tbWidthValue.setObjectName(_fromUtf8("tbWidthValue"))
        self.tbGunDelayValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.tbGunDelayValue.setGeometry(QtCore.QRect(168, 107, 60, 22))
        self.tbGunDelayValue.setObjectName(_fromUtf8("tbGunDelayValue"))
        self.rfEnbLed = TaurusLed(linacMainscreenSynoptic)
        self.rfEnbLed.setGeometry(QtCore.QRect(598, 15, 10, 10))
        self.rfEnbLed.setMinimumSize(QtCore.QSize(10, 10))
        self.rfEnbLed.setMaximumSize(QtCore.QSize(10, 10))
        self.rfEnbLed.setObjectName(_fromUtf8("rfEnbLed"))
        self.tbTimerStatusStateLed = TaurusLed(linacMainscreenSynoptic)
        self.tbTimerStatusStateLed.setGeometry(QtCore.QRect(464, 20, 10, 10))
        self.tbTimerStatusStateLed.setMinimumSize(QtCore.QSize(10, 10))
        self.tbTimerStatusStateLed.setMaximumSize(QtCore.QSize(10, 10))
        self.tbTimerStatusStateLed.setObjectName(_fromUtf8("tbTimerStatusStateLed"))
        self.sf6p1Value = TaurusLabel(linacMainscreenSynoptic)
        self.sf6p1Value.setGeometry(QtCore.QRect(720, 310, 90, 16))
        self.sf6p1Value.setObjectName(_fromUtf8("sf6p1Value"))
        self.sf6p2Value = TaurusLabel(linacMainscreenSynoptic)
        self.sf6p2Value.setGeometry(QtCore.QRect(1000, 310, 90, 16))
        self.sf6p2Value.setObjectName(_fromUtf8("sf6p2Value"))
        self.coolingLoop1Led = TaurusLed(linacMainscreenSynoptic)
        self.coolingLoop1Led.setGeometry(QtCore.QRect(1170, 285, 10, 10))
        self.coolingLoop1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.coolingLoop1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.coolingLoop1Led.setObjectName(_fromUtf8("coolingLoop1Led"))
        self.coolingLoop2Led = TaurusLed(linacMainscreenSynoptic)
        self.coolingLoop2Led.setGeometry(QtCore.QRect(1170, 303, 10, 10))
        self.coolingLoop2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.coolingLoop2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.coolingLoop2Led.setObjectName(_fromUtf8("coolingLoop2Led"))
        self.coolingLoop3Led = TaurusLed(linacMainscreenSynoptic)
        self.coolingLoop3Led.setGeometry(QtCore.QRect(1170, 320, 10, 10))
        self.coolingLoop3Led.setMinimumSize(QtCore.QSize(10, 10))
        self.coolingLoop3Led.setMaximumSize(QtCore.QSize(10, 10))
        self.coolingLoop3Led.setObjectName(_fromUtf8("coolingLoop3Led"))
        self.layoutWidget_2 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 430, 132, 96))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.kdLayout = QtGui.QGridLayout(self.layoutWidget_2)
        self.kdLayout.setContentsMargins(7, -1, -1, -1)
        self.kdLayout.setObjectName(_fromUtf8("kdLayout"))
        self.cathodeLabel = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.cathodeLabel.setFont(font)
        self.cathodeLabel.setObjectName(_fromUtf8("cathodeLabel"))
        self.kdLayout.addWidget(self.cathodeLabel, 1, 1, 1, 1)
        self.filamentCurrent = TaurusLabel(self.layoutWidget_2)
        self.filamentCurrent.setMinimumSize(QtCore.QSize(60, 20))
        self.filamentCurrent.setObjectName(_fromUtf8("filamentCurrent"))
        self.kdLayout.addWidget(self.filamentCurrent, 2, 0, 1, 1)
        self.temperatureValue = TaurusLabel(self.layoutWidget_2)
        self.temperatureValue.setMinimumSize(QtCore.QSize(60, 20))
        self.temperatureValue.setObjectName(_fromUtf8("temperatureValue"))
        self.kdLayout.addWidget(self.temperatureValue, 2, 1, 1, 1)
        self.filamentILabel = QtGui.QLabel(self.layoutWidget_2)
        self.filamentILabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.filamentILabel.setFont(font)
        self.filamentILabel.setObjectName(_fromUtf8("filamentILabel"))
        self.kdLayout.addWidget(self.filamentILabel, 3, 0, 1, 1)
        self.temperatureLabel = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.temperatureLabel.setFont(font)
        self.temperatureLabel.setObjectName(_fromUtf8("temperatureLabel"))
        self.kdLayout.addWidget(self.temperatureLabel, 3, 1, 1, 1)
        self.cathodeCurrent = TaurusLabel(self.layoutWidget_2)
        self.cathodeCurrent.setObjectName(_fromUtf8("cathodeCurrent"))
        self.kdLayout.addWidget(self.cathodeCurrent, 0, 1, 1, 1)
        self.bc2hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc2hValue.setGeometry(QtCore.QRect(500, 640, 65, 22))
        self.bc2hValue.setObjectName(_fromUtf8("bc2hValue"))
        self.bc2vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc2vValue.setGeometry(QtCore.QRect(500, 670, 65, 22))
        self.bc2vValue.setObjectName(_fromUtf8("bc2vValue"))
        self.bc2fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc2fValue.setGeometry(QtCore.QRect(490, 700, 75, 22))
        self.bc2fValue.setObjectName(_fromUtf8("bc2fValue"))
        self.bc1fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc1fValue.setGeometry(QtCore.QRect(415, 700, 75, 22))
        self.bc1fValue.setObjectName(_fromUtf8("bc1fValue"))
        self.bc1vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc1vValue.setGeometry(QtCore.QRect(425, 670, 65, 22))
        self.bc1vValue.setObjectName(_fromUtf8("bc1vValue"))
        self.bc1hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc1hValue.setGeometry(QtCore.QRect(425, 640, 65, 22))
        self.bc1hValue.setObjectName(_fromUtf8("bc1hValue"))
        self.sl4hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl4hValue.setGeometry(QtCore.QRect(350, 640, 65, 22))
        self.sl4hValue.setObjectName(_fromUtf8("sl4hValue"))
        self.sl3hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl3hValue.setGeometry(QtCore.QRect(285, 640, 65, 22))
        self.sl3hValue.setObjectName(_fromUtf8("sl3hValue"))
        self.sl2hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl2hValue.setGeometry(QtCore.QRect(218, 640, 65, 22))
        self.sl2hValue.setObjectName(_fromUtf8("sl2hValue"))
        self.sl1hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl1hValue.setGeometry(QtCore.QRect(133, 640, 65, 22))
        self.sl1hValue.setObjectName(_fromUtf8("sl1hValue"))
        self.sl4vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl4vValue.setGeometry(QtCore.QRect(350, 670, 65, 22))
        self.sl4vValue.setObjectName(_fromUtf8("sl4vValue"))
        self.sl4fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl4fValue.setGeometry(QtCore.QRect(350, 700, 65, 22))
        self.sl4fValue.setObjectName(_fromUtf8("sl4fValue"))
        self.sl3vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl3vValue.setGeometry(QtCore.QRect(285, 670, 65, 22))
        self.sl3vValue.setObjectName(_fromUtf8("sl3vValue"))
        self.sl2vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl2vValue.setGeometry(QtCore.QRect(218, 670, 65, 22))
        self.sl2vValue.setObjectName(_fromUtf8("sl2vValue"))
        self.sl1vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl1vValue.setGeometry(QtCore.QRect(133, 670, 65, 22))
        self.sl1vValue.setObjectName(_fromUtf8("sl1vValue"))
        self.sl1fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl1fValue.setGeometry(QtCore.QRect(133, 700, 65, 22))
        self.sl1fValue.setObjectName(_fromUtf8("sl1fValue"))
        self.sl3fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl3fValue.setGeometry(QtCore.QRect(285, 700, 65, 22))
        self.sl3fValue.setObjectName(_fromUtf8("sl3fValue"))
        self.sl2fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl2fValue.setGeometry(QtCore.QRect(218, 700, 65, 22))
        self.sl2fValue.setObjectName(_fromUtf8("sl2fValue"))
        self.glhValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.glhValue.setGeometry(QtCore.QRect(616, 640, 65, 22))
        self.glhValue.setObjectName(_fromUtf8("glhValue"))
        self.glvValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.glvValue.setGeometry(QtCore.QRect(616, 670, 65, 22))
        self.glvValue.setObjectName(_fromUtf8("glvValue"))
        self.glfValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.glfValue.setGeometry(QtCore.QRect(616, 700, 65, 22))
        self.glfValue.setObjectName(_fromUtf8("glfValue"))
        self.as1hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.as1hValue.setGeometry(QtCore.QRect(719, 640, 65, 22))
        self.as1hValue.setObjectName(_fromUtf8("as1hValue"))
        self.as1vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.as1vValue.setGeometry(QtCore.QRect(719, 670, 65, 22))
        self.as1vValue.setObjectName(_fromUtf8("as1vValue"))
        self.qt1hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.qt1hValue.setGeometry(QtCore.QRect(870, 640, 65, 22))
        self.qt1hValue.setObjectName(_fromUtf8("qt1hValue"))
        self.qt1vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.qt1vValue.setGeometry(QtCore.QRect(870, 670, 65, 22))
        self.qt1vValue.setObjectName(_fromUtf8("qt1vValue"))
        self.qt1fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.qt1fValue.setGeometry(QtCore.QRect(870, 700, 65, 22))
        self.qt1fValue.setObjectName(_fromUtf8("qt1fValue"))
        self.as2hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.as2hValue.setGeometry(QtCore.QRect(1005, 640, 65, 22))
        self.as2hValue.setObjectName(_fromUtf8("as2hValue"))
        self.as2vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.as2vValue.setGeometry(QtCore.QRect(1005, 670, 65, 22))
        self.as2vValue.setObjectName(_fromUtf8("as2vValue"))
        self.qt2fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.qt2fValue.setGeometry(QtCore.QRect(940, 700, 65, 22))
        self.qt2fValue.setObjectName(_fromUtf8("qt2fValue"))
        self.sl1LedInfo = TaurusLed(linacMainscreenSynoptic)
        self.sl1LedInfo.setGeometry(QtCore.QRect(162, 500, 10, 10))
        self.sl1LedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.sl1LedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.sl1LedInfo.setObjectName(_fromUtf8("sl1LedInfo"))
        self.vcvOnLedInfo = TaurusLed(linacMainscreenSynoptic)
        self.vcvOnLedInfo.setGeometry(QtCore.QRect(196, 540, 10, 10))
        self.vcvOnLedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.vcvOnLedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.vcvOnLedInfo.setObjectName(_fromUtf8("vcvOnLedInfo"))
        self.sl2LedInfo = TaurusLed(linacMainscreenSynoptic)
        self.sl2LedInfo.setGeometry(QtCore.QRect(247, 500, 10, 10))
        self.sl2LedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.sl2LedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.sl2LedInfo.setObjectName(_fromUtf8("sl2LedInfo"))
        self.sl3LedInfo = TaurusLed(linacMainscreenSynoptic)
        self.sl3LedInfo.setGeometry(QtCore.QRect(331, 500, 10, 10))
        self.sl3LedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.sl3LedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.sl3LedInfo.setObjectName(_fromUtf8("sl3LedInfo"))
        self.sl4LedInfo = TaurusLed(linacMainscreenSynoptic)
        self.sl4LedInfo.setGeometry(QtCore.QRect(403, 500, 10, 10))
        self.sl4LedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.sl4LedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.sl4LedInfo.setObjectName(_fromUtf8("sl4LedInfo"))
        self.bc1LedInfo = TaurusLed(linacMainscreenSynoptic)
        self.bc1LedInfo.setGeometry(QtCore.QRect(457, 500, 10, 10))
        self.bc1LedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.bc1LedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.bc1LedInfo.setObjectName(_fromUtf8("bc1LedInfo"))
        self.bc2LedInfo = TaurusLed(linacMainscreenSynoptic)
        self.bc2LedInfo.setGeometry(QtCore.QRect(517, 500, 10, 10))
        self.bc2LedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.bc2LedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.bc2LedInfo.setObjectName(_fromUtf8("bc2LedInfo"))
        self.sm1Led = TaurusLed(linacMainscreenSynoptic)
        self.sm1Led.setGeometry(QtCore.QRect(606, 505, 10, 10))
        self.sm1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sm1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sm1Led.setObjectName(_fromUtf8("sm1Led"))
        self.glLedInfo = TaurusLed(linacMainscreenSynoptic)
        self.glLedInfo.setGeometry(QtCore.QRect(643, 500, 10, 10))
        self.glLedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.glLedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.glLedInfo.setObjectName(_fromUtf8("glLedInfo"))
        self.as1LedInfo = TaurusLed(linacMainscreenSynoptic)
        self.as1LedInfo.setGeometry(QtCore.QRect(746, 520, 10, 10))
        self.as1LedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.as1LedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.as1LedInfo.setObjectName(_fromUtf8("as1LedInfo"))
        self.sm2Led = TaurusLed(linacMainscreenSynoptic)
        self.sm2Led.setGeometry(QtCore.QRect(859, 505, 10, 10))
        self.sm2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sm2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sm2Led.setObjectName(_fromUtf8("sm2Led"))
        self.qtLedInfo = TaurusLed(linacMainscreenSynoptic)
        self.qtLedInfo.setGeometry(QtCore.QRect(919, 500, 10, 10))
        self.qtLedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.qtLedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.qtLedInfo.setObjectName(_fromUtf8("qtLedInfo"))
        self.as2LedInfo = TaurusLed(linacMainscreenSynoptic)
        self.as2LedInfo.setGeometry(QtCore.QRect(1033, 520, 10, 10))
        self.as2LedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.as2LedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.as2LedInfo.setObjectName(_fromUtf8("as2LedInfo"))
        self.sm3Led = TaurusLed(linacMainscreenSynoptic)
        self.sm3Led.setGeometry(QtCore.QRect(1135, 505, 10, 10))
        self.sm3Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sm3Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sm3Led.setObjectName(_fromUtf8("sm3Led"))
        self.layoutWidget = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 630, 81, 91))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.hvsLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.hvsLayout.setMargin(0)
        self.hvsLayout.setObjectName(_fromUtf8("hvsLayout"))
        self.eGunHVStatus = TaurusLabel(self.layoutWidget)
        self.eGunHVStatus.setObjectName(_fromUtf8("eGunHVStatus"))
        self.hvsLayout.addWidget(self.eGunHVStatus)
        self.eGunHVValue = TaurusLabel(self.layoutWidget)
        self.eGunHVValue.setObjectName(_fromUtf8("eGunHVValue"))
        self.hvsLayout.addWidget(self.eGunHVValue)
        self.hvsVoltageValue = TaurusValueSpinBox(self.layoutWidget)
        self.hvsVoltageValue.setObjectName(_fromUtf8("hvsVoltageValue"))
        self.hvsLayout.addWidget(self.hvsVoltageValue)
        self.hvsCurrentValue = TaurusLabel(self.layoutWidget)
        self.hvsCurrentValue.setObjectName(_fromUtf8("hvsCurrentValue"))
        self.hvsLayout.addWidget(self.hvsCurrentValue)
        self.klystron2HVPopupWidget = klystronHV(linacMainscreenSynoptic)
        self.klystron2HVPopupWidget.setGeometry(QtCore.QRect(870, 90, 220, 190))
        self.klystron2HVPopupWidget.setObjectName(_fromUtf8("klystron2HVPopupWidget"))
        self.klystron1HVPopupWidget = klystronHV(linacMainscreenSynoptic)
        self.klystron1HVPopupWidget.setGeometry(QtCore.QRect(480, 57, 220, 190))
        self.klystron1HVPopupWidget.setObjectName(_fromUtf8("klystron1HVPopupWidget"))
        self.rfSourceStatusLed = TaurusLed(linacMainscreenSynoptic)
        self.rfSourceStatusLed.setGeometry(QtCore.QRect(1104, 278, 10, 10))
        self.rfSourceStatusLed.setMinimumSize(QtCore.QSize(10, 10))
        self.rfSourceStatusLed.setMaximumSize(QtCore.QSize(10, 10))
        self.rfSourceStatusLed.setObjectName(_fromUtf8("rfSourceStatusLed"))
        self.rfA0StatusLed = TaurusLed(linacMainscreenSynoptic)
        self.rfA0StatusLed.setGeometry(QtCore.QRect(280, 370, 10, 10))
        self.rfA0StatusLed.setMinimumSize(QtCore.QSize(10, 10))
        self.rfA0StatusLed.setMaximumSize(QtCore.QSize(10, 10))
        self.rfA0StatusLed.setObjectName(_fromUtf8("rfA0StatusLed"))
        self.phaseShifter1PopupWidget = phaseShifter(linacMainscreenSynoptic)
        self.phaseShifter1PopupWidget.setGeometry(QtCore.QRect(627, 390, 120, 80))
        self.phaseShifter1PopupWidget.setObjectName(_fromUtf8("phaseShifter1PopupWidget"))
        self.phaseShifter2PopupWidget = phaseShifter(linacMainscreenSynoptic)
        self.phaseShifter2PopupWidget.setGeometry(QtCore.QRect(510, 340, 120, 80))
        self.phaseShifter2PopupWidget.setObjectName(_fromUtf8("phaseShifter2PopupWidget"))
        self.attenuatorPopupWidget = Attenuator(linacMainscreenSynoptic)
        self.attenuatorPopupWidget.setGeometry(QtCore.QRect(280, 380, 120, 80))
        self.attenuatorPopupWidget.setObjectName(_fromUtf8("attenuatorPopupWidget"))
        self.sl1PopupWidget = magnet(linacMainscreenSynoptic)
        self.sl1PopupWidget.setGeometry(QtCore.QRect(203, 627, 220, 80))
        self.sl1PopupWidget.setObjectName(_fromUtf8("sl1PopupWidget"))
        self.sl2PopupWidget = magnet(linacMainscreenSynoptic)
        self.sl2PopupWidget.setGeometry(QtCore.QRect(291, 600, 220, 80))
        self.sl2PopupWidget.setObjectName(_fromUtf8("sl2PopupWidget"))
        self.sl3PopupWidget = magnet(linacMainscreenSynoptic)
        self.sl3PopupWidget.setGeometry(QtCore.QRect(376, 600, 220, 80))
        self.sl3PopupWidget.setObjectName(_fromUtf8("sl3PopupWidget"))
        self.sl4PopupWidget = magnet(linacMainscreenSynoptic)
        self.sl4PopupWidget.setGeometry(QtCore.QRect(440, 600, 220, 80))
        self.sl4PopupWidget.setObjectName(_fromUtf8("sl4PopupWidget"))
        self.bc1PopupWidget = magnet(linacMainscreenSynoptic)
        self.bc1PopupWidget.setGeometry(QtCore.QRect(505, 600, 220, 80))
        self.bc1PopupWidget.setObjectName(_fromUtf8("bc1PopupWidget"))
        self.bc2PopupWidget = magnet(linacMainscreenSynoptic)
        self.bc2PopupWidget.setGeometry(QtCore.QRect(569, 600, 220, 80))
        self.bc2PopupWidget.setObjectName(_fromUtf8("bc2PopupWidget"))
        self.glPopupWidget = magnet(linacMainscreenSynoptic)
        self.glPopupWidget.setGeometry(QtCore.QRect(681, 600, 220, 80))
        self.glPopupWidget.setObjectName(_fromUtf8("glPopupWidget"))
        self.qtPopupWidget = magnet(linacMainscreenSynoptic)
        self.qtPopupWidget.setGeometry(QtCore.QRect(939, 600, 220, 100))
        self.qtPopupWidget.setObjectName(_fromUtf8("qtPopupWidget"))
        self.as2PopupWidget = magnet(linacMainscreenSynoptic)
        self.as2PopupWidget.setGeometry(QtCore.QRect(1030, 585, 220, 60))
        self.as2PopupWidget.setObjectName(_fromUtf8("as2PopupWidget"))
        self.as1PopupWidget = magnet(linacMainscreenSynoptic)
        self.as1PopupWidget.setGeometry(QtCore.QRect(786, 585, 220, 60))
        self.as1PopupWidget.setObjectName(_fromUtf8("as1PopupWidget"))
        self.hvsPopupWidget = eGunHV(linacMainscreenSynoptic)
        self.hvsPopupWidget.setGeometry(QtCore.QRect(-2, 529, 114, 60))
        self.hvsPopupWidget.setObjectName(_fromUtf8("hvsPopupWidget"))
        self.MainScreenSchematic = QtGui.QLabel(linacMainscreenSynoptic)
        self.MainScreenSchematic.setGeometry(QtCore.QRect(0, 0, 1265, 829))
        self.MainScreenSchematic.setText(_fromUtf8(""))
        self.MainScreenSchematic.setPixmap(QtGui.QPixmap(_fromUtf8("jdraw/linac_mainscreen_synoptic.png")))
        self.MainScreenSchematic.setObjectName(_fromUtf8("MainScreenSchematic"))
        self.klystron1HVPopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.klystron1HVPopupCheck.setGeometry(QtCore.QRect(754, 110, 20, 20))
        self.klystron1HVPopupCheck.setCheckable(True)
        self.klystron1HVPopupCheck.setObjectName(_fromUtf8("klystron1HVPopupCheck"))
        self.klystron2HVPopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.klystron2HVPopupCheck.setGeometry(QtCore.QRect(1042, 70, 20, 20))
        self.klystron2HVPopupCheck.setCheckable(True)
        self.klystron2HVPopupCheck.setObjectName(_fromUtf8("klystron2HVPopupCheck"))
        self.hvsPopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.hvsPopupCheck.setGeometry(QtCore.QRect(94, 602, 20, 20))
        self.hvsPopupCheck.setCheckable(True)
        self.hvsPopupCheck.setObjectName(_fromUtf8("hvsPopupCheck"))
        self.attenuatorPopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.attenuatorPopupCheck.setGeometry(QtCore.QRect(413, 422, 20, 20))
        self.attenuatorPopupCheck.setCheckable(True)
        self.attenuatorPopupCheck.setObjectName(_fromUtf8("attenuatorPopupCheck"))
        self.phaseShifter2PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.phaseShifter2PopupCheck.setGeometry(QtCore.QRect(466, 422, 20, 20))
        self.phaseShifter2PopupCheck.setCheckable(True)
        self.phaseShifter2PopupCheck.setObjectName(_fromUtf8("phaseShifter2PopupCheck"))
        self.phaseShifter1PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.phaseShifter1PopupCheck.setGeometry(QtCore.QRect(605, 455, 20, 20))
        self.phaseShifter1PopupCheck.setCheckable(True)
        self.phaseShifter1PopupCheck.setObjectName(_fromUtf8("phaseShifter1PopupCheck"))
        self.sl1PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.sl1PopupCheck.setGeometry(QtCore.QRect(156, 514, 20, 20))
        self.sl1PopupCheck.setCheckable(True)
        self.sl1PopupCheck.setObjectName(_fromUtf8("sl1PopupCheck"))
        self.sl2PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.sl2PopupCheck.setGeometry(QtCore.QRect(241, 513, 20, 20))
        self.sl2PopupCheck.setCheckable(True)
        self.sl2PopupCheck.setObjectName(_fromUtf8("sl2PopupCheck"))
        self.sl3PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.sl3PopupCheck.setGeometry(QtCore.QRect(326, 514, 20, 20))
        self.sl3PopupCheck.setCheckable(True)
        self.sl3PopupCheck.setChecked(False)
        self.sl3PopupCheck.setObjectName(_fromUtf8("sl3PopupCheck"))
        self.sl4PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.sl4PopupCheck.setGeometry(QtCore.QRect(397, 513, 20, 20))
        self.sl4PopupCheck.setCheckable(True)
        self.sl4PopupCheck.setObjectName(_fromUtf8("sl4PopupCheck"))
        self.bc1PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.bc1PopupCheck.setGeometry(QtCore.QRect(452, 515, 20, 20))
        self.bc1PopupCheck.setCheckable(True)
        self.bc1PopupCheck.setObjectName(_fromUtf8("bc1PopupCheck"))
        self.bc2PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.bc2PopupCheck.setGeometry(QtCore.QRect(511, 516, 20, 20))
        self.bc2PopupCheck.setCheckable(True)
        self.bc2PopupCheck.setObjectName(_fromUtf8("bc2PopupCheck"))
        self.glPopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.glPopupCheck.setGeometry(QtCore.QRect(637, 514, 20, 20))
        self.glPopupCheck.setCheckable(True)
        self.glPopupCheck.setObjectName(_fromUtf8("glPopupCheck"))
        self.as1PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.as1PopupCheck.setGeometry(QtCore.QRect(741, 531, 20, 20))
        self.as1PopupCheck.setCheckable(True)
        self.as1PopupCheck.setObjectName(_fromUtf8("as1PopupCheck"))
        self.qtPopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.qtPopupCheck.setGeometry(QtCore.QRect(914, 513, 20, 20))
        self.qtPopupCheck.setCheckable(True)
        self.qtPopupCheck.setObjectName(_fromUtf8("qtPopupCheck"))
        self.as2PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.as2PopupCheck.setGeometry(QtCore.QRect(1027, 531, 20, 20))
        self.as2PopupCheck.setCheckable(True)
        self.as2PopupCheck.setObjectName(_fromUtf8("as2PopupCheck"))
        self.tbRf2DelayValue = TaurusLabel(linacMainscreenSynoptic)
        self.tbRf2DelayValue.setGeometry(QtCore.QRect(177, 52, 48, 16))
        self.tbRf2DelayValue.setObjectName(_fromUtf8("tbRf2DelayValue"))
        self.tbWidthLabel = QtGui.QLabel(linacMainscreenSynoptic)
        self.tbWidthLabel.setGeometry(QtCore.QRect(246, 130, 41, 16))
        self.tbWidthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tbWidthLabel.setObjectName(_fromUtf8("tbWidthLabel"))
        self.tbNumberLabel = QtGui.QLabel(linacMainscreenSynoptic)
        self.tbNumberLabel.setGeometry(QtCore.QRect(312, 130, 41, 16))
        self.tbNumberLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tbNumberLabel.setObjectName(_fromUtf8("tbNumberLabel"))
        self.tbGunDelayLabel = QtGui.QLabel(linacMainscreenSynoptic)
        self.tbGunDelayLabel.setGeometry(QtCore.QRect(180, 130, 57, 14))
        self.tbGunDelayLabel.setObjectName(_fromUtf8("tbGunDelayLabel"))
        self.layoutWidget1 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 80, 141, 71))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.multibunchLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.multibunchLayout.setMargin(0)
        self.multibunchLayout.setObjectName(_fromUtf8("multibunchLayout"))
        self.tbGatedPulseModeCombo = TaurusValueComboBox(self.layoutWidget1)
        self.tbGatedPulseModeCombo.setObjectName(_fromUtf8("tbGatedPulseModeCombo"))
        self.multibunchLayout.addWidget(self.tbGatedPulseModeCombo, 1, 2, 1, 1)
        self.multibunchLabel = QtGui.QLabel(self.layoutWidget1)
        self.multibunchLabel.setObjectName(_fromUtf8("multibunchLabel"))
        self.multibunchLayout.addWidget(self.multibunchLabel, 1, 0, 1, 1)
        self.tbMultiBunchValue = TaurusLabel(self.layoutWidget1)
        self.tbMultiBunchValue.setObjectName(_fromUtf8("tbMultiBunchValue"))
        self.multibunchLayout.addWidget(self.tbMultiBunchValue, 0, 0, 1, 2)
        self.tbGatedPulseModeLabel = QtGui.QLabel(self.layoutWidget1)
        self.tbGatedPulseModeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tbGatedPulseModeLabel.setWordWrap(True)
        self.tbGatedPulseModeLabel.setObjectName(_fromUtf8("tbGatedPulseModeLabel"))
        self.multibunchLayout.addWidget(self.tbGatedPulseModeLabel, 2, 2, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.multibunchLayout.addWidget(self.label, 2, 0, 1, 2)
        self.tbMultiBunchCheck = LinacValueCheckBox(self.layoutWidget1)
        self.tbMultiBunchCheck.setShowText(False)
        self.tbMultiBunchCheck.setObjectName(_fromUtf8("tbMultiBunchCheck"))
        self.multibunchLayout.addWidget(self.tbMultiBunchCheck, 1, 1, 1, 1)
        self.tbGatedPulseModeValue = TaurusLabel(self.layoutWidget1)
        self.tbGatedPulseModeValue.setObjectName(_fromUtf8("tbGatedPulseModeValue"))
        self.multibunchLayout.addWidget(self.tbGatedPulseModeValue, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(linacMainscreenSynoptic)
        self.label_2.setGeometry(QtCore.QRect(459, 66, 16, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.eGunVacuumWidget = CavityVacuum(linacMainscreenSynoptic)
        self.eGunVacuumWidget.setGeometry(QtCore.QRect(140, 487, 116, 97))
        self.eGunVacuumWidget.setObjectName(_fromUtf8("eGunVacuumWidget"))
        self.preBuncherVacuumWidget = CavityVacuum(linacMainscreenSynoptic)
        self.preBuncherVacuumWidget.setGeometry(QtCore.QRect(300, 570, 116, 97))
        self.preBuncherVacuumWidget.setObjectName(_fromUtf8("preBuncherVacuumWidget"))
        self.buncherVacuumWidget = CavityVacuum(linacMainscreenSynoptic)
        self.buncherVacuumWidget.setGeometry(QtCore.QRect(540, 570, 116, 97))
        self.buncherVacuumWidget.setObjectName(_fromUtf8("buncherVacuumWidget"))
        self.as1VacuumWidget = CavityVacuum(linacMainscreenSynoptic)
        self.as1VacuumWidget.setGeometry(QtCore.QRect(790, 570, 116, 97))
        self.as1VacuumWidget.setObjectName(_fromUtf8("as1VacuumWidget"))
        self.as2VacuumWidget = CavityVacuum(linacMainscreenSynoptic)
        self.as2VacuumWidget.setGeometry(QtCore.QRect(1080, 570, 116, 97))
        self.as2VacuumWidget.setObjectName(_fromUtf8("as2VacuumWidget"))
        self.eGunVacuumCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.eGunVacuumCheck.setGeometry(QtCore.QRect(109, 580, 40, 20))
        self.eGunVacuumCheck.setCheckable(True)
        self.eGunVacuumCheck.setObjectName(_fromUtf8("eGunVacuumCheck"))
        self.preBuncherVacuumCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.preBuncherVacuumCheck.setGeometry(QtCore.QRect(263, 580, 40, 20))
        self.preBuncherVacuumCheck.setCheckable(True)
        self.preBuncherVacuumCheck.setObjectName(_fromUtf8("preBuncherVacuumCheck"))
        self.buncherVacuumCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.buncherVacuumCheck.setGeometry(QtCore.QRect(470, 568, 40, 20))
        self.buncherVacuumCheck.setCheckable(True)
        self.buncherVacuumCheck.setObjectName(_fromUtf8("buncherVacuumCheck"))
        self.as1VacuumCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.as1VacuumCheck.setGeometry(QtCore.QRect(730, 568, 40, 20))
        self.as1VacuumCheck.setCheckable(True)
        self.as1VacuumCheck.setObjectName(_fromUtf8("as1VacuumCheck"))
        self.as2VacuumCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.as2VacuumCheck.setGeometry(QtCore.QRect(1019, 569, 40, 20))
        self.as2VacuumCheck.setCheckable(True)
        self.as2VacuumCheck.setObjectName(_fromUtf8("as2VacuumCheck"))
        self.beamChargeMonitors = beamChargeMonitors(linacMainscreenSynoptic)
        self.beamChargeMonitors.setGeometry(QtCore.QRect(1120, 400, 131, 101))
        self.beamChargeMonitors.setObjectName(_fromUtf8("beamChargeMonitors"))
        self.layoutWidget2 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget2.setGeometry(QtCore.QRect(790, 110, 81, 51))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.klystron1HVRead = TaurusLabel(self.layoutWidget2)
        self.klystron1HVRead.setObjectName(_fromUtf8("klystron1HVRead"))
        self.verticalLayout.addWidget(self.klystron1HVRead)
        self.klystron1HVWrite = TaurusValueSpinBox(self.layoutWidget2)
        self.klystron1HVWrite.setObjectName(_fromUtf8("klystron1HVWrite"))
        self.verticalLayout.addWidget(self.klystron1HVWrite)
        self.layoutWidget3 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget3.setGeometry(QtCore.QRect(1080, 70, 81, 51))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.klystron2HVRead = TaurusLabel(self.layoutWidget3)
        self.klystron2HVRead.setObjectName(_fromUtf8("klystron2HVRead"))
        self.verticalLayout_2.addWidget(self.klystron2HVRead)
        self.klystron2HVWrite = TaurusValueSpinBox(self.layoutWidget3)
        self.klystron2HVWrite.setObjectName(_fromUtf8("klystron2HVWrite"))
        self.verticalLayout_2.addWidget(self.klystron2HVWrite)
        self.tbKaDelay1Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.tbKaDelay1Value.setGeometry(QtCore.QRect(28, 48, 60, 22))
        self.tbKaDelay1Value.setObjectName(_fromUtf8("tbKaDelay1Value"))
        self.tbKaDelay2Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.tbKaDelay2Value.setGeometry(QtCore.QRect(102, 49, 60, 22))
        self.tbKaDelay2Value.setObjectName(_fromUtf8("tbKaDelay2Value"))
        self.klystron1On = actionForm(linacMainscreenSynoptic)
        self.klystron1On.setGeometry(QtCore.QRect(800, 166, 60, 40))
        self.klystron1On.setObjectName(_fromUtf8("klystron1On"))
        self.klystron1Rst = actionForm(linacMainscreenSynoptic)
        self.klystron1Rst.setGeometry(QtCore.QRect(800, 209, 60, 40))
        self.klystron1Rst.setObjectName(_fromUtf8("klystron1Rst"))
        self.klystron2On = actionForm(linacMainscreenSynoptic)
        self.klystron2On.setGeometry(QtCore.QRect(1090, 126, 60, 40))
        self.klystron2On.setObjectName(_fromUtf8("klystron2On"))
        self.klystron2Rst = actionForm(linacMainscreenSynoptic)
        self.klystron2Rst.setGeometry(QtCore.QRect(1090, 170, 60, 40))
        self.klystron2Rst.setObjectName(_fromUtf8("klystron2Rst"))
        self.hvsOn = actionForm(linacMainscreenSynoptic)
        self.hvsOn.setGeometry(QtCore.QRect(42, 724, 60, 40))
        self.hvsOn.setObjectName(_fromUtf8("hvsOn"))
        self.magnetsRst = actionForm(linacMainscreenSynoptic)
        self.magnetsRst.setGeometry(QtCore.QRect(12, 767, 60, 55))
        self.magnetsRst.setObjectName(_fromUtf8("magnetsRst"))
        self.magnetsOn = actionForm(linacMainscreenSynoptic)
        self.magnetsOn.setGeometry(QtCore.QRect(77, 774, 60, 40))
        self.magnetsOn.setObjectName(_fromUtf8("magnetsOn"))
        self.vcvOn = actionForm(linacMainscreenSynoptic)
        self.vcvOn.setGeometry(QtCore.QRect(170, 767, 60, 58))
        self.vcvOn.setObjectName(_fromUtf8("vcvOn"))
        self.sl2On = actionForm(linacMainscreenSynoptic)
        self.sl2On.setGeometry(QtCore.QRect(218, 722, 60, 40))
        self.sl2On.setObjectName(_fromUtf8("sl2On"))
        self.sl1On = actionForm(linacMainscreenSynoptic)
        self.sl1On.setGeometry(QtCore.QRect(135, 722, 60, 40))
        self.sl1On.setObjectName(_fromUtf8("sl1On"))
        self.sl3On = actionForm(linacMainscreenSynoptic)
        self.sl3On.setGeometry(QtCore.QRect(285, 722, 60, 40))
        self.sl3On.setObjectName(_fromUtf8("sl3On"))
        self.sl4On = actionForm(linacMainscreenSynoptic)
        self.sl4On.setGeometry(QtCore.QRect(350, 722, 60, 40))
        self.sl4On.setObjectName(_fromUtf8("sl4On"))
        self.bc1On = actionForm(linacMainscreenSynoptic)
        self.bc1On.setGeometry(QtCore.QRect(425, 722, 60, 40))
        self.bc1On.setObjectName(_fromUtf8("bc1On"))
        self.bc2On = actionForm(linacMainscreenSynoptic)
        self.bc2On.setGeometry(QtCore.QRect(500, 722, 60, 40))
        self.bc2On.setObjectName(_fromUtf8("bc2On"))
        self.glOn = actionForm(linacMainscreenSynoptic)
        self.glOn.setGeometry(QtCore.QRect(618, 722, 60, 40))
        self.glOn.setObjectName(_fromUtf8("glOn"))
        self.as1On = actionForm(linacMainscreenSynoptic)
        self.as1On.setGeometry(QtCore.QRect(721, 722, 60, 40))
        self.as1On.setObjectName(_fromUtf8("as1On"))
        self.qtOn = actionForm(linacMainscreenSynoptic)
        self.qtOn.setGeometry(QtCore.QRect(873, 722, 60, 40))
        self.qtOn.setObjectName(_fromUtf8("qtOn"))
        self.as2On = actionForm(linacMainscreenSynoptic)
        self.as2On.setGeometry(QtCore.QRect(1008, 722, 60, 40))
        self.as2On.setObjectName(_fromUtf8("as2On"))
        self.tbKaDelay1Unit = QtGui.QLabel(linacMainscreenSynoptic)
        self.tbKaDelay1Unit.setGeometry(QtCore.QRect(87, 50, 16, 16))
        self.tbKaDelay1Unit.setObjectName(_fromUtf8("tbKaDelay1Unit"))
        self.tbKaDelay2Unit = QtGui.QLabel(linacMainscreenSynoptic)
        self.tbKaDelay2Unit.setGeometry(QtCore.QRect(163, 50, 16, 16))
        self.tbKaDelay2Unit.setObjectName(_fromUtf8("tbKaDelay2Unit"))
        self.tbGunDelayUnit = QtGui.QLabel(linacMainscreenSynoptic)
        self.tbGunDelayUnit.setGeometry(QtCore.QRect(227, 110, 16, 16))
        self.tbGunDelayUnit.setObjectName(_fromUtf8("tbGunDelayUnit"))
        self.tbGunDelayUnit_2 = QtGui.QLabel(linacMainscreenSynoptic)
        self.tbGunDelayUnit_2.setGeometry(QtCore.QRect(295, 110, 16, 16))
        self.tbGunDelayUnit_2.setObjectName(_fromUtf8("tbGunDelayUnit_2"))
        self.attenuatorLed = TaurusLed(linacMainscreenSynoptic)
        self.attenuatorLed.setGeometry(QtCore.QRect(400, 427, 10, 10))
        self.attenuatorLed.setMinimumSize(QtCore.QSize(10, 10))
        self.attenuatorLed.setMaximumSize(QtCore.QSize(10, 10))
        self.attenuatorLed.setObjectName(_fromUtf8("attenuatorLed"))
        self.phaseShifter2Led = TaurusLed(linacMainscreenSynoptic)
        self.phaseShifter2Led.setGeometry(QtCore.QRect(453, 427, 10, 10))
        self.phaseShifter2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.phaseShifter2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.phaseShifter2Led.setObjectName(_fromUtf8("phaseShifter2Led"))
        self.phaseShifter1Led = TaurusLed(linacMainscreenSynoptic)
        self.phaseShifter1Led.setGeometry(QtCore.QRect(592, 459, 10, 10))
        self.phaseShifter1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.phaseShifter1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.phaseShifter1Led.setObjectName(_fromUtf8("phaseShifter1Led"))
        self.klystron1HVLed = TaurusLed(linacMainscreenSynoptic)
        self.klystron1HVLed.setGeometry(QtCore.QRect(740, 115, 10, 10))
        self.klystron1HVLed.setMinimumSize(QtCore.QSize(10, 10))
        self.klystron1HVLed.setMaximumSize(QtCore.QSize(10, 10))
        self.klystron1HVLed.setObjectName(_fromUtf8("klystron1HVLed"))
        self.klystron2HVLed = TaurusLed(linacMainscreenSynoptic)
        self.klystron2HVLed.setGeometry(QtCore.QRect(1029, 75, 10, 10))
        self.klystron2HVLed.setMinimumSize(QtCore.QSize(10, 10))
        self.klystron2HVLed.setMaximumSize(QtCore.QSize(10, 10))
        self.klystron2HVLed.setObjectName(_fromUtf8("klystron2HVLed"))
        self.vacuumCollimatorValveOnStatus = TaurusLabel(linacMainscreenSynoptic)
        self.vacuumCollimatorValveOnStatus.setGeometry(QtCore.QRect(178, 611, 60, 16))
        self.vacuumCollimatorValveOnStatus.setObjectName(_fromUtf8("vacuumCollimatorValveOnStatus"))
        self.layoutWidget4 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget4.setGeometry(QtCore.QRect(110, 310, 71, 50))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.rfTimePhaseShifter0Layout = QtGui.QVBoxLayout(self.layoutWidget4)
        self.rfTimePhaseShifter0Layout.setMargin(0)
        self.rfTimePhaseShifter0Layout.setObjectName(_fromUtf8("rfTimePhaseShifter0Layout"))
        self.rfTimePhaseShifter0Setpoint = TaurusValueSpinBox(self.layoutWidget4)
        self.rfTimePhaseShifter0Setpoint.setObjectName(_fromUtf8("rfTimePhaseShifter0Setpoint"))
        self.rfTimePhaseShifter0Layout.addWidget(self.rfTimePhaseShifter0Setpoint)
        self.rfTimePhaseShifter0Value = TaurusLabel(self.layoutWidget4)
        self.rfTimePhaseShifter0Value.setMinimumSize(QtCore.QSize(65, 22))
        self.rfTimePhaseShifter0Value.setObjectName(_fromUtf8("rfTimePhaseShifter0Value"))
        self.rfTimePhaseShifter0Layout.addWidget(self.rfTimePhaseShifter0Value)
        self.layoutWidget5 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget5.setGeometry(QtCore.QRect(180, 310, 71, 50))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.rfA0OutputPowerLayout = QtGui.QVBoxLayout(self.layoutWidget5)
        self.rfA0OutputPowerLayout.setMargin(0)
        self.rfA0OutputPowerLayout.setObjectName(_fromUtf8("rfA0OutputPowerLayout"))
        self.rfA0OutputPowerSetpoint = TaurusValueSpinBox(self.layoutWidget5)
        self.rfA0OutputPowerSetpoint.setObjectName(_fromUtf8("rfA0OutputPowerSetpoint"))
        self.rfA0OutputPowerLayout.addWidget(self.rfA0OutputPowerSetpoint)
        self.rfA0OutputPowerValue = TaurusLabel(self.layoutWidget5)
        self.rfA0OutputPowerValue.setMinimumSize(QtCore.QSize(65, 22))
        self.rfA0OutputPowerValue.setObjectName(_fromUtf8("rfA0OutputPowerValue"))
        self.rfA0OutputPowerLayout.addWidget(self.rfA0OutputPowerValue)
        self.layoutWidget6 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget6.setGeometry(QtCore.QRect(260, 250, 67, 50))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.rfTimePhaseShifterXLayout = QtGui.QVBoxLayout(self.layoutWidget6)
        self.rfTimePhaseShifterXLayout.setMargin(0)
        self.rfTimePhaseShifterXLayout.setObjectName(_fromUtf8("rfTimePhaseShifterXLayout"))
        self.rfTimePhaseShifterXValue = TaurusLabel(self.layoutWidget6)
        self.rfTimePhaseShifterXValue.setMinimumSize(QtCore.QSize(65, 22))
        self.rfTimePhaseShifterXValue.setObjectName(_fromUtf8("rfTimePhaseShifterXValue"))
        self.rfTimePhaseShifterXLayout.addWidget(self.rfTimePhaseShifterXValue)
        self.rfTimePhaseShifterXSetpoint = TaurusValueSpinBox(self.layoutWidget6)
        self.rfTimePhaseShifterXSetpoint.setObjectName(_fromUtf8("rfTimePhaseShifterXSetpoint"))
        self.rfTimePhaseShifterXLayout.addWidget(self.rfTimePhaseShifterXSetpoint)
        self.layoutWidget7 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget7.setGeometry(QtCore.QRect(510, 250, 67, 50))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.rfTimePhaseShifter1Value = TaurusLabel(self.layoutWidget7)
        self.rfTimePhaseShifter1Value.setMinimumSize(QtCore.QSize(65, 22))
        self.rfTimePhaseShifter1Value.setObjectName(_fromUtf8("rfTimePhaseShifter1Value"))
        self.verticalLayout_6.addWidget(self.rfTimePhaseShifter1Value)
        self.rfTimePhaseShifter1Setpoint = TaurusValueSpinBox(self.layoutWidget7)
        self.rfTimePhaseShifter1Setpoint.setObjectName(_fromUtf8("rfTimePhaseShifter1Setpoint"))
        self.verticalLayout_6.addWidget(self.rfTimePhaseShifter1Setpoint)
        self.layoutWidget8 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget8.setGeometry(QtCore.QRect(770, 270, 136, 24))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.rfTimePhaseShifter2Layout = QtGui.QHBoxLayout(self.layoutWidget8)
        self.rfTimePhaseShifter2Layout.setMargin(0)
        self.rfTimePhaseShifter2Layout.setObjectName(_fromUtf8("rfTimePhaseShifter2Layout"))
        self.rfTimePhaseShifter2Value = TaurusLabel(self.layoutWidget8)
        self.rfTimePhaseShifter2Value.setMinimumSize(QtCore.QSize(65, 22))
        self.rfTimePhaseShifter2Value.setObjectName(_fromUtf8("rfTimePhaseShifter2Value"))
        self.rfTimePhaseShifter2Layout.addWidget(self.rfTimePhaseShifter2Value)
        self.rfTimePhaseShifter2Setpoint = TaurusValueSpinBox(self.layoutWidget8)
        self.rfTimePhaseShifter2Setpoint.setMinimumSize(QtCore.QSize(65, 0))
        self.rfTimePhaseShifter2Setpoint.setObjectName(_fromUtf8("rfTimePhaseShifter2Setpoint"))
        self.rfTimePhaseShifter2Layout.addWidget(self.rfTimePhaseShifter2Setpoint)
        self.layoutWidget9 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget9.setGeometry(QtCore.QRect(570, 310, 136, 24))
        self.layoutWidget9.setObjectName(_fromUtf8("layoutWidget9"))
        self.rfPhaseShifter1Layout = QtGui.QHBoxLayout(self.layoutWidget9)
        self.rfPhaseShifter1Layout.setMargin(0)
        self.rfPhaseShifter1Layout.setObjectName(_fromUtf8("rfPhaseShifter1Layout"))
        self.rfPhaseShifter1Value = TaurusLabel(self.layoutWidget9)
        self.rfPhaseShifter1Value.setMinimumSize(QtCore.QSize(65, 22))
        self.rfPhaseShifter1Value.setObjectName(_fromUtf8("rfPhaseShifter1Value"))
        self.rfPhaseShifter1Layout.addWidget(self.rfPhaseShifter1Value)
        self.rfPhaseShifter1Setpoint = TaurusValueSpinBox(self.layoutWidget9)
        self.rfPhaseShifter1Setpoint.setMinimumSize(QtCore.QSize(65, 22))
        self.rfPhaseShifter1Setpoint.setObjectName(_fromUtf8("rfPhaseShifter1Setpoint"))
        self.rfPhaseShifter1Layout.addWidget(self.rfPhaseShifter1Setpoint)
        self.layoutWidget10 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget10.setGeometry(QtCore.QRect(440, 310, 67, 50))
        self.layoutWidget10.setObjectName(_fromUtf8("layoutWidget10"))
        self.rfPhaseShifter2Layout = QtGui.QVBoxLayout(self.layoutWidget10)
        self.rfPhaseShifter2Layout.setMargin(0)
        self.rfPhaseShifter2Layout.setObjectName(_fromUtf8("rfPhaseShifter2Layout"))
        self.rfPhaseShifter2Setpoint = TaurusValueSpinBox(self.layoutWidget10)
        self.rfPhaseShifter2Setpoint.setObjectName(_fromUtf8("rfPhaseShifter2Setpoint"))
        self.rfPhaseShifter2Layout.addWidget(self.rfPhaseShifter2Setpoint)
        self.rfPhaseShifter2Value = TaurusLabel(self.layoutWidget10)
        self.rfPhaseShifter2Value.setMinimumSize(QtCore.QSize(65, 22))
        self.rfPhaseShifter2Value.setObjectName(_fromUtf8("rfPhaseShifter2Value"))
        self.rfPhaseShifter2Layout.addWidget(self.rfPhaseShifter2Value)
        self.layoutWidget11 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget11.setGeometry(QtCore.QRect(370, 310, 67, 50))
        self.layoutWidget11.setObjectName(_fromUtf8("layoutWidget11"))
        self.attenuator2Layout = QtGui.QVBoxLayout(self.layoutWidget11)
        self.attenuator2Layout.setMargin(0)
        self.attenuator2Layout.setObjectName(_fromUtf8("attenuator2Layout"))
        self.attenuator2Setpoint = TaurusValueSpinBox(self.layoutWidget11)
        self.attenuator2Setpoint.setObjectName(_fromUtf8("attenuator2Setpoint"))
        self.attenuator2Layout.addWidget(self.attenuator2Setpoint)
        self.attenuator2Value = TaurusLabel(self.layoutWidget11)
        self.attenuator2Value.setMinimumSize(QtCore.QSize(65, 22))
        self.attenuator2Value.setObjectName(_fromUtf8("attenuator2Value"))
        self.attenuator2Layout.addWidget(self.attenuator2Value)
        self.layoutWidget12 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget12.setGeometry(QtCore.QRect(510, 770, 201, 43))
        self.layoutWidget12.setObjectName(_fromUtf8("layoutWidget12"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget12)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.fluorescentScreen1Valve = actionForm(self.layoutWidget12)
        self.fluorescentScreen1Valve.setMinimumSize(QtCore.QSize(65, 0))
        self.fluorescentScreen1Valve.setObjectName(_fromUtf8("fluorescentScreen1Valve"))
        self.gridLayout.addWidget(self.fluorescentScreen1Valve, 0, 0, 2, 1)
        self.fluorescentScreen1Status = TaurusLabel(self.layoutWidget12)
        self.fluorescentScreen1Status.setMinimumSize(QtCore.QSize(50, 0))
        self.fluorescentScreen1Status.setObjectName(_fromUtf8("fluorescentScreen1Status"))
        self.gridLayout.addWidget(self.fluorescentScreen1Status, 0, 1, 1, 1)
        self.fluorescentScreen1Light = actionForm(self.layoutWidget12)
        self.fluorescentScreen1Light.setMinimumSize(QtCore.QSize(65, 0))
        self.fluorescentScreen1Light.setObjectName(_fromUtf8("fluorescentScreen1Light"))
        self.gridLayout.addWidget(self.fluorescentScreen1Light, 0, 2, 2, 1)
        self.fluorescentScreen1View = QtGui.QPushButton(self.layoutWidget12)
        self.fluorescentScreen1View.setMinimumSize(QtCore.QSize(50, 0))
        self.fluorescentScreen1View.setObjectName(_fromUtf8("fluorescentScreen1View"))
        self.gridLayout.addWidget(self.fluorescentScreen1View, 1, 1, 1, 1)
        self.layoutWidget13 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget13.setGeometry(QtCore.QRect(760, 770, 201, 43))
        self.layoutWidget13.setObjectName(_fromUtf8("layoutWidget13"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget13)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.fluorescentScreen2Valve = actionForm(self.layoutWidget13)
        self.fluorescentScreen2Valve.setMinimumSize(QtCore.QSize(65, 0))
        self.fluorescentScreen2Valve.setObjectName(_fromUtf8("fluorescentScreen2Valve"))
        self.gridLayout_2.addWidget(self.fluorescentScreen2Valve, 0, 0, 2, 1)
        self.fluorescentScreen2Status = TaurusLabel(self.layoutWidget13)
        self.fluorescentScreen2Status.setMinimumSize(QtCore.QSize(50, 0))
        self.fluorescentScreen2Status.setObjectName(_fromUtf8("fluorescentScreen2Status"))
        self.gridLayout_2.addWidget(self.fluorescentScreen2Status, 0, 1, 1, 1)
        self.fluorescentScreen2Light = actionForm(self.layoutWidget13)
        self.fluorescentScreen2Light.setMinimumSize(QtCore.QSize(65, 0))
        self.fluorescentScreen2Light.setObjectName(_fromUtf8("fluorescentScreen2Light"))
        self.gridLayout_2.addWidget(self.fluorescentScreen2Light, 0, 2, 2, 1)
        self.fluorescentScreen2View = QtGui.QPushButton(self.layoutWidget13)
        self.fluorescentScreen2View.setMinimumSize(QtCore.QSize(50, 0))
        self.fluorescentScreen2View.setObjectName(_fromUtf8("fluorescentScreen2View"))
        self.gridLayout_2.addWidget(self.fluorescentScreen2View, 1, 1, 1, 1)
        self.layoutWidget14 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget14.setGeometry(QtCore.QRect(1040, 770, 201, 43))
        self.layoutWidget14.setObjectName(_fromUtf8("layoutWidget14"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget14)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.fluorescentScreen3Valve = actionForm(self.layoutWidget14)
        self.fluorescentScreen3Valve.setMinimumSize(QtCore.QSize(65, 0))
        self.fluorescentScreen3Valve.setObjectName(_fromUtf8("fluorescentScreen3Valve"))
        self.gridLayout_3.addWidget(self.fluorescentScreen3Valve, 0, 0, 2, 1)
        self.fluorescentScreen3Status = TaurusLabel(self.layoutWidget14)
        self.fluorescentScreen3Status.setMinimumSize(QtCore.QSize(50, 0))
        self.fluorescentScreen3Status.setObjectName(_fromUtf8("fluorescentScreen3Status"))
        self.gridLayout_3.addWidget(self.fluorescentScreen3Status, 0, 1, 1, 1)
        self.fluorescentScreen3Light = actionForm(self.layoutWidget14)
        self.fluorescentScreen3Light.setMinimumSize(QtCore.QSize(65, 0))
        self.fluorescentScreen3Light.setObjectName(_fromUtf8("fluorescentScreen3Light"))
        self.gridLayout_3.addWidget(self.fluorescentScreen3Light, 0, 2, 2, 1)
        self.fluorescentScreen3View = QtGui.QPushButton(self.layoutWidget14)
        self.fluorescentScreen3View.setMinimumSize(QtCore.QSize(50, 0))
        self.fluorescentScreen3View.setObjectName(_fromUtf8("fluorescentScreen3View"))
        self.gridLayout_3.addWidget(self.fluorescentScreen3View, 1, 1, 1, 1)

        self.retranslateUi(linacMainscreenSynoptic)
        QtCore.QMetaObject.connectSlotsByName(linacMainscreenSynoptic)

    def retranslateUi(self, linacMainscreenSynoptic):
        linacMainscreenSynoptic.setWindowTitle(QtGui.QApplication.translate("linacMainscreenSynoptic", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.cathodeLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Cathode V", None, QtGui.QApplication.UnicodeUTF8))
        self.filamentCurrent.setSuffixText(QtGui.QApplication.translate("linacMainscreenSynoptic", " A", None, QtGui.QApplication.UnicodeUTF8))
        self.temperatureValue.setSuffixText(QtGui.QApplication.translate("linacMainscreenSynoptic", " C", None, QtGui.QApplication.UnicodeUTF8))
        self.filamentILabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Filament I", None, QtGui.QApplication.UnicodeUTF8))
        self.temperatureLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.klystron1HVPopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.klystron2HVPopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.hvsPopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.attenuatorPopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseShifter2PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseShifter1PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.sl1PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.sl2PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.sl3PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.sl4PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.glPopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.as1PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.qtPopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.as2PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.tbWidthLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.tbNumberLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Number", None, QtGui.QApplication.UnicodeUTF8))
        self.tbGunDelayLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Gun Delay", None, QtGui.QApplication.UnicodeUTF8))
        self.multibunchLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "MBM", None, QtGui.QApplication.UnicodeUTF8))
        self.tbGatedPulseModeLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Gated Pulse Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Operation mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "dB", None, QtGui.QApplication.UnicodeUTF8))
        self.eGunVacuumCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Vacuum", None, QtGui.QApplication.UnicodeUTF8))
        self.preBuncherVacuumCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Vacuum", None, QtGui.QApplication.UnicodeUTF8))
        self.buncherVacuumCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Vacuum", None, QtGui.QApplication.UnicodeUTF8))
        self.as1VacuumCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Vacuum", None, QtGui.QApplication.UnicodeUTF8))
        self.as2VacuumCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Vacuum", None, QtGui.QApplication.UnicodeUTF8))
        self.tbKaDelay1Unit.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "us", None, QtGui.QApplication.UnicodeUTF8))
        self.tbKaDelay2Unit.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "ns", None, QtGui.QApplication.UnicodeUTF8))
        self.tbGunDelayUnit.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "ns", None, QtGui.QApplication.UnicodeUTF8))
        self.tbGunDelayUnit_2.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "ns", None, QtGui.QApplication.UnicodeUTF8))
        self.fluorescentScreen1View.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.fluorescentScreen2View.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.fluorescentScreen3View.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "View", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusLed, TaurusLabel
from attenuator import Attenuator
from phaseshifter import phaseShifter
from egunhv import eGunHV
from actionform import actionForm
from magnet import magnet
from taurus.qt.qtgui.panel import TaurusWidget
from cavityvacuum import CavityVacuum
from beamchargemonitors import beamChargeMonitors
from taurus.qt.qtgui.input import TaurusValueSpinBox, TaurusValueComboBox
from linacvaluecheckbox import LinacValueCheckBox
from klystronhv import klystronHV
