# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/ui/linacStartupSynoptic.ui'
#
# Created: Thu Nov 27 12:52:50 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_linacStartupSynoptic(object):
    def setupUi(self, linacStartupSynoptic):
        linacStartupSynoptic.setObjectName(_fromUtf8("linacStartupSynoptic"))
        linacStartupSynoptic.resize(1250, 825)
        linacStartupSynoptic.setMinimumSize(QtCore.QSize(1250, 825))
        linacStartupSynoptic.setMaximumSize(QtCore.QSize(1250, 825))
        linacStartupSynoptic.setAutoFillBackground(True)
        self.sl1Led = LinacLed(linacStartupSynoptic)
        self.sl1Led.setGeometry(QtCore.QRect(158, 475, 10, 10))
        self.sl1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sl1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sl1Led.setObjectName(_fromUtf8("sl1Led"))
        self.vacuumValve1OnLedInfo = LinacLed(linacStartupSynoptic)
        self.vacuumValve1OnLedInfo.setGeometry(QtCore.QRect(194, 515, 10, 10))
        self.vacuumValve1OnLedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.vacuumValve1OnLedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.vacuumValve1OnLedInfo.setObjectName(_fromUtf8("vacuumValve1OnLedInfo"))
        self.sl2Led = LinacLed(linacStartupSynoptic)
        self.sl2Led.setGeometry(QtCore.QRect(242, 475, 10, 10))
        self.sl2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sl2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sl2Led.setObjectName(_fromUtf8("sl2Led"))
        self.sl3Led = LinacLed(linacStartupSynoptic)
        self.sl3Led.setGeometry(QtCore.QRect(326, 475, 10, 10))
        self.sl3Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sl3Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sl3Led.setObjectName(_fromUtf8("sl3Led"))
        self.sl4Led = LinacLed(linacStartupSynoptic)
        self.sl4Led.setGeometry(QtCore.QRect(398, 475, 10, 10))
        self.sl4Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sl4Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sl4Led.setObjectName(_fromUtf8("sl4Led"))
        self.bc1Led = LinacLed(linacStartupSynoptic)
        self.bc1Led.setGeometry(QtCore.QRect(460, 475, 10, 10))
        self.bc1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.bc1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.bc1Led.setObjectName(_fromUtf8("bc1Led"))
        self.bc2Led = LinacLed(linacStartupSynoptic)
        self.bc2Led.setGeometry(QtCore.QRect(505, 475, 10, 10))
        self.bc2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.bc2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.bc2Led.setObjectName(_fromUtf8("bc2Led"))
        self.coolingLoop1TemperatureValue = TaurusValueSpinBox(linacStartupSynoptic)
        self.coolingLoop1TemperatureValue.setGeometry(QtCore.QRect(454, 390, 70, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.coolingLoop1TemperatureValue.setFont(font)
        self.coolingLoop1TemperatureValue.setObjectName(_fromUtf8("coolingLoop1TemperatureValue"))
        self.vacuumValve2OnLedInfo = LinacLed(linacStartupSynoptic)
        self.vacuumValve2OnLedInfo.setGeometry(QtCore.QRect(555, 515, 10, 10))
        self.vacuumValve2OnLedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.vacuumValve2OnLedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.vacuumValve2OnLedInfo.setObjectName(_fromUtf8("vacuumValve2OnLedInfo"))
        self.glLed = LinacLed(linacStartupSynoptic)
        self.glLed.setGeometry(QtCore.QRect(640, 475, 10, 10))
        self.glLed.setMinimumSize(QtCore.QSize(10, 10))
        self.glLed.setMaximumSize(QtCore.QSize(10, 10))
        self.glLed.setObjectName(_fromUtf8("glLed"))
        self.vacuumValve3OnLedInfo = LinacLed(linacStartupSynoptic)
        self.vacuumValve3OnLedInfo.setGeometry(QtCore.QRect(675, 515, 10, 10))
        self.vacuumValve3OnLedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.vacuumValve3OnLedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.vacuumValve3OnLedInfo.setObjectName(_fromUtf8("vacuumValve3OnLedInfo"))
        self.coolingLoop2TemperatureValue = TaurusValueSpinBox(linacStartupSynoptic)
        self.coolingLoop2TemperatureValue.setGeometry(QtCore.QRect(665, 390, 70, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.coolingLoop2TemperatureValue.setFont(font)
        self.coolingLoop2TemperatureValue.setObjectName(_fromUtf8("coolingLoop2TemperatureValue"))
        self.vacuumValve4OnLedInfo = LinacLed(linacStartupSynoptic)
        self.vacuumValve4OnLedInfo.setGeometry(QtCore.QRect(808, 515, 10, 10))
        self.vacuumValve4OnLedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.vacuumValve4OnLedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.vacuumValve4OnLedInfo.setObjectName(_fromUtf8("vacuumValve4OnLedInfo"))
        self.vacuumValve5OnLedInfo = LinacLed(linacStartupSynoptic)
        self.vacuumValve5OnLedInfo.setGeometry(QtCore.QRect(963, 515, 10, 10))
        self.vacuumValve5OnLedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.vacuumValve5OnLedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.vacuumValve5OnLedInfo.setObjectName(_fromUtf8("vacuumValve5OnLedInfo"))
        self.coolingLoop3TemperatureValue = TaurusValueSpinBox(linacStartupSynoptic)
        self.coolingLoop3TemperatureValue.setGeometry(QtCore.QRect(945, 390, 70, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.coolingLoop3TemperatureValue.setFont(font)
        self.coolingLoop3TemperatureValue.setObjectName(_fromUtf8("coolingLoop3TemperatureValue"))
        self.vacuumValve6OnLedInfo = LinacLed(linacStartupSynoptic)
        self.vacuumValve6OnLedInfo.setGeometry(QtCore.QRect(1096, 515, 10, 10))
        self.vacuumValve6OnLedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.vacuumValve6OnLedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.vacuumValve6OnLedInfo.setObjectName(_fromUtf8("vacuumValve6OnLedInfo"))
        self.vacuumValve7OnLedInfo = LinacLed(linacStartupSynoptic)
        self.vacuumValve7OnLedInfo.setGeometry(QtCore.QRect(1216, 515, 10, 10))
        self.vacuumValve7OnLedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.vacuumValve7OnLedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.vacuumValve7OnLedInfo.setObjectName(_fromUtf8("vacuumValve7OnLedInfo"))
        self.ip1Led = LinacLed(linacStartupSynoptic)
        self.ip1Led.setGeometry(QtCore.QRect(24, 645, 10, 10))
        self.ip1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip1Led.setObjectName(_fromUtf8("ip1Led"))
        self.ip2Led = LinacLed(linacStartupSynoptic)
        self.ip2Led.setGeometry(QtCore.QRect(78, 646, 10, 10))
        self.ip2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip2Led.setObjectName(_fromUtf8("ip2Led"))
        self.ip3Led = LinacLed(linacStartupSynoptic)
        self.ip3Led.setGeometry(QtCore.QRect(304, 634, 10, 10))
        self.ip3Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip3Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip3Led.setObjectName(_fromUtf8("ip3Led"))
        self.ip4Led = LinacLed(linacStartupSynoptic)
        self.ip4Led.setGeometry(QtCore.QRect(457, 634, 10, 10))
        self.ip4Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip4Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip4Led.setObjectName(_fromUtf8("ip4Led"))
        self.ip5Led = LinacLed(linacStartupSynoptic)
        self.ip5Led.setGeometry(QtCore.QRect(611, 645, 10, 10))
        self.ip5Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip5Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip5Led.setObjectName(_fromUtf8("ip5Led"))
        self.ip6Led = LinacLed(linacStartupSynoptic)
        self.ip6Led.setGeometry(QtCore.QRect(714, 645, 10, 10))
        self.ip6Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip6Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip6Led.setObjectName(_fromUtf8("ip6Led"))
        self.ip7Led = LinacLed(linacStartupSynoptic)
        self.ip7Led.setGeometry(QtCore.QRect(863, 645, 10, 10))
        self.ip7Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip7Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip7Led.setObjectName(_fromUtf8("ip7Led"))
        self.ip8Led = LinacLed(linacStartupSynoptic)
        self.ip8Led.setGeometry(QtCore.QRect(1005, 645, 10, 10))
        self.ip8Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip8Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip8Led.setObjectName(_fromUtf8("ip8Led"))
        self.ip9Led = LinacLed(linacStartupSynoptic)
        self.ip9Led.setGeometry(QtCore.QRect(1140, 645, 10, 10))
        self.ip9Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip9Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip9Led.setObjectName(_fromUtf8("ip9Led"))
        self.hvg1Led = LinacLed(linacStartupSynoptic)
        self.hvg1Led.setGeometry(QtCore.QRect(144, 692, 10, 10))
        self.hvg1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.hvg1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.hvg1Led.setObjectName(_fromUtf8("hvg1Led"))
        self.hvg2Led = LinacLed(linacStartupSynoptic)
        self.hvg2Led.setGeometry(QtCore.QRect(300, 691, 10, 10))
        self.hvg2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.hvg2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.hvg2Led.setObjectName(_fromUtf8("hvg2Led"))
        self.hvg3Led = LinacLed(linacStartupSynoptic)
        self.hvg3Led.setGeometry(QtCore.QRect(505, 690, 10, 10))
        self.hvg3Led.setMinimumSize(QtCore.QSize(10, 10))
        self.hvg3Led.setMaximumSize(QtCore.QSize(10, 10))
        self.hvg3Led.setObjectName(_fromUtf8("hvg3Led"))
        self.hvg4Led = LinacLed(linacStartupSynoptic)
        self.hvg4Led.setGeometry(QtCore.QRect(793, 690, 10, 10))
        self.hvg4Led.setMinimumSize(QtCore.QSize(10, 10))
        self.hvg4Led.setMaximumSize(QtCore.QSize(10, 10))
        self.hvg4Led.setObjectName(_fromUtf8("hvg4Led"))
        self.hvg5Led = LinacLed(linacStartupSynoptic)
        self.hvg5Led.setGeometry(QtCore.QRect(1075, 690, 10, 10))
        self.hvg5Led.setMinimumSize(QtCore.QSize(10, 10))
        self.hvg5Led.setMaximumSize(QtCore.QSize(10, 10))
        self.hvg5Led.setObjectName(_fromUtf8("hvg5Led"))
        self.ipc1Value1 = TaurusLabel(linacStartupSynoptic)
        self.ipc1Value1.setGeometry(QtCore.QRect(20, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc1Value1.setFont(font)
        self.ipc1Value1.setObjectName(_fromUtf8("ipc1Value1"))
        self.ipc1Value2 = TaurusLabel(linacStartupSynoptic)
        self.ipc1Value2.setGeometry(QtCore.QRect(20, 740, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc1Value2.setFont(font)
        self.ipc1Value2.setObjectName(_fromUtf8("ipc1Value2"))
        self.hvg1Value = TaurusLabel(linacStartupSynoptic)
        self.hvg1Value.setGeometry(QtCore.QRect(100, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.hvg1Value.setFont(font)
        self.hvg1Value.setObjectName(_fromUtf8("hvg1Value"))
        self.hvg2Value = TaurusLabel(linacStartupSynoptic)
        self.hvg2Value.setGeometry(QtCore.QRect(240, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.hvg2Value.setFont(font)
        self.hvg2Value.setObjectName(_fromUtf8("hvg2Value"))
        self.ipc2Value1 = TaurusLabel(linacStartupSynoptic)
        self.ipc2Value1.setGeometry(QtCore.QRect(350, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc2Value1.setFont(font)
        self.ipc2Value1.setObjectName(_fromUtf8("ipc2Value1"))
        self.ipc2Value2 = TaurusLabel(linacStartupSynoptic)
        self.ipc2Value2.setGeometry(QtCore.QRect(350, 740, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc2Value2.setFont(font)
        self.ipc2Value2.setObjectName(_fromUtf8("ipc2Value2"))
        self.hvg3Value = TaurusLabel(linacStartupSynoptic)
        self.hvg3Value.setGeometry(QtCore.QRect(450, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.hvg3Value.setFont(font)
        self.hvg3Value.setObjectName(_fromUtf8("hvg3Value"))
        self.ipc3Value1 = TaurusLabel(linacStartupSynoptic)
        self.ipc3Value1.setGeometry(QtCore.QRect(590, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc3Value1.setFont(font)
        self.ipc3Value1.setObjectName(_fromUtf8("ipc3Value1"))
        self.ipc3Value2 = TaurusLabel(linacStartupSynoptic)
        self.ipc3Value2.setGeometry(QtCore.QRect(590, 740, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc3Value2.setFont(font)
        self.ipc3Value2.setObjectName(_fromUtf8("ipc3Value2"))
        self.hvg4Value = TaurusLabel(linacStartupSynoptic)
        self.hvg4Value.setGeometry(QtCore.QRect(730, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.hvg4Value.setFont(font)
        self.hvg4Value.setObjectName(_fromUtf8("hvg4Value"))
        self.ipc4Value1 = TaurusLabel(linacStartupSynoptic)
        self.ipc4Value1.setGeometry(QtCore.QRect(840, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc4Value1.setFont(font)
        self.ipc4Value1.setObjectName(_fromUtf8("ipc4Value1"))
        self.ipc4Value2 = TaurusLabel(linacStartupSynoptic)
        self.ipc4Value2.setGeometry(QtCore.QRect(840, 740, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc4Value2.setFont(font)
        self.ipc4Value2.setObjectName(_fromUtf8("ipc4Value2"))
        self.hvg5Value = TaurusLabel(linacStartupSynoptic)
        self.hvg5Value.setGeometry(QtCore.QRect(1020, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.hvg5Value.setFont(font)
        self.hvg5Value.setObjectName(_fromUtf8("hvg5Value"))
        self.ipc5Value1 = TaurusLabel(linacStartupSynoptic)
        self.ipc5Value1.setGeometry(QtCore.QRect(1110, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc5Value1.setFont(font)
        self.ipc5Value1.setObjectName(_fromUtf8("ipc5Value1"))
        self.klystron2LVWidget = klystronLV(linacStartupSynoptic)
        self.klystron2LVWidget.setGeometry(QtCore.QRect(1062, 10, 188, 255))
        self.klystron2LVWidget.setAutoFillBackground(True)
        self.klystron2LVWidget.setObjectName(_fromUtf8("klystron2LVWidget"))
        self.klystron1LVWidget = klystronLV(linacStartupSynoptic)
        self.klystron1LVWidget.setGeometry(QtCore.QRect(776, 10, 188, 255))
        self.klystron1LVWidget.setObjectName(_fromUtf8("klystron1LVWidget"))
        self.vacuumValve1OnStatus = TaurusLabel(linacStartupSynoptic)
        self.vacuumValve1OnStatus.setGeometry(QtCore.QRect(165, 605, 70, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve1OnStatus.setFont(font)
        self.vacuumValve1OnStatus.setObjectName(_fromUtf8("vacuumValve1OnStatus"))
        self.vacuumValve2OnStatus = TaurusLabel(linacStartupSynoptic)
        self.vacuumValve2OnStatus.setGeometry(QtCore.QRect(524, 605, 70, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve2OnStatus.setFont(font)
        self.vacuumValve2OnStatus.setObjectName(_fromUtf8("vacuumValve2OnStatus"))
        self.vacuumValve3OnStatus = TaurusLabel(linacStartupSynoptic)
        self.vacuumValve3OnStatus.setGeometry(QtCore.QRect(643, 605, 70, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve3OnStatus.setFont(font)
        self.vacuumValve3OnStatus.setObjectName(_fromUtf8("vacuumValve3OnStatus"))
        self.vacuumValve4OnStatus = TaurusLabel(linacStartupSynoptic)
        self.vacuumValve4OnStatus.setGeometry(QtCore.QRect(776, 605, 70, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve4OnStatus.setFont(font)
        self.vacuumValve4OnStatus.setObjectName(_fromUtf8("vacuumValve4OnStatus"))
        self.vacuumValve5OnStatus = TaurusLabel(linacStartupSynoptic)
        self.vacuumValve5OnStatus.setGeometry(QtCore.QRect(931, 605, 70, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve5OnStatus.setFont(font)
        self.vacuumValve5OnStatus.setObjectName(_fromUtf8("vacuumValve5OnStatus"))
        self.vacuumValve6OnStatus = TaurusLabel(linacStartupSynoptic)
        self.vacuumValve6OnStatus.setGeometry(QtCore.QRect(1065, 605, 70, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve6OnStatus.setFont(font)
        self.vacuumValve6OnStatus.setObjectName(_fromUtf8("vacuumValve6OnStatus"))
        self.vacuumValve7OnStatus = TaurusLabel(linacStartupSynoptic)
        self.vacuumValve7OnStatus.setGeometry(QtCore.QRect(1168, 604, 70, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve7OnStatus.setFont(font)
        self.vacuumValve7OnStatus.setObjectName(_fromUtf8("vacuumValve7OnStatus"))
        self.coolingLoop1Widget = CoolingLoop(linacStartupSynoptic)
        self.coolingLoop1Widget.setGeometry(QtCore.QRect(526, 300, 170, 150))
        self.coolingLoop1Widget.setObjectName(_fromUtf8("coolingLoop1Widget"))
        self.coolingLoop2Widget = CoolingLoop(linacStartupSynoptic)
        self.coolingLoop2Widget.setGeometry(QtCore.QRect(745, 300, 200, 150))
        self.coolingLoop2Widget.setObjectName(_fromUtf8("coolingLoop2Widget"))
        self.coolingLoop3Widget = CoolingLoop(linacStartupSynoptic)
        self.coolingLoop3Widget.setGeometry(QtCore.QRect(1030, 300, 200, 150))
        self.coolingLoop3Widget.setObjectName(_fromUtf8("coolingLoop3Widget"))
        self.qtLed = LinacLed(linacStartupSynoptic)
        self.qtLed.setGeometry(QtCore.QRect(915, 475, 10, 10))
        self.qtLed.setMinimumSize(QtCore.QSize(10, 10))
        self.qtLed.setMaximumSize(QtCore.QSize(10, 10))
        self.qtLed.setObjectName(_fromUtf8("qtLed"))
        self.as1Led = LinacLed(linacStartupSynoptic)
        self.as1Led.setGeometry(QtCore.QRect(743, 497, 10, 10))
        self.as1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.as1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.as1Led.setObjectName(_fromUtf8("as1Led"))
        self.as2Led = LinacLed(linacStartupSynoptic)
        self.as2Led.setGeometry(QtCore.QRect(1030, 497, 10, 10))
        self.as2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.as2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.as2Led.setObjectName(_fromUtf8("as2Led"))
        self.klystron2InterlockPopupWidget = klystron2itck(linacStartupSynoptic)
        self.klystron2InterlockPopupWidget.setGeometry(QtCore.QRect(350, 10, 183, 100))
        self.klystron2InterlockPopupWidget.setObjectName(_fromUtf8("klystron2InterlockPopupWidget"))
        self.klystron1InterlockPopupWidget = klystron1itck(linacStartupSynoptic)
        self.klystron1InterlockPopupWidget.setGeometry(QtCore.QRect(350, 110, 183, 140))
        self.klystron1InterlockPopupWidget.setObjectName(_fromUtf8("klystron1InterlockPopupWidget"))
        self.layoutWidget = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 390, 128, 94))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.KDLayout = QtGui.QGridLayout(self.layoutWidget)
        self.KDLayout.setContentsMargins(3, -1, -1, -1)
        self.KDLayout.setObjectName(_fromUtf8("KDLayout"))
        self.filamentSetpoint = TaurusValueSpinBox(self.layoutWidget)
        self.filamentSetpoint.setMinimumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.filamentSetpoint.setFont(font)
        self.filamentSetpoint.setAutoApply(False)
        self.filamentSetpoint.setObjectName(_fromUtf8("filamentSetpoint"))
        self.KDLayout.addWidget(self.filamentSetpoint, 0, 0, 1, 1)
        self.cathodeSetpoint = TaurusValueSpinBox(self.layoutWidget)
        self.cathodeSetpoint.setMinimumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cathodeSetpoint.setFont(font)
        self.cathodeSetpoint.setAutoApply(True)
        self.cathodeSetpoint.setObjectName(_fromUtf8("cathodeSetpoint"))
        self.KDLayout.addWidget(self.cathodeSetpoint, 0, 1, 1, 1)
        self.filamentVLabel = QtGui.QLabel(self.layoutWidget)
        self.filamentVLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.filamentVLabel.setFont(font)
        self.filamentVLabel.setObjectName(_fromUtf8("filamentVLabel"))
        self.KDLayout.addWidget(self.filamentVLabel, 1, 0, 1, 1)
        self.cathodeLabel = QtGui.QLabel(self.layoutWidget)
        self.cathodeLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.cathodeLabel.setFont(font)
        self.cathodeLabel.setObjectName(_fromUtf8("cathodeLabel"))
        self.KDLayout.addWidget(self.cathodeLabel, 1, 1, 1, 1)
        self.filamentCurrent = TaurusLabel(self.layoutWidget)
        self.filamentCurrent.setMinimumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.filamentCurrent.setFont(font)
        self.filamentCurrent.setSuffixText(_fromUtf8(""))
        self.filamentCurrent.setObjectName(_fromUtf8("filamentCurrent"))
        self.KDLayout.addWidget(self.filamentCurrent, 2, 0, 1, 1)
        self.temperatureValue = TaurusLabel(self.layoutWidget)
        self.temperatureValue.setMinimumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.temperatureValue.setFont(font)
        self.temperatureValue.setSuffixText(_fromUtf8(""))
        self.temperatureValue.setObjectName(_fromUtf8("temperatureValue"))
        self.KDLayout.addWidget(self.temperatureValue, 2, 1, 1, 1)
        self.filamentILabel = QtGui.QLabel(self.layoutWidget)
        self.filamentILabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.filamentILabel.setFont(font)
        self.filamentILabel.setObjectName(_fromUtf8("filamentILabel"))
        self.KDLayout.addWidget(self.filamentILabel, 3, 0, 1, 1)
        self.temperatureLabel = QtGui.QLabel(self.layoutWidget)
        self.temperatureLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.temperatureLabel.setFont(font)
        self.temperatureLabel.setObjectName(_fromUtf8("temperatureLabel"))
        self.KDLayout.addWidget(self.temperatureLabel, 3, 1, 1, 1)
        self.kdeGunLVWidget = eGunLV(linacStartupSynoptic)
        self.kdeGunLVWidget.setGeometry(QtCore.QRect(155, 343, 180, 111))
        self.kdeGunLVWidget.setObjectName(_fromUtf8("kdeGunLVWidget"))
        self.klystronAmplifierEnabledLed = LinacLed(linacStartupSynoptic)
        self.klystronAmplifierEnabledLed.setGeometry(QtCore.QRect(70, 40, 10, 10))
        self.klystronAmplifierEnabledLed.setMinimumSize(QtCore.QSize(10, 10))
        self.klystronAmplifierEnabledLed.setMaximumSize(QtCore.QSize(10, 10))
        self.klystronAmplifierEnabledLed.setObjectName(_fromUtf8("klystronAmplifierEnabledLed"))
        self.magnetInterlockStateLed = LinacLed(linacStartupSynoptic)
        self.magnetInterlockStateLed.setGeometry(QtCore.QRect(125, 71, 10, 10))
        self.magnetInterlockStateLed.setMinimumSize(QtCore.QSize(10, 10))
        self.magnetInterlockStateLed.setMaximumSize(QtCore.QSize(10, 10))
        self.magnetInterlockStateLed.setObjectName(_fromUtf8("magnetInterlockStateLed"))
        self.utilitiesInterlockStateLed = LinacLed(linacStartupSynoptic)
        self.utilitiesInterlockStateLed.setGeometry(QtCore.QRect(125, 143, 10, 10))
        self.utilitiesInterlockStateLed.setMinimumSize(QtCore.QSize(10, 10))
        self.utilitiesInterlockStateLed.setMaximumSize(QtCore.QSize(10, 10))
        self.utilitiesInterlockStateLed.setObjectName(_fromUtf8("utilitiesInterlockStateLed"))
        self.compressedAirStateLed = LinacLed(linacStartupSynoptic)
        self.compressedAirStateLed.setGeometry(QtCore.QRect(125, 165, 10, 10))
        self.compressedAirStateLed.setMinimumSize(QtCore.QSize(10, 10))
        self.compressedAirStateLed.setMaximumSize(QtCore.QSize(10, 10))
        self.compressedAirStateLed.setObjectName(_fromUtf8("compressedAirStateLed"))
        self.transferlineVacuumStateLed = LinacLed(linacStartupSynoptic)
        self.transferlineVacuumStateLed.setGeometry(QtCore.QRect(70, 179, 10, 10))
        self.transferlineVacuumStateLed.setMinimumSize(QtCore.QSize(10, 10))
        self.transferlineVacuumStateLed.setMaximumSize(QtCore.QSize(10, 10))
        self.transferlineVacuumStateLed.setObjectName(_fromUtf8("transferlineVacuumStateLed"))
        self.linacVacuumStateLed = LinacLed(linacStartupSynoptic)
        self.linacVacuumStateLed.setGeometry(QtCore.QRect(125, 191, 10, 10))
        self.linacVacuumStateLed.setMinimumSize(QtCore.QSize(10, 10))
        self.linacVacuumStateLed.setMaximumSize(QtCore.QSize(10, 10))
        self.linacVacuumStateLed.setObjectName(_fromUtf8("linacVacuumStateLed"))
        self.electronGunEnabledLed = LinacLed(linacStartupSynoptic)
        self.electronGunEnabledLed.setGeometry(QtCore.QRect(70, 203, 10, 10))
        self.electronGunEnabledLed.setMinimumSize(QtCore.QSize(10, 10))
        self.electronGunEnabledLed.setMaximumSize(QtCore.QSize(10, 10))
        self.electronGunEnabledLed.setObjectName(_fromUtf8("electronGunEnabledLed"))
        self.gmdiLed = LinacLed(linacStartupSynoptic)
        self.gmdiLed.setGeometry(QtCore.QRect(125, 218, 10, 10))
        self.gmdiLed.setMinimumSize(QtCore.QSize(10, 10))
        self.gmdiLed.setMaximumSize(QtCore.QSize(10, 10))
        self.gmdiLed.setObjectName(_fromUtf8("gmdiLed"))
        self.interlockUnitReadyStateLed = LinacLed(linacStartupSynoptic)
        self.interlockUnitReadyStateLed.setGeometry(QtCore.QRect(271, 19, 10, 10))
        self.interlockUnitReadyStateLed.setMinimumSize(QtCore.QSize(10, 10))
        self.interlockUnitReadyStateLed.setMaximumSize(QtCore.QSize(10, 10))
        self.interlockUnitReadyStateLed.setObjectName(_fromUtf8("interlockUnitReadyStateLed"))
        self.klystron2AmplifierEnabledLed = LinacLed(linacStartupSynoptic)
        self.klystron2AmplifierEnabledLed.setGeometry(QtCore.QRect(280, 48, 10, 10))
        self.klystron2AmplifierEnabledLed.setMinimumSize(QtCore.QSize(10, 10))
        self.klystron2AmplifierEnabledLed.setMaximumSize(QtCore.QSize(10, 10))
        self.klystron2AmplifierEnabledLed.setObjectName(_fromUtf8("klystron2AmplifierEnabledLed"))
        self.klystron1AmplifierEnabledLed = LinacLed(linacStartupSynoptic)
        self.klystron1AmplifierEnabledLed.setGeometry(QtCore.QRect(280, 118, 10, 10))
        self.klystron1AmplifierEnabledLed.setMinimumSize(QtCore.QSize(10, 10))
        self.klystron1AmplifierEnabledLed.setMaximumSize(QtCore.QSize(10, 10))
        self.klystron1AmplifierEnabledLed.setObjectName(_fromUtf8("klystron1AmplifierEnabledLed"))
        self.linacVacuumStateLed_2 = LinacLed(linacStartupSynoptic)
        self.linacVacuumStateLed_2.setGeometry(QtCore.QRect(280, 168, 10, 10))
        self.linacVacuumStateLed_2.setMinimumSize(QtCore.QSize(10, 10))
        self.linacVacuumStateLed_2.setMaximumSize(QtCore.QSize(10, 10))
        self.linacVacuumStateLed_2.setObjectName(_fromUtf8("linacVacuumStateLed_2"))
        self.linacReadyStateLed = LinacLed(linacStartupSynoptic)
        self.linacReadyStateLed.setGeometry(QtCore.QRect(280, 192, 10, 10))
        self.linacReadyStateLed.setMinimumSize(QtCore.QSize(10, 10))
        self.linacReadyStateLed.setMaximumSize(QtCore.QSize(10, 10))
        self.linacReadyStateLed.setObjectName(_fromUtf8("linacReadyStateLed"))
        self.StartUpSchematic = QtGui.QLabel(linacStartupSynoptic)
        self.StartUpSchematic.setGeometry(QtCore.QRect(0, 0, 1250, 825))
        self.StartUpSchematic.setText(_fromUtf8(""))
        self.StartUpSchematic.setPixmap(QtGui.QPixmap(_fromUtf8("jdraw/linac_startup_synoptic.png")))
        self.StartUpSchematic.setObjectName(_fromUtf8("StartUpSchematic"))
        self.w1Led = LinacLed(linacStartupSynoptic)
        self.w1Led.setGeometry(QtCore.QRect(500, 430, 10, 10))
        self.w1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.w1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.w1Led.setObjectName(_fromUtf8("w1Led"))
        self.w2Led = LinacLed(linacStartupSynoptic)
        self.w2Led.setGeometry(QtCore.QRect(716, 430, 10, 10))
        self.w2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.w2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.w2Led.setObjectName(_fromUtf8("w2Led"))
        self.w3Led = LinacLed(linacStartupSynoptic)
        self.w3Led.setGeometry(QtCore.QRect(1005, 430, 10, 10))
        self.w3Led.setMinimumSize(QtCore.QSize(10, 10))
        self.w3Led.setMaximumSize(QtCore.QSize(10, 10))
        self.w3Led.setObjectName(_fromUtf8("w3Led"))
        self.rl1Led = LinacLed(linacStartupSynoptic)
        self.rl1Led.setGeometry(QtCore.QRect(571, 450, 10, 10))
        self.rl1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.rl1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.rl1Led.setObjectName(_fromUtf8("rl1Led"))
        self.rl2Led = LinacLed(linacStartupSynoptic)
        self.rl2Led.setGeometry(QtCore.QRect(784, 450, 10, 10))
        self.rl2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.rl2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.rl2Led.setObjectName(_fromUtf8("rl2Led"))
        self.rl3Led = LinacLed(linacStartupSynoptic)
        self.rl3Led.setGeometry(QtCore.QRect(1070, 450, 10, 10))
        self.rl3Led.setMinimumSize(QtCore.QSize(10, 10))
        self.rl3Led.setMaximumSize(QtCore.QSize(10, 10))
        self.rl3Led.setObjectName(_fromUtf8("rl3Led"))
        self.klystron1LVPopupCheck = QtGui.QToolButton(linacStartupSynoptic)
        self.klystron1LVPopupCheck.setGeometry(QtCore.QRect(750, 100, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.klystron1LVPopupCheck.setFont(font)
        self.klystron1LVPopupCheck.setCheckable(True)
        self.klystron1LVPopupCheck.setObjectName(_fromUtf8("klystron1LVPopupCheck"))
        self.klystron2LVPopupCheck = QtGui.QToolButton(linacStartupSynoptic)
        self.klystron2LVPopupCheck.setGeometry(QtCore.QRect(1040, 30, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.klystron2LVPopupCheck.setFont(font)
        self.klystron2LVPopupCheck.setCheckable(True)
        self.klystron2LVPopupCheck.setObjectName(_fromUtf8("klystron2LVPopupCheck"))
        self.kdeGunLVPopupCheck = QtGui.QToolButton(linacStartupSynoptic)
        self.kdeGunLVPopupCheck.setGeometry(QtCore.QRect(118, 366, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.kdeGunLVPopupCheck.setFont(font)
        self.kdeGunLVPopupCheck.setCheckable(True)
        self.kdeGunLVPopupCheck.setObjectName(_fromUtf8("kdeGunLVPopupCheck"))
        self.coolingLoop1PopupCheck = QtGui.QToolButton(linacStartupSynoptic)
        self.coolingLoop1PopupCheck.setGeometry(QtCore.QRect(503, 345, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.coolingLoop1PopupCheck.setFont(font)
        self.coolingLoop1PopupCheck.setCheckable(True)
        self.coolingLoop1PopupCheck.setObjectName(_fromUtf8("coolingLoop1PopupCheck"))
        self.coolingLoop2PopupCheck = QtGui.QToolButton(linacStartupSynoptic)
        self.coolingLoop2PopupCheck.setGeometry(QtCore.QRect(720, 345, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.coolingLoop2PopupCheck.setFont(font)
        self.coolingLoop2PopupCheck.setCheckable(True)
        self.coolingLoop2PopupCheck.setObjectName(_fromUtf8("coolingLoop2PopupCheck"))
        self.coolingLoop3PopupCheck = QtGui.QToolButton(linacStartupSynoptic)
        self.coolingLoop3PopupCheck.setGeometry(QtCore.QRect(1007, 345, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.coolingLoop3PopupCheck.setFont(font)
        self.coolingLoop3PopupCheck.setCheckable(True)
        self.coolingLoop3PopupCheck.setObjectName(_fromUtf8("coolingLoop3PopupCheck"))
        self.klystron2InterlockPopupCheck = QtGui.QToolButton(linacStartupSynoptic)
        self.klystron2InterlockPopupCheck.setGeometry(QtCore.QRect(140, 43, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.klystron2InterlockPopupCheck.setFont(font)
        self.klystron2InterlockPopupCheck.setCheckable(True)
        self.klystron2InterlockPopupCheck.setObjectName(_fromUtf8("klystron2InterlockPopupCheck"))
        self.klystron1InterlockPopupCheck = QtGui.QToolButton(linacStartupSynoptic)
        self.klystron1InterlockPopupCheck.setGeometry(QtCore.QRect(140, 114, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.klystron1InterlockPopupCheck.setFont(font)
        self.klystron1InterlockPopupCheck.setCheckable(True)
        self.klystron1InterlockPopupCheck.setObjectName(_fromUtf8("klystron1InterlockPopupCheck"))
        self.klystron1On = actionForm(linacStartupSynoptic)
        self.klystron1On.setGeometry(QtCore.QRect(717, 170, 60, 40))
        self.klystron1On.setObjectName(_fromUtf8("klystron1On"))
        self.klystron1Rst = actionForm(linacStartupSynoptic)
        self.klystron1Rst.setGeometry(QtCore.QRect(717, 210, 60, 40))
        self.klystron1Rst.setObjectName(_fromUtf8("klystron1Rst"))
        self.klystron2On = actionForm(linacStartupSynoptic)
        self.klystron2On.setGeometry(QtCore.QRect(1006, 170, 60, 40))
        self.klystron2On.setObjectName(_fromUtf8("klystron2On"))
        self.klystron2Rst = actionForm(linacStartupSynoptic)
        self.klystron2Rst.setGeometry(QtCore.QRect(1006, 210, 60, 40))
        self.klystron2Rst.setObjectName(_fromUtf8("klystron2Rst"))
        self.coolingLoop1On = actionForm(linacStartupSynoptic)
        self.coolingLoop1On.setGeometry(QtCore.QRect(416, 262, 60, 40))
        self.coolingLoop1On.setObjectName(_fromUtf8("coolingLoop1On"))
        self.coolingLoop2On = actionForm(linacStartupSynoptic)
        self.coolingLoop2On.setGeometry(QtCore.QRect(629, 262, 60, 40))
        self.coolingLoop2On.setObjectName(_fromUtf8("coolingLoop2On"))
        self.coolingLoop3On = actionForm(linacStartupSynoptic)
        self.coolingLoop3On.setGeometry(QtCore.QRect(916, 262, 60, 40))
        self.coolingLoop3On.setObjectName(_fromUtf8("coolingLoop3On"))
        self.eGunOn = actionForm(linacStartupSynoptic)
        self.eGunOn.setGeometry(QtCore.QRect(15, 300, 60, 40))
        self.eGunOn.setObjectName(_fromUtf8("eGunOn"))
        self.vvRst = actionForm(linacStartupSynoptic)
        self.vvRst.setGeometry(QtCore.QRect(0, 503, 60, 55))
        self.vvRst.setObjectName(_fromUtf8("vvRst"))
        self.vvOn = actionForm(linacStartupSynoptic)
        self.vvOn.setGeometry(QtCore.QRect(70, 763, 60, 40))
        self.vvOn.setObjectName(_fromUtf8("vvOn"))
        self.vacuumValve1On = actionForm(linacStartupSynoptic)
        self.vacuumValve1On.setGeometry(QtCore.QRect(170, 763, 60, 40))
        self.vacuumValve1On.setObjectName(_fromUtf8("vacuumValve1On"))
        self.vacuumValve2On = actionForm(linacStartupSynoptic)
        self.vacuumValve2On.setGeometry(QtCore.QRect(529, 763, 60, 40))
        self.vacuumValve2On.setObjectName(_fromUtf8("vacuumValve2On"))
        self.vacuumValve3On = actionForm(linacStartupSynoptic)
        self.vacuumValve3On.setGeometry(QtCore.QRect(650, 763, 60, 40))
        self.vacuumValve3On.setObjectName(_fromUtf8("vacuumValve3On"))
        self.vacuumValve4On = actionForm(linacStartupSynoptic)
        self.vacuumValve4On.setGeometry(QtCore.QRect(783, 763, 60, 40))
        self.vacuumValve4On.setObjectName(_fromUtf8("vacuumValve4On"))
        self.vacuumValve5On = actionForm(linacStartupSynoptic)
        self.vacuumValve5On.setGeometry(QtCore.QRect(938, 763, 60, 40))
        self.vacuumValve5On.setObjectName(_fromUtf8("vacuumValve5On"))
        self.vacuumValve6On = actionForm(linacStartupSynoptic)
        self.vacuumValve6On.setGeometry(QtCore.QRect(1070, 763, 60, 40))
        self.vacuumValve6On.setObjectName(_fromUtf8("vacuumValve6On"))
        self.vacuumValve7On = actionForm(linacStartupSynoptic)
        self.vacuumValve7On.setGeometry(QtCore.QRect(1180, 763, 60, 40))
        self.vacuumValve7On.setObjectName(_fromUtf8("vacuumValve7On"))
        self.iuRst = actionForm(linacStartupSynoptic)
        self.iuRst.setGeometry(QtCore.QRect(20, 73, 60, 55))
        self.iuRst.setObjectName(_fromUtf8("iuRst"))
        self.kdeGunLVLed = LinacLed(linacStartupSynoptic)
        self.kdeGunLVLed.setGeometry(QtCore.QRect(100, 370, 10, 10))
        self.kdeGunLVLed.setMinimumSize(QtCore.QSize(10, 10))
        self.kdeGunLVLed.setMaximumSize(QtCore.QSize(10, 10))
        self.kdeGunLVLed.setObjectName(_fromUtf8("kdeGunLVLed"))
        self.klystron2InterlockLed = LinacLed(linacStartupSynoptic)
        self.klystron2InterlockLed.setGeometry(QtCore.QRect(125, 48, 10, 10))
        self.klystron2InterlockLed.setMinimumSize(QtCore.QSize(10, 10))
        self.klystron2InterlockLed.setMaximumSize(QtCore.QSize(10, 10))
        self.klystron2InterlockLed.setObjectName(_fromUtf8("klystron2InterlockLed"))
        self.klystron1InterlockLed = LinacLed(linacStartupSynoptic)
        self.klystron1InterlockLed.setGeometry(QtCore.QRect(125, 120, 10, 10))
        self.klystron1InterlockLed.setMinimumSize(QtCore.QSize(10, 10))
        self.klystron1InterlockLed.setMaximumSize(QtCore.QSize(10, 10))
        self.klystron1InterlockLed.setObjectName(_fromUtf8("klystron1InterlockLed"))
        self.coolingLoop1Led = LinacLed(linacStartupSynoptic)
        self.coolingLoop1Led.setGeometry(QtCore.QRect(508, 334, 10, 10))
        self.coolingLoop1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.coolingLoop1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.coolingLoop1Led.setObjectName(_fromUtf8("coolingLoop1Led"))
        self.coolingLoop2Led = LinacLed(linacStartupSynoptic)
        self.coolingLoop2Led.setGeometry(QtCore.QRect(724, 334, 10, 10))
        self.coolingLoop2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.coolingLoop2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.coolingLoop2Led.setObjectName(_fromUtf8("coolingLoop2Led"))
        self.coolingLoop3Led = LinacLed(linacStartupSynoptic)
        self.coolingLoop3Led.setGeometry(QtCore.QRect(1012, 334, 10, 10))
        self.coolingLoop3Led.setMinimumSize(QtCore.QSize(10, 10))
        self.coolingLoop3Led.setMaximumSize(QtCore.QSize(10, 10))
        self.coolingLoop3Led.setObjectName(_fromUtf8("coolingLoop3Led"))
        self.klystron1LVLed = LinacLed(linacStartupSynoptic)
        self.klystron1LVLed.setGeometry(QtCore.QRect(737, 105, 10, 10))
        self.klystron1LVLed.setMinimumSize(QtCore.QSize(10, 10))
        self.klystron1LVLed.setMaximumSize(QtCore.QSize(10, 10))
        self.klystron1LVLed.setObjectName(_fromUtf8("klystron1LVLed"))
        self.klystron2LVLed = LinacLed(linacStartupSynoptic)
        self.klystron2LVLed.setGeometry(QtCore.QRect(1027, 34, 10, 10))
        self.klystron2LVLed.setMinimumSize(QtCore.QSize(10, 10))
        self.klystron2LVLed.setMaximumSize(QtCore.QSize(10, 10))
        self.klystron2LVLed.setObjectName(_fromUtf8("klystron2LVLed"))

        self.retranslateUi(linacStartupSynoptic)
        QtCore.QMetaObject.connectSlotsByName(linacStartupSynoptic)
        linacStartupSynoptic.setTabOrder(self.coolingLoop1TemperatureValue, self.coolingLoop2TemperatureValue)
        linacStartupSynoptic.setTabOrder(self.coolingLoop2TemperatureValue, self.coolingLoop3TemperatureValue)
        linacStartupSynoptic.setTabOrder(self.coolingLoop3TemperatureValue, self.cathodeSetpoint)
        linacStartupSynoptic.setTabOrder(self.cathodeSetpoint, self.filamentSetpoint)

    def retranslateUi(self, linacStartupSynoptic):
        linacStartupSynoptic.setWindowTitle(QtGui.QApplication.translate("linacStartupSynoptic", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.filamentVLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Filament V", None, QtGui.QApplication.UnicodeUTF8))
        self.cathodeLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Cathode V", None, QtGui.QApplication.UnicodeUTF8))
        self.filamentILabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Filament I", None, QtGui.QApplication.UnicodeUTF8))
        self.temperatureLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.klystron1LVPopupCheck.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.klystron2LVPopupCheck.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.kdeGunLVPopupCheck.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.coolingLoop1PopupCheck.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.coolingLoop2PopupCheck.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.coolingLoop3PopupCheck.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.klystron2InterlockPopupCheck.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.klystron1InterlockPopupCheck.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusLabel
from klystron2itck import klystron2itck
from coolingloop import CoolingLoop
from actionform import actionForm
from klystronlv import klystronLV
from taurus.qt.qtgui.panel import TaurusWidget
from egunlv import eGunLV
from klystron1itck import klystron1itck
from taurus.qt.qtgui.input import TaurusValueSpinBox
from linacled import LinacLed
