# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/ui/linacMainscreenSynoptic.ui'
#
# Created: Thu Mar 13 15:50:04 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_linacMainscreenSynoptic(object):
    def setupUi(self, linacMainscreenSynoptic):
        linacMainscreenSynoptic.setObjectName(_fromUtf8("linacMainscreenSynoptic"))
        linacMainscreenSynoptic.resize(1250, 825)
        linacMainscreenSynoptic.setMinimumSize(QtCore.QSize(1250, 825))
        linacMainscreenSynoptic.setMaximumSize(QtCore.QSize(1250, 825))
        font = QtGui.QFont()
        font.setPointSize(7)
        linacMainscreenSynoptic.setFont(font)
        self.tbGunLevelValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.tbGunLevelValue.setGeometry(QtCore.QRect(386, 62, 70, 22))
        self.tbGunLevelValue.setObjectName(_fromUtf8("tbGunLevelValue"))
        self.tbNumberValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.tbNumberValue.setGeometry(QtCore.QRect(295, 107, 60, 22))
        self.tbNumberValue.setObjectName(_fromUtf8("tbNumberValue"))
        self.tbWidthValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.tbWidthValue.setGeometry(QtCore.QRect(232, 107, 60, 22))
        self.tbWidthValue.setObjectName(_fromUtf8("tbWidthValue"))
        self.tbGunDelayValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.tbGunDelayValue.setGeometry(QtCore.QRect(170, 107, 60, 22))
        self.tbGunDelayValue.setObjectName(_fromUtf8("tbGunDelayValue"))
        self.rfEnbLed = TaurusLed(linacMainscreenSynoptic)
        self.rfEnbLed.setGeometry(QtCore.QRect(598, 15, 10, 10))
        self.rfEnbLed.setMinimumSize(QtCore.QSize(10, 10))
        self.rfEnbLed.setMaximumSize(QtCore.QSize(10, 10))
        self.rfEnbLed.setObjectName(_fromUtf8("rfEnbLed"))
        self.tbTimerStatusStateLed = TaurusLed(linacMainscreenSynoptic)
        self.tbTimerStatusStateLed.setGeometry(QtCore.QRect(464, 20, 10, 10))
        self.tbTimerStatusStateLed.setMinimumSize(QtCore.QSize(10, 10))
        self.tbTimerStatusStateLed.setMaximumSize(QtCore.QSize(10, 10))
        self.tbTimerStatusStateLed.setObjectName(_fromUtf8("tbTimerStatusStateLed"))
        self.rfTimePhaseShifter0Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.rfTimePhaseShifter0Value.setGeometry(QtCore.QRect(110, 310, 70, 22))
        self.rfTimePhaseShifter0Value.setObjectName(_fromUtf8("rfTimePhaseShifter0Value"))
        self.rfA0OutputPowerValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.rfA0OutputPowerValue.setGeometry(QtCore.QRect(180, 310, 70, 22))
        self.rfA0OutputPowerValue.setObjectName(_fromUtf8("rfA0OutputPowerValue"))
        self.rfTimePhaseShifterXValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.rfTimePhaseShifterXValue.setGeometry(QtCore.QRect(260, 280, 70, 22))
        self.rfTimePhaseShifterXValue.setObjectName(_fromUtf8("rfTimePhaseShifterXValue"))
        self.attenuator2Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.attenuator2Value.setGeometry(QtCore.QRect(370, 310, 70, 22))
        self.attenuator2Value.setObjectName(_fromUtf8("attenuator2Value"))
        self.rfPhaseShifter2Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.rfPhaseShifter2Value.setGeometry(QtCore.QRect(440, 310, 70, 22))
        self.rfPhaseShifter2Value.setObjectName(_fromUtf8("rfPhaseShifter2Value"))
        self.rfTimePhaseShifter1Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.rfTimePhaseShifter1Value.setGeometry(QtCore.QRect(510, 280, 70, 22))
        self.rfTimePhaseShifter1Value.setObjectName(_fromUtf8("rfTimePhaseShifter1Value"))
        self.rfPhaseShifter1Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.rfPhaseShifter1Value.setGeometry(QtCore.QRect(560, 310, 70, 22))
        self.rfPhaseShifter1Value.setObjectName(_fromUtf8("rfPhaseShifter1Value"))
        self.sf6p1Value = TaurusLabel(linacMainscreenSynoptic)
        self.sf6p1Value.setGeometry(QtCore.QRect(720, 310, 90, 16))
        self.sf6p1Value.setObjectName(_fromUtf8("sf6p1Value"))
        self.sf6p2Value = TaurusLabel(linacMainscreenSynoptic)
        self.sf6p2Value.setGeometry(QtCore.QRect(1000, 310, 90, 16))
        self.sf6p2Value.setObjectName(_fromUtf8("sf6p2Value"))
        self.rfTimePhaseShifter2Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.rfTimePhaseShifter2Value.setGeometry(QtCore.QRect(840, 280, 70, 22))
        self.rfTimePhaseShifter2Value.setObjectName(_fromUtf8("rfTimePhaseShifter2Value"))
        self.coolingLoop1Led = TaurusLed(linacMainscreenSynoptic)
        self.coolingLoop1Led.setGeometry(QtCore.QRect(1170, 285, 10, 10))
        self.coolingLoop1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.coolingLoop1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.coolingLoop1Led.setObjectName(_fromUtf8("coolingLoop1Led"))
        self.coolingLoop2Led = TaurusLed(linacMainscreenSynoptic)
        self.coolingLoop2Led.setGeometry(QtCore.QRect(1170, 303, 10, 10))
        self.coolingLoop2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.coolingLoop2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.coolingLoop2Led.setObjectName(_fromUtf8("coolingLoop2Led"))
        self.coolingLoop3Led = TaurusLed(linacMainscreenSynoptic)
        self.coolingLoop3Led.setGeometry(QtCore.QRect(1170, 320, 10, 10))
        self.coolingLoop3Led.setMinimumSize(QtCore.QSize(10, 10))
        self.coolingLoop3Led.setMaximumSize(QtCore.QSize(10, 10))
        self.coolingLoop3Led.setObjectName(_fromUtf8("coolingLoop3Led"))
        self.layoutWidget_2 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 430, 132, 96))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.kdLayout = QtGui.QGridLayout(self.layoutWidget_2)
        self.kdLayout.setContentsMargins(7, -1, -1, -1)
        self.kdLayout.setObjectName(_fromUtf8("kdLayout"))
        self.filamentSetpoint = TaurusValueSpinBox(self.layoutWidget_2)
        self.filamentSetpoint.setMinimumSize(QtCore.QSize(60, 20))
        self.filamentSetpoint.setAutoApply(True)
        self.filamentSetpoint.setObjectName(_fromUtf8("filamentSetpoint"))
        self.kdLayout.addWidget(self.filamentSetpoint, 0, 0, 1, 1)
        self.cathodeSetpoint = TaurusValueSpinBox(self.layoutWidget_2)
        self.cathodeSetpoint.setMinimumSize(QtCore.QSize(60, 20))
        self.cathodeSetpoint.setAutoApply(True)
        self.cathodeSetpoint.setObjectName(_fromUtf8("cathodeSetpoint"))
        self.kdLayout.addWidget(self.cathodeSetpoint, 0, 1, 1, 1)
        self.filamentVLabel = QtGui.QLabel(self.layoutWidget_2)
        self.filamentVLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.filamentVLabel.setFont(font)
        self.filamentVLabel.setObjectName(_fromUtf8("filamentVLabel"))
        self.kdLayout.addWidget(self.filamentVLabel, 1, 0, 1, 1)
        self.cathodeLabel = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.cathodeLabel.setFont(font)
        self.cathodeLabel.setObjectName(_fromUtf8("cathodeLabel"))
        self.kdLayout.addWidget(self.cathodeLabel, 1, 1, 1, 1)
        self.filamentCurrent = TaurusLabel(self.layoutWidget_2)
        self.filamentCurrent.setMinimumSize(QtCore.QSize(60, 20))
        self.filamentCurrent.setObjectName(_fromUtf8("filamentCurrent"))
        self.kdLayout.addWidget(self.filamentCurrent, 2, 0, 1, 1)
        self.temperatureValue = TaurusLabel(self.layoutWidget_2)
        self.temperatureValue.setMinimumSize(QtCore.QSize(60, 20))
        self.temperatureValue.setObjectName(_fromUtf8("temperatureValue"))
        self.kdLayout.addWidget(self.temperatureValue, 2, 1, 1, 1)
        self.filamentILabel = QtGui.QLabel(self.layoutWidget_2)
        self.filamentILabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.filamentILabel.setFont(font)
        self.filamentILabel.setObjectName(_fromUtf8("filamentILabel"))
        self.kdLayout.addWidget(self.filamentILabel, 3, 0, 1, 1)
        self.temperatureLabel = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.temperatureLabel.setFont(font)
        self.temperatureLabel.setObjectName(_fromUtf8("temperatureLabel"))
        self.kdLayout.addWidget(self.temperatureLabel, 3, 1, 1, 1)
        self.layoutWidget_4 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_4.setGeometry(QtCore.QRect(160, 790, 81, 31))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.vcvLayout = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.vcvLayout.setContentsMargins(5, -1, -1, -1)
        self.vcvLayout.setObjectName(_fromUtf8("vcvLayout"))
        self.vcv_oncLabel = QtGui.QLabel(self.layoutWidget_4)
        self.vcv_oncLabel.setObjectName(_fromUtf8("vcv_oncLabel"))
        self.vcvLayout.addWidget(self.vcv_oncLabel)
        self.vcv_oncLed = TaurusLed(self.layoutWidget_4)
        self.vcv_oncLed.setMinimumSize(QtCore.QSize(15, 15))
        self.vcv_oncLed.setMaximumSize(QtCore.QSize(15, 15))
        self.vcv_oncLed.setObjectName(_fromUtf8("vcv_oncLed"))
        self.vcvLayout.addWidget(self.vcv_oncLed)
        self.vcv_oncCheck = LinacValueCheckBox(self.layoutWidget_4)
        self.vcv_oncCheck.setShowText(False)
        self.vcv_oncCheck.setObjectName(_fromUtf8("vcv_oncCheck"))
        self.vcvLayout.addWidget(self.vcv_oncCheck)
        self.bc2hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc2hValue.setGeometry(QtCore.QRect(505, 640, 65, 22))
        self.bc2hValue.setObjectName(_fromUtf8("bc2hValue"))
        self.bc2vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc2vValue.setGeometry(QtCore.QRect(505, 670, 65, 22))
        self.bc2vValue.setObjectName(_fromUtf8("bc2vValue"))
        self.bc2fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc2fValue.setGeometry(QtCore.QRect(505, 700, 65, 22))
        self.bc2fValue.setObjectName(_fromUtf8("bc2fValue"))
        self.bc1fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc1fValue.setGeometry(QtCore.QRect(440, 700, 65, 22))
        self.bc1fValue.setObjectName(_fromUtf8("bc1fValue"))
        self.bc1vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc1vValue.setGeometry(QtCore.QRect(440, 670, 65, 22))
        self.bc1vValue.setObjectName(_fromUtf8("bc1vValue"))
        self.bc1hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc1hValue.setGeometry(QtCore.QRect(440, 640, 65, 22))
        self.bc1hValue.setObjectName(_fromUtf8("bc1hValue"))
        self.sl4hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl4hValue.setGeometry(QtCore.QRect(375, 640, 65, 22))
        self.sl4hValue.setObjectName(_fromUtf8("sl4hValue"))
        self.sl3hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl3hValue.setGeometry(QtCore.QRect(310, 640, 65, 22))
        self.sl3hValue.setObjectName(_fromUtf8("sl3hValue"))
        self.sl2hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl2hValue.setGeometry(QtCore.QRect(225, 640, 65, 22))
        self.sl2hValue.setObjectName(_fromUtf8("sl2hValue"))
        self.sl1hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl1hValue.setGeometry(QtCore.QRect(140, 640, 65, 22))
        self.sl1hValue.setObjectName(_fromUtf8("sl1hValue"))
        self.sl4vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl4vValue.setGeometry(QtCore.QRect(375, 670, 65, 22))
        self.sl4vValue.setObjectName(_fromUtf8("sl4vValue"))
        self.sl4fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl4fValue.setGeometry(QtCore.QRect(375, 700, 65, 22))
        self.sl4fValue.setObjectName(_fromUtf8("sl4fValue"))
        self.sl3vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl3vValue.setGeometry(QtCore.QRect(310, 670, 65, 22))
        self.sl3vValue.setObjectName(_fromUtf8("sl3vValue"))
        self.sl2vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl2vValue.setGeometry(QtCore.QRect(225, 670, 65, 22))
        self.sl2vValue.setObjectName(_fromUtf8("sl2vValue"))
        self.sl1vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl1vValue.setGeometry(QtCore.QRect(140, 670, 65, 22))
        self.sl1vValue.setObjectName(_fromUtf8("sl1vValue"))
        self.sl1fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl1fValue.setGeometry(QtCore.QRect(140, 700, 65, 22))
        self.sl1fValue.setObjectName(_fromUtf8("sl1fValue"))
        self.sl3fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl3fValue.setGeometry(QtCore.QRect(310, 700, 65, 22))
        self.sl3fValue.setObjectName(_fromUtf8("sl3fValue"))
        self.sl2fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl2fValue.setGeometry(QtCore.QRect(225, 700, 65, 22))
        self.sl2fValue.setObjectName(_fromUtf8("sl2fValue"))
        self.layoutWidget_6 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_6.setGeometry(QtCore.QRect(140, 740, 63, 23))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.sl1OnLayout = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.sl1OnLayout.setMargin(0)
        self.sl1OnLayout.setObjectName(_fromUtf8("sl1OnLayout"))
        self.sl1OnLabel = QtGui.QLabel(self.layoutWidget_6)
        self.sl1OnLabel.setObjectName(_fromUtf8("sl1OnLabel"))
        self.sl1OnLayout.addWidget(self.sl1OnLabel)
        self.sl1Led = TaurusLed(self.layoutWidget_6)
        self.sl1Led.setMinimumSize(QtCore.QSize(15, 15))
        self.sl1Led.setMaximumSize(QtCore.QSize(15, 15))
        self.sl1Led.setObjectName(_fromUtf8("sl1Led"))
        self.sl1OnLayout.addWidget(self.sl1Led)
        self.sl1OnCheck = LinacValueCheckBox(self.layoutWidget_6)
        self.sl1OnCheck.setShowText(False)
        self.sl1OnCheck.setObjectName(_fromUtf8("sl1OnCheck"))
        self.sl1OnLayout.addWidget(self.sl1OnCheck)
        self.layoutWidget_7 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_7.setGeometry(QtCore.QRect(220, 740, 63, 23))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.sl21OnLayout = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.sl21OnLayout.setMargin(0)
        self.sl21OnLayout.setObjectName(_fromUtf8("sl21OnLayout"))
        self.sl2OnLabel = QtGui.QLabel(self.layoutWidget_7)
        self.sl2OnLabel.setObjectName(_fromUtf8("sl2OnLabel"))
        self.sl21OnLayout.addWidget(self.sl2OnLabel)
        self.sl2Led = TaurusLed(self.layoutWidget_7)
        self.sl2Led.setMinimumSize(QtCore.QSize(15, 15))
        self.sl2Led.setMaximumSize(QtCore.QSize(15, 15))
        self.sl2Led.setObjectName(_fromUtf8("sl2Led"))
        self.sl21OnLayout.addWidget(self.sl2Led)
        self.sl2OnCheck = LinacValueCheckBox(self.layoutWidget_7)
        self.sl2OnCheck.setShowText(False)
        self.sl2OnCheck.setObjectName(_fromUtf8("sl2OnCheck"))
        self.sl21OnLayout.addWidget(self.sl2OnCheck)
        self.layoutWidget_8 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_8.setGeometry(QtCore.QRect(310, 740, 63, 23))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.sl3OnLayout = QtGui.QHBoxLayout(self.layoutWidget_8)
        self.sl3OnLayout.setMargin(0)
        self.sl3OnLayout.setObjectName(_fromUtf8("sl3OnLayout"))
        self.sl3OnLabel = QtGui.QLabel(self.layoutWidget_8)
        self.sl3OnLabel.setObjectName(_fromUtf8("sl3OnLabel"))
        self.sl3OnLayout.addWidget(self.sl3OnLabel)
        self.sl3Led = TaurusLed(self.layoutWidget_8)
        self.sl3Led.setMinimumSize(QtCore.QSize(15, 15))
        self.sl3Led.setMaximumSize(QtCore.QSize(15, 15))
        self.sl3Led.setObjectName(_fromUtf8("sl3Led"))
        self.sl3OnLayout.addWidget(self.sl3Led)
        self.sl3OnCheck = LinacValueCheckBox(self.layoutWidget_8)
        self.sl3OnCheck.setShowText(False)
        self.sl3OnCheck.setObjectName(_fromUtf8("sl3OnCheck"))
        self.sl3OnLayout.addWidget(self.sl3OnCheck)
        self.layoutWidget_9 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_9.setGeometry(QtCore.QRect(380, 740, 63, 23))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.sl4OnLayout = QtGui.QHBoxLayout(self.layoutWidget_9)
        self.sl4OnLayout.setMargin(0)
        self.sl4OnLayout.setObjectName(_fromUtf8("sl4OnLayout"))
        self.sl4OnLabel = QtGui.QLabel(self.layoutWidget_9)
        self.sl4OnLabel.setObjectName(_fromUtf8("sl4OnLabel"))
        self.sl4OnLayout.addWidget(self.sl4OnLabel)
        self.sl4Led = TaurusLed(self.layoutWidget_9)
        self.sl4Led.setMinimumSize(QtCore.QSize(15, 15))
        self.sl4Led.setMaximumSize(QtCore.QSize(15, 15))
        self.sl4Led.setObjectName(_fromUtf8("sl4Led"))
        self.sl4OnLayout.addWidget(self.sl4Led)
        self.sl4OnCheck = LinacValueCheckBox(self.layoutWidget_9)
        self.sl4OnCheck.setShowText(False)
        self.sl4OnCheck.setObjectName(_fromUtf8("sl4OnCheck"))
        self.sl4OnLayout.addWidget(self.sl4OnCheck)
        self.layoutWidget_10 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_10.setGeometry(QtCore.QRect(440, 740, 63, 23))
        self.layoutWidget_10.setObjectName(_fromUtf8("layoutWidget_10"))
        self.bc1Layout = QtGui.QHBoxLayout(self.layoutWidget_10)
        self.bc1Layout.setMargin(0)
        self.bc1Layout.setObjectName(_fromUtf8("bc1Layout"))
        self.bc1OnLabel = QtGui.QLabel(self.layoutWidget_10)
        self.bc1OnLabel.setObjectName(_fromUtf8("bc1OnLabel"))
        self.bc1Layout.addWidget(self.bc1OnLabel)
        self.bc1Led = TaurusLed(self.layoutWidget_10)
        self.bc1Led.setMinimumSize(QtCore.QSize(15, 15))
        self.bc1Led.setMaximumSize(QtCore.QSize(15, 15))
        self.bc1Led.setObjectName(_fromUtf8("bc1Led"))
        self.bc1Layout.addWidget(self.bc1Led)
        self.bc1OnCheck = LinacValueCheckBox(self.layoutWidget_10)
        self.bc1OnCheck.setShowText(False)
        self.bc1OnCheck.setObjectName(_fromUtf8("bc1OnCheck"))
        self.bc1Layout.addWidget(self.bc1OnCheck)
        self.layoutWidget_11 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_11.setGeometry(QtCore.QRect(500, 740, 63, 23))
        self.layoutWidget_11.setObjectName(_fromUtf8("layoutWidget_11"))
        self.bc2Layout = QtGui.QHBoxLayout(self.layoutWidget_11)
        self.bc2Layout.setMargin(0)
        self.bc2Layout.setObjectName(_fromUtf8("bc2Layout"))
        self.bc2OnLabel = QtGui.QLabel(self.layoutWidget_11)
        self.bc2OnLabel.setObjectName(_fromUtf8("bc2OnLabel"))
        self.bc2Layout.addWidget(self.bc2OnLabel)
        self.bc2Led = TaurusLed(self.layoutWidget_11)
        self.bc2Led.setMinimumSize(QtCore.QSize(15, 15))
        self.bc2Led.setMaximumSize(QtCore.QSize(15, 15))
        self.bc2Led.setObjectName(_fromUtf8("bc2Led"))
        self.bc2Layout.addWidget(self.bc2Led)
        self.bc2OnCheck = LinacValueCheckBox(self.layoutWidget_11)
        self.bc2OnCheck.setShowText(False)
        self.bc2OnCheck.setObjectName(_fromUtf8("bc2OnCheck"))
        self.bc2Layout.addWidget(self.bc2OnCheck)
        self.glhValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.glhValue.setGeometry(QtCore.QRect(630, 640, 65, 22))
        self.glhValue.setObjectName(_fromUtf8("glhValue"))
        self.glvValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.glvValue.setGeometry(QtCore.QRect(630, 670, 65, 22))
        self.glvValue.setObjectName(_fromUtf8("glvValue"))
        self.glfValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.glfValue.setGeometry(QtCore.QRect(630, 700, 65, 22))
        self.glfValue.setObjectName(_fromUtf8("glfValue"))
        self.layoutWidget_12 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_12.setGeometry(QtCore.QRect(620, 740, 63, 23))
        self.layoutWidget_12.setObjectName(_fromUtf8("layoutWidget_12"))
        self.glLayout = QtGui.QHBoxLayout(self.layoutWidget_12)
        self.glLayout.setMargin(0)
        self.glLayout.setObjectName(_fromUtf8("glLayout"))
        self.glOnLabel = QtGui.QLabel(self.layoutWidget_12)
        self.glOnLabel.setObjectName(_fromUtf8("glOnLabel"))
        self.glLayout.addWidget(self.glOnLabel)
        self.glLed = TaurusLed(self.layoutWidget_12)
        self.glLed.setMinimumSize(QtCore.QSize(15, 15))
        self.glLed.setMaximumSize(QtCore.QSize(15, 15))
        self.glLed.setObjectName(_fromUtf8("glLed"))
        self.glLayout.addWidget(self.glLed)
        self.glOnCheck = LinacValueCheckBox(self.layoutWidget_12)
        self.glOnCheck.setShowText(False)
        self.glOnCheck.setObjectName(_fromUtf8("glOnCheck"))
        self.glLayout.addWidget(self.glOnCheck)
        self.as1hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.as1hValue.setGeometry(QtCore.QRect(730, 640, 65, 22))
        self.as1hValue.setObjectName(_fromUtf8("as1hValue"))
        self.as1vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.as1vValue.setGeometry(QtCore.QRect(730, 670, 65, 22))
        self.as1vValue.setObjectName(_fromUtf8("as1vValue"))
        self.layoutWidget_13 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_13.setGeometry(QtCore.QRect(730, 740, 63, 23))
        self.layoutWidget_13.setObjectName(_fromUtf8("layoutWidget_13"))
        self.as1OnLayout = QtGui.QHBoxLayout(self.layoutWidget_13)
        self.as1OnLayout.setMargin(0)
        self.as1OnLayout.setObjectName(_fromUtf8("as1OnLayout"))
        self.as1OnLabel = QtGui.QLabel(self.layoutWidget_13)
        self.as1OnLabel.setObjectName(_fromUtf8("as1OnLabel"))
        self.as1OnLayout.addWidget(self.as1OnLabel)
        self.as1Led = TaurusLed(self.layoutWidget_13)
        self.as1Led.setMinimumSize(QtCore.QSize(15, 15))
        self.as1Led.setMaximumSize(QtCore.QSize(15, 15))
        self.as1Led.setObjectName(_fromUtf8("as1Led"))
        self.as1OnLayout.addWidget(self.as1Led)
        self.as1OnCheck = LinacValueCheckBox(self.layoutWidget_13)
        self.as1OnCheck.setShowText(False)
        self.as1OnCheck.setObjectName(_fromUtf8("as1OnCheck"))
        self.as1OnLayout.addWidget(self.as1OnCheck)
        self.qt1hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.qt1hValue.setGeometry(QtCore.QRect(870, 650, 65, 22))
        self.qt1hValue.setObjectName(_fromUtf8("qt1hValue"))
        self.qt1vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.qt1vValue.setGeometry(QtCore.QRect(870, 680, 65, 22))
        self.qt1vValue.setObjectName(_fromUtf8("qt1vValue"))
        self.qt1fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.qt1fValue.setGeometry(QtCore.QRect(870, 710, 65, 22))
        self.qt1fValue.setObjectName(_fromUtf8("qt1fValue"))
        self.layoutWidget_14 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_14.setGeometry(QtCore.QRect(870, 740, 63, 23))
        self.layoutWidget_14.setObjectName(_fromUtf8("layoutWidget_14"))
        self.qt1OnLayout = QtGui.QHBoxLayout(self.layoutWidget_14)
        self.qt1OnLayout.setMargin(0)
        self.qt1OnLayout.setObjectName(_fromUtf8("qt1OnLayout"))
        self.qt1OnLabel = QtGui.QLabel(self.layoutWidget_14)
        self.qt1OnLabel.setObjectName(_fromUtf8("qt1OnLabel"))
        self.qt1OnLayout.addWidget(self.qt1OnLabel)
        self.qtLed = TaurusLed(self.layoutWidget_14)
        self.qtLed.setMinimumSize(QtCore.QSize(15, 15))
        self.qtLed.setMaximumSize(QtCore.QSize(15, 15))
        self.qtLed.setObjectName(_fromUtf8("qtLed"))
        self.qt1OnLayout.addWidget(self.qtLed)
        self.qt1OnCheck = LinacValueCheckBox(self.layoutWidget_14)
        self.qt1OnCheck.setShowText(False)
        self.qt1OnCheck.setObjectName(_fromUtf8("qt1OnCheck"))
        self.qt1OnLayout.addWidget(self.qt1OnCheck)
        self.as2hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.as2hValue.setGeometry(QtCore.QRect(1015, 650, 65, 22))
        self.as2hValue.setObjectName(_fromUtf8("as2hValue"))
        self.as2vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.as2vValue.setGeometry(QtCore.QRect(1015, 680, 65, 22))
        self.as2vValue.setObjectName(_fromUtf8("as2vValue"))
        self.qt2fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.qt2fValue.setGeometry(QtCore.QRect(940, 710, 65, 22))
        self.qt2fValue.setObjectName(_fromUtf8("qt2fValue"))
        self.layoutWidget_15 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_15.setGeometry(QtCore.QRect(1010, 740, 63, 23))
        self.layoutWidget_15.setObjectName(_fromUtf8("layoutWidget_15"))
        self.as2OnLayout = QtGui.QHBoxLayout(self.layoutWidget_15)
        self.as2OnLayout.setMargin(0)
        self.as2OnLayout.setObjectName(_fromUtf8("as2OnLayout"))
        self.as2OnLabel = QtGui.QLabel(self.layoutWidget_15)
        self.as2OnLabel.setObjectName(_fromUtf8("as2OnLabel"))
        self.as2OnLayout.addWidget(self.as2OnLabel)
        self.as2Led = TaurusLed(self.layoutWidget_15)
        self.as2Led.setMinimumSize(QtCore.QSize(15, 15))
        self.as2Led.setMaximumSize(QtCore.QSize(15, 15))
        self.as2Led.setObjectName(_fromUtf8("as2Led"))
        self.as2OnLayout.addWidget(self.as2Led)
        self.as2OnCheck = LinacValueCheckBox(self.layoutWidget_15)
        self.as2OnCheck.setShowText(False)
        self.as2OnCheck.setObjectName(_fromUtf8("as2OnCheck"))
        self.as2OnLayout.addWidget(self.as2OnCheck)
        self.sl1LedInfo = TaurusLed(linacMainscreenSynoptic)
        self.sl1LedInfo.setGeometry(QtCore.QRect(162, 500, 10, 10))
        self.sl1LedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.sl1LedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.sl1LedInfo.setObjectName(_fromUtf8("sl1LedInfo"))
        self.vcv_oncLedInfo = TaurusLed(linacMainscreenSynoptic)
        self.vcv_oncLedInfo.setGeometry(QtCore.QRect(196, 540, 10, 10))
        self.vcv_oncLedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.vcv_oncLedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.vcv_oncLedInfo.setObjectName(_fromUtf8("vcv_oncLedInfo"))
        self.sl2LedInfo = TaurusLed(linacMainscreenSynoptic)
        self.sl2LedInfo.setGeometry(QtCore.QRect(247, 500, 10, 10))
        self.sl2LedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.sl2LedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.sl2LedInfo.setObjectName(_fromUtf8("sl2LedInfo"))
        self.sl3LedInfo = TaurusLed(linacMainscreenSynoptic)
        self.sl3LedInfo.setGeometry(QtCore.QRect(331, 500, 10, 10))
        self.sl3LedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.sl3LedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.sl3LedInfo.setObjectName(_fromUtf8("sl3LedInfo"))
        self.sl4LedInfo = TaurusLed(linacMainscreenSynoptic)
        self.sl4LedInfo.setGeometry(QtCore.QRect(403, 500, 10, 10))
        self.sl4LedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.sl4LedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.sl4LedInfo.setObjectName(_fromUtf8("sl4LedInfo"))
        self.bc1LedInfo = TaurusLed(linacMainscreenSynoptic)
        self.bc1LedInfo.setGeometry(QtCore.QRect(457, 500, 10, 10))
        self.bc1LedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.bc1LedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.bc1LedInfo.setObjectName(_fromUtf8("bc1LedInfo"))
        self.bc2LedInfo = TaurusLed(linacMainscreenSynoptic)
        self.bc2LedInfo.setGeometry(QtCore.QRect(517, 500, 10, 10))
        self.bc2LedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.bc2LedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.bc2LedInfo.setObjectName(_fromUtf8("bc2LedInfo"))
        self.sm1Led = TaurusLed(linacMainscreenSynoptic)
        self.sm1Led.setGeometry(QtCore.QRect(606, 505, 10, 10))
        self.sm1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sm1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sm1Led.setObjectName(_fromUtf8("sm1Led"))
        self.glLedInfo = TaurusLed(linacMainscreenSynoptic)
        self.glLedInfo.setGeometry(QtCore.QRect(643, 500, 10, 10))
        self.glLedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.glLedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.glLedInfo.setObjectName(_fromUtf8("glLedInfo"))
        self.as1LedInfo = TaurusLed(linacMainscreenSynoptic)
        self.as1LedInfo.setGeometry(QtCore.QRect(746, 520, 10, 10))
        self.as1LedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.as1LedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.as1LedInfo.setObjectName(_fromUtf8("as1LedInfo"))
        self.sm2Led = TaurusLed(linacMainscreenSynoptic)
        self.sm2Led.setGeometry(QtCore.QRect(859, 505, 10, 10))
        self.sm2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sm2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sm2Led.setObjectName(_fromUtf8("sm2Led"))
        self.qtLedInfo = TaurusLed(linacMainscreenSynoptic)
        self.qtLedInfo.setGeometry(QtCore.QRect(919, 500, 10, 10))
        self.qtLedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.qtLedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.qtLedInfo.setObjectName(_fromUtf8("qtLedInfo"))
        self.as2LedInfo = TaurusLed(linacMainscreenSynoptic)
        self.as2LedInfo.setGeometry(QtCore.QRect(1033, 520, 10, 10))
        self.as2LedInfo.setMinimumSize(QtCore.QSize(10, 10))
        self.as2LedInfo.setMaximumSize(QtCore.QSize(10, 10))
        self.as2LedInfo.setObjectName(_fromUtf8("as2LedInfo"))
        self.sm3Led = TaurusLed(linacMainscreenSynoptic)
        self.sm3Led.setGeometry(QtCore.QRect(1135, 505, 10, 10))
        self.sm3Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sm3Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sm3Led.setObjectName(_fromUtf8("sm3Led"))
        self.layoutWidget_16 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_16.setGeometry(QtCore.QRect(660, 790, 67, 23))
        self.layoutWidget_16.setObjectName(_fromUtf8("layoutWidget_16"))
        self.fluorescentScreen1LightLayout = QtGui.QHBoxLayout(self.layoutWidget_16)
        self.fluorescentScreen1LightLayout.setMargin(0)
        self.fluorescentScreen1LightLayout.setObjectName(_fromUtf8("fluorescentScreen1LightLayout"))
        self.fluorescentScreen1LightLabel = QtGui.QLabel(self.layoutWidget_16)
        self.fluorescentScreen1LightLabel.setObjectName(_fromUtf8("fluorescentScreen1LightLabel"))
        self.fluorescentScreen1LightLayout.addWidget(self.fluorescentScreen1LightLabel)
        self.fluorescentScreen1LightLed = TaurusLed(self.layoutWidget_16)
        self.fluorescentScreen1LightLed.setMinimumSize(QtCore.QSize(15, 15))
        self.fluorescentScreen1LightLed.setMaximumSize(QtCore.QSize(15, 15))
        self.fluorescentScreen1LightLed.setObjectName(_fromUtf8("fluorescentScreen1LightLed"))
        self.fluorescentScreen1LightLayout.addWidget(self.fluorescentScreen1LightLed)
        self.fluorescentScreen1LightCheck = LinacValueCheckBox(self.layoutWidget_16)
        self.fluorescentScreen1LightCheck.setShowText(False)
        self.fluorescentScreen1LightCheck.setObjectName(_fromUtf8("fluorescentScreen1LightCheck"))
        self.fluorescentScreen1LightLayout.addWidget(self.fluorescentScreen1LightCheck)
        self.layoutWidget_17 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_17.setGeometry(QtCore.QRect(580, 790, 61, 23))
        self.layoutWidget_17.setObjectName(_fromUtf8("layoutWidget_17"))
        self.fluorescentScreenValveLayout = QtGui.QHBoxLayout(self.layoutWidget_17)
        self.fluorescentScreenValveLayout.setMargin(0)
        self.fluorescentScreenValveLayout.setObjectName(_fromUtf8("fluorescentScreenValveLayout"))
        self.fluorescentScreen1ValveLabel = QtGui.QLabel(self.layoutWidget_17)
        self.fluorescentScreen1ValveLabel.setObjectName(_fromUtf8("fluorescentScreen1ValveLabel"))
        self.fluorescentScreenValveLayout.addWidget(self.fluorescentScreen1ValveLabel)
        self.fluorescentScreen1ValveLed = TaurusLed(self.layoutWidget_17)
        self.fluorescentScreen1ValveLed.setMinimumSize(QtCore.QSize(15, 15))
        self.fluorescentScreen1ValveLed.setMaximumSize(QtCore.QSize(15, 15))
        self.fluorescentScreen1ValveLed.setObjectName(_fromUtf8("fluorescentScreen1ValveLed"))
        self.fluorescentScreenValveLayout.addWidget(self.fluorescentScreen1ValveLed)
        self.fluorescentScreen1ValveCheck = LinacValueCheckBox(self.layoutWidget_17)
        self.fluorescentScreen1ValveCheck.setShowText(False)
        self.fluorescentScreen1ValveCheck.setObjectName(_fromUtf8("fluorescentScreen1ValveCheck"))
        self.fluorescentScreenValveLayout.addWidget(self.fluorescentScreen1ValveCheck)
        self.layoutWidget_18 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_18.setGeometry(QtCore.QRect(840, 790, 61, 23))
        self.layoutWidget_18.setObjectName(_fromUtf8("layoutWidget_18"))
        self.fluorescentScreen2ValveLayout = QtGui.QHBoxLayout(self.layoutWidget_18)
        self.fluorescentScreen2ValveLayout.setMargin(0)
        self.fluorescentScreen2ValveLayout.setObjectName(_fromUtf8("fluorescentScreen2ValveLayout"))
        self.fluorescentScreen2ValveLabel = QtGui.QLabel(self.layoutWidget_18)
        self.fluorescentScreen2ValveLabel.setObjectName(_fromUtf8("fluorescentScreen2ValveLabel"))
        self.fluorescentScreen2ValveLayout.addWidget(self.fluorescentScreen2ValveLabel)
        self.fluorescentScreen2ValveLed = TaurusLed(self.layoutWidget_18)
        self.fluorescentScreen2ValveLed.setMinimumSize(QtCore.QSize(15, 15))
        self.fluorescentScreen2ValveLed.setMaximumSize(QtCore.QSize(15, 15))
        self.fluorescentScreen2ValveLed.setObjectName(_fromUtf8("fluorescentScreen2ValveLed"))
        self.fluorescentScreen2ValveLayout.addWidget(self.fluorescentScreen2ValveLed)
        self.fluorescentScreen2ValveCheck = LinacValueCheckBox(self.layoutWidget_18)
        self.fluorescentScreen2ValveCheck.setShowText(False)
        self.fluorescentScreen2ValveCheck.setObjectName(_fromUtf8("fluorescentScreen2ValveCheck"))
        self.fluorescentScreen2ValveLayout.addWidget(self.fluorescentScreen2ValveCheck)
        self.layoutWidget_19 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_19.setGeometry(QtCore.QRect(910, 790, 67, 23))
        self.layoutWidget_19.setObjectName(_fromUtf8("layoutWidget_19"))
        self.fluorescentScreen2LightLayout = QtGui.QHBoxLayout(self.layoutWidget_19)
        self.fluorescentScreen2LightLayout.setMargin(0)
        self.fluorescentScreen2LightLayout.setObjectName(_fromUtf8("fluorescentScreen2LightLayout"))
        self.fluorescentScreen2LightLabel = QtGui.QLabel(self.layoutWidget_19)
        self.fluorescentScreen2LightLabel.setObjectName(_fromUtf8("fluorescentScreen2LightLabel"))
        self.fluorescentScreen2LightLayout.addWidget(self.fluorescentScreen2LightLabel)
        self.fluorescentScreen2LightLed = TaurusLed(self.layoutWidget_19)
        self.fluorescentScreen2LightLed.setMinimumSize(QtCore.QSize(15, 15))
        self.fluorescentScreen2LightLed.setMaximumSize(QtCore.QSize(15, 15))
        self.fluorescentScreen2LightLed.setObjectName(_fromUtf8("fluorescentScreen2LightLed"))
        self.fluorescentScreen2LightLayout.addWidget(self.fluorescentScreen2LightLed)
        self.fluorescentScreen2LightCheck = LinacValueCheckBox(self.layoutWidget_19)
        self.fluorescentScreen2LightCheck.setShowText(False)
        self.fluorescentScreen2LightCheck.setObjectName(_fromUtf8("fluorescentScreen2LightCheck"))
        self.fluorescentScreen2LightLayout.addWidget(self.fluorescentScreen2LightCheck)
        self.layoutWidget_20 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_20.setGeometry(QtCore.QRect(1070, 790, 61, 23))
        self.layoutWidget_20.setObjectName(_fromUtf8("layoutWidget_20"))
        self.fluorescentScreen3ValveLayout = QtGui.QHBoxLayout(self.layoutWidget_20)
        self.fluorescentScreen3ValveLayout.setMargin(0)
        self.fluorescentScreen3ValveLayout.setObjectName(_fromUtf8("fluorescentScreen3ValveLayout"))
        self.fluorescentScreen3ValveLabel = QtGui.QLabel(self.layoutWidget_20)
        self.fluorescentScreen3ValveLabel.setObjectName(_fromUtf8("fluorescentScreen3ValveLabel"))
        self.fluorescentScreen3ValveLayout.addWidget(self.fluorescentScreen3ValveLabel)
        self.fluorescentScreen3ValveLed = TaurusLed(self.layoutWidget_20)
        self.fluorescentScreen3ValveLed.setMinimumSize(QtCore.QSize(15, 15))
        self.fluorescentScreen3ValveLed.setMaximumSize(QtCore.QSize(15, 15))
        self.fluorescentScreen3ValveLed.setObjectName(_fromUtf8("fluorescentScreen3ValveLed"))
        self.fluorescentScreen3ValveLayout.addWidget(self.fluorescentScreen3ValveLed)
        self.fluorescentScreen3ValveCheck = LinacValueCheckBox(self.layoutWidget_20)
        self.fluorescentScreen3ValveCheck.setShowText(False)
        self.fluorescentScreen3ValveCheck.setObjectName(_fromUtf8("fluorescentScreen3ValveCheck"))
        self.fluorescentScreen3ValveLayout.addWidget(self.fluorescentScreen3ValveCheck)
        self.layoutWidget_21 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_21.setGeometry(QtCore.QRect(1140, 790, 67, 23))
        self.layoutWidget_21.setObjectName(_fromUtf8("layoutWidget_21"))
        self.fluorescentScreen3LightLayout = QtGui.QHBoxLayout(self.layoutWidget_21)
        self.fluorescentScreen3LightLayout.setMargin(0)
        self.fluorescentScreen3LightLayout.setObjectName(_fromUtf8("fluorescentScreen3LightLayout"))
        self.fluorescentScreen3LightLabel = QtGui.QLabel(self.layoutWidget_21)
        self.fluorescentScreen3LightLabel.setObjectName(_fromUtf8("fluorescentScreen3LightLabel"))
        self.fluorescentScreen3LightLayout.addWidget(self.fluorescentScreen3LightLabel)
        self.fluorescentScreen3LightLed = TaurusLed(self.layoutWidget_21)
        self.fluorescentScreen3LightLed.setMinimumSize(QtCore.QSize(15, 15))
        self.fluorescentScreen3LightLed.setMaximumSize(QtCore.QSize(15, 15))
        self.fluorescentScreen3LightLed.setObjectName(_fromUtf8("fluorescentScreen3LightLed"))
        self.fluorescentScreen3LightLayout.addWidget(self.fluorescentScreen3LightLed)
        self.fluorescentScreen3LightCheck = LinacValueCheckBox(self.layoutWidget_21)
        self.fluorescentScreen3LightCheck.setShowText(False)
        self.fluorescentScreen3LightCheck.setObjectName(_fromUtf8("fluorescentScreen3LightCheck"))
        self.fluorescentScreen3LightLayout.addWidget(self.fluorescentScreen3LightCheck)
        self.layoutWidget = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 630, 91, 101))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.hvsLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.hvsLayout.setMargin(0)
        self.hvsLayout.setObjectName(_fromUtf8("hvsLayout"))
        self.eGunHVStatus = TaurusLabel(self.layoutWidget)
        self.eGunHVStatus.setObjectName(_fromUtf8("eGunHVStatus"))
        self.hvsLayout.addWidget(self.eGunHVStatus)
        self.eGunHVValue = TaurusLabel(self.layoutWidget)
        self.eGunHVValue.setObjectName(_fromUtf8("eGunHVValue"))
        self.hvsLayout.addWidget(self.eGunHVValue)
        self.hvsVoltageValue = TaurusValueSpinBox(self.layoutWidget)
        self.hvsVoltageValue.setObjectName(_fromUtf8("hvsVoltageValue"))
        self.hvsLayout.addWidget(self.hvsVoltageValue)
        self.hvsCurrentValue = TaurusLabel(self.layoutWidget)
        self.hvsCurrentValue.setObjectName(_fromUtf8("hvsCurrentValue"))
        self.hvsLayout.addWidget(self.hvsCurrentValue)
        self.klystron2HVPopupWidget = klystronHV(linacMainscreenSynoptic)
        self.klystron2HVPopupWidget.setGeometry(QtCore.QRect(869, 30, 170, 240))
        self.klystron2HVPopupWidget.setObjectName(_fromUtf8("klystron2HVPopupWidget"))
        self.klystron1HVPopupWidget = klystronHV(linacMainscreenSynoptic)
        self.klystron1HVPopupWidget.setGeometry(QtCore.QRect(500, 30, 170, 240))
        self.klystron1HVPopupWidget.setObjectName(_fromUtf8("klystron1HVPopupWidget"))
        self.rfSourceStatusLed = TaurusLed(linacMainscreenSynoptic)
        self.rfSourceStatusLed.setGeometry(QtCore.QRect(1104, 278, 10, 10))
        self.rfSourceStatusLed.setMinimumSize(QtCore.QSize(10, 10))
        self.rfSourceStatusLed.setMaximumSize(QtCore.QSize(10, 10))
        self.rfSourceStatusLed.setObjectName(_fromUtf8("rfSourceStatusLed"))
        self.rfA0StatusLed = TaurusLed(linacMainscreenSynoptic)
        self.rfA0StatusLed.setGeometry(QtCore.QRect(280, 370, 10, 10))
        self.rfA0StatusLed.setMinimumSize(QtCore.QSize(10, 10))
        self.rfA0StatusLed.setMaximumSize(QtCore.QSize(10, 10))
        self.rfA0StatusLed.setObjectName(_fromUtf8("rfA0StatusLed"))
        self.phaseShifter1PopupWidget = phaseShifter(linacMainscreenSynoptic)
        self.phaseShifter1PopupWidget.setGeometry(QtCore.QRect(640, 390, 100, 100))
        self.phaseShifter1PopupWidget.setObjectName(_fromUtf8("phaseShifter1PopupWidget"))
        self.phaseShifter2PopupWidget = phaseShifter(linacMainscreenSynoptic)
        self.phaseShifter2PopupWidget.setGeometry(QtCore.QRect(500, 360, 100, 100))
        self.phaseShifter2PopupWidget.setObjectName(_fromUtf8("phaseShifter2PopupWidget"))
        self.attenuatorPopupWidget = Attenuator(linacMainscreenSynoptic)
        self.attenuatorPopupWidget.setGeometry(QtCore.QRect(300, 340, 100, 100))
        self.attenuatorPopupWidget.setObjectName(_fromUtf8("attenuatorPopupWidget"))
        self.sl1PopupWidget = magnet(linacMainscreenSynoptic)
        self.sl1PopupWidget.setGeometry(QtCore.QRect(203, 610, 210, 100))
        self.sl1PopupWidget.setObjectName(_fromUtf8("sl1PopupWidget"))
        self.sl2PopupWidget = magnet(linacMainscreenSynoptic)
        self.sl2PopupWidget.setGeometry(QtCore.QRect(291, 610, 210, 100))
        self.sl2PopupWidget.setObjectName(_fromUtf8("sl2PopupWidget"))
        self.sl3PopupWidget = magnet(linacMainscreenSynoptic)
        self.sl3PopupWidget.setGeometry(QtCore.QRect(376, 610, 210, 100))
        self.sl3PopupWidget.setObjectName(_fromUtf8("sl3PopupWidget"))
        self.sl4PopupWidget = magnet(linacMainscreenSynoptic)
        self.sl4PopupWidget.setGeometry(QtCore.QRect(440, 610, 210, 100))
        self.sl4PopupWidget.setObjectName(_fromUtf8("sl4PopupWidget"))
        self.bc1PopupWidget = magnet(linacMainscreenSynoptic)
        self.bc1PopupWidget.setGeometry(QtCore.QRect(505, 610, 210, 100))
        self.bc1PopupWidget.setObjectName(_fromUtf8("bc1PopupWidget"))
        self.bc2PopupWidget = magnet(linacMainscreenSynoptic)
        self.bc2PopupWidget.setGeometry(QtCore.QRect(569, 610, 210, 100))
        self.bc2PopupWidget.setObjectName(_fromUtf8("bc2PopupWidget"))
        self.glPopupWidget = magnet(linacMainscreenSynoptic)
        self.glPopupWidget.setGeometry(QtCore.QRect(697, 610, 210, 100))
        self.glPopupWidget.setObjectName(_fromUtf8("glPopupWidget"))
        self.qt1PopupWidget = magnet(linacMainscreenSynoptic)
        self.qt1PopupWidget.setGeometry(QtCore.QRect(939, 610, 210, 100))
        self.qt1PopupWidget.setObjectName(_fromUtf8("qt1PopupWidget"))
        self.qt2PopupWidget = magnet(linacMainscreenSynoptic)
        self.qt2PopupWidget.setGeometry(QtCore.QRect(1007, 610, 210, 100))
        self.qt2PopupWidget.setObjectName(_fromUtf8("qt2PopupWidget"))
        self.as2PopupWidget = magnet(linacMainscreenSynoptic)
        self.as2PopupWidget.setGeometry(QtCore.QRect(801, 610, 210, 100))
        self.as2PopupWidget.setObjectName(_fromUtf8("as2PopupWidget"))
        self.as1PopupWidget = magnet(linacMainscreenSynoptic)
        self.as1PopupWidget.setGeometry(QtCore.QRect(798, 610, 210, 100))
        self.as1PopupWidget.setObjectName(_fromUtf8("as1PopupWidget"))
        self.fluorescentScreen1Status = TaurusLabel(linacMainscreenSynoptic)
        self.fluorescentScreen1Status.setGeometry(QtCore.QRect(620, 770, 60, 16))
        self.fluorescentScreen1Status.setObjectName(_fromUtf8("fluorescentScreen1Status"))
        self.fluorescentScreen2Status = TaurusLabel(linacMainscreenSynoptic)
        self.fluorescentScreen2Status.setGeometry(QtCore.QRect(870, 770, 60, 16))
        self.fluorescentScreen2Status.setObjectName(_fromUtf8("fluorescentScreen2Status"))
        self.fluorescentScreen3Status = TaurusLabel(linacMainscreenSynoptic)
        self.fluorescentScreen3Status.setGeometry(QtCore.QRect(1100, 770, 60, 16))
        self.fluorescentScreen3Status.setObjectName(_fromUtf8("fluorescentScreen3Status"))
        self.hvsPopupWidget = eGunHV(linacMainscreenSynoptic)
        self.hvsPopupWidget.setGeometry(QtCore.QRect(-2, 529, 114, 60))
        self.hvsPopupWidget.setObjectName(_fromUtf8("hvsPopupWidget"))
        self.MainScreenSchematic = QtGui.QLabel(linacMainscreenSynoptic)
        self.MainScreenSchematic.setGeometry(QtCore.QRect(0, 0, 1265, 829))
        self.MainScreenSchematic.setText(_fromUtf8(""))
        self.MainScreenSchematic.setPixmap(QtGui.QPixmap(_fromUtf8("jdraw/linac_mainscreen_synoptic.png")))
        self.MainScreenSchematic.setObjectName(_fromUtf8("MainScreenSchematic"))
        self.layoutWidget1 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget1.setGeometry(QtCore.QRect(790, 170, 81, 48))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.klystron1Layout = QtGui.QGridLayout(self.layoutWidget1)
        self.klystron1Layout.setMargin(0)
        self.klystron1Layout.setObjectName(_fromUtf8("klystron1Layout"))
        self.klystron1OnLabel = QtGui.QLabel(self.layoutWidget1)
        self.klystron1OnLabel.setObjectName(_fromUtf8("klystron1OnLabel"))
        self.klystron1Layout.addWidget(self.klystron1OnLabel, 0, 1, 1, 1)
        self.klystron1RstLabel = QtGui.QLabel(self.layoutWidget1)
        self.klystron1RstLabel.setObjectName(_fromUtf8("klystron1RstLabel"))
        self.klystron1Layout.addWidget(self.klystron1RstLabel, 1, 1, 1, 1)
        self.klystron1OnLed = TaurusLed(self.layoutWidget1)
        self.klystron1OnLed.setMinimumSize(QtCore.QSize(15, 15))
        self.klystron1OnLed.setMaximumSize(QtCore.QSize(15, 15))
        self.klystron1OnLed.setObjectName(_fromUtf8("klystron1OnLed"))
        self.klystron1Layout.addWidget(self.klystron1OnLed, 0, 2, 1, 1)
        self.klystron1RstLed = TaurusLed(self.layoutWidget1)
        self.klystron1RstLed.setMinimumSize(QtCore.QSize(15, 15))
        self.klystron1RstLed.setMaximumSize(QtCore.QSize(15, 15))
        self.klystron1RstLed.setObjectName(_fromUtf8("klystron1RstLed"))
        self.klystron1Layout.addWidget(self.klystron1RstLed, 1, 2, 1, 1)
        self.klystron1RstCheck = LinacValueCheckBox(self.layoutWidget1)
        self.klystron1RstCheck.setShowText(False)
        self.klystron1RstCheck.setObjectName(_fromUtf8("klystron1RstCheck"))
        self.klystron1Layout.addWidget(self.klystron1RstCheck, 1, 3, 1, 1)
        self.klystron1OnCheck = LinacValueCheckBox(self.layoutWidget1)
        self.klystron1OnCheck.setShowText(False)
        self.klystron1OnCheck.setObjectName(_fromUtf8("klystron1OnCheck"))
        self.klystron1Layout.addWidget(self.klystron1OnCheck, 0, 3, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget2.setGeometry(QtCore.QRect(1080, 130, 77, 48))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.klystron2Layout = QtGui.QGridLayout(self.layoutWidget2)
        self.klystron2Layout.setMargin(0)
        self.klystron2Layout.setObjectName(_fromUtf8("klystron2Layout"))
        self.klystron2OnLabel = QtGui.QLabel(self.layoutWidget2)
        self.klystron2OnLabel.setObjectName(_fromUtf8("klystron2OnLabel"))
        self.klystron2Layout.addWidget(self.klystron2OnLabel, 0, 1, 1, 1)
        self.klystron2RstLabel = QtGui.QLabel(self.layoutWidget2)
        self.klystron2RstLabel.setObjectName(_fromUtf8("klystron2RstLabel"))
        self.klystron2Layout.addWidget(self.klystron2RstLabel, 1, 1, 1, 1)
        self.klystron2OnLed = TaurusLed(self.layoutWidget2)
        self.klystron2OnLed.setMinimumSize(QtCore.QSize(15, 15))
        self.klystron2OnLed.setMaximumSize(QtCore.QSize(15, 15))
        self.klystron2OnLed.setObjectName(_fromUtf8("klystron2OnLed"))
        self.klystron2Layout.addWidget(self.klystron2OnLed, 0, 2, 1, 1)
        self.klystron2RstLed = TaurusLed(self.layoutWidget2)
        self.klystron2RstLed.setMinimumSize(QtCore.QSize(15, 15))
        self.klystron2RstLed.setMaximumSize(QtCore.QSize(15, 15))
        self.klystron2RstLed.setObjectName(_fromUtf8("klystron2RstLed"))
        self.klystron2Layout.addWidget(self.klystron2RstLed, 1, 2, 1, 1)
        self.klystron2RstCheck = LinacValueCheckBox(self.layoutWidget2)
        self.klystron2RstCheck.setShowText(False)
        self.klystron2RstCheck.setObjectName(_fromUtf8("klystron2RstCheck"))
        self.klystron2Layout.addWidget(self.klystron2RstCheck, 1, 4, 1, 1)
        self.klystron2OnCheck = LinacValueCheckBox(self.layoutWidget2)
        self.klystron2OnCheck.setShowText(False)
        self.klystron2OnCheck.setObjectName(_fromUtf8("klystron2OnCheck"))
        self.klystron2Layout.addWidget(self.klystron2OnCheck, 0, 4, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget3.setGeometry(QtCore.QRect(41, 740, 63, 23))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.hvsOnLayout = QtGui.QHBoxLayout(self.layoutWidget3)
        self.hvsOnLayout.setMargin(0)
        self.hvsOnLayout.setObjectName(_fromUtf8("hvsOnLayout"))
        self.hvsOnLabel = QtGui.QLabel(self.layoutWidget3)
        self.hvsOnLabel.setObjectName(_fromUtf8("hvsOnLabel"))
        self.hvsOnLayout.addWidget(self.hvsOnLabel)
        self.hvsOnLed = TaurusLed(self.layoutWidget3)
        self.hvsOnLed.setMinimumSize(QtCore.QSize(15, 15))
        self.hvsOnLed.setMaximumSize(QtCore.QSize(15, 15))
        self.hvsOnLed.setObjectName(_fromUtf8("hvsOnLed"))
        self.hvsOnLayout.addWidget(self.hvsOnLed)
        self.hvsOnCheck = LinacValueCheckBox(self.layoutWidget3)
        self.hvsOnCheck.setShowText(False)
        self.hvsOnCheck.setObjectName(_fromUtf8("hvsOnCheck"))
        self.hvsOnLayout.addWidget(self.hvsOnCheck)
        self.klystron1HVPopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.klystron1HVPopupCheck.setGeometry(QtCore.QRect(754, 110, 20, 20))
        self.klystron1HVPopupCheck.setCheckable(True)
        self.klystron1HVPopupCheck.setObjectName(_fromUtf8("klystron1HVPopupCheck"))
        self.klystron2HVPopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.klystron2HVPopupCheck.setGeometry(QtCore.QRect(1042, 70, 20, 20))
        self.klystron2HVPopupCheck.setCheckable(True)
        self.klystron2HVPopupCheck.setObjectName(_fromUtf8("klystron2HVPopupCheck"))
        self.hvsPopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.hvsPopupCheck.setGeometry(QtCore.QRect(94, 602, 20, 20))
        self.hvsPopupCheck.setCheckable(True)
        self.hvsPopupCheck.setObjectName(_fromUtf8("hvsPopupCheck"))
        self.attenuatorPopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.attenuatorPopupCheck.setGeometry(QtCore.QRect(413, 422, 20, 20))
        self.attenuatorPopupCheck.setCheckable(True)
        self.attenuatorPopupCheck.setObjectName(_fromUtf8("attenuatorPopupCheck"))
        self.phaseShifter2PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.phaseShifter2PopupCheck.setGeometry(QtCore.QRect(466, 422, 20, 20))
        self.phaseShifter2PopupCheck.setCheckable(True)
        self.phaseShifter2PopupCheck.setObjectName(_fromUtf8("phaseShifter2PopupCheck"))
        self.phaseShifter1PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.phaseShifter1PopupCheck.setGeometry(QtCore.QRect(605, 455, 20, 20))
        self.phaseShifter1PopupCheck.setCheckable(True)
        self.phaseShifter1PopupCheck.setObjectName(_fromUtf8("phaseShifter1PopupCheck"))
        self.sl1PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.sl1PopupCheck.setGeometry(QtCore.QRect(156, 514, 20, 20))
        self.sl1PopupCheck.setCheckable(True)
        self.sl1PopupCheck.setObjectName(_fromUtf8("sl1PopupCheck"))
        self.sl2PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.sl2PopupCheck.setGeometry(QtCore.QRect(241, 513, 20, 20))
        self.sl2PopupCheck.setCheckable(True)
        self.sl2PopupCheck.setObjectName(_fromUtf8("sl2PopupCheck"))
        self.sl3PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.sl3PopupCheck.setGeometry(QtCore.QRect(326, 514, 20, 20))
        self.sl3PopupCheck.setCheckable(True)
        self.sl3PopupCheck.setChecked(False)
        self.sl3PopupCheck.setObjectName(_fromUtf8("sl3PopupCheck"))
        self.sl4PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.sl4PopupCheck.setGeometry(QtCore.QRect(397, 513, 20, 20))
        self.sl4PopupCheck.setCheckable(True)
        self.sl4PopupCheck.setObjectName(_fromUtf8("sl4PopupCheck"))
        self.bc1PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.bc1PopupCheck.setGeometry(QtCore.QRect(452, 515, 20, 20))
        self.bc1PopupCheck.setCheckable(True)
        self.bc1PopupCheck.setObjectName(_fromUtf8("bc1PopupCheck"))
        self.bc2PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.bc2PopupCheck.setGeometry(QtCore.QRect(511, 516, 20, 20))
        self.bc2PopupCheck.setCheckable(True)
        self.bc2PopupCheck.setObjectName(_fromUtf8("bc2PopupCheck"))
        self.glPopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.glPopupCheck.setGeometry(QtCore.QRect(637, 514, 20, 20))
        self.glPopupCheck.setCheckable(True)
        self.glPopupCheck.setObjectName(_fromUtf8("glPopupCheck"))
        self.as1PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.as1PopupCheck.setGeometry(QtCore.QRect(741, 531, 20, 20))
        self.as1PopupCheck.setCheckable(True)
        self.as1PopupCheck.setObjectName(_fromUtf8("as1PopupCheck"))
        self.qt1PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.qt1PopupCheck.setGeometry(QtCore.QRect(890, 513, 20, 20))
        self.qt1PopupCheck.setCheckable(True)
        self.qt1PopupCheck.setObjectName(_fromUtf8("qt1PopupCheck"))
        self.qt2PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.qt2PopupCheck.setGeometry(QtCore.QRect(937, 513, 20, 20))
        self.qt2PopupCheck.setCheckable(True)
        self.qt2PopupCheck.setObjectName(_fromUtf8("qt2PopupCheck"))
        self.as2PopupCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.as2PopupCheck.setGeometry(QtCore.QRect(1027, 531, 20, 20))
        self.as2PopupCheck.setCheckable(True)
        self.as2PopupCheck.setObjectName(_fromUtf8("as2PopupCheck"))
        self.tbRf2DelayValue = TaurusLabel(linacMainscreenSynoptic)
        self.tbRf2DelayValue.setGeometry(QtCore.QRect(177, 52, 48, 16))
        self.tbRf2DelayValue.setObjectName(_fromUtf8("tbRf2DelayValue"))
        self.tbWidthLabel = QtGui.QLabel(linacMainscreenSynoptic)
        self.tbWidthLabel.setGeometry(QtCore.QRect(240, 130, 41, 16))
        self.tbWidthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tbWidthLabel.setObjectName(_fromUtf8("tbWidthLabel"))
        self.tbNumberLabel = QtGui.QLabel(linacMainscreenSynoptic)
        self.tbNumberLabel.setGeometry(QtCore.QRect(300, 130, 41, 16))
        self.tbNumberLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tbNumberLabel.setObjectName(_fromUtf8("tbNumberLabel"))
        self.tbGunDelayLabel = QtGui.QLabel(linacMainscreenSynoptic)
        self.tbGunDelayLabel.setGeometry(QtCore.QRect(174, 130, 57, 14))
        self.tbGunDelayLabel.setObjectName(_fromUtf8("tbGunDelayLabel"))
        self.layoutWidget4 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 90, 141, 61))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.multibunchLayout = QtGui.QGridLayout(self.layoutWidget4)
        self.multibunchLayout.setMargin(0)
        self.multibunchLayout.setObjectName(_fromUtf8("multibunchLayout"))
        self.tbGatedPulseModeCombo = TaurusValueComboBox(self.layoutWidget4)
        self.tbGatedPulseModeCombo.setObjectName(_fromUtf8("tbGatedPulseModeCombo"))
        self.multibunchLayout.addWidget(self.tbGatedPulseModeCombo, 1, 2, 1, 1)
        self.multibunchLabel = QtGui.QLabel(self.layoutWidget4)
        self.multibunchLabel.setObjectName(_fromUtf8("multibunchLabel"))
        self.multibunchLayout.addWidget(self.multibunchLabel, 1, 0, 1, 1)
        self.tbMultiBunchValue = TaurusLabel(self.layoutWidget4)
        self.tbMultiBunchValue.setObjectName(_fromUtf8("tbMultiBunchValue"))
        self.multibunchLayout.addWidget(self.tbMultiBunchValue, 0, 0, 1, 2)
        self.tbGatedPulseModeLabel = QtGui.QLabel(self.layoutWidget4)
        self.tbGatedPulseModeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tbGatedPulseModeLabel.setWordWrap(True)
        self.tbGatedPulseModeLabel.setObjectName(_fromUtf8("tbGatedPulseModeLabel"))
        self.multibunchLayout.addWidget(self.tbGatedPulseModeLabel, 2, 2, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget4)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.multibunchLayout.addWidget(self.label, 2, 0, 1, 2)
        self.tbMultiBunchCheck = LinacValueCheckBox(self.layoutWidget4)
        self.tbMultiBunchCheck.setShowText(False)
        self.tbMultiBunchCheck.setObjectName(_fromUtf8("tbMultiBunchCheck"))
        self.multibunchLayout.addWidget(self.tbMultiBunchCheck, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(linacMainscreenSynoptic)
        self.label_2.setGeometry(QtCore.QRect(459, 66, 16, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.fluorescentScreen1LightView = QtGui.QPushButton(linacMainscreenSynoptic)
        self.fluorescentScreen1LightView.setGeometry(QtCore.QRect(687, 767, 40, 23))
        self.fluorescentScreen1LightView.setObjectName(_fromUtf8("fluorescentScreen1LightView"))
        self.fluorescentScreen2LightView = QtGui.QPushButton(linacMainscreenSynoptic)
        self.fluorescentScreen2LightView.setGeometry(QtCore.QRect(940, 768, 40, 23))
        self.fluorescentScreen2LightView.setObjectName(_fromUtf8("fluorescentScreen2LightView"))
        self.fluorescentScreen3LightView = QtGui.QPushButton(linacMainscreenSynoptic)
        self.fluorescentScreen3LightView.setGeometry(QtCore.QRect(1166, 767, 40, 23))
        self.fluorescentScreen3LightView.setObjectName(_fromUtf8("fluorescentScreen3LightView"))
        self.layoutWidget5 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 780, 77, 48))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.magnetsLayout = QtGui.QGridLayout(self.layoutWidget5)
        self.magnetsLayout.setMargin(0)
        self.magnetsLayout.setObjectName(_fromUtf8("magnetsLayout"))
        self.magnetsRstLabel = QtGui.QLabel(self.layoutWidget5)
        self.magnetsRstLabel.setObjectName(_fromUtf8("magnetsRstLabel"))
        self.magnetsLayout.addWidget(self.magnetsRstLabel, 0, 0, 1, 1)
        self.magnetsRstLed = TaurusLed(self.layoutWidget5)
        self.magnetsRstLed.setMinimumSize(QtCore.QSize(15, 15))
        self.magnetsRstLed.setMaximumSize(QtCore.QSize(15, 15))
        self.magnetsRstLed.setObjectName(_fromUtf8("magnetsRstLed"))
        self.magnetsLayout.addWidget(self.magnetsRstLed, 0, 1, 1, 1)
        self.magnetsOnLabel = QtGui.QLabel(self.layoutWidget5)
        self.magnetsOnLabel.setObjectName(_fromUtf8("magnetsOnLabel"))
        self.magnetsLayout.addWidget(self.magnetsOnLabel, 1, 0, 1, 1)
        self.magnetsOnLed = TaurusLed(self.layoutWidget5)
        self.magnetsOnLed.setMinimumSize(QtCore.QSize(15, 15))
        self.magnetsOnLed.setMaximumSize(QtCore.QSize(15, 15))
        self.magnetsOnLed.setObjectName(_fromUtf8("magnetsOnLed"))
        self.magnetsLayout.addWidget(self.magnetsOnLed, 1, 1, 1, 1)
        self.magnetsRstCheck = LinacValueCheckBox(self.layoutWidget5)
        self.magnetsRstCheck.setShowText(False)
        self.magnetsRstCheck.setObjectName(_fromUtf8("magnetsRstCheck"))
        self.magnetsLayout.addWidget(self.magnetsRstCheck, 0, 2, 1, 1)
        self.magnetsOnCheck = LinacValueCheckBox(self.layoutWidget5)
        self.magnetsOnCheck.setShowText(False)
        self.magnetsOnCheck.setObjectName(_fromUtf8("magnetsOnCheck"))
        self.magnetsLayout.addWidget(self.magnetsOnCheck, 1, 2, 1, 1)
        self.eGunVacuumWidget = CavityVacuum(linacMainscreenSynoptic)
        self.eGunVacuumWidget.setGeometry(QtCore.QRect(140, 570, 116, 97))
        self.eGunVacuumWidget.setObjectName(_fromUtf8("eGunVacuumWidget"))
        self.preBuncherVacuumWidget = CavityVacuum(linacMainscreenSynoptic)
        self.preBuncherVacuumWidget.setGeometry(QtCore.QRect(300, 570, 116, 97))
        self.preBuncherVacuumWidget.setObjectName(_fromUtf8("preBuncherVacuumWidget"))
        self.buncherVacuumWidget = CavityVacuum(linacMainscreenSynoptic)
        self.buncherVacuumWidget.setGeometry(QtCore.QRect(540, 570, 116, 97))
        self.buncherVacuumWidget.setObjectName(_fromUtf8("buncherVacuumWidget"))
        self.as1VacuumWidget = CavityVacuum(linacMainscreenSynoptic)
        self.as1VacuumWidget.setGeometry(QtCore.QRect(790, 570, 116, 97))
        self.as1VacuumWidget.setObjectName(_fromUtf8("as1VacuumWidget"))
        self.as2VacuumWidget = CavityVacuum(linacMainscreenSynoptic)
        self.as2VacuumWidget.setGeometry(QtCore.QRect(1080, 570, 116, 97))
        self.as2VacuumWidget.setObjectName(_fromUtf8("as2VacuumWidget"))
        self.eGunVacuumCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.eGunVacuumCheck.setGeometry(QtCore.QRect(109, 580, 40, 20))
        self.eGunVacuumCheck.setCheckable(True)
        self.eGunVacuumCheck.setObjectName(_fromUtf8("eGunVacuumCheck"))
        self.preBuncherVacuumCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.preBuncherVacuumCheck.setGeometry(QtCore.QRect(263, 580, 40, 20))
        self.preBuncherVacuumCheck.setCheckable(True)
        self.preBuncherVacuumCheck.setObjectName(_fromUtf8("preBuncherVacuumCheck"))
        self.buncherVacuumCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.buncherVacuumCheck.setGeometry(QtCore.QRect(470, 568, 40, 20))
        self.buncherVacuumCheck.setCheckable(True)
        self.buncherVacuumCheck.setObjectName(_fromUtf8("buncherVacuumCheck"))
        self.as1VacuumCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.as1VacuumCheck.setGeometry(QtCore.QRect(730, 568, 40, 20))
        self.as1VacuumCheck.setCheckable(True)
        self.as1VacuumCheck.setObjectName(_fromUtf8("as1VacuumCheck"))
        self.as2VacuumCheck = QtGui.QToolButton(linacMainscreenSynoptic)
        self.as2VacuumCheck.setGeometry(QtCore.QRect(1019, 569, 40, 20))
        self.as2VacuumCheck.setCheckable(True)
        self.as2VacuumCheck.setObjectName(_fromUtf8("as2VacuumCheck"))
        self.beamChargeMonitors = beamChargeMonitors(linacMainscreenSynoptic)
        self.beamChargeMonitors.setGeometry(QtCore.QRect(1120, 420, 131, 81))
        self.beamChargeMonitors.setObjectName(_fromUtf8("beamChargeMonitors"))
        self.layoutWidget6 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget6.setGeometry(QtCore.QRect(790, 110, 81, 51))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.klystron1HVRead = TaurusLabel(self.layoutWidget6)
        self.klystron1HVRead.setObjectName(_fromUtf8("klystron1HVRead"))
        self.verticalLayout.addWidget(self.klystron1HVRead)
        self.klystron1HVWrite = TaurusValueSpinBox(self.layoutWidget6)
        self.klystron1HVWrite.setObjectName(_fromUtf8("klystron1HVWrite"))
        self.verticalLayout.addWidget(self.klystron1HVWrite)
        self.layoutWidget7 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget7.setGeometry(QtCore.QRect(1080, 70, 81, 51))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.klystron2HVRead = TaurusLabel(self.layoutWidget7)
        self.klystron2HVRead.setObjectName(_fromUtf8("klystron2HVRead"))
        self.verticalLayout_2.addWidget(self.klystron2HVRead)
        self.klystron2HVWrite = TaurusValueSpinBox(self.layoutWidget7)
        self.klystron2HVWrite.setObjectName(_fromUtf8("klystron2HVWrite"))
        self.verticalLayout_2.addWidget(self.klystron2HVWrite)
        self.tbKaDelay1Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.tbKaDelay1Value.setGeometry(QtCore.QRect(38, 48, 60, 22))
        self.tbKaDelay1Value.setObjectName(_fromUtf8("tbKaDelay1Value"))
        self.tbKaDelay2Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.tbKaDelay2Value.setGeometry(QtCore.QRect(102, 49, 60, 22))
        self.tbKaDelay2Value.setObjectName(_fromUtf8("tbKaDelay2Value"))

        self.retranslateUi(linacMainscreenSynoptic)
        QtCore.QMetaObject.connectSlotsByName(linacMainscreenSynoptic)

    def retranslateUi(self, linacMainscreenSynoptic):
        linacMainscreenSynoptic.setWindowTitle(QtGui.QApplication.translate("linacMainscreenSynoptic", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.filamentVLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Filament V", None, QtGui.QApplication.UnicodeUTF8))
        self.cathodeLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Cathode V", None, QtGui.QApplication.UnicodeUTF8))
        self.filamentCurrent.setSuffixText(QtGui.QApplication.translate("linacMainscreenSynoptic", " A", None, QtGui.QApplication.UnicodeUTF8))
        self.temperatureValue.setSuffixText(QtGui.QApplication.translate("linacMainscreenSynoptic", " C", None, QtGui.QApplication.UnicodeUTF8))
        self.filamentILabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Filament I", None, QtGui.QApplication.UnicodeUTF8))
        self.temperatureLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.vcv_oncLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.sl1OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.sl2OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.sl3OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.sl4OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.glOnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.as1OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.qt1OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.as2OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.fluorescentScreen1LightLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.fluorescentScreen1ValveLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "In", None, QtGui.QApplication.UnicodeUTF8))
        self.fluorescentScreen2ValveLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "In", None, QtGui.QApplication.UnicodeUTF8))
        self.fluorescentScreen2LightLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.fluorescentScreen3ValveLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "In", None, QtGui.QApplication.UnicodeUTF8))
        self.fluorescentScreen3LightLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.klystron1OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.klystron1RstLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.klystron2OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.klystron2RstLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.hvsOnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.klystron1HVPopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.klystron2HVPopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.hvsPopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.attenuatorPopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseShifter2PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseShifter1PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.sl1PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.sl2PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.sl3PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.sl4PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.glPopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.as1PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.qt1PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.qt2PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.as2PopupCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.tbWidthLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.tbNumberLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Number", None, QtGui.QApplication.UnicodeUTF8))
        self.tbGunDelayLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Gun Delay", None, QtGui.QApplication.UnicodeUTF8))
        self.multibunchLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "MBM", None, QtGui.QApplication.UnicodeUTF8))
        self.tbGatedPulseModeLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Gated Pulse Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Operation mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "dB", None, QtGui.QApplication.UnicodeUTF8))
        self.fluorescentScreen1LightView.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.fluorescentScreen2LightView.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.fluorescentScreen3LightView.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.magnetsRstLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.magnetsOnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.eGunVacuumCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Vacuum", None, QtGui.QApplication.UnicodeUTF8))
        self.preBuncherVacuumCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Vacuum", None, QtGui.QApplication.UnicodeUTF8))
        self.buncherVacuumCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Vacuum", None, QtGui.QApplication.UnicodeUTF8))
        self.as1VacuumCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Vacuum", None, QtGui.QApplication.UnicodeUTF8))
        self.as2VacuumCheck.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Vacuum", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusLed, TaurusLabel
from attenuator import Attenuator
from phaseshifter import phaseShifter
from egunhv import eGunHV
from magnet import magnet
from taurus.qt.qtgui.panel import TaurusWidget
from cavityvacuum import CavityVacuum
from beamchargemonitors import beamChargeMonitors
from taurus.qt.qtgui.input import TaurusValueSpinBox, TaurusValueComboBox
from linacvaluecheckbox import LinacValueCheckBox
from klystronhv import klystronHV
