# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'linacMainscreenSynoptic.ui'
#
# Created: Wed Jan 22 16:46:26 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_linacMainscreenSynoptic(object):
    def setupUi(self, linacMainscreenSynoptic):
        linacMainscreenSynoptic.setObjectName(_fromUtf8("linacMainscreenSynoptic"))
        linacMainscreenSynoptic.resize(1250, 825)
        linacMainscreenSynoptic.setMinimumSize(QtCore.QSize(1250, 825))
        linacMainscreenSynoptic.setMaximumSize(QtCore.QSize(1250, 825))
        self.MainScreenSchematic = TaurusJDrawSynopticsView(linacMainscreenSynoptic)
        self.MainScreenSchematic.setGeometry(QtCore.QRect(0, 0, 1265, 829))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.MainScreenSchematic.setForegroundBrush(brush)
        self.MainScreenSchematic.setObjectName(_fromUtf8("MainScreenSchematic"))
        self.kadelay1Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.kadelay1Value.setGeometry(QtCore.QRect(50, 50, 56, 22))
        self.kadelay1Value.setObjectName(_fromUtf8("kadelay1Value"))
        self.kadelay2Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.kadelay2Value.setGeometry(QtCore.QRect(110, 50, 56, 22))
        self.kadelay2Value.setObjectName(_fromUtf8("kadelay2Value"))
        self.rf2delayValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.rf2delayValue.setGeometry(QtCore.QRect(180, 50, 56, 22))
        self.rf2delayValue.setObjectName(_fromUtf8("rf2delayValue"))
        self.gunLevelValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.gunLevelValue.setGeometry(QtCore.QRect(400, 66, 70, 22))
        self.gunLevelValue.setObjectName(_fromUtf8("gunLevelValue"))
        self.numberValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.numberValue.setGeometry(QtCore.QRect(300, 110, 56, 22))
        self.numberValue.setObjectName(_fromUtf8("numberValue"))
        self.WidthValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.WidthValue.setGeometry(QtCore.QRect(240, 110, 56, 22))
        self.WidthValue.setObjectName(_fromUtf8("WidthValue"))
        self.gunDelayValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.gunDelayValue.setGeometry(QtCore.QRect(180, 110, 56, 22))
        self.gunDelayValue.setObjectName(_fromUtf8("gunDelayValue"))
        self.gatedPulseModeValue = TaurusValueComboBox(linacMainscreenSynoptic)
        self.gatedPulseModeValue.setGeometry(QtCore.QRect(100, 100, 70, 23))
        self.gatedPulseModeValue.setObjectName(_fromUtf8("gatedPulseModeValue"))
        self.k1Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.k1Value.setGeometry(QtCore.QRect(800, 130, 56, 22))
        self.k1Value.setObjectName(_fromUtf8("k1Value"))
        self.k2Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.k2Value.setGeometry(QtCore.QRect(1085, 85, 56, 22))
        self.k2Value.setObjectName(_fromUtf8("k2Value"))
        self.rfEnbLed = TaurusLed(linacMainscreenSynoptic)
        self.rfEnbLed.setGeometry(QtCore.QRect(602, 15, 15, 15))
        self.rfEnbLed.setMinimumSize(QtCore.QSize(15, 15))
        self.rfEnbLed.setMaximumSize(QtCore.QSize(15, 15))
        self.rfEnbLed.setObjectName(_fromUtf8("rfEnbLed"))
        self.tbLed = TaurusLed(linacMainscreenSynoptic)
        self.tbLed.setGeometry(QtCore.QRect(473, 23, 10, 10))
        self.tbLed.setMinimumSize(QtCore.QSize(10, 10))
        self.tbLed.setMaximumSize(QtCore.QSize(10, 10))
        self.tbLed.setObjectName(_fromUtf8("tbLed"))
        self.tps0Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.tps0Value.setGeometry(QtCore.QRect(130, 310, 56, 22))
        self.tps0Value.setObjectName(_fromUtf8("tps0Value"))
        self.a0gsValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.a0gsValue.setGeometry(QtCore.QRect(190, 310, 56, 22))
        self.a0gsValue.setObjectName(_fromUtf8("a0gsValue"))
        self.tpsxValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.tpsxValue.setGeometry(QtCore.QRect(280, 280, 56, 22))
        self.tpsxValue.setObjectName(_fromUtf8("tpsxValue"))
        self.att2Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.att2Value.setGeometry(QtCore.QRect(380, 310, 56, 22))
        self.att2Value.setObjectName(_fromUtf8("att2Value"))
        self.phs2Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.phs2Value.setGeometry(QtCore.QRect(440, 310, 56, 22))
        self.phs2Value.setObjectName(_fromUtf8("phs2Value"))
        self.tps1Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.tps1Value.setGeometry(QtCore.QRect(530, 280, 56, 22))
        self.tps1Value.setObjectName(_fromUtf8("tps1Value"))
        self.phs1Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.phs1Value.setGeometry(QtCore.QRect(580, 310, 56, 22))
        self.phs1Value.setObjectName(_fromUtf8("phs1Value"))
        self.sf6p1Value = TaurusLabel(linacMainscreenSynoptic)
        self.sf6p1Value.setGeometry(QtCore.QRect(740, 310, 75, 16))
        self.sf6p1Value.setObjectName(_fromUtf8("sf6p1Value"))
        self.sf6p2Value = TaurusLabel(linacMainscreenSynoptic)
        self.sf6p2Value.setGeometry(QtCore.QRect(1020, 310, 75, 16))
        self.sf6p2Value.setObjectName(_fromUtf8("sf6p2Value"))
        self.tps2Value = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.tps2Value.setGeometry(QtCore.QRect(850, 280, 56, 22))
        self.tps2Value.setObjectName(_fromUtf8("tps2Value"))
        self.cl1Led = TaurusLed(linacMainscreenSynoptic)
        self.cl1Led.setGeometry(QtCore.QRect(1170, 285, 10, 10))
        self.cl1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.cl1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.cl1Led.setObjectName(_fromUtf8("cl1Led"))
        self.cl2Led = TaurusLed(linacMainscreenSynoptic)
        self.cl2Led.setGeometry(QtCore.QRect(1170, 303, 10, 10))
        self.cl2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.cl2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.cl2Led.setObjectName(_fromUtf8("cl2Led"))
        self.cl3Led = TaurusLed(linacMainscreenSynoptic)
        self.cl3Led.setGeometry(QtCore.QRect(1170, 320, 10, 10))
        self.cl3Led.setMinimumSize(QtCore.QSize(10, 10))
        self.cl3Led.setMaximumSize(QtCore.QSize(10, 10))
        self.cl3Led.setObjectName(_fromUtf8("cl3Led"))
        self.layoutWidget_2 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 440, 132, 81))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setContentsMargins(7, -1, -1, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.filamentSetpoint = TaurusValueSpinBox(self.layoutWidget_2)
        self.filamentSetpoint.setAutoApply(True)
        self.filamentSetpoint.setObjectName(_fromUtf8("filamentSetpoint"))
        self.gridLayout.addWidget(self.filamentSetpoint, 0, 0, 1, 1)
        self.cathodeSetpoint = TaurusValueSpinBox(self.layoutWidget_2)
        self.cathodeSetpoint.setAutoApply(True)
        self.cathodeSetpoint.setObjectName(_fromUtf8("cathodeSetpoint"))
        self.gridLayout.addWidget(self.cathodeSetpoint, 0, 1, 1, 1)
        self.filamentVLabel = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.filamentVLabel.setFont(font)
        self.filamentVLabel.setObjectName(_fromUtf8("filamentVLabel"))
        self.gridLayout.addWidget(self.filamentVLabel, 1, 0, 1, 1)
        self.cathodeLabel = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.cathodeLabel.setFont(font)
        self.cathodeLabel.setObjectName(_fromUtf8("cathodeLabel"))
        self.gridLayout.addWidget(self.cathodeLabel, 1, 1, 1, 1)
        self.filamentCurrent = TaurusLabel(self.layoutWidget_2)
        self.filamentCurrent.setObjectName(_fromUtf8("filamentCurrent"))
        self.gridLayout.addWidget(self.filamentCurrent, 2, 0, 1, 1)
        self.temperatureValue = TaurusLabel(self.layoutWidget_2)
        self.temperatureValue.setObjectName(_fromUtf8("temperatureValue"))
        self.gridLayout.addWidget(self.temperatureValue, 2, 1, 1, 1)
        self.filamentILabel = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.filamentILabel.setFont(font)
        self.filamentILabel.setObjectName(_fromUtf8("filamentILabel"))
        self.gridLayout.addWidget(self.filamentILabel, 3, 0, 1, 1)
        self.temperatureLabel = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.temperatureLabel.setFont(font)
        self.temperatureLabel.setObjectName(_fromUtf8("temperatureLabel"))
        self.gridLayout.addWidget(self.temperatureLabel, 3, 1, 1, 1)
        self.layoutWidget_3 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_3.setGeometry(QtCore.QRect(40, 740, 71, 23))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.hvsOnLayout = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.hvsOnLayout.setMargin(0)
        self.hvsOnLayout.setObjectName(_fromUtf8("hvsOnLayout"))
        self.hvsOnLabel = QtGui.QLabel(self.layoutWidget_3)
        self.hvsOnLabel.setObjectName(_fromUtf8("hvsOnLabel"))
        self.hvsOnLayout.addWidget(self.hvsOnLabel)
        self.hvsOnCheck = TaurusValueCheckBox(self.layoutWidget_3)
        self.hvsOnCheck.setShowText(False)
        self.hvsOnCheck.setAutoApply(True)
        self.hvsOnCheck.setForcedApply(False)
        self.hvsOnCheck.setObjectName(_fromUtf8("hvsOnCheck"))
        self.hvsOnLayout.addWidget(self.hvsOnCheck)
        self.hvsOnLed = TaurusLed(self.layoutWidget_3)
        self.hvsOnLed.setMinimumSize(QtCore.QSize(15, 15))
        self.hvsOnLed.setMaximumSize(QtCore.QSize(15, 15))
        self.hvsOnLed.setObjectName(_fromUtf8("hvsOnLed"))
        self.hvsOnLayout.addWidget(self.hvsOnLed)
        self.layoutWidget_4 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_4.setGeometry(QtCore.QRect(200, 790, 68, 23))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.vv1Layout = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.vv1Layout.setContentsMargins(5, -1, -1, -1)
        self.vv1Layout.setObjectName(_fromUtf8("vv1Layout"))
        self.vv1_oncCheck = TaurusValueCheckBox(self.layoutWidget_4)
        self.vv1_oncCheck.setShowText(False)
        self.vv1_oncCheck.setAutoApply(True)
        self.vv1_oncCheck.setForcedApply(False)
        self.vv1_oncCheck.setObjectName(_fromUtf8("vv1_oncCheck"))
        self.vv1Layout.addWidget(self.vv1_oncCheck)
        self.vv1_oncLabel = QtGui.QLabel(self.layoutWidget_4)
        self.vv1_oncLabel.setObjectName(_fromUtf8("vv1_oncLabel"))
        self.vv1Layout.addWidget(self.vv1_oncLabel)
        self.bc2hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc2hValue.setGeometry(QtCore.QRect(510, 640, 56, 22))
        self.bc2hValue.setObjectName(_fromUtf8("bc2hValue"))
        self.bc2vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc2vValue.setGeometry(QtCore.QRect(510, 670, 56, 22))
        self.bc2vValue.setObjectName(_fromUtf8("bc2vValue"))
        self.bc2fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc2fValue.setGeometry(QtCore.QRect(510, 700, 56, 22))
        self.bc2fValue.setObjectName(_fromUtf8("bc2fValue"))
        self.bc1fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc1fValue.setGeometry(QtCore.QRect(450, 700, 56, 22))
        self.bc1fValue.setObjectName(_fromUtf8("bc1fValue"))
        self.bc1vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc1vValue.setGeometry(QtCore.QRect(450, 670, 56, 22))
        self.bc1vValue.setObjectName(_fromUtf8("bc1vValue"))
        self.bc1hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.bc1hValue.setGeometry(QtCore.QRect(450, 640, 56, 22))
        self.bc1hValue.setObjectName(_fromUtf8("bc1hValue"))
        self.sl4hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl4hValue.setGeometry(QtCore.QRect(390, 640, 56, 22))
        self.sl4hValue.setObjectName(_fromUtf8("sl4hValue"))
        self.sl3hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl3hValue.setGeometry(QtCore.QRect(320, 640, 56, 22))
        self.sl3hValue.setObjectName(_fromUtf8("sl3hValue"))
        self.sl2hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl2hValue.setGeometry(QtCore.QRect(230, 640, 56, 22))
        self.sl2hValue.setObjectName(_fromUtf8("sl2hValue"))
        self.sl1hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl1hValue.setGeometry(QtCore.QRect(150, 640, 56, 22))
        self.sl1hValue.setObjectName(_fromUtf8("sl1hValue"))
        self.sl4vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl4vValue.setGeometry(QtCore.QRect(390, 670, 56, 22))
        self.sl4vValue.setObjectName(_fromUtf8("sl4vValue"))
        self.sl4fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl4fValue.setGeometry(QtCore.QRect(390, 700, 56, 22))
        self.sl4fValue.setObjectName(_fromUtf8("sl4fValue"))
        self.sl3vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl3vValue.setGeometry(QtCore.QRect(320, 670, 56, 22))
        self.sl3vValue.setObjectName(_fromUtf8("sl3vValue"))
        self.sl2vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl2vValue.setGeometry(QtCore.QRect(230, 670, 56, 22))
        self.sl2vValue.setObjectName(_fromUtf8("sl2vValue"))
        self.sl1vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl1vValue.setGeometry(QtCore.QRect(150, 670, 56, 22))
        self.sl1vValue.setObjectName(_fromUtf8("sl1vValue"))
        self.sl1fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl1fValue.setGeometry(QtCore.QRect(150, 700, 56, 22))
        self.sl1fValue.setObjectName(_fromUtf8("sl1fValue"))
        self.sl3fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl3fValue.setGeometry(QtCore.QRect(320, 700, 56, 22))
        self.sl3fValue.setObjectName(_fromUtf8("sl3fValue"))
        self.sl2fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.sl2fValue.setGeometry(QtCore.QRect(230, 700, 56, 22))
        self.sl2fValue.setObjectName(_fromUtf8("sl2fValue"))
        self.layoutWidget_6 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_6.setGeometry(QtCore.QRect(140, 730, 51, 23))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.sl1OnLayout = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.sl1OnLayout.setMargin(0)
        self.sl1OnLayout.setObjectName(_fromUtf8("sl1OnLayout"))
        self.sl1OnLabel = QtGui.QLabel(self.layoutWidget_6)
        self.sl1OnLabel.setObjectName(_fromUtf8("sl1OnLabel"))
        self.sl1OnLayout.addWidget(self.sl1OnLabel)
        self.sl1OnCheck = TaurusValueCheckBox(self.layoutWidget_6)
        self.sl1OnCheck.setShowText(False)
        self.sl1OnCheck.setAutoApply(True)
        self.sl1OnCheck.setForcedApply(False)
        self.sl1OnCheck.setObjectName(_fromUtf8("sl1OnCheck"))
        self.sl1OnLayout.addWidget(self.sl1OnCheck)
        self.layoutWidget_7 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_7.setGeometry(QtCore.QRect(250, 730, 51, 23))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.sl21OnLayout = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.sl21OnLayout.setMargin(0)
        self.sl21OnLayout.setObjectName(_fromUtf8("sl21OnLayout"))
        self.sl2OnCheck = TaurusValueCheckBox(self.layoutWidget_7)
        self.sl2OnCheck.setShowText(False)
        self.sl2OnCheck.setAutoApply(True)
        self.sl2OnCheck.setForcedApply(False)
        self.sl2OnCheck.setObjectName(_fromUtf8("sl2OnCheck"))
        self.sl21OnLayout.addWidget(self.sl2OnCheck)
        self.sl2OnLabel = QtGui.QLabel(self.layoutWidget_7)
        self.sl2OnLabel.setObjectName(_fromUtf8("sl2OnLabel"))
        self.sl21OnLayout.addWidget(self.sl2OnLabel)
        self.layoutWidget_8 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_8.setGeometry(QtCore.QRect(330, 730, 51, 23))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.sl3OnLayout = QtGui.QHBoxLayout(self.layoutWidget_8)
        self.sl3OnLayout.setMargin(0)
        self.sl3OnLayout.setObjectName(_fromUtf8("sl3OnLayout"))
        self.sl3OnCheck = TaurusValueCheckBox(self.layoutWidget_8)
        self.sl3OnCheck.setShowText(False)
        self.sl3OnCheck.setAutoApply(True)
        self.sl3OnCheck.setForcedApply(False)
        self.sl3OnCheck.setObjectName(_fromUtf8("sl3OnCheck"))
        self.sl3OnLayout.addWidget(self.sl3OnCheck)
        self.sl3OnLabel = QtGui.QLabel(self.layoutWidget_8)
        self.sl3OnLabel.setObjectName(_fromUtf8("sl3OnLabel"))
        self.sl3OnLayout.addWidget(self.sl3OnLabel)
        self.layoutWidget_9 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_9.setGeometry(QtCore.QRect(400, 730, 51, 23))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.sl4OnLayout = QtGui.QHBoxLayout(self.layoutWidget_9)
        self.sl4OnLayout.setMargin(0)
        self.sl4OnLayout.setObjectName(_fromUtf8("sl4OnLayout"))
        self.sl4OnCheck = TaurusValueCheckBox(self.layoutWidget_9)
        self.sl4OnCheck.setShowText(False)
        self.sl4OnCheck.setAutoApply(True)
        self.sl4OnCheck.setForcedApply(False)
        self.sl4OnCheck.setObjectName(_fromUtf8("sl4OnCheck"))
        self.sl4OnLayout.addWidget(self.sl4OnCheck)
        self.sl4OnLabel = QtGui.QLabel(self.layoutWidget_9)
        self.sl4OnLabel.setObjectName(_fromUtf8("sl4OnLabel"))
        self.sl4OnLayout.addWidget(self.sl4OnLabel)
        self.layoutWidget_10 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_10.setGeometry(QtCore.QRect(460, 730, 51, 23))
        self.layoutWidget_10.setObjectName(_fromUtf8("layoutWidget_10"))
        self.bc1Layout = QtGui.QHBoxLayout(self.layoutWidget_10)
        self.bc1Layout.setMargin(0)
        self.bc1Layout.setObjectName(_fromUtf8("bc1Layout"))
        self.bc1OnCheck = TaurusValueCheckBox(self.layoutWidget_10)
        self.bc1OnCheck.setShowText(False)
        self.bc1OnCheck.setAutoApply(True)
        self.bc1OnCheck.setForcedApply(False)
        self.bc1OnCheck.setObjectName(_fromUtf8("bc1OnCheck"))
        self.bc1Layout.addWidget(self.bc1OnCheck)
        self.bc1OnLabel = QtGui.QLabel(self.layoutWidget_10)
        self.bc1OnLabel.setObjectName(_fromUtf8("bc1OnLabel"))
        self.bc1Layout.addWidget(self.bc1OnLabel)
        self.layoutWidget_11 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_11.setGeometry(QtCore.QRect(520, 730, 51, 23))
        self.layoutWidget_11.setObjectName(_fromUtf8("layoutWidget_11"))
        self.bc2Layout = QtGui.QHBoxLayout(self.layoutWidget_11)
        self.bc2Layout.setMargin(0)
        self.bc2Layout.setObjectName(_fromUtf8("bc2Layout"))
        self.bc2OnCheck = TaurusValueCheckBox(self.layoutWidget_11)
        self.bc2OnCheck.setShowText(False)
        self.bc2OnCheck.setAutoApply(True)
        self.bc2OnCheck.setForcedApply(False)
        self.bc2OnCheck.setObjectName(_fromUtf8("bc2OnCheck"))
        self.bc2Layout.addWidget(self.bc2OnCheck)
        self.bc2OnLabel = QtGui.QLabel(self.layoutWidget_11)
        self.bc2OnLabel.setObjectName(_fromUtf8("bc2OnLabel"))
        self.bc2Layout.addWidget(self.bc2OnLabel)
        self.glhValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.glhValue.setGeometry(QtCore.QRect(630, 640, 56, 22))
        self.glhValue.setObjectName(_fromUtf8("glhValue"))
        self.glvValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.glvValue.setGeometry(QtCore.QRect(630, 670, 56, 22))
        self.glvValue.setObjectName(_fromUtf8("glvValue"))
        self.glfValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.glfValue.setGeometry(QtCore.QRect(630, 700, 56, 22))
        self.glfValue.setObjectName(_fromUtf8("glfValue"))
        self.layoutWidget_12 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_12.setGeometry(QtCore.QRect(640, 730, 51, 23))
        self.layoutWidget_12.setObjectName(_fromUtf8("layoutWidget_12"))
        self.glLayout = QtGui.QHBoxLayout(self.layoutWidget_12)
        self.glLayout.setMargin(0)
        self.glLayout.setObjectName(_fromUtf8("glLayout"))
        self.glOnCheck = TaurusValueCheckBox(self.layoutWidget_12)
        self.glOnCheck.setShowText(False)
        self.glOnCheck.setAutoApply(True)
        self.glOnCheck.setForcedApply(False)
        self.glOnCheck.setObjectName(_fromUtf8("glOnCheck"))
        self.glLayout.addWidget(self.glOnCheck)
        self.glOnLabel = QtGui.QLabel(self.layoutWidget_12)
        self.glOnLabel.setObjectName(_fromUtf8("glOnLabel"))
        self.glLayout.addWidget(self.glOnLabel)
        self.as1hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.as1hValue.setGeometry(QtCore.QRect(730, 640, 56, 22))
        self.as1hValue.setObjectName(_fromUtf8("as1hValue"))
        self.as1vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.as1vValue.setGeometry(QtCore.QRect(730, 670, 56, 22))
        self.as1vValue.setObjectName(_fromUtf8("as1vValue"))
        self.layoutWidget_13 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_13.setGeometry(QtCore.QRect(750, 730, 51, 23))
        self.layoutWidget_13.setObjectName(_fromUtf8("layoutWidget_13"))
        self.as1OnLayout = QtGui.QHBoxLayout(self.layoutWidget_13)
        self.as1OnLayout.setMargin(0)
        self.as1OnLayout.setObjectName(_fromUtf8("as1OnLayout"))
        self.as1OnCheck = TaurusValueCheckBox(self.layoutWidget_13)
        self.as1OnCheck.setShowText(False)
        self.as1OnCheck.setAutoApply(True)
        self.as1OnCheck.setForcedApply(False)
        self.as1OnCheck.setObjectName(_fromUtf8("as1OnCheck"))
        self.as1OnLayout.addWidget(self.as1OnCheck)
        self.as1OnLabel = QtGui.QLabel(self.layoutWidget_13)
        self.as1OnLabel.setObjectName(_fromUtf8("as1OnLabel"))
        self.as1OnLayout.addWidget(self.as1OnLabel)
        self.qt1hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.qt1hValue.setGeometry(QtCore.QRect(880, 650, 56, 22))
        self.qt1hValue.setObjectName(_fromUtf8("qt1hValue"))
        self.qt1vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.qt1vValue.setGeometry(QtCore.QRect(880, 680, 56, 22))
        self.qt1vValue.setObjectName(_fromUtf8("qt1vValue"))
        self.qt1fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.qt1fValue.setGeometry(QtCore.QRect(880, 710, 56, 22))
        self.qt1fValue.setObjectName(_fromUtf8("qt1fValue"))
        self.layoutWidget_14 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_14.setGeometry(QtCore.QRect(890, 740, 51, 23))
        self.layoutWidget_14.setObjectName(_fromUtf8("layoutWidget_14"))
        self.qt1OnLayout = QtGui.QHBoxLayout(self.layoutWidget_14)
        self.qt1OnLayout.setMargin(0)
        self.qt1OnLayout.setObjectName(_fromUtf8("qt1OnLayout"))
        self.qt1OnCheck = TaurusValueCheckBox(self.layoutWidget_14)
        self.qt1OnCheck.setShowText(False)
        self.qt1OnCheck.setAutoApply(True)
        self.qt1OnCheck.setForcedApply(False)
        self.qt1OnCheck.setObjectName(_fromUtf8("qt1OnCheck"))
        self.qt1OnLayout.addWidget(self.qt1OnCheck)
        self.qt1OnLabel = QtGui.QLabel(self.layoutWidget_14)
        self.qt1OnLabel.setObjectName(_fromUtf8("qt1OnLabel"))
        self.qt1OnLayout.addWidget(self.qt1OnLabel)
        self.as2hValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.as2hValue.setGeometry(QtCore.QRect(1015, 650, 56, 22))
        self.as2hValue.setObjectName(_fromUtf8("as2hValue"))
        self.as2vValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.as2vValue.setGeometry(QtCore.QRect(1015, 680, 56, 22))
        self.as2vValue.setObjectName(_fromUtf8("as2vValue"))
        self.qt2fValue = TaurusValueSpinBox(linacMainscreenSynoptic)
        self.qt2fValue.setGeometry(QtCore.QRect(940, 710, 56, 22))
        self.qt2fValue.setObjectName(_fromUtf8("qt2fValue"))
        self.layoutWidget_15 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_15.setGeometry(QtCore.QRect(1030, 740, 51, 23))
        self.layoutWidget_15.setObjectName(_fromUtf8("layoutWidget_15"))
        self.as2OnLayout = QtGui.QHBoxLayout(self.layoutWidget_15)
        self.as2OnLayout.setMargin(0)
        self.as2OnLayout.setObjectName(_fromUtf8("as2OnLayout"))
        self.as2OnCheck = TaurusValueCheckBox(self.layoutWidget_15)
        self.as2OnCheck.setShowText(False)
        self.as2OnCheck.setAutoApply(True)
        self.as2OnCheck.setForcedApply(False)
        self.as2OnCheck.setObjectName(_fromUtf8("as2OnCheck"))
        self.as2OnLayout.addWidget(self.as2OnCheck)
        self.as2OnLabel = QtGui.QLabel(self.layoutWidget_15)
        self.as2OnLabel.setObjectName(_fromUtf8("as2OnLabel"))
        self.as2OnLayout.addWidget(self.as2OnLabel)
        self.sl1Led = TaurusLed(linacMainscreenSynoptic)
        self.sl1Led.setGeometry(QtCore.QRect(172, 500, 10, 10))
        self.sl1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sl1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sl1Led.setObjectName(_fromUtf8("sl1Led"))
        self.vv1led = TaurusLed(linacMainscreenSynoptic)
        self.vv1led.setGeometry(QtCore.QRect(207, 540, 10, 10))
        self.vv1led.setMinimumSize(QtCore.QSize(10, 10))
        self.vv1led.setMaximumSize(QtCore.QSize(10, 10))
        self.vv1led.setObjectName(_fromUtf8("vv1led"))
        self.sl2Led = TaurusLed(linacMainscreenSynoptic)
        self.sl2Led.setGeometry(QtCore.QRect(257, 500, 10, 10))
        self.sl2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sl2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sl2Led.setObjectName(_fromUtf8("sl2Led"))
        self.sl3Led = TaurusLed(linacMainscreenSynoptic)
        self.sl3Led.setGeometry(QtCore.QRect(339, 500, 10, 10))
        self.sl3Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sl3Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sl3Led.setObjectName(_fromUtf8("sl3Led"))
        self.sl4Led = TaurusLed(linacMainscreenSynoptic)
        self.sl4Led.setGeometry(QtCore.QRect(411, 500, 10, 10))
        self.sl4Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sl4Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sl4Led.setObjectName(_fromUtf8("sl4Led"))
        self.bc1Led = TaurusLed(linacMainscreenSynoptic)
        self.bc1Led.setGeometry(QtCore.QRect(470, 500, 10, 10))
        self.bc1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.bc1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.bc1Led.setObjectName(_fromUtf8("bc1Led"))
        self.bc2Led = TaurusLed(linacMainscreenSynoptic)
        self.bc2Led.setGeometry(QtCore.QRect(520, 500, 10, 10))
        self.bc2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.bc2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.bc2Led.setObjectName(_fromUtf8("bc2Led"))
        self.sm1Led = TaurusLed(linacMainscreenSynoptic)
        self.sm1Led.setGeometry(QtCore.QRect(613, 505, 10, 10))
        self.sm1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sm1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sm1Led.setObjectName(_fromUtf8("sm1Led"))
        self.glLed = TaurusLed(linacMainscreenSynoptic)
        self.glLed.setGeometry(QtCore.QRect(650, 500, 10, 10))
        self.glLed.setMinimumSize(QtCore.QSize(10, 10))
        self.glLed.setMaximumSize(QtCore.QSize(10, 10))
        self.glLed.setObjectName(_fromUtf8("glLed"))
        self.as1Led = TaurusLed(linacMainscreenSynoptic)
        self.as1Led.setGeometry(QtCore.QRect(752, 520, 10, 10))
        self.as1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.as1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.as1Led.setObjectName(_fromUtf8("as1Led"))
        self.sm2Led = TaurusLed(linacMainscreenSynoptic)
        self.sm2Led.setGeometry(QtCore.QRect(866, 505, 10, 10))
        self.sm2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sm2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sm2Led.setObjectName(_fromUtf8("sm2Led"))
        self.qtLed = TaurusLed(linacMainscreenSynoptic)
        self.qtLed.setGeometry(QtCore.QRect(923, 500, 10, 10))
        self.qtLed.setMinimumSize(QtCore.QSize(10, 10))
        self.qtLed.setMaximumSize(QtCore.QSize(10, 10))
        self.qtLed.setObjectName(_fromUtf8("qtLed"))
        self.as2Led = TaurusLed(linacMainscreenSynoptic)
        self.as2Led.setGeometry(QtCore.QRect(1037, 520, 10, 10))
        self.as2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.as2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.as2Led.setObjectName(_fromUtf8("as2Led"))
        self.sm3Led = TaurusLed(linacMainscreenSynoptic)
        self.sm3Led.setGeometry(QtCore.QRect(1139, 505, 10, 10))
        self.sm3Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sm3Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sm3Led.setObjectName(_fromUtf8("sm3Led"))
        self.layoutWidget_16 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_16.setGeometry(QtCore.QRect(660, 790, 67, 23))
        self.layoutWidget_16.setObjectName(_fromUtf8("layoutWidget_16"))
        self.sm1OnLayout = QtGui.QHBoxLayout(self.layoutWidget_16)
        self.sm1OnLayout.setMargin(0)
        self.sm1OnLayout.setObjectName(_fromUtf8("sm1OnLayout"))
        self.sm1OnLabel = QtGui.QLabel(self.layoutWidget_16)
        self.sm1OnLabel.setObjectName(_fromUtf8("sm1OnLabel"))
        self.sm1OnLayout.addWidget(self.sm1OnLabel)
        self.sm1OnCheck = TaurusValueCheckBox(self.layoutWidget_16)
        self.sm1OnCheck.setShowText(False)
        self.sm1OnCheck.setAutoApply(True)
        self.sm1OnCheck.setForcedApply(False)
        self.sm1OnCheck.setObjectName(_fromUtf8("sm1OnCheck"))
        self.sm1OnLayout.addWidget(self.sm1OnCheck)
        self.sm1OnLed = TaurusLed(self.layoutWidget_16)
        self.sm1OnLed.setMinimumSize(QtCore.QSize(15, 15))
        self.sm1OnLed.setMaximumSize(QtCore.QSize(15, 15))
        self.sm1OnLed.setObjectName(_fromUtf8("sm1OnLed"))
        self.sm1OnLayout.addWidget(self.sm1OnLed)
        self.layoutWidget_17 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_17.setGeometry(QtCore.QRect(590, 790, 61, 23))
        self.layoutWidget_17.setObjectName(_fromUtf8("layoutWidget_17"))
        self.sm1InLayout = QtGui.QHBoxLayout(self.layoutWidget_17)
        self.sm1InLayout.setMargin(0)
        self.sm1InLayout.setObjectName(_fromUtf8("sm1InLayout"))
        self.sm1InLabel = QtGui.QLabel(self.layoutWidget_17)
        self.sm1InLabel.setObjectName(_fromUtf8("sm1InLabel"))
        self.sm1InLayout.addWidget(self.sm1InLabel)
        self.sm1InCheck = TaurusValueCheckBox(self.layoutWidget_17)
        self.sm1InCheck.setShowText(False)
        self.sm1InCheck.setAutoApply(True)
        self.sm1InCheck.setForcedApply(False)
        self.sm1InCheck.setObjectName(_fromUtf8("sm1InCheck"))
        self.sm1InLayout.addWidget(self.sm1InCheck)
        self.sm1InLed = TaurusLed(self.layoutWidget_17)
        self.sm1InLed.setMinimumSize(QtCore.QSize(15, 15))
        self.sm1InLed.setMaximumSize(QtCore.QSize(15, 15))
        self.sm1InLed.setObjectName(_fromUtf8("sm1InLed"))
        self.sm1InLayout.addWidget(self.sm1InLed)
        self.layoutWidget_18 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_18.setGeometry(QtCore.QRect(840, 790, 61, 23))
        self.layoutWidget_18.setObjectName(_fromUtf8("layoutWidget_18"))
        self.sm2InLayout = QtGui.QHBoxLayout(self.layoutWidget_18)
        self.sm2InLayout.setMargin(0)
        self.sm2InLayout.setObjectName(_fromUtf8("sm2InLayout"))
        self.sm2InLabel = QtGui.QLabel(self.layoutWidget_18)
        self.sm2InLabel.setObjectName(_fromUtf8("sm2InLabel"))
        self.sm2InLayout.addWidget(self.sm2InLabel)
        self.sm2InCheck = TaurusValueCheckBox(self.layoutWidget_18)
        self.sm2InCheck.setShowText(False)
        self.sm2InCheck.setAutoApply(True)
        self.sm2InCheck.setForcedApply(False)
        self.sm2InCheck.setObjectName(_fromUtf8("sm2InCheck"))
        self.sm2InLayout.addWidget(self.sm2InCheck)
        self.sm2InLed = TaurusLed(self.layoutWidget_18)
        self.sm2InLed.setMinimumSize(QtCore.QSize(15, 15))
        self.sm2InLed.setMaximumSize(QtCore.QSize(15, 15))
        self.sm2InLed.setObjectName(_fromUtf8("sm2InLed"))
        self.sm2InLayout.addWidget(self.sm2InLed)
        self.layoutWidget_19 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_19.setGeometry(QtCore.QRect(910, 790, 67, 23))
        self.layoutWidget_19.setObjectName(_fromUtf8("layoutWidget_19"))
        self.sm2OnLayout = QtGui.QHBoxLayout(self.layoutWidget_19)
        self.sm2OnLayout.setMargin(0)
        self.sm2OnLayout.setObjectName(_fromUtf8("sm2OnLayout"))
        self.sm2OnLabel = QtGui.QLabel(self.layoutWidget_19)
        self.sm2OnLabel.setObjectName(_fromUtf8("sm2OnLabel"))
        self.sm2OnLayout.addWidget(self.sm2OnLabel)
        self.sm2OnCheck = TaurusValueCheckBox(self.layoutWidget_19)
        self.sm2OnCheck.setShowText(False)
        self.sm2OnCheck.setAutoApply(True)
        self.sm2OnCheck.setForcedApply(False)
        self.sm2OnCheck.setObjectName(_fromUtf8("sm2OnCheck"))
        self.sm2OnLayout.addWidget(self.sm2OnCheck)
        self.sm2OnLed = TaurusLed(self.layoutWidget_19)
        self.sm2OnLed.setMinimumSize(QtCore.QSize(15, 15))
        self.sm2OnLed.setMaximumSize(QtCore.QSize(15, 15))
        self.sm2OnLed.setObjectName(_fromUtf8("sm2OnLed"))
        self.sm2OnLayout.addWidget(self.sm2OnLed)
        self.layoutWidget_20 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_20.setGeometry(QtCore.QRect(1070, 790, 61, 23))
        self.layoutWidget_20.setObjectName(_fromUtf8("layoutWidget_20"))
        self.sm3InLayout = QtGui.QHBoxLayout(self.layoutWidget_20)
        self.sm3InLayout.setMargin(0)
        self.sm3InLayout.setObjectName(_fromUtf8("sm3InLayout"))
        self.sm3InLabel = QtGui.QLabel(self.layoutWidget_20)
        self.sm3InLabel.setObjectName(_fromUtf8("sm3InLabel"))
        self.sm3InLayout.addWidget(self.sm3InLabel)
        self.sm3InCheck = TaurusValueCheckBox(self.layoutWidget_20)
        self.sm3InCheck.setShowText(False)
        self.sm3InCheck.setAutoApply(True)
        self.sm3InCheck.setForcedApply(False)
        self.sm3InCheck.setObjectName(_fromUtf8("sm3InCheck"))
        self.sm3InLayout.addWidget(self.sm3InCheck)
        self.sm3InLed = TaurusLed(self.layoutWidget_20)
        self.sm3InLed.setMinimumSize(QtCore.QSize(15, 15))
        self.sm3InLed.setMaximumSize(QtCore.QSize(15, 15))
        self.sm3InLed.setObjectName(_fromUtf8("sm3InLed"))
        self.sm3InLayout.addWidget(self.sm3InLed)
        self.layoutWidget_21 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget_21.setGeometry(QtCore.QRect(1140, 790, 67, 23))
        self.layoutWidget_21.setObjectName(_fromUtf8("layoutWidget_21"))
        self.sm3OnLayout = QtGui.QHBoxLayout(self.layoutWidget_21)
        self.sm3OnLayout.setMargin(0)
        self.sm3OnLayout.setObjectName(_fromUtf8("sm3OnLayout"))
        self.sm3OnLabel = QtGui.QLabel(self.layoutWidget_21)
        self.sm3OnLabel.setObjectName(_fromUtf8("sm3OnLabel"))
        self.sm3OnLayout.addWidget(self.sm3OnLabel)
        self.sm3OnCheck = TaurusValueCheckBox(self.layoutWidget_21)
        self.sm3OnCheck.setShowText(False)
        self.sm3OnCheck.setAutoApply(True)
        self.sm3OnCheck.setForcedApply(False)
        self.sm3OnCheck.setObjectName(_fromUtf8("sm3OnCheck"))
        self.sm3OnLayout.addWidget(self.sm3OnCheck)
        self.sm3OnLed = TaurusLed(self.layoutWidget_21)
        self.sm3OnLed.setMinimumSize(QtCore.QSize(15, 15))
        self.sm3OnLed.setMaximumSize(QtCore.QSize(15, 15))
        self.sm3OnLed.setObjectName(_fromUtf8("sm3OnLed"))
        self.sm3OnLayout.addWidget(self.sm3OnLed)
        self.layoutWidget = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 100, 59, 23))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.multiBunchLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.multiBunchLayout.setMargin(0)
        self.multiBunchLayout.setObjectName(_fromUtf8("multiBunchLayout"))
        self.multibunchLabel = QtGui.QLabel(self.layoutWidget)
        self.multibunchLabel.setObjectName(_fromUtf8("multibunchLabel"))
        self.multiBunchLayout.addWidget(self.multibunchLabel)
        self.multiBunchValue = TaurusValueCheckBox(self.layoutWidget)
        self.multiBunchValue.setShowText(False)
        self.multiBunchValue.setObjectName(_fromUtf8("multiBunchValue"))
        self.multiBunchLayout.addWidget(self.multiBunchValue)
        self.layoutWidget1 = QtGui.QWidget(linacMainscreenSynoptic)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 630, 81, 51))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.hvsLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.hvsLayout.setMargin(0)
        self.hvsLayout.setObjectName(_fromUtf8("hvsLayout"))
        self.hvsVoltageValue = TaurusValueSpinBox(self.layoutWidget1)
        self.hvsVoltageValue.setObjectName(_fromUtf8("hvsVoltageValue"))
        self.hvsLayout.addWidget(self.hvsVoltageValue)
        self.hvsCurrentValue = TaurusLabel(self.layoutWidget1)
        self.hvsCurrentValue.setObjectName(_fromUtf8("hvsCurrentValue"))
        self.hvsLayout.addWidget(self.hvsCurrentValue)
        self.widget = QtGui.QWidget(linacMainscreenSynoptic)
        self.widget.setGeometry(QtCore.QRect(756, 170, 85, 48))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.k1Layout = QtGui.QGridLayout(self.widget)
        self.k1Layout.setMargin(0)
        self.k1Layout.setObjectName(_fromUtf8("k1Layout"))
        self.k1onLabel = QtGui.QLabel(self.widget)
        self.k1onLabel.setObjectName(_fromUtf8("k1onLabel"))
        self.k1Layout.addWidget(self.k1onLabel, 0, 0, 1, 1)
        self.k1onCheck = TaurusValueCheckBox(self.widget)
        self.k1onCheck.setShowText(False)
        self.k1onCheck.setAutoApply(True)
        self.k1onCheck.setForcedApply(False)
        self.k1onCheck.setObjectName(_fromUtf8("k1onCheck"))
        self.k1Layout.addWidget(self.k1onCheck, 0, 1, 1, 1)
        self.k1onLed = TaurusLed(self.widget)
        self.k1onLed.setMinimumSize(QtCore.QSize(15, 15))
        self.k1onLed.setMaximumSize(QtCore.QSize(15, 15))
        self.k1onLed.setObjectName(_fromUtf8("k1onLed"))
        self.k1Layout.addWidget(self.k1onLed, 0, 2, 1, 1)
        self.k1rstLabel = QtGui.QLabel(self.widget)
        self.k1rstLabel.setObjectName(_fromUtf8("k1rstLabel"))
        self.k1Layout.addWidget(self.k1rstLabel, 1, 0, 1, 1)
        self.k1rstCheck = TaurusValueCheckBox(self.widget)
        self.k1rstCheck.setShowText(False)
        self.k1rstCheck.setAutoApply(True)
        self.k1rstCheck.setForcedApply(False)
        self.k1rstCheck.setObjectName(_fromUtf8("k1rstCheck"))
        self.k1Layout.addWidget(self.k1rstCheck, 1, 1, 1, 1)
        self.k1rstLed = TaurusLed(self.widget)
        self.k1rstLed.setMinimumSize(QtCore.QSize(15, 15))
        self.k1rstLed.setMaximumSize(QtCore.QSize(15, 15))
        self.k1rstLed.setObjectName(_fromUtf8("k1rstLed"))
        self.k1Layout.addWidget(self.k1rstLed, 1, 2, 1, 1)
        self.widget1 = QtGui.QWidget(linacMainscreenSynoptic)
        self.widget1.setGeometry(QtCore.QRect(1041, 132, 85, 48))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.k2Layout = QtGui.QGridLayout(self.widget1)
        self.k2Layout.setMargin(0)
        self.k2Layout.setObjectName(_fromUtf8("k2Layout"))
        self.k2onLabel = QtGui.QLabel(self.widget1)
        self.k2onLabel.setObjectName(_fromUtf8("k2onLabel"))
        self.k2Layout.addWidget(self.k2onLabel, 0, 0, 1, 1)
        self.k2onCheck = TaurusValueCheckBox(self.widget1)
        self.k2onCheck.setShowText(False)
        self.k2onCheck.setAutoApply(True)
        self.k2onCheck.setForcedApply(False)
        self.k2onCheck.setObjectName(_fromUtf8("k2onCheck"))
        self.k2Layout.addWidget(self.k2onCheck, 0, 1, 1, 1)
        self.k2onLed = TaurusLed(self.widget1)
        self.k2onLed.setMinimumSize(QtCore.QSize(15, 15))
        self.k2onLed.setMaximumSize(QtCore.QSize(15, 15))
        self.k2onLed.setObjectName(_fromUtf8("k2onLed"))
        self.k2Layout.addWidget(self.k2onLed, 0, 2, 1, 1)
        self.k2rstLabel = QtGui.QLabel(self.widget1)
        self.k2rstLabel.setObjectName(_fromUtf8("k2rstLabel"))
        self.k2Layout.addWidget(self.k2rstLabel, 1, 0, 1, 1)
        self.k2rstCheck = TaurusValueCheckBox(self.widget1)
        self.k2rstCheck.setShowText(False)
        self.k2rstCheck.setAutoApply(True)
        self.k2rstCheck.setForcedApply(False)
        self.k2rstCheck.setObjectName(_fromUtf8("k2rstCheck"))
        self.k2Layout.addWidget(self.k2rstCheck, 1, 1, 1, 1)
        self.k2rstLed = TaurusLed(self.widget1)
        self.k2rstLed.setMinimumSize(QtCore.QSize(15, 15))
        self.k2rstLed.setMaximumSize(QtCore.QSize(15, 15))
        self.k2rstLed.setObjectName(_fromUtf8("k2rstLed"))
        self.k2Layout.addWidget(self.k2rstLed, 1, 2, 1, 1)
        self.widget2 = QtGui.QWidget(linacMainscreenSynoptic)
        self.widget2.setGeometry(QtCore.QRect(140, 780, 46, 41))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.magnetOnLayout = QtGui.QGridLayout(self.widget2)
        self.magnetOnLayout.setMargin(0)
        self.magnetOnLayout.setObjectName(_fromUtf8("magnetOnLayout"))
        self.magnetsOnCheck = TaurusValueCheckBox(self.widget2)
        self.magnetsOnCheck.setShowText(False)
        self.magnetsOnCheck.setAutoApply(True)
        self.magnetsOnCheck.setForcedApply(False)
        self.magnetsOnCheck.setObjectName(_fromUtf8("magnetsOnCheck"))
        self.magnetOnLayout.addWidget(self.magnetsOnCheck, 0, 0, 1, 1)
        self.magnetsOnLed = TaurusLed(self.widget2)
        self.magnetsOnLed.setMinimumSize(QtCore.QSize(15, 15))
        self.magnetsOnLed.setMaximumSize(QtCore.QSize(15, 15))
        self.magnetsOnLed.setObjectName(_fromUtf8("magnetsOnLed"))
        self.magnetOnLayout.addWidget(self.magnetsOnLed, 0, 1, 1, 1)
        self.magnetsOnLabel = QtGui.QLabel(self.widget2)
        self.magnetsOnLabel.setObjectName(_fromUtf8("magnetsOnLabel"))
        self.magnetOnLayout.addWidget(self.magnetsOnLabel, 1, 0, 1, 1)
        self.widget3 = QtGui.QWidget(linacMainscreenSynoptic)
        self.widget3.setGeometry(QtCore.QRect(30, 781, 66, 23))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget3)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.magnetsRstLabel = QtGui.QLabel(self.widget3)
        self.magnetsRstLabel.setObjectName(_fromUtf8("magnetsRstLabel"))
        self.horizontalLayout.addWidget(self.magnetsRstLabel)
        self.magnetsRstCheck = TaurusValueCheckBox(self.widget3)
        self.magnetsRstCheck.setShowText(False)
        self.magnetsRstCheck.setAutoApply(True)
        self.magnetsRstCheck.setForcedApply(False)
        self.magnetsRstCheck.setObjectName(_fromUtf8("magnetsRstCheck"))
        self.horizontalLayout.addWidget(self.magnetsRstCheck)

        self.retranslateUi(linacMainscreenSynoptic)
        QtCore.QMetaObject.connectSlotsByName(linacMainscreenSynoptic)

    def retranslateUi(self, linacMainscreenSynoptic):
        linacMainscreenSynoptic.setWindowTitle(QtGui.QApplication.translate("linacMainscreenSynoptic", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.MainScreenSchematic.setModel(QtGui.QApplication.translate("linacMainscreenSynoptic", "jdraw/linac_mainscreen_synoptic.jdw", None, QtGui.QApplication.UnicodeUTF8))
        self.filamentVLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Filament V", None, QtGui.QApplication.UnicodeUTF8))
        self.cathodeLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Cathode V", None, QtGui.QApplication.UnicodeUTF8))
        self.filamentCurrent.setSuffixText(QtGui.QApplication.translate("linacMainscreenSynoptic", " A", None, QtGui.QApplication.UnicodeUTF8))
        self.temperatureValue.setSuffixText(QtGui.QApplication.translate("linacMainscreenSynoptic", " C", None, QtGui.QApplication.UnicodeUTF8))
        self.filamentILabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Filament I", None, QtGui.QApplication.UnicodeUTF8))
        self.temperatureLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.hvsOnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.vv1_oncLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.sl1OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.sl2OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.sl3OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.sl4OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.glOnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.as1OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.qt1OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.as2OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.sm1OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.sm1InLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "In", None, QtGui.QApplication.UnicodeUTF8))
        self.sm2InLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "In", None, QtGui.QApplication.UnicodeUTF8))
        self.sm2OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.sm3InLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "In", None, QtGui.QApplication.UnicodeUTF8))
        self.sm3OnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.multibunchLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "MBM", None, QtGui.QApplication.UnicodeUTF8))
        self.k1onLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.k1rstLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.k2onLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.k2rstLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.magnetsOnLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.magnetsRstLabel.setText(QtGui.QApplication.translate("linacMainscreenSynoptic", "Reset", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusLed, TaurusLabel
from taurus.qt.qtgui.container import TaurusWidget
from taurus.qt.qtgui.graphic.jdraw import TaurusJDrawSynopticsView
from taurus.qt.qtgui.input import TaurusValueComboBox, TaurusValueCheckBox, TaurusValueSpinBox
