# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'linacStartupSynoptic.ui'
#
# Created: Thu Feb  6 08:51:57 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_linacStartupSynoptic(object):
    def setupUi(self, linacStartupSynoptic):
        linacStartupSynoptic.setObjectName(_fromUtf8("linacStartupSynoptic"))
        linacStartupSynoptic.resize(1250, 825)
        linacStartupSynoptic.setMinimumSize(QtCore.QSize(1250, 825))
        linacStartupSynoptic.setMaximumSize(QtCore.QSize(1250, 825))
        self.sl1Led = TaurusLed(linacStartupSynoptic)
        self.sl1Led.setGeometry(QtCore.QRect(158, 475, 10, 10))
        self.sl1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sl1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sl1Led.setObjectName(_fromUtf8("sl1Led"))
        self.vacuumValve1OnLed = TaurusLed(linacStartupSynoptic)
        self.vacuumValve1OnLed.setGeometry(QtCore.QRect(194, 515, 10, 10))
        self.vacuumValve1OnLed.setMinimumSize(QtCore.QSize(10, 10))
        self.vacuumValve1OnLed.setMaximumSize(QtCore.QSize(10, 10))
        self.vacuumValve1OnLed.setObjectName(_fromUtf8("vacuumValve1OnLed"))
        self.sl2Led = TaurusLed(linacStartupSynoptic)
        self.sl2Led.setGeometry(QtCore.QRect(242, 475, 10, 10))
        self.sl2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sl2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sl2Led.setObjectName(_fromUtf8("sl2Led"))
        self.sl3Led = TaurusLed(linacStartupSynoptic)
        self.sl3Led.setGeometry(QtCore.QRect(326, 475, 10, 10))
        self.sl3Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sl3Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sl3Led.setObjectName(_fromUtf8("sl3Led"))
        self.sl4Led = TaurusLed(linacStartupSynoptic)
        self.sl4Led.setGeometry(QtCore.QRect(398, 475, 10, 10))
        self.sl4Led.setMinimumSize(QtCore.QSize(10, 10))
        self.sl4Led.setMaximumSize(QtCore.QSize(10, 10))
        self.sl4Led.setObjectName(_fromUtf8("sl4Led"))
        self.bc1Led = TaurusLed(linacStartupSynoptic)
        self.bc1Led.setGeometry(QtCore.QRect(460, 475, 10, 10))
        self.bc1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.bc1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.bc1Led.setObjectName(_fromUtf8("bc1Led"))
        self.bc2Led = TaurusLed(linacStartupSynoptic)
        self.bc2Led.setGeometry(QtCore.QRect(505, 475, 10, 10))
        self.bc2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.bc2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.bc2Led.setObjectName(_fromUtf8("bc2Led"))
        self.coolingLoop1TemperatureValue = TaurusValueSpinBox(linacStartupSynoptic)
        self.coolingLoop1TemperatureValue.setGeometry(QtCore.QRect(454, 390, 70, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.coolingLoop1TemperatureValue.setFont(font)
        self.coolingLoop1TemperatureValue.setObjectName(_fromUtf8("coolingLoop1TemperatureValue"))
        self.vacuumValve2OnLed = TaurusLed(linacStartupSynoptic)
        self.vacuumValve2OnLed.setGeometry(QtCore.QRect(555, 515, 10, 10))
        self.vacuumValve2OnLed.setMinimumSize(QtCore.QSize(10, 10))
        self.vacuumValve2OnLed.setMaximumSize(QtCore.QSize(10, 10))
        self.vacuumValve2OnLed.setObjectName(_fromUtf8("vacuumValve2OnLed"))
        self.glLed = TaurusLed(linacStartupSynoptic)
        self.glLed.setGeometry(QtCore.QRect(640, 475, 10, 10))
        self.glLed.setMinimumSize(QtCore.QSize(10, 10))
        self.glLed.setMaximumSize(QtCore.QSize(10, 10))
        self.glLed.setObjectName(_fromUtf8("glLed"))
        self.vacuumValve3OnLed = TaurusLed(linacStartupSynoptic)
        self.vacuumValve3OnLed.setGeometry(QtCore.QRect(675, 515, 10, 10))
        self.vacuumValve3OnLed.setMinimumSize(QtCore.QSize(10, 10))
        self.vacuumValve3OnLed.setMaximumSize(QtCore.QSize(10, 10))
        self.vacuumValve3OnLed.setObjectName(_fromUtf8("vacuumValve3OnLed"))
        self.coolingLoop2TemperatureValue = TaurusValueSpinBox(linacStartupSynoptic)
        self.coolingLoop2TemperatureValue.setGeometry(QtCore.QRect(665, 390, 70, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.coolingLoop2TemperatureValue.setFont(font)
        self.coolingLoop2TemperatureValue.setObjectName(_fromUtf8("coolingLoop2TemperatureValue"))
        self.vacuumValve4OnLed = TaurusLed(linacStartupSynoptic)
        self.vacuumValve4OnLed.setGeometry(QtCore.QRect(808, 515, 10, 10))
        self.vacuumValve4OnLed.setMinimumSize(QtCore.QSize(10, 10))
        self.vacuumValve4OnLed.setMaximumSize(QtCore.QSize(10, 10))
        self.vacuumValve4OnLed.setObjectName(_fromUtf8("vacuumValve4OnLed"))
        self.vacuumValve5OnLed = TaurusLed(linacStartupSynoptic)
        self.vacuumValve5OnLed.setGeometry(QtCore.QRect(963, 515, 10, 10))
        self.vacuumValve5OnLed.setMinimumSize(QtCore.QSize(10, 10))
        self.vacuumValve5OnLed.setMaximumSize(QtCore.QSize(10, 10))
        self.vacuumValve5OnLed.setObjectName(_fromUtf8("vacuumValve5OnLed"))
        self.coolingLoop3TemperatureValue = TaurusValueSpinBox(linacStartupSynoptic)
        self.coolingLoop3TemperatureValue.setGeometry(QtCore.QRect(945, 390, 70, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.coolingLoop3TemperatureValue.setFont(font)
        self.coolingLoop3TemperatureValue.setObjectName(_fromUtf8("coolingLoop3TemperatureValue"))
        self.vacuumValve6OnLed = TaurusLed(linacStartupSynoptic)
        self.vacuumValve6OnLed.setGeometry(QtCore.QRect(1096, 515, 10, 10))
        self.vacuumValve6OnLed.setMinimumSize(QtCore.QSize(10, 10))
        self.vacuumValve6OnLed.setMaximumSize(QtCore.QSize(10, 10))
        self.vacuumValve6OnLed.setObjectName(_fromUtf8("vacuumValve6OnLed"))
        self.vacuumValve7OnLed = TaurusLed(linacStartupSynoptic)
        self.vacuumValve7OnLed.setGeometry(QtCore.QRect(1216, 515, 10, 10))
        self.vacuumValve7OnLed.setMinimumSize(QtCore.QSize(10, 10))
        self.vacuumValve7OnLed.setMaximumSize(QtCore.QSize(10, 10))
        self.vacuumValve7OnLed.setObjectName(_fromUtf8("vacuumValve7OnLed"))
        self.ip1Led = TaurusLed(linacStartupSynoptic)
        self.ip1Led.setGeometry(QtCore.QRect(24, 645, 10, 10))
        self.ip1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip1Led.setObjectName(_fromUtf8("ip1Led"))
        self.ip2Led = TaurusLed(linacStartupSynoptic)
        self.ip2Led.setGeometry(QtCore.QRect(78, 646, 10, 10))
        self.ip2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip2Led.setObjectName(_fromUtf8("ip2Led"))
        self.ip3Led = TaurusLed(linacStartupSynoptic)
        self.ip3Led.setGeometry(QtCore.QRect(304, 634, 10, 10))
        self.ip3Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip3Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip3Led.setObjectName(_fromUtf8("ip3Led"))
        self.ip4Led = TaurusLed(linacStartupSynoptic)
        self.ip4Led.setGeometry(QtCore.QRect(457, 634, 10, 10))
        self.ip4Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip4Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip4Led.setObjectName(_fromUtf8("ip4Led"))
        self.ip5Led = TaurusLed(linacStartupSynoptic)
        self.ip5Led.setGeometry(QtCore.QRect(611, 645, 10, 10))
        self.ip5Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip5Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip5Led.setObjectName(_fromUtf8("ip5Led"))
        self.ip6Led = TaurusLed(linacStartupSynoptic)
        self.ip6Led.setGeometry(QtCore.QRect(714, 645, 10, 10))
        self.ip6Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip6Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip6Led.setObjectName(_fromUtf8("ip6Led"))
        self.ip7Led = TaurusLed(linacStartupSynoptic)
        self.ip7Led.setGeometry(QtCore.QRect(863, 645, 10, 10))
        self.ip7Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip7Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip7Led.setObjectName(_fromUtf8("ip7Led"))
        self.ip8Led = TaurusLed(linacStartupSynoptic)
        self.ip8Led.setGeometry(QtCore.QRect(1005, 645, 10, 10))
        self.ip8Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip8Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip8Led.setObjectName(_fromUtf8("ip8Led"))
        self.ip9Led = TaurusLed(linacStartupSynoptic)
        self.ip9Led.setGeometry(QtCore.QRect(1140, 645, 10, 10))
        self.ip9Led.setMinimumSize(QtCore.QSize(10, 10))
        self.ip9Led.setMaximumSize(QtCore.QSize(10, 10))
        self.ip9Led.setObjectName(_fromUtf8("ip9Led"))
        self.hvg1Led = TaurusLed(linacStartupSynoptic)
        self.hvg1Led.setGeometry(QtCore.QRect(144, 692, 10, 10))
        self.hvg1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.hvg1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.hvg1Led.setObjectName(_fromUtf8("hvg1Led"))
        self.hvg2Led = TaurusLed(linacStartupSynoptic)
        self.hvg2Led.setGeometry(QtCore.QRect(300, 691, 10, 10))
        self.hvg2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.hvg2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.hvg2Led.setObjectName(_fromUtf8("hvg2Led"))
        self.hvg3Led = TaurusLed(linacStartupSynoptic)
        self.hvg3Led.setGeometry(QtCore.QRect(505, 690, 10, 10))
        self.hvg3Led.setMinimumSize(QtCore.QSize(10, 10))
        self.hvg3Led.setMaximumSize(QtCore.QSize(10, 10))
        self.hvg3Led.setObjectName(_fromUtf8("hvg3Led"))
        self.hvg4Led = TaurusLed(linacStartupSynoptic)
        self.hvg4Led.setGeometry(QtCore.QRect(793, 690, 10, 10))
        self.hvg4Led.setMinimumSize(QtCore.QSize(10, 10))
        self.hvg4Led.setMaximumSize(QtCore.QSize(10, 10))
        self.hvg4Led.setObjectName(_fromUtf8("hvg4Led"))
        self.hvg5Led = TaurusLed(linacStartupSynoptic)
        self.hvg5Led.setGeometry(QtCore.QRect(1075, 690, 10, 10))
        self.hvg5Led.setMinimumSize(QtCore.QSize(10, 10))
        self.hvg5Led.setMaximumSize(QtCore.QSize(10, 10))
        self.hvg5Led.setObjectName(_fromUtf8("hvg5Led"))
        self.ipc1Value1 = TaurusLabel(linacStartupSynoptic)
        self.ipc1Value1.setGeometry(QtCore.QRect(20, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc1Value1.setFont(font)
        self.ipc1Value1.setObjectName(_fromUtf8("ipc1Value1"))
        self.ipc1Value2 = TaurusLabel(linacStartupSynoptic)
        self.ipc1Value2.setGeometry(QtCore.QRect(20, 740, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc1Value2.setFont(font)
        self.ipc1Value2.setObjectName(_fromUtf8("ipc1Value2"))
        self.hvg1Value = TaurusLabel(linacStartupSynoptic)
        self.hvg1Value.setGeometry(QtCore.QRect(100, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.hvg1Value.setFont(font)
        self.hvg1Value.setObjectName(_fromUtf8("hvg1Value"))
        self.hvg2Value = TaurusLabel(linacStartupSynoptic)
        self.hvg2Value.setGeometry(QtCore.QRect(240, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.hvg2Value.setFont(font)
        self.hvg2Value.setObjectName(_fromUtf8("hvg2Value"))
        self.ipc2Value1 = TaurusLabel(linacStartupSynoptic)
        self.ipc2Value1.setGeometry(QtCore.QRect(350, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc2Value1.setFont(font)
        self.ipc2Value1.setObjectName(_fromUtf8("ipc2Value1"))
        self.ipc2Value2 = TaurusLabel(linacStartupSynoptic)
        self.ipc2Value2.setGeometry(QtCore.QRect(350, 740, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc2Value2.setFont(font)
        self.ipc2Value2.setObjectName(_fromUtf8("ipc2Value2"))
        self.hvg3Value = TaurusLabel(linacStartupSynoptic)
        self.hvg3Value.setGeometry(QtCore.QRect(450, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.hvg3Value.setFont(font)
        self.hvg3Value.setObjectName(_fromUtf8("hvg3Value"))
        self.ipc3Value1 = TaurusLabel(linacStartupSynoptic)
        self.ipc3Value1.setGeometry(QtCore.QRect(590, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc3Value1.setFont(font)
        self.ipc3Value1.setObjectName(_fromUtf8("ipc3Value1"))
        self.ipc3Value2 = TaurusLabel(linacStartupSynoptic)
        self.ipc3Value2.setGeometry(QtCore.QRect(590, 740, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc3Value2.setFont(font)
        self.ipc3Value2.setObjectName(_fromUtf8("ipc3Value2"))
        self.hvg4Value = TaurusLabel(linacStartupSynoptic)
        self.hvg4Value.setGeometry(QtCore.QRect(730, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.hvg4Value.setFont(font)
        self.hvg4Value.setObjectName(_fromUtf8("hvg4Value"))
        self.ipc4Value1 = TaurusLabel(linacStartupSynoptic)
        self.ipc4Value1.setGeometry(QtCore.QRect(840, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc4Value1.setFont(font)
        self.ipc4Value1.setObjectName(_fromUtf8("ipc4Value1"))
        self.ipc4Value2 = TaurusLabel(linacStartupSynoptic)
        self.ipc4Value2.setGeometry(QtCore.QRect(840, 740, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc4Value2.setFont(font)
        self.ipc4Value2.setObjectName(_fromUtf8("ipc4Value2"))
        self.hvg5Value = TaurusLabel(linacStartupSynoptic)
        self.hvg5Value.setGeometry(QtCore.QRect(1020, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.hvg5Value.setFont(font)
        self.hvg5Value.setObjectName(_fromUtf8("hvg5Value"))
        self.ipc5Value1 = TaurusLabel(linacStartupSynoptic)
        self.ipc5Value1.setGeometry(QtCore.QRect(1110, 720, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ipc5Value1.setFont(font)
        self.ipc5Value1.setObjectName(_fromUtf8("ipc5Value1"))
        self.klystron2LVWidget = klystronLV(linacStartupSynoptic)
        self.klystron2LVWidget.setGeometry(QtCore.QRect(1060, 10, 150, 200))
        self.klystron2LVWidget.setAutoFillBackground(True)
        self.klystron2LVWidget.setObjectName(_fromUtf8("klystron2LVWidget"))
        self.klystron1LVWidget = klystronLV(linacStartupSynoptic)
        self.klystron1LVWidget.setGeometry(QtCore.QRect(780, 10, 150, 200))
        self.klystron1LVWidget.setObjectName(_fromUtf8("klystron1LVWidget"))
        self.klystron1LVPopupCheck = QtGui.QCheckBox(linacStartupSynoptic)
        self.klystron1LVPopupCheck.setGeometry(QtCore.QRect(753, 83, 21, 21))
        self.klystron1LVPopupCheck.setText(_fromUtf8(""))
        self.klystron1LVPopupCheck.setObjectName(_fromUtf8("klystron1LVPopupCheck"))
        self.klystron2LVPopupCheck = QtGui.QCheckBox(linacStartupSynoptic)
        self.klystron2LVPopupCheck.setGeometry(QtCore.QRect(1041, 12, 21, 21))
        self.klystron2LVPopupCheck.setText(_fromUtf8(""))
        self.klystron2LVPopupCheck.setObjectName(_fromUtf8("klystron2LVPopupCheck"))
        self.coolingLoop1PopupCheck = QtGui.QCheckBox(linacStartupSynoptic)
        self.coolingLoop1PopupCheck.setGeometry(QtCore.QRect(510, 345, 21, 21))
        self.coolingLoop1PopupCheck.setText(_fromUtf8(""))
        self.coolingLoop1PopupCheck.setObjectName(_fromUtf8("coolingLoop1PopupCheck"))
        self.coolingLoop2PopupCheck = QtGui.QCheckBox(linacStartupSynoptic)
        self.coolingLoop2PopupCheck.setGeometry(QtCore.QRect(725, 345, 21, 21))
        self.coolingLoop2PopupCheck.setText(_fromUtf8(""))
        self.coolingLoop2PopupCheck.setObjectName(_fromUtf8("coolingLoop2PopupCheck"))
        self.coolingLoop3PopupCheck = QtGui.QCheckBox(linacStartupSynoptic)
        self.coolingLoop3PopupCheck.setGeometry(QtCore.QRect(1010, 345, 21, 21))
        self.coolingLoop3PopupCheck.setText(_fromUtf8(""))
        self.coolingLoop3PopupCheck.setObjectName(_fromUtf8("coolingLoop3PopupCheck"))
        self.vacuumValve1OnStatus = TaurusLabel(linacStartupSynoptic)
        self.vacuumValve1OnStatus.setGeometry(QtCore.QRect(165, 605, 70, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve1OnStatus.setFont(font)
        self.vacuumValve1OnStatus.setObjectName(_fromUtf8("vacuumValve1OnStatus"))
        self.vacuumValve2OnStatus = TaurusLabel(linacStartupSynoptic)
        self.vacuumValve2OnStatus.setGeometry(QtCore.QRect(524, 605, 70, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve2OnStatus.setFont(font)
        self.vacuumValve2OnStatus.setObjectName(_fromUtf8("vacuumValve2OnStatus"))
        self.vacuumValve3OnStatus = TaurusLabel(linacStartupSynoptic)
        self.vacuumValve3OnStatus.setGeometry(QtCore.QRect(643, 605, 70, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve3OnStatus.setFont(font)
        self.vacuumValve3OnStatus.setObjectName(_fromUtf8("vacuumValve3OnStatus"))
        self.vacuumValve4OnStatus = TaurusLabel(linacStartupSynoptic)
        self.vacuumValve4OnStatus.setGeometry(QtCore.QRect(776, 605, 70, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve4OnStatus.setFont(font)
        self.vacuumValve4OnStatus.setObjectName(_fromUtf8("vacuumValve4OnStatus"))
        self.vacuumValve5OnStatus = TaurusLabel(linacStartupSynoptic)
        self.vacuumValve5OnStatus.setGeometry(QtCore.QRect(931, 605, 70, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve5OnStatus.setFont(font)
        self.vacuumValve5OnStatus.setObjectName(_fromUtf8("vacuumValve5OnStatus"))
        self.vacuumValve6OnStatus = TaurusLabel(linacStartupSynoptic)
        self.vacuumValve6OnStatus.setGeometry(QtCore.QRect(1065, 605, 70, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve6OnStatus.setFont(font)
        self.vacuumValve6OnStatus.setObjectName(_fromUtf8("vacuumValve6OnStatus"))
        self.vacuumValve7OnStatus = TaurusLabel(linacStartupSynoptic)
        self.vacuumValve7OnStatus.setGeometry(QtCore.QRect(1168, 604, 70, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve7OnStatus.setFont(font)
        self.vacuumValve7OnStatus.setObjectName(_fromUtf8("vacuumValve7OnStatus"))
        self.layoutWidget = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget.setGeometry(QtCore.QRect(900, 272, 71, 31))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.coolingLoop3OnLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.coolingLoop3OnLayout.setContentsMargins(0, -1, -1, -1)
        self.coolingLoop3OnLayout.setObjectName(_fromUtf8("coolingLoop3OnLayout"))
        self.coolingLoop3OnLabel = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.coolingLoop3OnLabel.setFont(font)
        self.coolingLoop3OnLabel.setObjectName(_fromUtf8("coolingLoop3OnLabel"))
        self.coolingLoop3OnLayout.addWidget(self.coolingLoop3OnLabel)
        self.coolingLoop3OnCheck = TaurusValueCheckBox(self.layoutWidget)
        self.coolingLoop3OnCheck.setShowText(False)
        self.coolingLoop3OnCheck.setObjectName(_fromUtf8("coolingLoop3OnCheck"))
        self.coolingLoop3OnLayout.addWidget(self.coolingLoop3OnCheck)
        self.coolingLoop3OnLed = TaurusLed(self.layoutWidget)
        self.coolingLoop3OnLed.setMinimumSize(QtCore.QSize(15, 15))
        self.coolingLoop3OnLed.setMaximumSize(QtCore.QSize(15, 15))
        self.coolingLoop3OnLed.setObjectName(_fromUtf8("coolingLoop3OnLed"))
        self.coolingLoop3OnLayout.addWidget(self.coolingLoop3OnLed)
        self.layoutWidget1 = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget1.setGeometry(QtCore.QRect(610, 272, 71, 31))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.coolingLoop2OnLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.coolingLoop2OnLayout.setContentsMargins(0, -1, -1, -1)
        self.coolingLoop2OnLayout.setObjectName(_fromUtf8("coolingLoop2OnLayout"))
        self.coolingLoop2OnLabel = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.coolingLoop2OnLabel.setFont(font)
        self.coolingLoop2OnLabel.setObjectName(_fromUtf8("coolingLoop2OnLabel"))
        self.coolingLoop2OnLayout.addWidget(self.coolingLoop2OnLabel)
        self.coolingLoop2OnCheck = TaurusValueCheckBox(self.layoutWidget1)
        self.coolingLoop2OnCheck.setShowText(False)
        self.coolingLoop2OnCheck.setObjectName(_fromUtf8("coolingLoop2OnCheck"))
        self.coolingLoop2OnLayout.addWidget(self.coolingLoop2OnCheck)
        self.coolingLoop2OnLed = TaurusLed(self.layoutWidget1)
        self.coolingLoop2OnLed.setMinimumSize(QtCore.QSize(15, 15))
        self.coolingLoop2OnLed.setMaximumSize(QtCore.QSize(15, 15))
        self.coolingLoop2OnLed.setObjectName(_fromUtf8("coolingLoop2OnLed"))
        self.coolingLoop2OnLayout.addWidget(self.coolingLoop2OnLed)
        self.layoutWidget2 = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget2.setGeometry(QtCore.QRect(390, 272, 71, 31))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.coolingLoop1OnLayout = QtGui.QHBoxLayout(self.layoutWidget2)
        self.coolingLoop1OnLayout.setContentsMargins(0, -1, -1, -1)
        self.coolingLoop1OnLayout.setObjectName(_fromUtf8("coolingLoop1OnLayout"))
        self.coolingLoop1OnLabel = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.coolingLoop1OnLabel.setFont(font)
        self.coolingLoop1OnLabel.setObjectName(_fromUtf8("coolingLoop1OnLabel"))
        self.coolingLoop1OnLayout.addWidget(self.coolingLoop1OnLabel)
        self.coolingLoop1OnCheck = TaurusValueCheckBox(self.layoutWidget2)
        self.coolingLoop1OnCheck.setShowText(False)
        self.coolingLoop1OnCheck.setObjectName(_fromUtf8("coolingLoop1OnCheck"))
        self.coolingLoop1OnLayout.addWidget(self.coolingLoop1OnCheck)
        self.coolingLoop1OnLed = TaurusLed(self.layoutWidget2)
        self.coolingLoop1OnLed.setMinimumSize(QtCore.QSize(15, 15))
        self.coolingLoop1OnLed.setMaximumSize(QtCore.QSize(15, 15))
        self.coolingLoop1OnLed.setObjectName(_fromUtf8("coolingLoop1OnLed"))
        self.coolingLoop1OnLayout.addWidget(self.coolingLoop1OnLed)
        self.layoutWidget3 = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 540, 81, 31))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.vvrstLayout = QtGui.QHBoxLayout(self.layoutWidget3)
        self.vvrstLayout.setContentsMargins(7, -1, -1, -1)
        self.vvrstLayout.setObjectName(_fromUtf8("vvrstLayout"))
        self.vv_rstCheck = TaurusValueCheckBox(self.layoutWidget3)
        self.vv_rstCheck.setShowText(False)
        self.vv_rstCheck.setObjectName(_fromUtf8("vv_rstCheck"))
        self.vvrstLayout.addWidget(self.vv_rstCheck)
        self.vv_rstLabel = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vv_rstLabel.setFont(font)
        self.vv_rstLabel.setObjectName(_fromUtf8("vv_rstLabel"))
        self.vvrstLayout.addWidget(self.vv_rstLabel)
        self.layoutWidget4 = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget4.setGeometry(QtCore.QRect(80, 770, 71, 23))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.vvLayout = QtGui.QHBoxLayout(self.layoutWidget4)
        self.vvLayout.setContentsMargins(-1, 0, -1, -1)
        self.vvLayout.setObjectName(_fromUtf8("vvLayout"))
        self.vv_oncLabel = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vv_oncLabel.setFont(font)
        self.vv_oncLabel.setObjectName(_fromUtf8("vv_oncLabel"))
        self.vvLayout.addWidget(self.vv_oncLabel)
        self.vv_oncCheck = TaurusValueCheckBox(self.layoutWidget4)
        self.vv_oncCheck.setShowText(False)
        self.vv_oncCheck.setObjectName(_fromUtf8("vv_oncCheck"))
        self.vvLayout.addWidget(self.vv_oncCheck)
        self.coolingLoop1Widget = CoolingLoop(linacStartupSynoptic)
        self.coolingLoop1Widget.setGeometry(QtCore.QRect(535, 310, 130, 140))
        self.coolingLoop1Widget.setObjectName(_fromUtf8("coolingLoop1Widget"))
        self.coolingLoop2Widget = CoolingLoop(linacStartupSynoptic)
        self.coolingLoop2Widget.setGeometry(QtCore.QRect(745, 310, 130, 140))
        self.coolingLoop2Widget.setObjectName(_fromUtf8("coolingLoop2Widget"))
        self.coolingLoop3Widget = CoolingLoop(linacStartupSynoptic)
        self.coolingLoop3Widget.setGeometry(QtCore.QRect(1030, 310, 130, 140))
        self.coolingLoop3Widget.setObjectName(_fromUtf8("coolingLoop3Widget"))
        self.qtLed = TaurusLed(linacStartupSynoptic)
        self.qtLed.setGeometry(QtCore.QRect(915, 475, 10, 10))
        self.qtLed.setMinimumSize(QtCore.QSize(10, 10))
        self.qtLed.setMaximumSize(QtCore.QSize(10, 10))
        self.qtLed.setObjectName(_fromUtf8("qtLed"))
        self.as1Led = TaurusLed(linacStartupSynoptic)
        self.as1Led.setGeometry(QtCore.QRect(743, 497, 10, 10))
        self.as1Led.setMinimumSize(QtCore.QSize(10, 10))
        self.as1Led.setMaximumSize(QtCore.QSize(10, 10))
        self.as1Led.setObjectName(_fromUtf8("as1Led"))
        self.as2Led = TaurusLed(linacStartupSynoptic)
        self.as2Led.setGeometry(QtCore.QRect(1030, 497, 10, 10))
        self.as2Led.setMinimumSize(QtCore.QSize(10, 10))
        self.as2Led.setMaximumSize(QtCore.QSize(10, 10))
        self.as2Led.setObjectName(_fromUtf8("as2Led"))
        self.layoutWidget5 = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget5.setGeometry(QtCore.QRect(190, 750, 71, 31))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.vacuumValve1OnLayout = QtGui.QHBoxLayout(self.layoutWidget5)
        self.vacuumValve1OnLayout.setContentsMargins(0, -1, -1, -1)
        self.vacuumValve1OnLayout.setObjectName(_fromUtf8("vacuumValve1OnLayout"))
        self.vacuumValve1OnCheck = TaurusValueCheckBox(self.layoutWidget5)
        self.vacuumValve1OnCheck.setShowText(False)
        self.vacuumValve1OnCheck.setObjectName(_fromUtf8("vacuumValve1OnCheck"))
        self.vacuumValve1OnLayout.addWidget(self.vacuumValve1OnCheck)
        self.vacuumValve1OnLabel = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve1OnLabel.setFont(font)
        self.vacuumValve1OnLabel.setObjectName(_fromUtf8("vacuumValve1OnLabel"))
        self.vacuumValve1OnLayout.addWidget(self.vacuumValve1OnLabel)
        self.layoutWidget6 = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget6.setGeometry(QtCore.QRect(510, 750, 71, 31))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.vacuumValve2OnLayout = QtGui.QHBoxLayout(self.layoutWidget6)
        self.vacuumValve2OnLayout.setMargin(0)
        self.vacuumValve2OnLayout.setObjectName(_fromUtf8("vacuumValve2OnLayout"))
        self.vacuumValve2OnLabel = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve2OnLabel.setFont(font)
        self.vacuumValve2OnLabel.setObjectName(_fromUtf8("vacuumValve2OnLabel"))
        self.vacuumValve2OnLayout.addWidget(self.vacuumValve2OnLabel)
        self.vacuumValve2OnCheck = TaurusValueCheckBox(self.layoutWidget6)
        self.vacuumValve2OnCheck.setShowText(False)
        self.vacuumValve2OnCheck.setObjectName(_fromUtf8("vacuumValve2OnCheck"))
        self.vacuumValve2OnLayout.addWidget(self.vacuumValve2OnCheck)
        self.layoutWidget7 = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget7.setGeometry(QtCore.QRect(670, 750, 71, 31))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.vacuumValve3OnLayout = QtGui.QHBoxLayout(self.layoutWidget7)
        self.vacuumValve3OnLayout.setContentsMargins(0, -1, -1, -1)
        self.vacuumValve3OnLayout.setObjectName(_fromUtf8("vacuumValve3OnLayout"))
        self.vacuumValve3OnCheck = TaurusValueCheckBox(self.layoutWidget7)
        self.vacuumValve3OnCheck.setShowText(False)
        self.vacuumValve3OnCheck.setObjectName(_fromUtf8("vacuumValve3OnCheck"))
        self.vacuumValve3OnLayout.addWidget(self.vacuumValve3OnCheck)
        self.vacuumValve3OnLabel = QtGui.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve3OnLabel.setFont(font)
        self.vacuumValve3OnLabel.setObjectName(_fromUtf8("vacuumValve3OnLabel"))
        self.vacuumValve3OnLayout.addWidget(self.vacuumValve3OnLabel)
        self.layoutWidget8 = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget8.setGeometry(QtCore.QRect(760, 750, 81, 31))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.vacuumValve4OnLayout = QtGui.QHBoxLayout(self.layoutWidget8)
        self.vacuumValve4OnLayout.setMargin(0)
        self.vacuumValve4OnLayout.setObjectName(_fromUtf8("vacuumValve4OnLayout"))
        self.vacuumValve4OnLabel = QtGui.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve4OnLabel.setFont(font)
        self.vacuumValve4OnLabel.setObjectName(_fromUtf8("vacuumValve4OnLabel"))
        self.vacuumValve4OnLayout.addWidget(self.vacuumValve4OnLabel)
        self.vacuumValve4OnCheck = TaurusValueCheckBox(self.layoutWidget8)
        self.vacuumValve4OnCheck.setShowText(False)
        self.vacuumValve4OnCheck.setObjectName(_fromUtf8("vacuumValve4OnCheck"))
        self.vacuumValve4OnLayout.addWidget(self.vacuumValve4OnCheck)
        self.layoutWidget9 = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget9.setGeometry(QtCore.QRect(919, 752, 71, 31))
        self.layoutWidget9.setObjectName(_fromUtf8("layoutWidget9"))
        self.vacuumValve5OnLayout = QtGui.QHBoxLayout(self.layoutWidget9)
        self.vacuumValve5OnLayout.setContentsMargins(0, -1, -1, -1)
        self.vacuumValve5OnLayout.setObjectName(_fromUtf8("vacuumValve5OnLayout"))
        self.vacuumValve5OnLabel = QtGui.QLabel(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve5OnLabel.setFont(font)
        self.vacuumValve5OnLabel.setObjectName(_fromUtf8("vacuumValve5OnLabel"))
        self.vacuumValve5OnLayout.addWidget(self.vacuumValve5OnLabel)
        self.vacuumValve5OnCheck = TaurusValueCheckBox(self.layoutWidget9)
        self.vacuumValve5OnCheck.setShowText(False)
        self.vacuumValve5OnCheck.setObjectName(_fromUtf8("vacuumValve5OnCheck"))
        self.vacuumValve5OnLayout.addWidget(self.vacuumValve5OnCheck)
        self.layoutWidget10 = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget10.setGeometry(QtCore.QRect(1050, 750, 81, 31))
        self.layoutWidget10.setObjectName(_fromUtf8("layoutWidget10"))
        self.vacuumValve6OnLayout = QtGui.QHBoxLayout(self.layoutWidget10)
        self.vacuumValve6OnLayout.setContentsMargins(0, -1, -1, -1)
        self.vacuumValve6OnLayout.setObjectName(_fromUtf8("vacuumValve6OnLayout"))
        self.vacuumValve6OnLabel = QtGui.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve6OnLabel.setFont(font)
        self.vacuumValve6OnLabel.setObjectName(_fromUtf8("vacuumValve6OnLabel"))
        self.vacuumValve6OnLayout.addWidget(self.vacuumValve6OnLabel)
        self.vacuumValve6OnCheck = TaurusValueCheckBox(self.layoutWidget10)
        self.vacuumValve6OnCheck.setShowText(False)
        self.vacuumValve6OnCheck.setObjectName(_fromUtf8("vacuumValve6OnCheck"))
        self.vacuumValve6OnLayout.addWidget(self.vacuumValve6OnCheck)
        self.layoutWidget11 = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget11.setGeometry(QtCore.QRect(1170, 750, 71, 31))
        self.layoutWidget11.setObjectName(_fromUtf8("layoutWidget11"))
        self.vacuumValve7OnLayout = QtGui.QHBoxLayout(self.layoutWidget11)
        self.vacuumValve7OnLayout.setContentsMargins(0, -1, -1, -1)
        self.vacuumValve7OnLayout.setObjectName(_fromUtf8("vacuumValve7OnLayout"))
        self.vacuumValve7OnLabel = QtGui.QLabel(self.layoutWidget11)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.vacuumValve7OnLabel.setFont(font)
        self.vacuumValve7OnLabel.setObjectName(_fromUtf8("vacuumValve7OnLabel"))
        self.vacuumValve7OnLayout.addWidget(self.vacuumValve7OnLabel)
        self.vacuumValve7OnCheck = TaurusValueCheckBox(self.layoutWidget11)
        self.vacuumValve7OnCheck.setShowText(False)
        self.vacuumValve7OnCheck.setObjectName(_fromUtf8("vacuumValve7OnCheck"))
        self.vacuumValve7OnLayout.addWidget(self.vacuumValve7OnCheck)
        self.klystron2InterlockPopupCheck = QtGui.QCheckBox(linacStartupSynoptic)
        self.klystron2InterlockPopupCheck.setGeometry(QtCore.QRect(120, 44, 21, 21))
        self.klystron2InterlockPopupCheck.setText(_fromUtf8(""))
        self.klystron2InterlockPopupCheck.setObjectName(_fromUtf8("klystron2InterlockPopupCheck"))
        self.klystron1InterlockPopupCheck = QtGui.QCheckBox(linacStartupSynoptic)
        self.klystron1InterlockPopupCheck.setGeometry(QtCore.QRect(120, 115, 21, 21))
        self.klystron1InterlockPopupCheck.setText(_fromUtf8(""))
        self.klystron1InterlockPopupCheck.setObjectName(_fromUtf8("klystron1InterlockPopupCheck"))
        self.layoutWidget12 = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget12.setGeometry(QtCore.QRect(10, 80, 81, 31))
        self.layoutWidget12.setObjectName(_fromUtf8("layoutWidget12"))
        self.interlockUnitResetLayout = QtGui.QHBoxLayout(self.layoutWidget12)
        self.interlockUnitResetLayout.setContentsMargins(-1, 0, -1, -1)
        self.interlockUnitResetLayout.setObjectName(_fromUtf8("interlockUnitResetLayout"))
        self.interlockUnitResetLabel = QtGui.QLabel(self.layoutWidget12)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.interlockUnitResetLabel.setFont(font)
        self.interlockUnitResetLabel.setObjectName(_fromUtf8("interlockUnitResetLabel"))
        self.interlockUnitResetLayout.addWidget(self.interlockUnitResetLabel)
        self.interlockUnitResetCheck = TaurusValueCheckBox(self.layoutWidget12)
        self.interlockUnitResetCheck.setShowText(False)
        self.interlockUnitResetCheck.setObjectName(_fromUtf8("interlockUnitResetCheck"))
        self.interlockUnitResetLayout.addWidget(self.interlockUnitResetCheck)
        self.klystron2InterlockPopupWidget = klystron2itck(linacStartupSynoptic)
        self.klystron2InterlockPopupWidget.setGeometry(QtCore.QRect(350, 10, 183, 100))
        self.klystron2InterlockPopupWidget.setObjectName(_fromUtf8("klystron2InterlockPopupWidget"))
        self.klystron1InterlockPopupWidget = klystron1itck(linacStartupSynoptic)
        self.klystron1InterlockPopupWidget.setGeometry(QtCore.QRect(350, 110, 183, 140))
        self.klystron1InterlockPopupWidget.setObjectName(_fromUtf8("klystron1InterlockPopupWidget"))
        self.layoutWidget_3 = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 310, 71, 31))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.egunonLayout = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.egunonLayout.setContentsMargins(0, -1, -1, -1)
        self.egunonLayout.setObjectName(_fromUtf8("egunonLayout"))
        self.egunonLabel = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.egunonLabel.setFont(font)
        self.egunonLabel.setObjectName(_fromUtf8("egunonLabel"))
        self.egunonLayout.addWidget(self.egunonLabel)
        self.egunonCheck = TaurusValueCheckBox(self.layoutWidget_3)
        self.egunonCheck.setShowText(False)
        self.egunonCheck.setObjectName(_fromUtf8("egunonCheck"))
        self.egunonLayout.addWidget(self.egunonCheck)
        self.egunonLed = TaurusLed(self.layoutWidget_3)
        self.egunonLed.setMinimumSize(QtCore.QSize(15, 15))
        self.egunonLed.setMaximumSize(QtCore.QSize(15, 15))
        self.egunonLed.setObjectName(_fromUtf8("egunonLed"))
        self.egunonLayout.addWidget(self.egunonLed)
        self.kdeGunLVPopupCheck = QtGui.QCheckBox(linacStartupSynoptic)
        self.kdeGunLVPopupCheck.setGeometry(QtCore.QRect(115, 368, 21, 21))
        self.kdeGunLVPopupCheck.setText(_fromUtf8(""))
        self.kdeGunLVPopupCheck.setObjectName(_fromUtf8("kdeGunLVPopupCheck"))
        self.layoutWidget13 = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget13.setGeometry(QtCore.QRect(10, 390, 128, 94))
        self.layoutWidget13.setObjectName(_fromUtf8("layoutWidget13"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget13)
        self.gridLayout.setContentsMargins(3, -1, -1, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.filamentSetpoint = TaurusValueSpinBox(self.layoutWidget13)
        self.filamentSetpoint.setMinimumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.filamentSetpoint.setFont(font)
        self.filamentSetpoint.setAutoApply(False)
        self.filamentSetpoint.setObjectName(_fromUtf8("filamentSetpoint"))
        self.gridLayout.addWidget(self.filamentSetpoint, 0, 0, 1, 1)
        self.cathodeSetpoint = TaurusValueSpinBox(self.layoutWidget13)
        self.cathodeSetpoint.setMinimumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cathodeSetpoint.setFont(font)
        self.cathodeSetpoint.setAutoApply(True)
        self.cathodeSetpoint.setObjectName(_fromUtf8("cathodeSetpoint"))
        self.gridLayout.addWidget(self.cathodeSetpoint, 0, 1, 1, 1)
        self.filamentVLabel = QtGui.QLabel(self.layoutWidget13)
        self.filamentVLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.filamentVLabel.setFont(font)
        self.filamentVLabel.setObjectName(_fromUtf8("filamentVLabel"))
        self.gridLayout.addWidget(self.filamentVLabel, 1, 0, 1, 1)
        self.cathodeLabel = QtGui.QLabel(self.layoutWidget13)
        self.cathodeLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.cathodeLabel.setFont(font)
        self.cathodeLabel.setObjectName(_fromUtf8("cathodeLabel"))
        self.gridLayout.addWidget(self.cathodeLabel, 1, 1, 1, 1)
        self.filamentCurrent = TaurusLabel(self.layoutWidget13)
        self.filamentCurrent.setMinimumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.filamentCurrent.setFont(font)
        self.filamentCurrent.setSuffixText(_fromUtf8(""))
        self.filamentCurrent.setObjectName(_fromUtf8("filamentCurrent"))
        self.gridLayout.addWidget(self.filamentCurrent, 2, 0, 1, 1)
        self.temperatureValue = TaurusLabel(self.layoutWidget13)
        self.temperatureValue.setMinimumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.temperatureValue.setFont(font)
        self.temperatureValue.setSuffixText(_fromUtf8(""))
        self.temperatureValue.setObjectName(_fromUtf8("temperatureValue"))
        self.gridLayout.addWidget(self.temperatureValue, 2, 1, 1, 1)
        self.filamentILabel = QtGui.QLabel(self.layoutWidget13)
        self.filamentILabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.filamentILabel.setFont(font)
        self.filamentILabel.setObjectName(_fromUtf8("filamentILabel"))
        self.gridLayout.addWidget(self.filamentILabel, 3, 0, 1, 1)
        self.temperatureLabel = QtGui.QLabel(self.layoutWidget13)
        self.temperatureLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.temperatureLabel.setFont(font)
        self.temperatureLabel.setObjectName(_fromUtf8("temperatureLabel"))
        self.gridLayout.addWidget(self.temperatureLabel, 3, 1, 1, 1)
        self.kdeGunLVWidget = eGunLV(linacStartupSynoptic)
        self.kdeGunLVWidget.setGeometry(QtCore.QRect(155, 343, 157, 111))
        self.kdeGunLVWidget.setObjectName(_fromUtf8("kdeGunLVWidget"))
        self.klystronAmplifierEnabledLed = TaurusLed(linacStartupSynoptic)
        self.klystronAmplifierEnabledLed.setGeometry(QtCore.QRect(70, 40, 10, 10))
        self.klystronAmplifierEnabledLed.setMinimumSize(QtCore.QSize(10, 10))
        self.klystronAmplifierEnabledLed.setMaximumSize(QtCore.QSize(10, 10))
        self.klystronAmplifierEnabledLed.setObjectName(_fromUtf8("klystronAmplifierEnabledLed"))
        self.magnetInterlockStateLed = TaurusLed(linacStartupSynoptic)
        self.magnetInterlockStateLed.setGeometry(QtCore.QRect(125, 71, 10, 10))
        self.magnetInterlockStateLed.setMinimumSize(QtCore.QSize(10, 10))
        self.magnetInterlockStateLed.setMaximumSize(QtCore.QSize(10, 10))
        self.magnetInterlockStateLed.setObjectName(_fromUtf8("magnetInterlockStateLed"))
        self.utilitiesInterlockStateLed = TaurusLed(linacStartupSynoptic)
        self.utilitiesInterlockStateLed.setGeometry(QtCore.QRect(125, 143, 10, 10))
        self.utilitiesInterlockStateLed.setMinimumSize(QtCore.QSize(10, 10))
        self.utilitiesInterlockStateLed.setMaximumSize(QtCore.QSize(10, 10))
        self.utilitiesInterlockStateLed.setObjectName(_fromUtf8("utilitiesInterlockStateLed"))
        self.compressedAirStateLed = TaurusLed(linacStartupSynoptic)
        self.compressedAirStateLed.setGeometry(QtCore.QRect(125, 165, 10, 10))
        self.compressedAirStateLed.setMinimumSize(QtCore.QSize(10, 10))
        self.compressedAirStateLed.setMaximumSize(QtCore.QSize(10, 10))
        self.compressedAirStateLed.setObjectName(_fromUtf8("compressedAirStateLed"))
        self.transferlineVacuumStateLed = TaurusLed(linacStartupSynoptic)
        self.transferlineVacuumStateLed.setGeometry(QtCore.QRect(70, 179, 10, 10))
        self.transferlineVacuumStateLed.setMinimumSize(QtCore.QSize(10, 10))
        self.transferlineVacuumStateLed.setMaximumSize(QtCore.QSize(10, 10))
        self.transferlineVacuumStateLed.setObjectName(_fromUtf8("transferlineVacuumStateLed"))
        self.linacVacuumStateLed = TaurusLed(linacStartupSynoptic)
        self.linacVacuumStateLed.setGeometry(QtCore.QRect(125, 191, 10, 10))
        self.linacVacuumStateLed.setMinimumSize(QtCore.QSize(10, 10))
        self.linacVacuumStateLed.setMaximumSize(QtCore.QSize(10, 10))
        self.linacVacuumStateLed.setObjectName(_fromUtf8("linacVacuumStateLed"))
        self.electronGunEnabledLed = TaurusLed(linacStartupSynoptic)
        self.electronGunEnabledLed.setGeometry(QtCore.QRect(70, 203, 10, 10))
        self.electronGunEnabledLed.setMinimumSize(QtCore.QSize(10, 10))
        self.electronGunEnabledLed.setMaximumSize(QtCore.QSize(10, 10))
        self.electronGunEnabledLed.setObjectName(_fromUtf8("electronGunEnabledLed"))
        self.gmdiLed = TaurusLed(linacStartupSynoptic)
        self.gmdiLed.setGeometry(QtCore.QRect(125, 218, 10, 10))
        self.gmdiLed.setMinimumSize(QtCore.QSize(10, 10))
        self.gmdiLed.setMaximumSize(QtCore.QSize(10, 10))
        self.gmdiLed.setObjectName(_fromUtf8("gmdiLed"))
        self.interlockUnitReadyStateLed = TaurusLed(linacStartupSynoptic)
        self.interlockUnitReadyStateLed.setGeometry(QtCore.QRect(271, 19, 10, 10))
        self.interlockUnitReadyStateLed.setMinimumSize(QtCore.QSize(10, 10))
        self.interlockUnitReadyStateLed.setMaximumSize(QtCore.QSize(10, 10))
        self.interlockUnitReadyStateLed.setObjectName(_fromUtf8("interlockUnitReadyStateLed"))
        self.klystron2AmplifierEnabledLed = TaurusLed(linacStartupSynoptic)
        self.klystron2AmplifierEnabledLed.setGeometry(QtCore.QRect(280, 48, 10, 10))
        self.klystron2AmplifierEnabledLed.setMinimumSize(QtCore.QSize(10, 10))
        self.klystron2AmplifierEnabledLed.setMaximumSize(QtCore.QSize(10, 10))
        self.klystron2AmplifierEnabledLed.setObjectName(_fromUtf8("klystron2AmplifierEnabledLed"))
        self.klystron1AmplifierEnabledLed = TaurusLed(linacStartupSynoptic)
        self.klystron1AmplifierEnabledLed.setGeometry(QtCore.QRect(280, 118, 10, 10))
        self.klystron1AmplifierEnabledLed.setMinimumSize(QtCore.QSize(10, 10))
        self.klystron1AmplifierEnabledLed.setMaximumSize(QtCore.QSize(10, 10))
        self.klystron1AmplifierEnabledLed.setObjectName(_fromUtf8("klystron1AmplifierEnabledLed"))
        self.linacVacuumStateLed_2 = TaurusLed(linacStartupSynoptic)
        self.linacVacuumStateLed_2.setGeometry(QtCore.QRect(280, 168, 10, 10))
        self.linacVacuumStateLed_2.setMinimumSize(QtCore.QSize(10, 10))
        self.linacVacuumStateLed_2.setMaximumSize(QtCore.QSize(10, 10))
        self.linacVacuumStateLed_2.setObjectName(_fromUtf8("linacVacuumStateLed_2"))
        self.linacReadyStateLed = TaurusLed(linacStartupSynoptic)
        self.linacReadyStateLed.setGeometry(QtCore.QRect(280, 192, 10, 10))
        self.linacReadyStateLed.setMinimumSize(QtCore.QSize(10, 10))
        self.linacReadyStateLed.setMaximumSize(QtCore.QSize(10, 10))
        self.linacReadyStateLed.setObjectName(_fromUtf8("linacReadyStateLed"))
        self.layoutWidget14 = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget14.setGeometry(QtCore.QRect(740, 213, 85, 48))
        self.layoutWidget14.setObjectName(_fromUtf8("layoutWidget14"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget14)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.klystron1OnLed = TaurusLed(self.layoutWidget14)
        self.klystron1OnLed.setMinimumSize(QtCore.QSize(15, 15))
        self.klystron1OnLed.setMaximumSize(QtCore.QSize(15, 15))
        self.klystron1OnLed.setObjectName(_fromUtf8("klystron1OnLed"))
        self.gridLayout_2.addWidget(self.klystron1OnLed, 0, 0, 1, 1)
        self.klystron1OnCheck = TaurusValueCheckBox(self.layoutWidget14)
        self.klystron1OnCheck.setShowText(False)
        self.klystron1OnCheck.setObjectName(_fromUtf8("klystron1OnCheck"))
        self.gridLayout_2.addWidget(self.klystron1OnCheck, 0, 1, 1, 1)
        self.klystron1OnLabel = QtGui.QLabel(self.layoutWidget14)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.klystron1OnLabel.setFont(font)
        self.klystron1OnLabel.setObjectName(_fromUtf8("klystron1OnLabel"))
        self.gridLayout_2.addWidget(self.klystron1OnLabel, 0, 2, 1, 1)
        self.klystron1RstLed = TaurusLed(self.layoutWidget14)
        self.klystron1RstLed.setMinimumSize(QtCore.QSize(15, 15))
        self.klystron1RstLed.setMaximumSize(QtCore.QSize(15, 15))
        self.klystron1RstLed.setObjectName(_fromUtf8("klystron1RstLed"))
        self.gridLayout_2.addWidget(self.klystron1RstLed, 1, 0, 1, 1)
        self.klystron1RstCheck = TaurusValueCheckBox(self.layoutWidget14)
        self.klystron1RstCheck.setShowText(False)
        self.klystron1RstCheck.setObjectName(_fromUtf8("klystron1RstCheck"))
        self.gridLayout_2.addWidget(self.klystron1RstCheck, 1, 1, 1, 1)
        self.klystron1RstLabel = QtGui.QLabel(self.layoutWidget14)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.klystron1RstLabel.setFont(font)
        self.klystron1RstLabel.setObjectName(_fromUtf8("klystron1RstLabel"))
        self.gridLayout_2.addWidget(self.klystron1RstLabel, 1, 2, 1, 1)
        self.layoutWidget15 = QtGui.QWidget(linacStartupSynoptic)
        self.layoutWidget15.setGeometry(QtCore.QRect(1030, 212, 85, 48))
        self.layoutWidget15.setObjectName(_fromUtf8("layoutWidget15"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget15)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.klystron2OnLed = TaurusLed(self.layoutWidget15)
        self.klystron2OnLed.setMinimumSize(QtCore.QSize(15, 15))
        self.klystron2OnLed.setMaximumSize(QtCore.QSize(15, 15))
        self.klystron2OnLed.setObjectName(_fromUtf8("klystron2OnLed"))
        self.gridLayout_3.addWidget(self.klystron2OnLed, 0, 0, 1, 1)
        self.klystron2OnCheck = TaurusValueCheckBox(self.layoutWidget15)
        self.klystron2OnCheck.setShowText(False)
        self.klystron2OnCheck.setObjectName(_fromUtf8("klystron2OnCheck"))
        self.gridLayout_3.addWidget(self.klystron2OnCheck, 0, 1, 1, 1)
        self.klystron2OnLabel = QtGui.QLabel(self.layoutWidget15)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.klystron2OnLabel.setFont(font)
        self.klystron2OnLabel.setObjectName(_fromUtf8("klystron2OnLabel"))
        self.gridLayout_3.addWidget(self.klystron2OnLabel, 0, 2, 1, 1)
        self.klystron2RstLed = TaurusLed(self.layoutWidget15)
        self.klystron2RstLed.setMinimumSize(QtCore.QSize(15, 15))
        self.klystron2RstLed.setMaximumSize(QtCore.QSize(15, 15))
        self.klystron2RstLed.setObjectName(_fromUtf8("klystron2RstLed"))
        self.gridLayout_3.addWidget(self.klystron2RstLed, 1, 0, 1, 1)
        self.klystron2RstCheck = TaurusValueCheckBox(self.layoutWidget15)
        self.klystron2RstCheck.setShowText(False)
        self.klystron2RstCheck.setObjectName(_fromUtf8("klystron2RstCheck"))
        self.gridLayout_3.addWidget(self.klystron2RstCheck, 1, 1, 1, 1)
        self.klystron2RstLabel = QtGui.QLabel(self.layoutWidget15)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.klystron2RstLabel.setFont(font)
        self.klystron2RstLabel.setObjectName(_fromUtf8("klystron2RstLabel"))
        self.gridLayout_3.addWidget(self.klystron2RstLabel, 1, 2, 1, 1)
        self.StartUpSchematic = QtGui.QLabel(linacStartupSynoptic)
        self.StartUpSchematic.setGeometry(QtCore.QRect(0, 0, 1250, 825))
        self.StartUpSchematic.setText(_fromUtf8(""))
        self.StartUpSchematic.setPixmap(QtGui.QPixmap(_fromUtf8("jdraw/linac_startup_synoptic.png")))
        self.StartUpSchematic.setObjectName(_fromUtf8("StartUpSchematic"))

        self.retranslateUi(linacStartupSynoptic)
        QtCore.QMetaObject.connectSlotsByName(linacStartupSynoptic)
        linacStartupSynoptic.setTabOrder(self.klystron2InterlockPopupCheck, self.interlockUnitResetCheck)
        linacStartupSynoptic.setTabOrder(self.interlockUnitResetCheck, self.klystron1InterlockPopupCheck)
        linacStartupSynoptic.setTabOrder(self.klystron1InterlockPopupCheck, self.klystron1LVPopupCheck)
        linacStartupSynoptic.setTabOrder(self.klystron1LVPopupCheck, self.klystron1OnCheck)
        linacStartupSynoptic.setTabOrder(self.klystron1OnCheck, self.klystron1RstCheck)
        linacStartupSynoptic.setTabOrder(self.klystron1RstCheck, self.klystron2LVPopupCheck)
        linacStartupSynoptic.setTabOrder(self.klystron2LVPopupCheck, self.klystron2OnCheck)
        linacStartupSynoptic.setTabOrder(self.klystron2OnCheck, self.klystron2RstCheck)
        linacStartupSynoptic.setTabOrder(self.klystron2RstCheck, self.coolingLoop1OnCheck)
        linacStartupSynoptic.setTabOrder(self.coolingLoop1OnCheck, self.coolingLoop1TemperatureValue)
        linacStartupSynoptic.setTabOrder(self.coolingLoop1TemperatureValue, self.coolingLoop1PopupCheck)
        linacStartupSynoptic.setTabOrder(self.coolingLoop1PopupCheck, self.coolingLoop2OnCheck)
        linacStartupSynoptic.setTabOrder(self.coolingLoop2OnCheck, self.coolingLoop2TemperatureValue)
        linacStartupSynoptic.setTabOrder(self.coolingLoop2TemperatureValue, self.coolingLoop2PopupCheck)
        linacStartupSynoptic.setTabOrder(self.coolingLoop2PopupCheck, self.coolingLoop3OnCheck)
        linacStartupSynoptic.setTabOrder(self.coolingLoop3OnCheck, self.coolingLoop3TemperatureValue)
        linacStartupSynoptic.setTabOrder(self.coolingLoop3TemperatureValue, self.coolingLoop3PopupCheck)
        linacStartupSynoptic.setTabOrder(self.coolingLoop3PopupCheck, self.cathodeSetpoint)
        linacStartupSynoptic.setTabOrder(self.cathodeSetpoint, self.vv_oncCheck)
        linacStartupSynoptic.setTabOrder(self.vv_oncCheck, self.vacuumValve1OnCheck)
        linacStartupSynoptic.setTabOrder(self.vacuumValve1OnCheck, self.vacuumValve2OnCheck)
        linacStartupSynoptic.setTabOrder(self.vacuumValve2OnCheck, self.vacuumValve3OnCheck)
        linacStartupSynoptic.setTabOrder(self.vacuumValve3OnCheck, self.vacuumValve4OnCheck)
        linacStartupSynoptic.setTabOrder(self.vacuumValve4OnCheck, self.vacuumValve5OnCheck)
        linacStartupSynoptic.setTabOrder(self.vacuumValve5OnCheck, self.vacuumValve6OnCheck)
        linacStartupSynoptic.setTabOrder(self.vacuumValve6OnCheck, self.vacuumValve7OnCheck)
        linacStartupSynoptic.setTabOrder(self.vacuumValve7OnCheck, self.vv_rstCheck)
        linacStartupSynoptic.setTabOrder(self.vv_rstCheck, self.kdeGunLVPopupCheck)
        linacStartupSynoptic.setTabOrder(self.kdeGunLVPopupCheck, self.filamentSetpoint)
        linacStartupSynoptic.setTabOrder(self.filamentSetpoint, self.egunonCheck)

    def retranslateUi(self, linacStartupSynoptic):
        linacStartupSynoptic.setWindowTitle(QtGui.QApplication.translate("linacStartupSynoptic", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.coolingLoop3OnLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.coolingLoop2OnLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.coolingLoop1OnLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.vv_rstLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.vv_oncLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.vacuumValve1OnLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.vacuumValve2OnLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.vacuumValve3OnLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.vacuumValve4OnLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.vacuumValve5OnLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.vacuumValve6OnLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.vacuumValve7OnLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.interlockUnitResetLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.egunonLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.filamentVLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Filament V", None, QtGui.QApplication.UnicodeUTF8))
        self.cathodeLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Cathode V", None, QtGui.QApplication.UnicodeUTF8))
        self.filamentILabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Filament I", None, QtGui.QApplication.UnicodeUTF8))
        self.temperatureLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.klystron1OnLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.klystron1RstLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.klystron2OnLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.klystron2RstLabel.setText(QtGui.QApplication.translate("linacStartupSynoptic", "Reset", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusLed, TaurusLabel
from taurus.qt.qtgui.container import TaurusWidget
from klystron2itck import klystron2itck
from coolingloop import CoolingLoop
from klystronlv import klystronLV
from egunlv import eGunLV
from klystron1itck import klystron1itck
from taurus.qt.qtgui.input import TaurusValueSpinBox, TaurusValueCheckBox
