# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'snapshot_timing.ui'
#
# Created: Wed Mar 12 08:39:04 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_timingSnapshot(object):
    def setupUi(self, timingSnapshot):
        timingSnapshot.setObjectName(_fromUtf8("timingSnapshot"))
        timingSnapshot.resize(388, 276)
        self.gridLayout_2 = QtGui.QGridLayout(timingSnapshot)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.timingGroup = TaurusGroupBox(timingSnapshot)
        self.timingGroup.setObjectName(_fromUtf8("timingGroup"))
        self.gridLayout = QtGui.QGridLayout(self.timingGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.GPIReading = TaurusLabel(self.timingGroup)
        self.GPIReading.setObjectName(_fromUtf8("GPIReading"))
        self.gridLayout.addWidget(self.GPIReading, 6, 1, 1, 1)
        self.GunDelayCheck = QtGui.QCheckBox(self.timingGroup)
        self.GunDelayCheck.setText(_fromUtf8(""))
        self.GunDelayCheck.setObjectName(_fromUtf8("GunDelayCheck"))
        self.gridLayout.addWidget(self.GunDelayCheck, 3, 4, 1, 1)
        self.GPILabel = QtGui.QLabel(self.timingGroup)
        self.GPILabel.setObjectName(_fromUtf8("GPILabel"))
        self.gridLayout.addWidget(self.GPILabel, 6, 0, 1, 1)
        self.MBMLabel = QtGui.QLabel(self.timingGroup)
        self.MBMLabel.setObjectName(_fromUtf8("MBMLabel"))
        self.gridLayout.addWidget(self.MBMLabel, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 1, 1, 1)
        self.GPIValue = QtGui.QSpinBox(self.timingGroup)
        self.GPIValue.setObjectName(_fromUtf8("GPIValue"))
        self.gridLayout.addWidget(self.GPIValue, 6, 2, 1, 1)
        self.MBMReading = TaurusLed(self.timingGroup)
        self.MBMReading.setMinimumSize(QtCore.QSize(15, 15))
        self.MBMReading.setMaximumSize(QtCore.QSize(15, 15))
        self.MBMReading.setObjectName(_fromUtf8("MBMReading"))
        self.gridLayout.addWidget(self.MBMReading, 1, 1, 1, 1)
        self.ka2DelayCheck = QtGui.QCheckBox(self.timingGroup)
        self.ka2DelayCheck.setText(_fromUtf8(""))
        self.ka2DelayCheck.setObjectName(_fromUtf8("ka2DelayCheck"))
        self.gridLayout.addWidget(self.ka2DelayCheck, 5, 4, 1, 1)
        self.GunDelayLabel = QtGui.QLabel(self.timingGroup)
        self.GunDelayLabel.setObjectName(_fromUtf8("GunDelayLabel"))
        self.gridLayout.addWidget(self.GunDelayLabel, 3, 0, 1, 1)
        self.ka1DelayLabel = QtGui.QLabel(self.timingGroup)
        self.ka1DelayLabel.setObjectName(_fromUtf8("ka1DelayLabel"))
        self.gridLayout.addWidget(self.ka1DelayLabel, 4, 0, 1, 1)
        self.GPMLabel = QtGui.QLabel(self.timingGroup)
        self.GPMLabel.setObjectName(_fromUtf8("GPMLabel"))
        self.gridLayout.addWidget(self.GPMLabel, 2, 0, 1, 1)
        self.ka2DelayLabel = QtGui.QLabel(self.timingGroup)
        self.ka2DelayLabel.setObjectName(_fromUtf8("ka2DelayLabel"))
        self.gridLayout.addWidget(self.ka2DelayLabel, 5, 0, 1, 1)
        self.GPNLabel = QtGui.QLabel(self.timingGroup)
        self.GPNLabel.setObjectName(_fromUtf8("GPNLabel"))
        self.gridLayout.addWidget(self.GPNLabel, 7, 0, 1, 1)
        self.SaveRetrieveTitle = QtGui.QLabel(self.timingGroup)
        self.SaveRetrieveTitle.setObjectName(_fromUtf8("SaveRetrieveTitle"))
        self.gridLayout.addWidget(self.SaveRetrieveTitle, 0, 2, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.timingGroup)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 0, 4, 1, 1)
        self.MBMCheck = QtGui.QCheckBox(self.timingGroup)
        self.MBMCheck.setText(_fromUtf8(""))
        self.MBMCheck.setObjectName(_fromUtf8("MBMCheck"))
        self.gridLayout.addWidget(self.MBMCheck, 1, 4, 1, 1)
        self.MBMValue = QtGui.QCheckBox(self.timingGroup)
        self.MBMValue.setObjectName(_fromUtf8("MBMValue"))
        self.gridLayout.addWidget(self.MBMValue, 1, 2, 1, 1)
        self.GPMReading = TaurusLabel(self.timingGroup)
        self.GPMReading.setObjectName(_fromUtf8("GPMReading"))
        self.gridLayout.addWidget(self.GPMReading, 2, 1, 1, 1)
        self.GPNValue = QtGui.QSpinBox(self.timingGroup)
        self.GPNValue.setObjectName(_fromUtf8("GPNValue"))
        self.gridLayout.addWidget(self.GPNValue, 7, 2, 1, 1)
        self.GunDelayValue = QtGui.QSpinBox(self.timingGroup)
        self.GunDelayValue.setObjectName(_fromUtf8("GunDelayValue"))
        self.gridLayout.addWidget(self.GunDelayValue, 3, 2, 1, 1)
        self.GPMCheck = QtGui.QCheckBox(self.timingGroup)
        self.GPMCheck.setText(_fromUtf8(""))
        self.GPMCheck.setObjectName(_fromUtf8("GPMCheck"))
        self.gridLayout.addWidget(self.GPMCheck, 2, 4, 1, 1)
        self.line = QtGui.QFrame(self.timingGroup)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 3, 8, 1)
        self.PresentValueTitle = QtGui.QLabel(self.timingGroup)
        self.PresentValueTitle.setObjectName(_fromUtf8("PresentValueTitle"))
        self.gridLayout.addWidget(self.PresentValueTitle, 0, 1, 1, 1)
        self.GPALabel = QtGui.QLabel(self.timingGroup)
        self.GPALabel.setObjectName(_fromUtf8("GPALabel"))
        self.gridLayout.addWidget(self.GPALabel, 8, 0, 1, 1)
        self.ka1DelayReading = TaurusLabel(self.timingGroup)
        self.ka1DelayReading.setObjectName(_fromUtf8("ka1DelayReading"))
        self.gridLayout.addWidget(self.ka1DelayReading, 4, 1, 1, 1)
        self.GPAReading = TaurusLabel(self.timingGroup)
        self.GPAReading.setObjectName(_fromUtf8("GPAReading"))
        self.gridLayout.addWidget(self.GPAReading, 8, 1, 1, 1)
        self.ka1DelayCheck = QtGui.QCheckBox(self.timingGroup)
        self.ka1DelayCheck.setText(_fromUtf8(""))
        self.ka1DelayCheck.setObjectName(_fromUtf8("ka1DelayCheck"))
        self.gridLayout.addWidget(self.ka1DelayCheck, 4, 4, 1, 1)
        self.GPNCheck = QtGui.QCheckBox(self.timingGroup)
        self.GPNCheck.setText(_fromUtf8(""))
        self.GPNCheck.setObjectName(_fromUtf8("GPNCheck"))
        self.gridLayout.addWidget(self.GPNCheck, 7, 4, 1, 1)
        self.GPICheck = QtGui.QCheckBox(self.timingGroup)
        self.GPICheck.setText(_fromUtf8(""))
        self.GPICheck.setObjectName(_fromUtf8("GPICheck"))
        self.gridLayout.addWidget(self.GPICheck, 6, 4, 1, 1)
        self.GPACheck = QtGui.QCheckBox(self.timingGroup)
        self.GPACheck.setText(_fromUtf8(""))
        self.GPACheck.setObjectName(_fromUtf8("GPACheck"))
        self.gridLayout.addWidget(self.GPACheck, 8, 4, 1, 1)
        self.ka2DelayReading = TaurusLabel(self.timingGroup)
        self.ka2DelayReading.setObjectName(_fromUtf8("ka2DelayReading"))
        self.gridLayout.addWidget(self.ka2DelayReading, 5, 1, 1, 1)
        self.GunDelayReaing = TaurusLabel(self.timingGroup)
        self.GunDelayReaing.setObjectName(_fromUtf8("GunDelayReaing"))
        self.gridLayout.addWidget(self.GunDelayReaing, 3, 1, 1, 1)
        self.GPNReading = TaurusLabel(self.timingGroup)
        self.GPNReading.setObjectName(_fromUtf8("GPNReading"))
        self.gridLayout.addWidget(self.GPNReading, 7, 1, 1, 1)
        self.GPMValue = QtGui.QSpinBox(self.timingGroup)
        self.GPMValue.setObjectName(_fromUtf8("GPMValue"))
        self.gridLayout.addWidget(self.GPMValue, 2, 2, 1, 1)
        self.ka1DelayValue = QtGui.QSpinBox(self.timingGroup)
        self.ka1DelayValue.setObjectName(_fromUtf8("ka1DelayValue"))
        self.gridLayout.addWidget(self.ka1DelayValue, 4, 2, 1, 1)
        self.ka2DelayValue = QtGui.QSpinBox(self.timingGroup)
        self.ka2DelayValue.setObjectName(_fromUtf8("ka2DelayValue"))
        self.gridLayout.addWidget(self.ka2DelayValue, 5, 2, 1, 1)
        self.GPAValue = QtGui.QDoubleSpinBox(self.timingGroup)
        self.GPAValue.setObjectName(_fromUtf8("GPAValue"))
        self.gridLayout.addWidget(self.GPAValue, 8, 2, 1, 1)
        self.gridLayout_2.addWidget(self.timingGroup, 0, 0, 1, 1)

        self.retranslateUi(timingSnapshot)
        QtCore.QMetaObject.connectSlotsByName(timingSnapshot)

    def retranslateUi(self, timingSnapshot):
        timingSnapshot.setWindowTitle(QtGui.QApplication.translate("timingSnapshot", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.timingGroup.setTitle(QtGui.QApplication.translate("timingSnapshot", "Timing", None, QtGui.QApplication.UnicodeUTF8))
        self.GPILabel.setText(QtGui.QApplication.translate("timingSnapshot", "Bunch Interval/width", None, QtGui.QApplication.UnicodeUTF8))
        self.MBMLabel.setText(QtGui.QApplication.translate("timingSnapshot", "Multi Bunch Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.GunDelayLabel.setText(QtGui.QApplication.translate("timingSnapshot", "Electron Gun Delay", None, QtGui.QApplication.UnicodeUTF8))
        self.ka1DelayLabel.setText(QtGui.QApplication.translate("timingSnapshot", "KA1 Delay", None, QtGui.QApplication.UnicodeUTF8))
        self.GPMLabel.setText(QtGui.QApplication.translate("timingSnapshot", "Gated Pulsed Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.ka2DelayLabel.setText(QtGui.QApplication.translate("timingSnapshot", "KA2 Delay", None, QtGui.QApplication.UnicodeUTF8))
        self.GPNLabel.setText(QtGui.QApplication.translate("timingSnapshot", "Bunch number", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveRetrieveTitle.setText(QtGui.QApplication.translate("timingSnapshot", "Save/Retrieve", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("timingSnapshot", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.MBMValue.setText(QtGui.QApplication.translate("timingSnapshot", "multi/single", None, QtGui.QApplication.UnicodeUTF8))
        self.PresentValueTitle.setText(QtGui.QApplication.translate("timingSnapshot", "Present value", None, QtGui.QApplication.UnicodeUTF8))
        self.GPALabel.setText(QtGui.QApplication.translate("timingSnapshot", "Pulses Attenuattion", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusLabel, TaurusLed
from taurus.qt.qtgui.container import TaurusGroupBox
from taurus.qt.qtgui.panel import TaurusWidget
