# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/ui/snapshot_timing.ui'
#
# Created: Wed Apr  9 13:05:01 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_timingSnapshot(object):
    def setupUi(self, timingSnapshot):
        timingSnapshot.setObjectName(_fromUtf8("timingSnapshot"))
        timingSnapshot.resize(314, 235)
        font = QtGui.QFont()
        font.setPointSize(7)
        timingSnapshot.setFont(font)
        self.gridLayout_2 = QtGui.QGridLayout(timingSnapshot)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.timingGroup = TaurusGroupBox(timingSnapshot)
        self.timingGroup.setObjectName(_fromUtf8("timingGroup"))
        self.gridLayout = QtGui.QGridLayout(self.timingGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 1, 1, 1)
        self.MBMLabel = QtGui.QLabel(self.timingGroup)
        self.MBMLabel.setObjectName(_fromUtf8("MBMLabel"))
        self.gridLayout.addWidget(self.MBMLabel, 1, 0, 1, 1)
        self.PresentWriteTitle = QtGui.QLabel(self.timingGroup)
        self.PresentWriteTitle.setObjectName(_fromUtf8("PresentWriteTitle"))
        self.gridLayout.addWidget(self.PresentWriteTitle, 0, 1, 1, 1)
        self.GPARead = TaurusLabel(self.timingGroup)
        self.GPARead.setObjectName(_fromUtf8("GPARead"))
        self.gridLayout.addWidget(self.GPARead, 7, 1, 1, 1)
        self.ka1DelayCheck = QtGui.QCheckBox(self.timingGroup)
        self.ka1DelayCheck.setText(_fromUtf8(""))
        self.ka1DelayCheck.setObjectName(_fromUtf8("ka1DelayCheck"))
        self.gridLayout.addWidget(self.ka1DelayCheck, 3, 4, 1, 1)
        self.GPNWrite = QtGui.QSpinBox(self.timingGroup)
        self.GPNWrite.setMinimum(1)
        self.GPNWrite.setMaximum(16)
        self.GPNWrite.setObjectName(_fromUtf8("GPNWrite"))
        self.gridLayout.addWidget(self.GPNWrite, 6, 2, 1, 1)
        self.ka1DelayRead = TaurusLabel(self.timingGroup)
        self.ka1DelayRead.setObjectName(_fromUtf8("ka1DelayRead"))
        self.gridLayout.addWidget(self.ka1DelayRead, 3, 1, 1, 1)
        self.line = QtGui.QFrame(self.timingGroup)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 3, 7, 1)
        self.GPIRead = TaurusLabel(self.timingGroup)
        self.GPIRead.setObjectName(_fromUtf8("GPIRead"))
        self.gridLayout.addWidget(self.GPIRead, 5, 1, 1, 1)
        self.GunDelayWrite = QtGui.QSpinBox(self.timingGroup)
        self.GunDelayWrite.setMinimum(32)
        self.GunDelayWrite.setMaximum(4096)
        self.GunDelayWrite.setSingleStep(32)
        self.GunDelayWrite.setObjectName(_fromUtf8("GunDelayWrite"))
        self.gridLayout.addWidget(self.GunDelayWrite, 2, 2, 1, 1)
        self.ka2DelayCheck = QtGui.QCheckBox(self.timingGroup)
        self.ka2DelayCheck.setText(_fromUtf8(""))
        self.ka2DelayCheck.setObjectName(_fromUtf8("ka2DelayCheck"))
        self.gridLayout.addWidget(self.ka2DelayCheck, 4, 4, 1, 1)
        self.SaveRetrieveTitle = QtGui.QLabel(self.timingGroup)
        self.SaveRetrieveTitle.setObjectName(_fromUtf8("SaveRetrieveTitle"))
        self.gridLayout.addWidget(self.SaveRetrieveTitle, 0, 2, 1, 1)
        self.GPNLabel = QtGui.QLabel(self.timingGroup)
        self.GPNLabel.setObjectName(_fromUtf8("GPNLabel"))
        self.gridLayout.addWidget(self.GPNLabel, 6, 0, 1, 1)
        self.GunDelayLabel = QtGui.QLabel(self.timingGroup)
        self.GunDelayLabel.setObjectName(_fromUtf8("GunDelayLabel"))
        self.gridLayout.addWidget(self.GunDelayLabel, 2, 0, 1, 1)
        self.ka2DelayLabel = QtGui.QLabel(self.timingGroup)
        self.ka2DelayLabel.setObjectName(_fromUtf8("ka2DelayLabel"))
        self.gridLayout.addWidget(self.ka2DelayLabel, 4, 0, 1, 1)
        self.MBMWrite = QtGui.QCheckBox(self.timingGroup)
        self.MBMWrite.setObjectName(_fromUtf8("MBMWrite"))
        self.gridLayout.addWidget(self.MBMWrite, 1, 2, 1, 1)
        self.MBMCheck = QtGui.QCheckBox(self.timingGroup)
        self.MBMCheck.setText(_fromUtf8(""))
        self.MBMCheck.setObjectName(_fromUtf8("MBMCheck"))
        self.gridLayout.addWidget(self.MBMCheck, 1, 4, 1, 1)
        self.GPALabel = QtGui.QLabel(self.timingGroup)
        self.GPALabel.setObjectName(_fromUtf8("GPALabel"))
        self.gridLayout.addWidget(self.GPALabel, 7, 0, 1, 1)
        self.GPILabel = QtGui.QLabel(self.timingGroup)
        self.GPILabel.setObjectName(_fromUtf8("GPILabel"))
        self.gridLayout.addWidget(self.GPILabel, 5, 0, 1, 1)
        self.GunDelayCheck = QtGui.QCheckBox(self.timingGroup)
        self.GunDelayCheck.setText(_fromUtf8(""))
        self.GunDelayCheck.setObjectName(_fromUtf8("GunDelayCheck"))
        self.gridLayout.addWidget(self.GunDelayCheck, 2, 4, 1, 1)
        self.ka1DelayLabel = QtGui.QLabel(self.timingGroup)
        self.ka1DelayLabel.setObjectName(_fromUtf8("ka1DelayLabel"))
        self.gridLayout.addWidget(self.ka1DelayLabel, 3, 0, 1, 1)
        self.MBMRead = TaurusLed(self.timingGroup)
        self.MBMRead.setMinimumSize(QtCore.QSize(15, 15))
        self.MBMRead.setMaximumSize(QtCore.QSize(15, 15))
        self.MBMRead.setObjectName(_fromUtf8("MBMRead"))
        self.gridLayout.addWidget(self.MBMRead, 1, 1, 1, 1)
        self.GPIWrite = QtGui.QSpinBox(self.timingGroup)
        self.GPIWrite.setMinimum(6)
        self.GPIWrite.setMaximum(1054)
        self.GPIWrite.setSingleStep(2)
        self.GPIWrite.setObjectName(_fromUtf8("GPIWrite"))
        self.gridLayout.addWidget(self.GPIWrite, 5, 2, 1, 1)
        self.GPNCheck = QtGui.QCheckBox(self.timingGroup)
        self.GPNCheck.setText(_fromUtf8(""))
        self.GPNCheck.setObjectName(_fromUtf8("GPNCheck"))
        self.gridLayout.addWidget(self.GPNCheck, 6, 4, 1, 1)
        self.GPICheck = QtGui.QCheckBox(self.timingGroup)
        self.GPICheck.setText(_fromUtf8(""))
        self.GPICheck.setObjectName(_fromUtf8("GPICheck"))
        self.gridLayout.addWidget(self.GPICheck, 5, 4, 1, 1)
        self.GPACheck = QtGui.QCheckBox(self.timingGroup)
        self.GPACheck.setText(_fromUtf8(""))
        self.GPACheck.setObjectName(_fromUtf8("GPACheck"))
        self.gridLayout.addWidget(self.GPACheck, 7, 4, 1, 1)
        self.ka2DelayRead = TaurusLabel(self.timingGroup)
        self.ka2DelayRead.setObjectName(_fromUtf8("ka2DelayRead"))
        self.gridLayout.addWidget(self.ka2DelayRead, 4, 1, 1, 1)
        self.GunDelayRead = TaurusLabel(self.timingGroup)
        self.GunDelayRead.setObjectName(_fromUtf8("GunDelayRead"))
        self.gridLayout.addWidget(self.GunDelayRead, 2, 1, 1, 1)
        self.GPNRead = TaurusLabel(self.timingGroup)
        self.GPNRead.setObjectName(_fromUtf8("GPNRead"))
        self.gridLayout.addWidget(self.GPNRead, 6, 1, 1, 1)
        self.ka1DelayWrite = QtGui.QSpinBox(self.timingGroup)
        self.ka1DelayWrite.setMinimum(1)
        self.ka1DelayWrite.setMaximum(56)
        self.ka1DelayWrite.setObjectName(_fromUtf8("ka1DelayWrite"))
        self.gridLayout.addWidget(self.ka1DelayWrite, 3, 2, 1, 1)
        self.ka2DelayWrite = QtGui.QSpinBox(self.timingGroup)
        self.ka2DelayWrite.setMinimum(2720)
        self.ka2DelayWrite.setMaximum(4096)
        self.ka2DelayWrite.setSingleStep(32)
        self.ka2DelayWrite.setObjectName(_fromUtf8("ka2DelayWrite"))
        self.gridLayout.addWidget(self.ka2DelayWrite, 4, 2, 1, 1)
        self.GPAWrite = QtGui.QDoubleSpinBox(self.timingGroup)
        self.GPAWrite.setMinimum(-40.0)
        self.GPAWrite.setMaximum(0.0)
        self.GPAWrite.setSingleStep(0.1)
        self.GPAWrite.setObjectName(_fromUtf8("GPAWrite"))
        self.gridLayout.addWidget(self.GPAWrite, 7, 2, 1, 1)
        self.gridLayout_2.addWidget(self.timingGroup, 0, 0, 1, 1)

        self.retranslateUi(timingSnapshot)
        QtCore.QMetaObject.connectSlotsByName(timingSnapshot)

    def retranslateUi(self, timingSnapshot):
        timingSnapshot.setWindowTitle(QtGui.QApplication.translate("timingSnapshot", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.timingGroup.setTitle(QtGui.QApplication.translate("timingSnapshot", "Timing", None, QtGui.QApplication.UnicodeUTF8))
        self.MBMLabel.setText(QtGui.QApplication.translate("timingSnapshot", "Multi Bunch Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.PresentWriteTitle.setText(QtGui.QApplication.translate("timingSnapshot", "Present value", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveRetrieveTitle.setText(QtGui.QApplication.translate("timingSnapshot", "Save/Retrieve", None, QtGui.QApplication.UnicodeUTF8))
        self.GPNLabel.setText(QtGui.QApplication.translate("timingSnapshot", "Bunch number", None, QtGui.QApplication.UnicodeUTF8))
        self.GunDelayLabel.setText(QtGui.QApplication.translate("timingSnapshot", "Electron Gun Delay", None, QtGui.QApplication.UnicodeUTF8))
        self.ka2DelayLabel.setText(QtGui.QApplication.translate("timingSnapshot", "KA2 Delay", None, QtGui.QApplication.UnicodeUTF8))
        self.MBMWrite.setText(QtGui.QApplication.translate("timingSnapshot", "multi/single", None, QtGui.QApplication.UnicodeUTF8))
        self.GPALabel.setText(QtGui.QApplication.translate("timingSnapshot", "Pulses Attenuattion", None, QtGui.QApplication.UnicodeUTF8))
        self.GPILabel.setText(QtGui.QApplication.translate("timingSnapshot", "Bunch Interval/width", None, QtGui.QApplication.UnicodeUTF8))
        self.ka1DelayLabel.setText(QtGui.QApplication.translate("timingSnapshot", "KA1 Delay", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusLabel, TaurusLed
from taurus.qt.qtgui.container import TaurusGroupBox
from taurus.qt.qtgui.panel import TaurusWidget
