# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'snapshot_magnets.ui'
#
# Created: Wed Mar 12 08:37:45 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_magnetSnapshot(object):
    def setupUi(self, magnetSnapshot):
        magnetSnapshot.setObjectName(_fromUtf8("magnetSnapshot"))
        magnetSnapshot.resize(692, 689)
        self.gridLayout_2 = QtGui.QGridLayout(magnetSnapshot)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.magnetsGroup = TaurusGroupBox(magnetSnapshot)
        self.magnetsGroup.setObjectName(_fromUtf8("magnetsGroup"))
        self.gridLayout = QtGui.QGridLayout(self.magnetsGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sl1VValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl1VValue.setObjectName(_fromUtf8("sl1VValue"))
        self.gridLayout.addWidget(self.sl1VValue, 2, 2, 1, 1)
        self.bc1VLabel = QtGui.QLabel(self.magnetsGroup)
        self.bc1VLabel.setObjectName(_fromUtf8("bc1VLabel"))
        self.gridLayout.addWidget(self.bc1VLabel, 18, 0, 1, 1)
        self.as1HReading = TaurusLabel(self.magnetsGroup)
        self.as1HReading.setObjectName(_fromUtf8("as1HReading"))
        self.gridLayout.addWidget(self.as1HReading, 5, 9, 1, 1)
        self.as1VLabel = QtGui.QLabel(self.magnetsGroup)
        self.as1VLabel.setObjectName(_fromUtf8("as1VLabel"))
        self.gridLayout.addWidget(self.as1VLabel, 6, 7, 1, 1)
        self.qt1VLabel = QtGui.QLabel(self.magnetsGroup)
        self.qt1VLabel.setObjectName(_fromUtf8("qt1VLabel"))
        self.gridLayout.addWidget(self.qt1VLabel, 10, 7, 1, 1)
        self.glVCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.glVCheck.setText(_fromUtf8(""))
        self.glVCheck.setObjectName(_fromUtf8("glVCheck"))
        self.gridLayout.addWidget(self.glVCheck, 2, 12, 1, 1)
        self.qtSwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.qtSwitchLabel.setObjectName(_fromUtf8("qtSwitchLabel"))
        self.gridLayout.addWidget(self.qtSwitchLabel, 13, 7, 1, 1)
        self.as1HValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.as1HValue.setObjectName(_fromUtf8("as1HValue"))
        self.gridLayout.addWidget(self.as1HValue, 5, 10, 1, 1)
        self.as1HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.as1HCheck.setText(_fromUtf8(""))
        self.as1HCheck.setObjectName(_fromUtf8("as1HCheck"))
        self.gridLayout.addWidget(self.as1HCheck, 5, 12, 1, 1)
        self.glVLabel = QtGui.QLabel(self.magnetsGroup)
        self.glVLabel.setObjectName(_fromUtf8("glVLabel"))
        self.gridLayout.addWidget(self.glVLabel, 2, 7, 1, 1)
        self.glFReading = TaurusLabel(self.magnetsGroup)
        self.glFReading.setObjectName(_fromUtf8("glFReading"))
        self.gridLayout.addWidget(self.glFReading, 3, 9, 1, 1)
        self.qt1FValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.qt1FValue.setObjectName(_fromUtf8("qt1FValue"))
        self.gridLayout.addWidget(self.qt1FValue, 11, 10, 1, 1)
        self.qtSwitchValue = QtGui.QCheckBox(self.magnetsGroup)
        self.qtSwitchValue.setObjectName(_fromUtf8("qtSwitchValue"))
        self.gridLayout.addWidget(self.qtSwitchValue, 13, 10, 1, 1)
        self.as2FValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.as2FValue.setObjectName(_fromUtf8("as2FValue"))
        self.gridLayout.addWidget(self.as2FValue, 16, 10, 1, 1)
        self.as1VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.as1VCheck.setText(_fromUtf8(""))
        self.as1VCheck.setObjectName(_fromUtf8("as1VCheck"))
        self.gridLayout.addWidget(self.as1VCheck, 6, 12, 1, 1)
        self.qt1FCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.qt1FCheck.setText(_fromUtf8(""))
        self.qt1FCheck.setObjectName(_fromUtf8("qt1FCheck"))
        self.gridLayout.addWidget(self.qt1FCheck, 11, 12, 1, 1)
        self.as2SwitchValue = QtGui.QCheckBox(self.magnetsGroup)
        self.as2SwitchValue.setObjectName(_fromUtf8("as2SwitchValue"))
        self.gridLayout.addWidget(self.as2SwitchValue, 17, 10, 1, 1)
        self.qt1HReading = TaurusLabel(self.magnetsGroup)
        self.qt1HReading.setObjectName(_fromUtf8("qt1HReading"))
        self.gridLayout.addWidget(self.qt1HReading, 9, 9, 1, 1)
        self.qt1FReading = TaurusLabel(self.magnetsGroup)
        self.qt1FReading.setObjectName(_fromUtf8("qt1FReading"))
        self.gridLayout.addWidget(self.qt1FReading, 11, 9, 1, 1)
        self.qt2FReading = TaurusLabel(self.magnetsGroup)
        self.qt2FReading.setObjectName(_fromUtf8("qt2FReading"))
        self.gridLayout.addWidget(self.qt2FReading, 12, 9, 1, 1)
        self.as2SwitchReading = TaurusLed(self.magnetsGroup)
        self.as2SwitchReading.setMinimumSize(QtCore.QSize(15, 15))
        self.as2SwitchReading.setMaximumSize(QtCore.QSize(15, 15))
        self.as2SwitchReading.setObjectName(_fromUtf8("as2SwitchReading"))
        self.gridLayout.addWidget(self.as2SwitchReading, 17, 9, 1, 1)
        self.as2FReading = TaurusLabel(self.magnetsGroup)
        self.as2FReading.setObjectName(_fromUtf8("as2FReading"))
        self.gridLayout.addWidget(self.as2FReading, 16, 9, 1, 1)
        self.as1VValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.as1VValue.setObjectName(_fromUtf8("as1VValue"))
        self.gridLayout.addWidget(self.as1VValue, 6, 10, 1, 1)
        self.as1FValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.as1FValue.setObjectName(_fromUtf8("as1FValue"))
        self.gridLayout.addWidget(self.as1FValue, 7, 10, 1, 1)
        self.qtSwitchReading = TaurusLed(self.magnetsGroup)
        self.qtSwitchReading.setMinimumSize(QtCore.QSize(15, 15))
        self.qtSwitchReading.setMaximumSize(QtCore.QSize(15, 15))
        self.qtSwitchReading.setObjectName(_fromUtf8("qtSwitchReading"))
        self.gridLayout.addWidget(self.qtSwitchReading, 13, 9, 1, 1)
        self.glHLabel = QtGui.QLabel(self.magnetsGroup)
        self.glHLabel.setObjectName(_fromUtf8("glHLabel"))
        self.gridLayout.addWidget(self.glHLabel, 1, 7, 1, 1)
        self.as1FLabel = QtGui.QLabel(self.magnetsGroup)
        self.as1FLabel.setObjectName(_fromUtf8("as1FLabel"))
        self.gridLayout.addWidget(self.as1FLabel, 7, 7, 1, 1)
        self.as2HLabel = QtGui.QLabel(self.magnetsGroup)
        self.as2HLabel.setObjectName(_fromUtf8("as2HLabel"))
        self.gridLayout.addWidget(self.as2HLabel, 14, 7, 1, 1)
        self.glSwitchReading = TaurusLed(self.magnetsGroup)
        self.glSwitchReading.setMinimumSize(QtCore.QSize(15, 15))
        self.glSwitchReading.setMaximumSize(QtCore.QSize(15, 15))
        self.glSwitchReading.setObjectName(_fromUtf8("glSwitchReading"))
        self.gridLayout.addWidget(self.glSwitchReading, 4, 9, 1, 1)
        self.glFValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.glFValue.setObjectName(_fromUtf8("glFValue"))
        self.gridLayout.addWidget(self.glFValue, 3, 10, 1, 1)
        self.glVReading = TaurusLabel(self.magnetsGroup)
        self.glVReading.setObjectName(_fromUtf8("glVReading"))
        self.gridLayout.addWidget(self.glVReading, 2, 9, 1, 1)
        self.glHValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.glHValue.setObjectName(_fromUtf8("glHValue"))
        self.gridLayout.addWidget(self.glHValue, 1, 10, 1, 1)
        self.as1HLabel = QtGui.QLabel(self.magnetsGroup)
        self.as1HLabel.setObjectName(_fromUtf8("as1HLabel"))
        self.gridLayout.addWidget(self.as1HLabel, 5, 7, 1, 1)
        self.glVValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.glVValue.setObjectName(_fromUtf8("glVValue"))
        self.gridLayout.addWidget(self.glVValue, 2, 10, 1, 1)
        self.glSwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.glSwitchCheck.setText(_fromUtf8(""))
        self.glSwitchCheck.setObjectName(_fromUtf8("glSwitchCheck"))
        self.gridLayout.addWidget(self.glSwitchCheck, 4, 12, 1, 1)
        self.glSwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.glSwitchLabel.setObjectName(_fromUtf8("glSwitchLabel"))
        self.gridLayout.addWidget(self.glSwitchLabel, 4, 7, 1, 1)
        self.glFLabel = QtGui.QLabel(self.magnetsGroup)
        self.glFLabel.setObjectName(_fromUtf8("glFLabel"))
        self.gridLayout.addWidget(self.glFLabel, 3, 7, 1, 1)
        self.glFCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.glFCheck.setText(_fromUtf8(""))
        self.glFCheck.setObjectName(_fromUtf8("glFCheck"))
        self.gridLayout.addWidget(self.glFCheck, 3, 12, 1, 1)
        self.qt1FLabel = QtGui.QLabel(self.magnetsGroup)
        self.qt1FLabel.setObjectName(_fromUtf8("qt1FLabel"))
        self.gridLayout.addWidget(self.qt1FLabel, 11, 7, 1, 1)
        self.line_1 = QtGui.QFrame(self.magnetsGroup)
        self.line_1.setFrameShape(QtGui.QFrame.VLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName(_fromUtf8("line_1"))
        self.gridLayout.addWidget(self.line_1, 1, 4, 24, 1)
        self.as2VReading = TaurusLabel(self.magnetsGroup)
        self.as2VReading.setObjectName(_fromUtf8("as2VReading"))
        self.gridLayout.addWidget(self.as2VReading, 15, 9, 1, 1)
        self.as1SwitchReading = TaurusLed(self.magnetsGroup)
        self.as1SwitchReading.setMinimumSize(QtCore.QSize(15, 15))
        self.as1SwitchReading.setMaximumSize(QtCore.QSize(15, 15))
        self.as1SwitchReading.setObjectName(_fromUtf8("as1SwitchReading"))
        self.gridLayout.addWidget(self.as1SwitchReading, 8, 9, 1, 1)
        self.as2FLabel = QtGui.QLabel(self.magnetsGroup)
        self.as2FLabel.setObjectName(_fromUtf8("as2FLabel"))
        self.gridLayout.addWidget(self.as2FLabel, 16, 7, 1, 1)
        self.as2SwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.as2SwitchLabel.setObjectName(_fromUtf8("as2SwitchLabel"))
        self.gridLayout.addWidget(self.as2SwitchLabel, 17, 7, 1, 1)
        self.qt2FLabel = QtGui.QLabel(self.magnetsGroup)
        self.qt2FLabel.setObjectName(_fromUtf8("qt2FLabel"))
        self.gridLayout.addWidget(self.qt2FLabel, 12, 7, 1, 1)
        self.as2VLabel = QtGui.QLabel(self.magnetsGroup)
        self.as2VLabel.setObjectName(_fromUtf8("as2VLabel"))
        self.gridLayout.addWidget(self.as2VLabel, 15, 7, 1, 1)
        self.as1FReading = TaurusLabel(self.magnetsGroup)
        self.as1FReading.setObjectName(_fromUtf8("as1FReading"))
        self.gridLayout.addWidget(self.as1FReading, 7, 9, 1, 1)
        self.qt1HValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.qt1HValue.setObjectName(_fromUtf8("qt1HValue"))
        self.gridLayout.addWidget(self.qt1HValue, 9, 10, 1, 1)
        self.as1SwitchValue = QtGui.QCheckBox(self.magnetsGroup)
        self.as1SwitchValue.setObjectName(_fromUtf8("as1SwitchValue"))
        self.gridLayout.addWidget(self.as1SwitchValue, 8, 10, 1, 1)
        self.as2HValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.as2HValue.setObjectName(_fromUtf8("as2HValue"))
        self.gridLayout.addWidget(self.as2HValue, 14, 10, 1, 1)
        self.as2HReading = TaurusLabel(self.magnetsGroup)
        self.as2HReading.setObjectName(_fromUtf8("as2HReading"))
        self.gridLayout.addWidget(self.as2HReading, 14, 9, 1, 1)
        self.as1VReading = TaurusLabel(self.magnetsGroup)
        self.as1VReading.setObjectName(_fromUtf8("as1VReading"))
        self.gridLayout.addWidget(self.as1VReading, 6, 9, 1, 1)
        self.sl1HValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl1HValue.setObjectName(_fromUtf8("sl1HValue"))
        self.gridLayout.addWidget(self.sl1HValue, 1, 2, 1, 1)
        self.bc1VReading = TaurusLabel(self.magnetsGroup)
        self.bc1VReading.setObjectName(_fromUtf8("bc1VReading"))
        self.gridLayout.addWidget(self.bc1VReading, 18, 1, 1, 1)
        self.bc1FLabel = QtGui.QLabel(self.magnetsGroup)
        self.bc1FLabel.setObjectName(_fromUtf8("bc1FLabel"))
        self.gridLayout.addWidget(self.bc1FLabel, 19, 0, 1, 1)
        self.bc2HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.bc2HCheck.setText(_fromUtf8(""))
        self.bc2HCheck.setObjectName(_fromUtf8("bc2HCheck"))
        self.gridLayout.addWidget(self.bc2HCheck, 21, 5, 1, 1)
        self.bc1FCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.bc1FCheck.setText(_fromUtf8(""))
        self.bc1FCheck.setObjectName(_fromUtf8("bc1FCheck"))
        self.gridLayout.addWidget(self.bc1FCheck, 19, 5, 1, 1)
        self.bc2SwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.bc2SwitchCheck.setText(_fromUtf8(""))
        self.bc2SwitchCheck.setObjectName(_fromUtf8("bc2SwitchCheck"))
        self.gridLayout.addWidget(self.bc2SwitchCheck, 24, 5, 1, 1)
        self.sl3SwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl3SwitchLabel.setObjectName(_fromUtf8("sl3SwitchLabel"))
        self.gridLayout.addWidget(self.sl3SwitchLabel, 12, 0, 1, 1)
        self.sl3FLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl3FLabel.setObjectName(_fromUtf8("sl3FLabel"))
        self.gridLayout.addWidget(self.sl3FLabel, 11, 0, 1, 1)
        self.bc2SwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.bc2SwitchLabel.setObjectName(_fromUtf8("bc2SwitchLabel"))
        self.gridLayout.addWidget(self.bc2SwitchLabel, 24, 0, 1, 1)
        self.sl4FReading = TaurusLabel(self.magnetsGroup)
        self.sl4FReading.setObjectName(_fromUtf8("sl4FReading"))
        self.gridLayout.addWidget(self.sl4FReading, 15, 1, 1, 1)
        self.sl3FReading = TaurusLabel(self.magnetsGroup)
        self.sl3FReading.setObjectName(_fromUtf8("sl3FReading"))
        self.gridLayout.addWidget(self.sl3FReading, 11, 1, 1, 1)
        self.sl3SwitchReading = TaurusLed(self.magnetsGroup)
        self.sl3SwitchReading.setMinimumSize(QtCore.QSize(15, 15))
        self.sl3SwitchReading.setMaximumSize(QtCore.QSize(15, 15))
        self.sl3SwitchReading.setObjectName(_fromUtf8("sl3SwitchReading"))
        self.gridLayout.addWidget(self.sl3SwitchReading, 12, 1, 1, 1)
        self.sl3Vvalue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl3Vvalue.setObjectName(_fromUtf8("sl3Vvalue"))
        self.gridLayout.addWidget(self.sl3Vvalue, 10, 2, 1, 1)
        self.sl2VReading = TaurusLabel(self.magnetsGroup)
        self.sl2VReading.setObjectName(_fromUtf8("sl2VReading"))
        self.gridLayout.addWidget(self.sl2VReading, 6, 1, 1, 1)
        self.sl1VReading = TaurusLabel(self.magnetsGroup)
        self.sl1VReading.setObjectName(_fromUtf8("sl1VReading"))
        self.gridLayout.addWidget(self.sl1VReading, 2, 1, 1, 1)
        self.sl1FLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl1FLabel.setObjectName(_fromUtf8("sl1FLabel"))
        self.gridLayout.addWidget(self.sl1FLabel, 3, 0, 1, 1)
        self.sl2HReading = TaurusLabel(self.magnetsGroup)
        self.sl2HReading.setObjectName(_fromUtf8("sl2HReading"))
        self.gridLayout.addWidget(self.sl2HReading, 5, 1, 1, 1)
        self.sl2FReading = TaurusLabel(self.magnetsGroup)
        self.sl2FReading.setObjectName(_fromUtf8("sl2FReading"))
        self.gridLayout.addWidget(self.sl2FReading, 7, 1, 1, 1)
        self.sl3HLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl3HLabel.setObjectName(_fromUtf8("sl3HLabel"))
        self.gridLayout.addWidget(self.sl3HLabel, 9, 0, 1, 1)
        self.PresentValueTitle = QtGui.QLabel(self.magnetsGroup)
        self.PresentValueTitle.setObjectName(_fromUtf8("PresentValueTitle"))
        self.gridLayout.addWidget(self.PresentValueTitle, 0, 1, 1, 1)
        self.sl3VReading = TaurusLabel(self.magnetsGroup)
        self.sl3VReading.setObjectName(_fromUtf8("sl3VReading"))
        self.gridLayout.addWidget(self.sl3VReading, 10, 1, 1, 1)
        self.bc2FValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.bc2FValue.setObjectName(_fromUtf8("bc2FValue"))
        self.gridLayout.addWidget(self.bc2FValue, 23, 2, 1, 1)
        self.bc2VLabel = QtGui.QLabel(self.magnetsGroup)
        self.bc2VLabel.setObjectName(_fromUtf8("bc2VLabel"))
        self.gridLayout.addWidget(self.bc2VLabel, 22, 0, 1, 1)
        self.sl1HLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl1HLabel.setObjectName(_fromUtf8("sl1HLabel"))
        self.gridLayout.addWidget(self.sl1HLabel, 1, 0, 1, 1)
        self.sl2VValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl2VValue.setObjectName(_fromUtf8("sl2VValue"))
        self.gridLayout.addWidget(self.sl2VValue, 6, 2, 1, 1)
        self.sl2SwitchReading = TaurusLed(self.magnetsGroup)
        self.sl2SwitchReading.setMinimumSize(QtCore.QSize(15, 15))
        self.sl2SwitchReading.setMaximumSize(QtCore.QSize(15, 15))
        self.sl2SwitchReading.setObjectName(_fromUtf8("sl2SwitchReading"))
        self.gridLayout.addWidget(self.sl2SwitchReading, 8, 1, 1, 1)
        self.sl2HLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl2HLabel.setObjectName(_fromUtf8("sl2HLabel"))
        self.gridLayout.addWidget(self.sl2HLabel, 5, 0, 1, 1)
        self.sl3HValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl3HValue.setObjectName(_fromUtf8("sl3HValue"))
        self.gridLayout.addWidget(self.sl3HValue, 9, 2, 1, 1)
        self.sl4VReading = TaurusLabel(self.magnetsGroup)
        self.sl4VReading.setObjectName(_fromUtf8("sl4VReading"))
        self.gridLayout.addWidget(self.sl4VReading, 14, 1, 1, 1)
        self.sl1FValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl1FValue.setObjectName(_fromUtf8("sl1FValue"))
        self.gridLayout.addWidget(self.sl1FValue, 3, 2, 1, 1)
        self.sl1HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl1HCheck.setText(_fromUtf8(""))
        self.sl1HCheck.setObjectName(_fromUtf8("sl1HCheck"))
        self.gridLayout.addWidget(self.sl1HCheck, 1, 5, 1, 1)
        self.sl4SwitchValue = QtGui.QCheckBox(self.magnetsGroup)
        self.sl4SwitchValue.setObjectName(_fromUtf8("sl4SwitchValue"))
        self.gridLayout.addWidget(self.sl4SwitchValue, 16, 2, 1, 1)
        self.sl1HReading = TaurusLabel(self.magnetsGroup)
        self.sl1HReading.setObjectName(_fromUtf8("sl1HReading"))
        self.gridLayout.addWidget(self.sl1HReading, 1, 1, 1, 1)
        self.sl1SwitchValue = QtGui.QCheckBox(self.magnetsGroup)
        self.sl1SwitchValue.setObjectName(_fromUtf8("sl1SwitchValue"))
        self.gridLayout.addWidget(self.sl1SwitchValue, 4, 2, 1, 1)
        self.sl3FValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl3FValue.setObjectName(_fromUtf8("sl3FValue"))
        self.gridLayout.addWidget(self.sl3FValue, 11, 2, 1, 1)
        self.sl4HLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl4HLabel.setObjectName(_fromUtf8("sl4HLabel"))
        self.gridLayout.addWidget(self.sl4HLabel, 13, 0, 1, 1)
        self.sl2FLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl2FLabel.setObjectName(_fromUtf8("sl2FLabel"))
        self.gridLayout.addWidget(self.sl2FLabel, 7, 0, 1, 1)
        self.sl3VLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl3VLabel.setObjectName(_fromUtf8("sl3VLabel"))
        self.gridLayout.addWidget(self.sl3VLabel, 10, 0, 1, 1)
        self.bc1HLabel = QtGui.QLabel(self.magnetsGroup)
        self.bc1HLabel.setObjectName(_fromUtf8("bc1HLabel"))
        self.gridLayout.addWidget(self.bc1HLabel, 17, 0, 1, 1)
        self.sl4FLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl4FLabel.setObjectName(_fromUtf8("sl4FLabel"))
        self.gridLayout.addWidget(self.sl4FLabel, 15, 0, 1, 1)
        self.SaveRetrieveTitle = QtGui.QLabel(self.magnetsGroup)
        self.SaveRetrieveTitle.setObjectName(_fromUtf8("SaveRetrieveTitle"))
        self.gridLayout.addWidget(self.SaveRetrieveTitle, 0, 2, 1, 1)
        self.sl2FValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl2FValue.setObjectName(_fromUtf8("sl2FValue"))
        self.gridLayout.addWidget(self.sl2FValue, 7, 2, 1, 1)
        self.sl1SwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl1SwitchLabel.setObjectName(_fromUtf8("sl1SwitchLabel"))
        self.gridLayout.addWidget(self.sl1SwitchLabel, 4, 0, 1, 1)
        self.sl4FValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl4FValue.setObjectName(_fromUtf8("sl4FValue"))
        self.gridLayout.addWidget(self.sl4FValue, 15, 2, 1, 1)
        self.sl4VValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl4VValue.setObjectName(_fromUtf8("sl4VValue"))
        self.gridLayout.addWidget(self.sl4VValue, 14, 2, 1, 1)
        self.bc1FValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.bc1FValue.setObjectName(_fromUtf8("bc1FValue"))
        self.gridLayout.addWidget(self.bc1FValue, 19, 2, 1, 1)
        self.bc1HValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.bc1HValue.setObjectName(_fromUtf8("bc1HValue"))
        self.gridLayout.addWidget(self.bc1HValue, 17, 2, 1, 1)
        self.sl1FReading = TaurusLabel(self.magnetsGroup)
        self.sl1FReading.setObjectName(_fromUtf8("sl1FReading"))
        self.gridLayout.addWidget(self.sl1FReading, 3, 1, 1, 1)
        self.bc1SwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.bc1SwitchLabel.setObjectName(_fromUtf8("bc1SwitchLabel"))
        self.gridLayout.addWidget(self.bc1SwitchLabel, 20, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 42, 1, 1, 1)
        self.bc1SwitchValue = QtGui.QCheckBox(self.magnetsGroup)
        self.bc1SwitchValue.setObjectName(_fromUtf8("bc1SwitchValue"))
        self.gridLayout.addWidget(self.bc1SwitchValue, 20, 2, 1, 1)
        self.sl2VLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl2VLabel.setObjectName(_fromUtf8("sl2VLabel"))
        self.gridLayout.addWidget(self.sl2VLabel, 6, 0, 1, 1)
        self.sl2SwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl2SwitchLabel.setObjectName(_fromUtf8("sl2SwitchLabel"))
        self.gridLayout.addWidget(self.sl2SwitchLabel, 8, 0, 1, 1)
        self.sl4HReading = TaurusLabel(self.magnetsGroup)
        self.sl4HReading.setObjectName(_fromUtf8("sl4HReading"))
        self.gridLayout.addWidget(self.sl4HReading, 13, 1, 1, 1)
        self.bc1SwitchReading = TaurusLed(self.magnetsGroup)
        self.bc1SwitchReading.setMinimumSize(QtCore.QSize(15, 15))
        self.bc1SwitchReading.setMaximumSize(QtCore.QSize(15, 15))
        self.bc1SwitchReading.setObjectName(_fromUtf8("bc1SwitchReading"))
        self.gridLayout.addWidget(self.bc1SwitchReading, 20, 1, 1, 1)
        self.bc1FReading = TaurusLabel(self.magnetsGroup)
        self.bc1FReading.setObjectName(_fromUtf8("bc1FReading"))
        self.gridLayout.addWidget(self.bc1FReading, 19, 1, 1, 1)
        self.bc2FReading = TaurusLabel(self.magnetsGroup)
        self.bc2FReading.setObjectName(_fromUtf8("bc2FReading"))
        self.gridLayout.addWidget(self.bc2FReading, 23, 1, 1, 1)
        self.bc2SwitchReading = TaurusLed(self.magnetsGroup)
        self.bc2SwitchReading.setMinimumSize(QtCore.QSize(15, 15))
        self.bc2SwitchReading.setMaximumSize(QtCore.QSize(15, 15))
        self.bc2SwitchReading.setObjectName(_fromUtf8("bc2SwitchReading"))
        self.gridLayout.addWidget(self.bc2SwitchReading, 24, 1, 1, 1)
        self.bc2VValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.bc2VValue.setObjectName(_fromUtf8("bc2VValue"))
        self.gridLayout.addWidget(self.bc2VValue, 22, 2, 1, 1)
        self.bc2HReading = TaurusLabel(self.magnetsGroup)
        self.bc2HReading.setObjectName(_fromUtf8("bc2HReading"))
        self.gridLayout.addWidget(self.bc2HReading, 21, 1, 1, 1)
        self.bc2VReading = TaurusLabel(self.magnetsGroup)
        self.bc2VReading.setObjectName(_fromUtf8("bc2VReading"))
        self.gridLayout.addWidget(self.bc2VReading, 22, 1, 1, 1)
        self.bc2HLabel = QtGui.QLabel(self.magnetsGroup)
        self.bc2HLabel.setObjectName(_fromUtf8("bc2HLabel"))
        self.gridLayout.addWidget(self.bc2HLabel, 21, 0, 1, 1)
        self.bc2FLabel = QtGui.QLabel(self.magnetsGroup)
        self.bc2FLabel.setObjectName(_fromUtf8("bc2FLabel"))
        self.gridLayout.addWidget(self.bc2FLabel, 23, 0, 1, 1)
        self.bc2SwitchValue = QtGui.QCheckBox(self.magnetsGroup)
        self.bc2SwitchValue.setObjectName(_fromUtf8("bc2SwitchValue"))
        self.gridLayout.addWidget(self.bc2SwitchValue, 24, 2, 1, 1)
        self.sl4SwitchReading = TaurusLed(self.magnetsGroup)
        self.sl4SwitchReading.setMinimumSize(QtCore.QSize(15, 15))
        self.sl4SwitchReading.setMaximumSize(QtCore.QSize(15, 15))
        self.sl4SwitchReading.setObjectName(_fromUtf8("sl4SwitchReading"))
        self.gridLayout.addWidget(self.sl4SwitchReading, 16, 1, 1, 1)
        self.sl3HReading = TaurusLabel(self.magnetsGroup)
        self.sl3HReading.setObjectName(_fromUtf8("sl3HReading"))
        self.gridLayout.addWidget(self.sl3HReading, 9, 1, 1, 1)
        self.sl1VLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl1VLabel.setObjectName(_fromUtf8("sl1VLabel"))
        self.gridLayout.addWidget(self.sl1VLabel, 2, 0, 1, 1)
        self.bc1VValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.bc1VValue.setObjectName(_fromUtf8("bc1VValue"))
        self.gridLayout.addWidget(self.bc1VValue, 18, 2, 1, 1)
        self.sl2SwitchValue = QtGui.QCheckBox(self.magnetsGroup)
        self.sl2SwitchValue.setObjectName(_fromUtf8("sl2SwitchValue"))
        self.gridLayout.addWidget(self.sl2SwitchValue, 8, 2, 1, 1)
        self.sl4HValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl4HValue.setObjectName(_fromUtf8("sl4HValue"))
        self.gridLayout.addWidget(self.sl4HValue, 13, 2, 1, 1)
        self.sl1SwitchReading = TaurusLed(self.magnetsGroup)
        self.sl1SwitchReading.setMinimumSize(QtCore.QSize(15, 15))
        self.sl1SwitchReading.setMaximumSize(QtCore.QSize(15, 15))
        self.sl1SwitchReading.setObjectName(_fromUtf8("sl1SwitchReading"))
        self.gridLayout.addWidget(self.sl1SwitchReading, 4, 1, 1, 1)
        self.sl3SwitchValue = QtGui.QCheckBox(self.magnetsGroup)
        self.sl3SwitchValue.setObjectName(_fromUtf8("sl3SwitchValue"))
        self.gridLayout.addWidget(self.sl3SwitchValue, 12, 2, 1, 1)
        self.sl4VLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl4VLabel.setObjectName(_fromUtf8("sl4VLabel"))
        self.gridLayout.addWidget(self.sl4VLabel, 14, 0, 1, 1)
        self.sl4SwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl4SwitchLabel.setObjectName(_fromUtf8("sl4SwitchLabel"))
        self.gridLayout.addWidget(self.sl4SwitchLabel, 16, 0, 1, 1)
        self.bc1HReading = TaurusLabel(self.magnetsGroup)
        self.bc1HReading.setObjectName(_fromUtf8("bc1HReading"))
        self.gridLayout.addWidget(self.bc1HReading, 17, 1, 1, 1)
        self.bc2HValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.bc2HValue.setObjectName(_fromUtf8("bc2HValue"))
        self.gridLayout.addWidget(self.bc2HValue, 21, 2, 1, 1)
        self.qt1HLabel = QtGui.QLabel(self.magnetsGroup)
        self.qt1HLabel.setObjectName(_fromUtf8("qt1HLabel"))
        self.gridLayout.addWidget(self.qt1HLabel, 9, 7, 1, 1)
        self.sl1VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl1VCheck.setText(_fromUtf8(""))
        self.sl1VCheck.setObjectName(_fromUtf8("sl1VCheck"))
        self.gridLayout.addWidget(self.sl1VCheck, 2, 5, 1, 1)
        self.sl2HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl2HCheck.setText(_fromUtf8(""))
        self.sl2HCheck.setObjectName(_fromUtf8("sl2HCheck"))
        self.gridLayout.addWidget(self.sl2HCheck, 5, 5, 1, 1)
        self.sl2FCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl2FCheck.setText(_fromUtf8(""))
        self.sl2FCheck.setObjectName(_fromUtf8("sl2FCheck"))
        self.gridLayout.addWidget(self.sl2FCheck, 7, 5, 1, 1)
        self.sl1FCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl1FCheck.setText(_fromUtf8(""))
        self.sl1FCheck.setObjectName(_fromUtf8("sl1FCheck"))
        self.gridLayout.addWidget(self.sl1FCheck, 3, 5, 1, 1)
        self.sl1SwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl1SwitchCheck.setText(_fromUtf8(""))
        self.sl1SwitchCheck.setObjectName(_fromUtf8("sl1SwitchCheck"))
        self.gridLayout.addWidget(self.sl1SwitchCheck, 4, 5, 1, 1)
        self.sl3HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl3HCheck.setText(_fromUtf8(""))
        self.sl3HCheck.setObjectName(_fromUtf8("sl3HCheck"))
        self.gridLayout.addWidget(self.sl3HCheck, 9, 5, 1, 1)
        self.sl2VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl2VCheck.setText(_fromUtf8(""))
        self.sl2VCheck.setObjectName(_fromUtf8("sl2VCheck"))
        self.gridLayout.addWidget(self.sl2VCheck, 6, 5, 1, 1)
        self.sl2SwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl2SwitchCheck.setText(_fromUtf8(""))
        self.sl2SwitchCheck.setObjectName(_fromUtf8("sl2SwitchCheck"))
        self.gridLayout.addWidget(self.sl2SwitchCheck, 8, 5, 1, 1)
        self.sl3VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl3VCheck.setText(_fromUtf8(""))
        self.sl3VCheck.setObjectName(_fromUtf8("sl3VCheck"))
        self.gridLayout.addWidget(self.sl3VCheck, 10, 5, 1, 1)
        self.sl3FCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl3FCheck.setText(_fromUtf8(""))
        self.sl3FCheck.setObjectName(_fromUtf8("sl3FCheck"))
        self.gridLayout.addWidget(self.sl3FCheck, 11, 5, 1, 1)
        self.sl3SwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl3SwitchCheck.setText(_fromUtf8(""))
        self.sl3SwitchCheck.setObjectName(_fromUtf8("sl3SwitchCheck"))
        self.gridLayout.addWidget(self.sl3SwitchCheck, 12, 5, 1, 1)
        self.sl4HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl4HCheck.setText(_fromUtf8(""))
        self.sl4HCheck.setObjectName(_fromUtf8("sl4HCheck"))
        self.gridLayout.addWidget(self.sl4HCheck, 13, 5, 1, 1)
        self.sl4VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl4VCheck.setText(_fromUtf8(""))
        self.sl4VCheck.setObjectName(_fromUtf8("sl4VCheck"))
        self.gridLayout.addWidget(self.sl4VCheck, 14, 5, 1, 1)
        self.sl4FCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl4FCheck.setText(_fromUtf8(""))
        self.sl4FCheck.setObjectName(_fromUtf8("sl4FCheck"))
        self.gridLayout.addWidget(self.sl4FCheck, 15, 5, 1, 1)
        self.sl4SwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl4SwitchCheck.setText(_fromUtf8(""))
        self.sl4SwitchCheck.setObjectName(_fromUtf8("sl4SwitchCheck"))
        self.gridLayout.addWidget(self.sl4SwitchCheck, 16, 5, 1, 1)
        self.bc1HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.bc1HCheck.setText(_fromUtf8(""))
        self.bc1HCheck.setObjectName(_fromUtf8("bc1HCheck"))
        self.gridLayout.addWidget(self.bc1HCheck, 17, 5, 1, 1)
        self.bc1VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.bc1VCheck.setText(_fromUtf8(""))
        self.bc1VCheck.setObjectName(_fromUtf8("bc1VCheck"))
        self.gridLayout.addWidget(self.bc1VCheck, 18, 5, 1, 1)
        self.bc1SwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.bc1SwitchCheck.setText(_fromUtf8(""))
        self.bc1SwitchCheck.setObjectName(_fromUtf8("bc1SwitchCheck"))
        self.gridLayout.addWidget(self.bc1SwitchCheck, 20, 5, 1, 1)
        self.bc2FCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.bc2FCheck.setText(_fromUtf8(""))
        self.bc2FCheck.setObjectName(_fromUtf8("bc2FCheck"))
        self.gridLayout.addWidget(self.bc2FCheck, 23, 5, 1, 1)
        self.as1SwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.as1SwitchLabel.setObjectName(_fromUtf8("as1SwitchLabel"))
        self.gridLayout.addWidget(self.as1SwitchLabel, 8, 7, 1, 1)
        self.bc2VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.bc2VCheck.setText(_fromUtf8(""))
        self.bc2VCheck.setObjectName(_fromUtf8("bc2VCheck"))
        self.gridLayout.addWidget(self.bc2VCheck, 22, 5, 1, 1)
        self.glSwitchValue = QtGui.QCheckBox(self.magnetsGroup)
        self.glSwitchValue.setObjectName(_fromUtf8("glSwitchValue"))
        self.gridLayout.addWidget(self.glSwitchValue, 4, 10, 1, 1)
        self.glHReading = TaurusLabel(self.magnetsGroup)
        self.glHReading.setObjectName(_fromUtf8("glHReading"))
        self.gridLayout.addWidget(self.glHReading, 1, 9, 1, 1)
        self.glHCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.glHCheck.setText(_fromUtf8(""))
        self.glHCheck.setObjectName(_fromUtf8("glHCheck"))
        self.gridLayout.addWidget(self.glHCheck, 1, 12, 1, 1)
        self.qt1VReading = TaurusLabel(self.magnetsGroup)
        self.qt1VReading.setObjectName(_fromUtf8("qt1VReading"))
        self.gridLayout.addWidget(self.qt1VReading, 10, 9, 1, 1)
        self.qt2FValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.qt2FValue.setObjectName(_fromUtf8("qt2FValue"))
        self.gridLayout.addWidget(self.qt2FValue, 12, 10, 1, 1)
        self.qt1VValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.qt1VValue.setObjectName(_fromUtf8("qt1VValue"))
        self.gridLayout.addWidget(self.qt1VValue, 10, 10, 1, 1)
        self.qt1VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.qt1VCheck.setText(_fromUtf8(""))
        self.qt1VCheck.setObjectName(_fromUtf8("qt1VCheck"))
        self.gridLayout.addWidget(self.qt1VCheck, 10, 12, 1, 1)
        self.as2Fcheck = QtGui.QCheckBox(self.magnetsGroup)
        self.as2Fcheck.setText(_fromUtf8(""))
        self.as2Fcheck.setObjectName(_fromUtf8("as2Fcheck"))
        self.gridLayout.addWidget(self.as2Fcheck, 16, 12, 1, 1)
        self.as2VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.as2VCheck.setText(_fromUtf8(""))
        self.as2VCheck.setObjectName(_fromUtf8("as2VCheck"))
        self.gridLayout.addWidget(self.as2VCheck, 15, 12, 1, 1)
        self.qt1HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.qt1HCheck.setText(_fromUtf8(""))
        self.qt1HCheck.setObjectName(_fromUtf8("qt1HCheck"))
        self.gridLayout.addWidget(self.qt1HCheck, 9, 12, 1, 1)
        self.as1FCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.as1FCheck.setText(_fromUtf8(""))
        self.as1FCheck.setObjectName(_fromUtf8("as1FCheck"))
        self.gridLayout.addWidget(self.as1FCheck, 7, 12, 1, 1)
        self.as1SwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.as1SwitchCheck.setText(_fromUtf8(""))
        self.as1SwitchCheck.setObjectName(_fromUtf8("as1SwitchCheck"))
        self.gridLayout.addWidget(self.as1SwitchCheck, 8, 12, 1, 1)
        self.qt2FCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.qt2FCheck.setText(_fromUtf8(""))
        self.qt2FCheck.setObjectName(_fromUtf8("qt2FCheck"))
        self.gridLayout.addWidget(self.qt2FCheck, 12, 12, 1, 1)
        self.qtSwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.qtSwitchCheck.setText(_fromUtf8(""))
        self.qtSwitchCheck.setObjectName(_fromUtf8("qtSwitchCheck"))
        self.gridLayout.addWidget(self.qtSwitchCheck, 13, 12, 1, 1)
        self.as2HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.as2HCheck.setText(_fromUtf8(""))
        self.as2HCheck.setObjectName(_fromUtf8("as2HCheck"))
        self.gridLayout.addWidget(self.as2HCheck, 14, 12, 1, 1)
        self.as2SwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.as2SwitchCheck.setText(_fromUtf8(""))
        self.as2SwitchCheck.setObjectName(_fromUtf8("as2SwitchCheck"))
        self.gridLayout.addWidget(self.as2SwitchCheck, 17, 12, 1, 1)
        self.ToApplyTitle = QtGui.QCheckBox(self.magnetsGroup)
        self.ToApplyTitle.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ToApplyTitle.setObjectName(_fromUtf8("ToApplyTitle"))
        self.gridLayout.addWidget(self.ToApplyTitle, 0, 12, 1, 1)
        self.sl2HValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl2HValue.setObjectName(_fromUtf8("sl2HValue"))
        self.gridLayout.addWidget(self.sl2HValue, 5, 2, 1, 1)
        self.SaveRetrieveTitle_2 = QtGui.QLabel(self.magnetsGroup)
        self.SaveRetrieveTitle_2.setObjectName(_fromUtf8("SaveRetrieveTitle_2"))
        self.gridLayout.addWidget(self.SaveRetrieveTitle_2, 0, 10, 1, 1)
        self.PresentValueTitle_2 = QtGui.QLabel(self.magnetsGroup)
        self.PresentValueTitle_2.setObjectName(_fromUtf8("PresentValueTitle_2"))
        self.gridLayout.addWidget(self.PresentValueTitle_2, 0, 9, 1, 1)
        self.as2VValue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.as2VValue.setObjectName(_fromUtf8("as2VValue"))
        self.gridLayout.addWidget(self.as2VValue, 15, 10, 1, 1)
        self.line_3 = QtGui.QFrame(self.magnetsGroup)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 1, 11, 17, 1)
        self.line_2 = QtGui.QFrame(self.magnetsGroup)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 0, 6, 25, 1)
        self.gridLayout_2.addWidget(self.magnetsGroup, 0, 0, 1, 1)

        self.retranslateUi(magnetSnapshot)
        QtCore.QMetaObject.connectSlotsByName(magnetSnapshot)

    def retranslateUi(self, magnetSnapshot):
        magnetSnapshot.setWindowTitle(QtGui.QApplication.translate("magnetSnapshot", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.magnetsGroup.setTitle(QtGui.QApplication.translate("magnetSnapshot", "Magnets", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "bc1 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.as1VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "AS1 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.qt1VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "QT1 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.qtSwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "QT Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.glVLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "gl Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.qtSwitchValue.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.as2SwitchValue.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.glHLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "gl Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.as1FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "AS1 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.as2HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "AS2 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.as1HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "AS1 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.glSwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "gl Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.glFLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "gl Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.qt1FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "QT1 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.as2FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "AS2 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.as2SwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "AS2 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.qt2FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "QT2 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.as2VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "AS2 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.as1SwitchValue.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "bc1 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.sl3SwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl3 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.sl3FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl3 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2SwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "bc2 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.sl1FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl1 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.sl3HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl3 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.PresentValueTitle.setText(QtGui.QApplication.translate("magnetSnapshot", "Present value", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "bc2 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.sl1HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl1 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.sl2HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl2 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.sl4SwitchValue.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.sl1SwitchValue.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.sl4HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl4 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.sl2FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl2 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.sl3VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl3 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "bc1 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.sl4FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl4 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveRetrieveTitle.setText(QtGui.QApplication.translate("magnetSnapshot", "Save/Retrieve", None, QtGui.QApplication.UnicodeUTF8))
        self.sl1SwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl1 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1SwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "bc1 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1SwitchValue.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.sl2VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl2 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.sl2SwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl2 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "bc2 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "bc2 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2SwitchValue.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.sl1VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl1 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.sl2SwitchValue.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.sl3SwitchValue.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.sl4VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl4 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.sl4SwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl4 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.qt1HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "QT1 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.as1SwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "AS1 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.glSwitchValue.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.ToApplyTitle.setText(QtGui.QApplication.translate("magnetSnapshot", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveRetrieveTitle_2.setText(QtGui.QApplication.translate("magnetSnapshot", "Save/Retrieve", None, QtGui.QApplication.UnicodeUTF8))
        self.PresentValueTitle_2.setText(QtGui.QApplication.translate("magnetSnapshot", "Present value", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusLabel, TaurusLed
from taurus.qt.qtgui.container import TaurusGroupBox
from taurus.qt.qtgui.panel import TaurusWidget
