# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/ui/snapshot_magnets.ui'
#
# Created: Wed Mar 12 14:27:49 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_magnetSnapshot(object):
    def setupUi(self, magnetSnapshot):
        magnetSnapshot.setObjectName(_fromUtf8("magnetSnapshot"))
        magnetSnapshot.resize(544, 597)
        font = QtGui.QFont()
        font.setPointSize(7)
        magnetSnapshot.setFont(font)
        self.gridLayout_2 = QtGui.QGridLayout(magnetSnapshot)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.magnetsGroup = TaurusGroupBox(magnetSnapshot)
        self.magnetsGroup.setObjectName(_fromUtf8("magnetsGroup"))
        self.gridLayout = QtGui.QGridLayout(self.magnetsGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.bc1FRead = TaurusLabel(self.magnetsGroup)
        self.bc1FRead.setObjectName(_fromUtf8("bc1FRead"))
        self.gridLayout.addWidget(self.bc1FRead, 19, 1, 1, 1)
        self.sl3VRead = TaurusLabel(self.magnetsGroup)
        self.sl3VRead.setObjectName(_fromUtf8("sl3VRead"))
        self.gridLayout.addWidget(self.sl3VRead, 10, 1, 1, 1)
        self.qtSwitchRead = TaurusLed(self.magnetsGroup)
        self.qtSwitchRead.setMinimumSize(QtCore.QSize(15, 15))
        self.qtSwitchRead.setMaximumSize(QtCore.QSize(15, 15))
        self.qtSwitchRead.setObjectName(_fromUtf8("qtSwitchRead"))
        self.gridLayout.addWidget(self.qtSwitchRead, 16, 9, 1, 1)
        self.glVCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.glVCheck.setText(_fromUtf8(""))
        self.glVCheck.setObjectName(_fromUtf8("glVCheck"))
        self.gridLayout.addWidget(self.glVCheck, 6, 12, 1, 1)
        self.sl3VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl3VCheck.setText(_fromUtf8(""))
        self.sl3VCheck.setObjectName(_fromUtf8("sl3VCheck"))
        self.gridLayout.addWidget(self.sl3VCheck, 10, 5, 1, 1)
        self.ToApplyTitle = QtGui.QCheckBox(self.magnetsGroup)
        self.ToApplyTitle.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ToApplyTitle.setObjectName(_fromUtf8("ToApplyTitle"))
        self.gridLayout.addWidget(self.ToApplyTitle, 0, 12, 1, 1)
        self.bc1HWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.bc1HWrite.setObjectName(_fromUtf8("bc1HWrite"))
        self.gridLayout.addWidget(self.bc1HWrite, 17, 2, 1, 1)
        self.SaveRetrieveTitle = QtGui.QLabel(self.magnetsGroup)
        self.SaveRetrieveTitle.setObjectName(_fromUtf8("SaveRetrieveTitle"))
        self.gridLayout.addWidget(self.SaveRetrieveTitle, 0, 2, 1, 1)
        self.bc1VRead = TaurusLabel(self.magnetsGroup)
        self.bc1VRead.setObjectName(_fromUtf8("bc1VRead"))
        self.gridLayout.addWidget(self.bc1VRead, 18, 1, 1, 1)
        self.qt1FRead = TaurusLabel(self.magnetsGroup)
        self.qt1FRead.setObjectName(_fromUtf8("qt1FRead"))
        self.gridLayout.addWidget(self.qt1FRead, 14, 9, 1, 1)
        self.glSwitchWrite = QtGui.QCheckBox(self.magnetsGroup)
        self.glSwitchWrite.setObjectName(_fromUtf8("glSwitchWrite"))
        self.gridLayout.addWidget(self.glSwitchWrite, 8, 10, 1, 1)
        self.sl3HWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl3HWrite.setObjectName(_fromUtf8("sl3HWrite"))
        self.gridLayout.addWidget(self.sl3HWrite, 9, 2, 1, 1)
        self.as2HWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.as2HWrite.setObjectName(_fromUtf8("as2HWrite"))
        self.gridLayout.addWidget(self.as2HWrite, 17, 10, 1, 1)
        self.as2SwitchRead = TaurusLed(self.magnetsGroup)
        self.as2SwitchRead.setMinimumSize(QtCore.QSize(15, 15))
        self.as2SwitchRead.setMaximumSize(QtCore.QSize(15, 15))
        self.as2SwitchRead.setObjectName(_fromUtf8("as2SwitchRead"))
        self.gridLayout.addWidget(self.as2SwitchRead, 19, 9, 1, 1)
        self.sl2SwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl2SwitchCheck.setText(_fromUtf8(""))
        self.sl2SwitchCheck.setObjectName(_fromUtf8("sl2SwitchCheck"))
        self.gridLayout.addWidget(self.sl2SwitchCheck, 8, 5, 1, 1)
        self.bc1VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.bc1VCheck.setText(_fromUtf8(""))
        self.bc1VCheck.setObjectName(_fromUtf8("bc1VCheck"))
        self.gridLayout.addWidget(self.bc1VCheck, 18, 5, 1, 1)
        self.sl1HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl1HCheck.setText(_fromUtf8(""))
        self.sl1HCheck.setObjectName(_fromUtf8("sl1HCheck"))
        self.gridLayout.addWidget(self.sl1HCheck, 1, 5, 1, 1)
        self.sl3Vvalue = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl3Vvalue.setObjectName(_fromUtf8("sl3Vvalue"))
        self.gridLayout.addWidget(self.sl3Vvalue, 10, 2, 1, 1)
        self.sl1SwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl1SwitchLabel.setObjectName(_fromUtf8("sl1SwitchLabel"))
        self.gridLayout.addWidget(self.sl1SwitchLabel, 4, 0, 1, 1)
        self.glFWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.glFWrite.setObjectName(_fromUtf8("glFWrite"))
        self.gridLayout.addWidget(self.glFWrite, 7, 10, 1, 1)
        self.as2SwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.as2SwitchLabel.setObjectName(_fromUtf8("as2SwitchLabel"))
        self.gridLayout.addWidget(self.as2SwitchLabel, 19, 7, 1, 1)
        self.sl2VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl2VCheck.setText(_fromUtf8(""))
        self.sl2VCheck.setObjectName(_fromUtf8("sl2VCheck"))
        self.gridLayout.addWidget(self.sl2VCheck, 6, 5, 1, 1)
        self.sl2HRead = TaurusLabel(self.magnetsGroup)
        self.sl2HRead.setObjectName(_fromUtf8("sl2HRead"))
        self.gridLayout.addWidget(self.sl2HRead, 5, 1, 1, 1)
        self.as2SwitchWrite = QtGui.QCheckBox(self.magnetsGroup)
        self.as2SwitchWrite.setObjectName(_fromUtf8("as2SwitchWrite"))
        self.gridLayout.addWidget(self.as2SwitchWrite, 19, 10, 1, 1)
        self.sl3HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl3HCheck.setText(_fromUtf8(""))
        self.sl3HCheck.setObjectName(_fromUtf8("sl3HCheck"))
        self.gridLayout.addWidget(self.sl3HCheck, 9, 5, 1, 1)
        self.sl4SwitchWrite = QtGui.QCheckBox(self.magnetsGroup)
        self.sl4SwitchWrite.setObjectName(_fromUtf8("sl4SwitchWrite"))
        self.gridLayout.addWidget(self.sl4SwitchWrite, 16, 2, 1, 1)
        self.glFCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.glFCheck.setText(_fromUtf8(""))
        self.glFCheck.setObjectName(_fromUtf8("glFCheck"))
        self.gridLayout.addWidget(self.glFCheck, 7, 12, 1, 1)
        self.sl3SwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl3SwitchLabel.setObjectName(_fromUtf8("sl3SwitchLabel"))
        self.gridLayout.addWidget(self.sl3SwitchLabel, 12, 0, 1, 1)
        self.bc1VLabel = QtGui.QLabel(self.magnetsGroup)
        self.bc1VLabel.setObjectName(_fromUtf8("bc1VLabel"))
        self.gridLayout.addWidget(self.bc1VLabel, 18, 0, 1, 1)
        self.as2HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.as2HCheck.setText(_fromUtf8(""))
        self.as2HCheck.setObjectName(_fromUtf8("as2HCheck"))
        self.gridLayout.addWidget(self.as2HCheck, 17, 12, 1, 1)
        self.bc1VWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.bc1VWrite.setObjectName(_fromUtf8("bc1VWrite"))
        self.gridLayout.addWidget(self.bc1VWrite, 18, 2, 1, 1)
        self.sl3FLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl3FLabel.setObjectName(_fromUtf8("sl3FLabel"))
        self.gridLayout.addWidget(self.sl3FLabel, 11, 0, 1, 1)
        self.sl2HWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl2HWrite.setObjectName(_fromUtf8("sl2HWrite"))
        self.gridLayout.addWidget(self.sl2HWrite, 5, 2, 1, 1)
        self.sl2VWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl2VWrite.setObjectName(_fromUtf8("sl2VWrite"))
        self.gridLayout.addWidget(self.sl2VWrite, 6, 2, 1, 1)
        self.sl4FRead = TaurusLabel(self.magnetsGroup)
        self.sl4FRead.setObjectName(_fromUtf8("sl4FRead"))
        self.gridLayout.addWidget(self.sl4FRead, 15, 1, 1, 1)
        self.sl1HRead = TaurusLabel(self.magnetsGroup)
        self.sl1HRead.setObjectName(_fromUtf8("sl1HRead"))
        self.gridLayout.addWidget(self.sl1HRead, 1, 1, 1, 1)
        self.bc1HLabel = QtGui.QLabel(self.magnetsGroup)
        self.bc1HLabel.setObjectName(_fromUtf8("bc1HLabel"))
        self.gridLayout.addWidget(self.bc1HLabel, 17, 0, 1, 1)
        self.bc1HRead = TaurusLabel(self.magnetsGroup)
        self.bc1HRead.setObjectName(_fromUtf8("bc1HRead"))
        self.gridLayout.addWidget(self.bc1HRead, 17, 1, 1, 1)
        self.sl1FLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl1FLabel.setObjectName(_fromUtf8("sl1FLabel"))
        self.gridLayout.addWidget(self.sl1FLabel, 3, 0, 1, 1)
        self.PresentWriteTitle = QtGui.QLabel(self.magnetsGroup)
        self.PresentWriteTitle.setObjectName(_fromUtf8("PresentWriteTitle"))
        self.gridLayout.addWidget(self.PresentWriteTitle, 0, 1, 1, 1)
        self.sl1SwitchWrite = QtGui.QCheckBox(self.magnetsGroup)
        self.sl1SwitchWrite.setObjectName(_fromUtf8("sl1SwitchWrite"))
        self.gridLayout.addWidget(self.sl1SwitchWrite, 4, 2, 1, 1)
        self.sl2FRead = TaurusLabel(self.magnetsGroup)
        self.sl2FRead.setObjectName(_fromUtf8("sl2FRead"))
        self.gridLayout.addWidget(self.sl2FRead, 7, 1, 1, 1)
        self.bc1SwitchWrite = QtGui.QCheckBox(self.magnetsGroup)
        self.bc1SwitchWrite.setObjectName(_fromUtf8("bc1SwitchWrite"))
        self.gridLayout.addWidget(self.bc1SwitchWrite, 20, 2, 1, 1)
        self.sl4SwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl4SwitchLabel.setObjectName(_fromUtf8("sl4SwitchLabel"))
        self.gridLayout.addWidget(self.sl4SwitchLabel, 16, 0, 1, 1)
        self.sl2SwitchWrite = QtGui.QCheckBox(self.magnetsGroup)
        self.sl2SwitchWrite.setObjectName(_fromUtf8("sl2SwitchWrite"))
        self.gridLayout.addWidget(self.sl2SwitchWrite, 8, 2, 1, 1)
        self.qt1VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.qt1VCheck.setText(_fromUtf8(""))
        self.qt1VCheck.setObjectName(_fromUtf8("qt1VCheck"))
        self.gridLayout.addWidget(self.qt1VCheck, 13, 12, 1, 1)
        self.sl2SwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl2SwitchLabel.setObjectName(_fromUtf8("sl2SwitchLabel"))
        self.gridLayout.addWidget(self.sl2SwitchLabel, 8, 0, 1, 1)
        self.bc1SwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.bc1SwitchLabel.setObjectName(_fromUtf8("bc1SwitchLabel"))
        self.gridLayout.addWidget(self.bc1SwitchLabel, 20, 0, 1, 1)
        self.sl4HRead = TaurusLabel(self.magnetsGroup)
        self.sl4HRead.setObjectName(_fromUtf8("sl4HRead"))
        self.gridLayout.addWidget(self.sl4HRead, 13, 1, 1, 1)
        self.as2VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.as2VCheck.setText(_fromUtf8(""))
        self.as2VCheck.setObjectName(_fromUtf8("as2VCheck"))
        self.gridLayout.addWidget(self.as2VCheck, 18, 12, 1, 1)
        self.qt1FWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.qt1FWrite.setObjectName(_fromUtf8("qt1FWrite"))
        self.gridLayout.addWidget(self.qt1FWrite, 14, 10, 1, 1)
        self.sl4VRead = TaurusLabel(self.magnetsGroup)
        self.sl4VRead.setObjectName(_fromUtf8("sl4VRead"))
        self.gridLayout.addWidget(self.sl4VRead, 14, 1, 1, 1)
        self.glHRead = TaurusLabel(self.magnetsGroup)
        self.glHRead.setObjectName(_fromUtf8("glHRead"))
        self.gridLayout.addWidget(self.glHRead, 5, 9, 1, 1)
        self.qt2FCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.qt2FCheck.setText(_fromUtf8(""))
        self.qt2FCheck.setObjectName(_fromUtf8("qt2FCheck"))
        self.gridLayout.addWidget(self.qt2FCheck, 15, 12, 1, 1)
        self.sl1VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl1VCheck.setText(_fromUtf8(""))
        self.sl1VCheck.setObjectName(_fromUtf8("sl1VCheck"))
        self.gridLayout.addWidget(self.sl1VCheck, 2, 5, 1, 1)
        self.sl3SwitchRead = TaurusLed(self.magnetsGroup)
        self.sl3SwitchRead.setMinimumSize(QtCore.QSize(15, 15))
        self.sl3SwitchRead.setMaximumSize(QtCore.QSize(15, 15))
        self.sl3SwitchRead.setObjectName(_fromUtf8("sl3SwitchRead"))
        self.gridLayout.addWidget(self.sl3SwitchRead, 12, 1, 1, 1)
        self.SaveRetrieveTitle_2 = QtGui.QLabel(self.magnetsGroup)
        self.SaveRetrieveTitle_2.setObjectName(_fromUtf8("SaveRetrieveTitle_2"))
        self.gridLayout.addWidget(self.SaveRetrieveTitle_2, 0, 10, 1, 1)
        self.qtSwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.qtSwitchCheck.setText(_fromUtf8(""))
        self.qtSwitchCheck.setObjectName(_fromUtf8("qtSwitchCheck"))
        self.gridLayout.addWidget(self.qtSwitchCheck, 16, 12, 1, 1)
        self.sl4VWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl4VWrite.setObjectName(_fromUtf8("sl4VWrite"))
        self.gridLayout.addWidget(self.sl4VWrite, 14, 2, 1, 1)
        self.as1HRead = TaurusLabel(self.magnetsGroup)
        self.as1HRead.setObjectName(_fromUtf8("as1HRead"))
        self.gridLayout.addWidget(self.as1HRead, 9, 9, 1, 1)
        self.bc1SwitchRead = TaurusLed(self.magnetsGroup)
        self.bc1SwitchRead.setMinimumSize(QtCore.QSize(15, 15))
        self.bc1SwitchRead.setMaximumSize(QtCore.QSize(15, 15))
        self.bc1SwitchRead.setObjectName(_fromUtf8("bc1SwitchRead"))
        self.gridLayout.addWidget(self.bc1SwitchRead, 20, 1, 1, 1)
        self.qt2FRead = TaurusLabel(self.magnetsGroup)
        self.qt2FRead.setObjectName(_fromUtf8("qt2FRead"))
        self.gridLayout.addWidget(self.qt2FRead, 15, 9, 1, 1)
        self.sl2HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl2HCheck.setText(_fromUtf8(""))
        self.sl2HCheck.setObjectName(_fromUtf8("sl2HCheck"))
        self.gridLayout.addWidget(self.sl2HCheck, 5, 5, 1, 1)
        self.sl2HLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl2HLabel.setObjectName(_fromUtf8("sl2HLabel"))
        self.gridLayout.addWidget(self.sl2HLabel, 5, 0, 1, 1)
        self.sl3HLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl3HLabel.setObjectName(_fromUtf8("sl3HLabel"))
        self.gridLayout.addWidget(self.sl3HLabel, 9, 0, 1, 1)
        self.sl2VLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl2VLabel.setObjectName(_fromUtf8("sl2VLabel"))
        self.gridLayout.addWidget(self.sl2VLabel, 6, 0, 1, 1)
        self.qt2FWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.qt2FWrite.setObjectName(_fromUtf8("qt2FWrite"))
        self.gridLayout.addWidget(self.qt2FWrite, 15, 10, 1, 1)
        self.sl4FLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl4FLabel.setObjectName(_fromUtf8("sl4FLabel"))
        self.gridLayout.addWidget(self.sl4FLabel, 15, 0, 1, 1)
        self.glVWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.glVWrite.setObjectName(_fromUtf8("glVWrite"))
        self.gridLayout.addWidget(self.glVWrite, 6, 10, 1, 1)
        self.as1VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.as1VCheck.setText(_fromUtf8(""))
        self.as1VCheck.setObjectName(_fromUtf8("as1VCheck"))
        self.gridLayout.addWidget(self.as1VCheck, 10, 12, 1, 1)
        self.bc1FWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.bc1FWrite.setObjectName(_fromUtf8("bc1FWrite"))
        self.gridLayout.addWidget(self.bc1FWrite, 19, 2, 1, 1)
        self.sl2SwitchRead = TaurusLed(self.magnetsGroup)
        self.sl2SwitchRead.setMinimumSize(QtCore.QSize(15, 15))
        self.sl2SwitchRead.setMaximumSize(QtCore.QSize(15, 15))
        self.sl2SwitchRead.setObjectName(_fromUtf8("sl2SwitchRead"))
        self.gridLayout.addWidget(self.sl2SwitchRead, 8, 1, 1, 1)
        self.sl3FCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl3FCheck.setText(_fromUtf8(""))
        self.sl3FCheck.setObjectName(_fromUtf8("sl3FCheck"))
        self.gridLayout.addWidget(self.sl3FCheck, 11, 5, 1, 1)
        self.qt1HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.qt1HCheck.setText(_fromUtf8(""))
        self.qt1HCheck.setObjectName(_fromUtf8("qt1HCheck"))
        self.gridLayout.addWidget(self.qt1HCheck, 12, 12, 1, 1)
        self.sl4VLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl4VLabel.setObjectName(_fromUtf8("sl4VLabel"))
        self.gridLayout.addWidget(self.sl4VLabel, 14, 0, 1, 1)
        self.as2VWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.as2VWrite.setObjectName(_fromUtf8("as2VWrite"))
        self.gridLayout.addWidget(self.as2VWrite, 18, 10, 1, 1)
        self.sl4HLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl4HLabel.setObjectName(_fromUtf8("sl4HLabel"))
        self.gridLayout.addWidget(self.sl4HLabel, 13, 0, 1, 1)
        self.as2HRead = TaurusLabel(self.magnetsGroup)
        self.as2HRead.setObjectName(_fromUtf8("as2HRead"))
        self.gridLayout.addWidget(self.as2HRead, 17, 9, 1, 1)
        self.sl2FCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl2FCheck.setText(_fromUtf8(""))
        self.sl2FCheck.setObjectName(_fromUtf8("sl2FCheck"))
        self.gridLayout.addWidget(self.sl2FCheck, 7, 5, 1, 1)
        self.glHWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.glHWrite.setObjectName(_fromUtf8("glHWrite"))
        self.gridLayout.addWidget(self.glHWrite, 5, 10, 1, 1)
        self.qt1HWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.qt1HWrite.setObjectName(_fromUtf8("qt1HWrite"))
        self.gridLayout.addWidget(self.qt1HWrite, 12, 10, 1, 1)
        self.sl1SwitchRead = TaurusLed(self.magnetsGroup)
        self.sl1SwitchRead.setMinimumSize(QtCore.QSize(15, 15))
        self.sl1SwitchRead.setMaximumSize(QtCore.QSize(15, 15))
        self.sl1SwitchRead.setObjectName(_fromUtf8("sl1SwitchRead"))
        self.gridLayout.addWidget(self.sl1SwitchRead, 4, 1, 1, 1)
        self.bc1SwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.bc1SwitchCheck.setText(_fromUtf8(""))
        self.bc1SwitchCheck.setObjectName(_fromUtf8("bc1SwitchCheck"))
        self.gridLayout.addWidget(self.bc1SwitchCheck, 20, 5, 1, 1)
        self.qt1VWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.qt1VWrite.setObjectName(_fromUtf8("qt1VWrite"))
        self.gridLayout.addWidget(self.qt1VWrite, 13, 10, 1, 1)
        self.as1HWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.as1HWrite.setObjectName(_fromUtf8("as1HWrite"))
        self.gridLayout.addWidget(self.as1HWrite, 9, 10, 1, 1)
        self.sl2FLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl2FLabel.setObjectName(_fromUtf8("sl2FLabel"))
        self.gridLayout.addWidget(self.sl2FLabel, 7, 0, 1, 1)
        self.as2SwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.as2SwitchCheck.setText(_fromUtf8(""))
        self.as2SwitchCheck.setObjectName(_fromUtf8("as2SwitchCheck"))
        self.gridLayout.addWidget(self.as2SwitchCheck, 19, 12, 1, 1)
        self.sl3FRead = TaurusLabel(self.magnetsGroup)
        self.sl3FRead.setObjectName(_fromUtf8("sl3FRead"))
        self.gridLayout.addWidget(self.sl3FRead, 11, 1, 1, 1)
        self.sl4HWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl4HWrite.setObjectName(_fromUtf8("sl4HWrite"))
        self.gridLayout.addWidget(self.sl4HWrite, 13, 2, 1, 1)
        self.sl1FRead = TaurusLabel(self.magnetsGroup)
        self.sl1FRead.setObjectName(_fromUtf8("sl1FRead"))
        self.gridLayout.addWidget(self.sl1FRead, 3, 1, 1, 1)
        self.PresentWriteTitle_2 = QtGui.QLabel(self.magnetsGroup)
        self.PresentWriteTitle_2.setObjectName(_fromUtf8("PresentWriteTitle_2"))
        self.gridLayout.addWidget(self.PresentWriteTitle_2, 0, 9, 1, 1)
        self.glHCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.glHCheck.setText(_fromUtf8(""))
        self.glHCheck.setObjectName(_fromUtf8("glHCheck"))
        self.gridLayout.addWidget(self.glHCheck, 5, 12, 1, 1)
        self.qtSwitchWrite = QtGui.QCheckBox(self.magnetsGroup)
        self.qtSwitchWrite.setObjectName(_fromUtf8("qtSwitchWrite"))
        self.gridLayout.addWidget(self.qtSwitchWrite, 16, 10, 1, 1)
        self.sl1HWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl1HWrite.setObjectName(_fromUtf8("sl1HWrite"))
        self.gridLayout.addWidget(self.sl1HWrite, 1, 2, 1, 1)
        self.sl4FWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl4FWrite.setObjectName(_fromUtf8("sl4FWrite"))
        self.gridLayout.addWidget(self.sl4FWrite, 15, 2, 1, 1)
        self.qt1FCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.qt1FCheck.setText(_fromUtf8(""))
        self.qt1FCheck.setObjectName(_fromUtf8("qt1FCheck"))
        self.gridLayout.addWidget(self.qt1FCheck, 14, 12, 1, 1)
        self.bc1FLabel = QtGui.QLabel(self.magnetsGroup)
        self.bc1FLabel.setObjectName(_fromUtf8("bc1FLabel"))
        self.gridLayout.addWidget(self.bc1FLabel, 19, 0, 1, 1)
        self.sl2VRead = TaurusLabel(self.magnetsGroup)
        self.sl2VRead.setObjectName(_fromUtf8("sl2VRead"))
        self.gridLayout.addWidget(self.sl2VRead, 6, 1, 1, 1)
        self.line_1 = QtGui.QFrame(self.magnetsGroup)
        self.line_1.setFrameShape(QtGui.QFrame.VLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName(_fromUtf8("line_1"))
        self.gridLayout.addWidget(self.line_1, 1, 4, 24, 1)
        self.glVRead = TaurusLabel(self.magnetsGroup)
        self.glVRead.setObjectName(_fromUtf8("glVRead"))
        self.gridLayout.addWidget(self.glVRead, 6, 9, 1, 1)
        self.sl3VLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl3VLabel.setObjectName(_fromUtf8("sl3VLabel"))
        self.gridLayout.addWidget(self.sl3VLabel, 10, 0, 1, 1)
        self.bc1HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.bc1HCheck.setText(_fromUtf8(""))
        self.bc1HCheck.setObjectName(_fromUtf8("bc1HCheck"))
        self.gridLayout.addWidget(self.bc1HCheck, 17, 5, 1, 1)
        self.as1VWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.as1VWrite.setObjectName(_fromUtf8("as1VWrite"))
        self.gridLayout.addWidget(self.as1VWrite, 10, 10, 1, 1)
        self.as1SwitchWrite = QtGui.QCheckBox(self.magnetsGroup)
        self.as1SwitchWrite.setObjectName(_fromUtf8("as1SwitchWrite"))
        self.gridLayout.addWidget(self.as1SwitchWrite, 11, 10, 1, 1)
        self.sl4SwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl4SwitchCheck.setText(_fromUtf8(""))
        self.sl4SwitchCheck.setObjectName(_fromUtf8("sl4SwitchCheck"))
        self.gridLayout.addWidget(self.sl4SwitchCheck, 16, 5, 1, 1)
        self.as1SwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.as1SwitchCheck.setText(_fromUtf8(""))
        self.as1SwitchCheck.setObjectName(_fromUtf8("as1SwitchCheck"))
        self.gridLayout.addWidget(self.as1SwitchCheck, 11, 12, 1, 1)
        self.sl1VLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl1VLabel.setObjectName(_fromUtf8("sl1VLabel"))
        self.gridLayout.addWidget(self.sl1VLabel, 2, 0, 1, 1)
        self.sl3HRead = TaurusLabel(self.magnetsGroup)
        self.sl3HRead.setObjectName(_fromUtf8("sl3HRead"))
        self.gridLayout.addWidget(self.sl3HRead, 9, 1, 1, 1)
        self.sl4FCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl4FCheck.setText(_fromUtf8(""))
        self.sl4FCheck.setObjectName(_fromUtf8("sl4FCheck"))
        self.gridLayout.addWidget(self.sl4FCheck, 15, 5, 1, 1)
        self.as1HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.as1HCheck.setText(_fromUtf8(""))
        self.as1HCheck.setObjectName(_fromUtf8("as1HCheck"))
        self.gridLayout.addWidget(self.as1HCheck, 9, 12, 1, 1)
        self.sl4VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl4VCheck.setText(_fromUtf8(""))
        self.sl4VCheck.setObjectName(_fromUtf8("sl4VCheck"))
        self.gridLayout.addWidget(self.sl4VCheck, 14, 5, 1, 1)
        self.sl3SwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl3SwitchCheck.setText(_fromUtf8(""))
        self.sl3SwitchCheck.setObjectName(_fromUtf8("sl3SwitchCheck"))
        self.gridLayout.addWidget(self.sl3SwitchCheck, 12, 5, 1, 1)
        self.bc1FCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.bc1FCheck.setText(_fromUtf8(""))
        self.bc1FCheck.setObjectName(_fromUtf8("bc1FCheck"))
        self.gridLayout.addWidget(self.bc1FCheck, 19, 5, 1, 1)
        self.sl4SwitchRead = TaurusLed(self.magnetsGroup)
        self.sl4SwitchRead.setMinimumSize(QtCore.QSize(15, 15))
        self.sl4SwitchRead.setMaximumSize(QtCore.QSize(15, 15))
        self.sl4SwitchRead.setObjectName(_fromUtf8("sl4SwitchRead"))
        self.gridLayout.addWidget(self.sl4SwitchRead, 16, 1, 1, 1)
        self.glSwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.glSwitchCheck.setText(_fromUtf8(""))
        self.glSwitchCheck.setObjectName(_fromUtf8("glSwitchCheck"))
        self.gridLayout.addWidget(self.glSwitchCheck, 8, 12, 1, 1)
        self.sl3FWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl3FWrite.setObjectName(_fromUtf8("sl3FWrite"))
        self.gridLayout.addWidget(self.sl3FWrite, 11, 2, 1, 1)
        self.sl1HLabel = QtGui.QLabel(self.magnetsGroup)
        self.sl1HLabel.setObjectName(_fromUtf8("sl1HLabel"))
        self.gridLayout.addWidget(self.sl1HLabel, 1, 0, 1, 1)
        self.sl4HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl4HCheck.setText(_fromUtf8(""))
        self.sl4HCheck.setObjectName(_fromUtf8("sl4HCheck"))
        self.gridLayout.addWidget(self.sl4HCheck, 13, 5, 1, 1)
        self.sl1VWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl1VWrite.setObjectName(_fromUtf8("sl1VWrite"))
        self.gridLayout.addWidget(self.sl1VWrite, 2, 2, 1, 1)
        self.sl1FCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl1FCheck.setText(_fromUtf8(""))
        self.sl1FCheck.setObjectName(_fromUtf8("sl1FCheck"))
        self.gridLayout.addWidget(self.sl1FCheck, 3, 5, 1, 1)
        self.sl1FWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl1FWrite.setObjectName(_fromUtf8("sl1FWrite"))
        self.gridLayout.addWidget(self.sl1FWrite, 3, 2, 1, 1)
        self.sl1VRead = TaurusLabel(self.magnetsGroup)
        self.sl1VRead.setObjectName(_fromUtf8("sl1VRead"))
        self.gridLayout.addWidget(self.sl1VRead, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 42, 1, 1, 1)
        self.sl3SwitchWrite = QtGui.QCheckBox(self.magnetsGroup)
        self.sl3SwitchWrite.setObjectName(_fromUtf8("sl3SwitchWrite"))
        self.gridLayout.addWidget(self.sl3SwitchWrite, 12, 2, 1, 1)
        self.sl2FWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.sl2FWrite.setObjectName(_fromUtf8("sl2FWrite"))
        self.gridLayout.addWidget(self.sl2FWrite, 7, 2, 1, 1)
        self.sl1SwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.sl1SwitchCheck.setText(_fromUtf8(""))
        self.sl1SwitchCheck.setObjectName(_fromUtf8("sl1SwitchCheck"))
        self.gridLayout.addWidget(self.sl1SwitchCheck, 4, 5, 1, 1)
        self.glFRead = TaurusLabel(self.magnetsGroup)
        self.glFRead.setObjectName(_fromUtf8("glFRead"))
        self.gridLayout.addWidget(self.glFRead, 7, 9, 1, 1)
        self.as1VRead = TaurusLabel(self.magnetsGroup)
        self.as1VRead.setObjectName(_fromUtf8("as1VRead"))
        self.gridLayout.addWidget(self.as1VRead, 10, 9, 1, 1)
        self.qtSwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.qtSwitchLabel.setObjectName(_fromUtf8("qtSwitchLabel"))
        self.gridLayout.addWidget(self.qtSwitchLabel, 16, 7, 1, 1)
        self.qt2FLabel = QtGui.QLabel(self.magnetsGroup)
        self.qt2FLabel.setObjectName(_fromUtf8("qt2FLabel"))
        self.gridLayout.addWidget(self.qt2FLabel, 15, 7, 1, 1)
        self.glSwitchRead = TaurusLed(self.magnetsGroup)
        self.glSwitchRead.setMinimumSize(QtCore.QSize(15, 15))
        self.glSwitchRead.setMaximumSize(QtCore.QSize(15, 15))
        self.glSwitchRead.setObjectName(_fromUtf8("glSwitchRead"))
        self.gridLayout.addWidget(self.glSwitchRead, 8, 9, 1, 1)
        self.as1SwitchRead = TaurusLed(self.magnetsGroup)
        self.as1SwitchRead.setMinimumSize(QtCore.QSize(15, 15))
        self.as1SwitchRead.setMaximumSize(QtCore.QSize(15, 15))
        self.as1SwitchRead.setObjectName(_fromUtf8("as1SwitchRead"))
        self.gridLayout.addWidget(self.as1SwitchRead, 11, 9, 1, 1)
        self.as2HLabel = QtGui.QLabel(self.magnetsGroup)
        self.as2HLabel.setObjectName(_fromUtf8("as2HLabel"))
        self.gridLayout.addWidget(self.as2HLabel, 17, 7, 1, 1)
        self.qt1VRead = TaurusLabel(self.magnetsGroup)
        self.qt1VRead.setObjectName(_fromUtf8("qt1VRead"))
        self.gridLayout.addWidget(self.qt1VRead, 13, 9, 1, 1)
        self.line_2 = QtGui.QFrame(self.magnetsGroup)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 0, 6, 25, 1)
        self.qt1HRead = TaurusLabel(self.magnetsGroup)
        self.qt1HRead.setObjectName(_fromUtf8("qt1HRead"))
        self.gridLayout.addWidget(self.qt1HRead, 12, 9, 1, 1)
        self.as2VLabel = QtGui.QLabel(self.magnetsGroup)
        self.as2VLabel.setObjectName(_fromUtf8("as2VLabel"))
        self.gridLayout.addWidget(self.as2VLabel, 18, 7, 1, 1)
        self.as2VRead = TaurusLabel(self.magnetsGroup)
        self.as2VRead.setObjectName(_fromUtf8("as2VRead"))
        self.gridLayout.addWidget(self.as2VRead, 18, 9, 1, 1)
        self.qt1FLabel = QtGui.QLabel(self.magnetsGroup)
        self.qt1FLabel.setObjectName(_fromUtf8("qt1FLabel"))
        self.gridLayout.addWidget(self.qt1FLabel, 14, 7, 1, 1)
        self.qt1VLabel = QtGui.QLabel(self.magnetsGroup)
        self.qt1VLabel.setObjectName(_fromUtf8("qt1VLabel"))
        self.gridLayout.addWidget(self.qt1VLabel, 13, 7, 1, 1)
        self.qt1HLabel = QtGui.QLabel(self.magnetsGroup)
        self.qt1HLabel.setObjectName(_fromUtf8("qt1HLabel"))
        self.gridLayout.addWidget(self.qt1HLabel, 12, 7, 1, 1)
        self.as1SwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.as1SwitchLabel.setObjectName(_fromUtf8("as1SwitchLabel"))
        self.gridLayout.addWidget(self.as1SwitchLabel, 11, 7, 1, 1)
        self.as1VLabel = QtGui.QLabel(self.magnetsGroup)
        self.as1VLabel.setObjectName(_fromUtf8("as1VLabel"))
        self.gridLayout.addWidget(self.as1VLabel, 10, 7, 1, 1)
        self.as1HLabel = QtGui.QLabel(self.magnetsGroup)
        self.as1HLabel.setObjectName(_fromUtf8("as1HLabel"))
        self.gridLayout.addWidget(self.as1HLabel, 9, 7, 1, 1)
        self.glSwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.glSwitchLabel.setObjectName(_fromUtf8("glSwitchLabel"))
        self.gridLayout.addWidget(self.glSwitchLabel, 8, 7, 1, 1)
        self.glFLabel = QtGui.QLabel(self.magnetsGroup)
        self.glFLabel.setObjectName(_fromUtf8("glFLabel"))
        self.gridLayout.addWidget(self.glFLabel, 7, 7, 1, 1)
        self.glVLabel = QtGui.QLabel(self.magnetsGroup)
        self.glVLabel.setObjectName(_fromUtf8("glVLabel"))
        self.gridLayout.addWidget(self.glVLabel, 6, 7, 1, 1)
        self.glHLabel = QtGui.QLabel(self.magnetsGroup)
        self.glHLabel.setObjectName(_fromUtf8("glHLabel"))
        self.gridLayout.addWidget(self.glHLabel, 5, 7, 1, 1)
        self.bc2SwitchCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.bc2SwitchCheck.setText(_fromUtf8(""))
        self.bc2SwitchCheck.setObjectName(_fromUtf8("bc2SwitchCheck"))
        self.gridLayout.addWidget(self.bc2SwitchCheck, 4, 12, 1, 1)
        self.bc2FCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.bc2FCheck.setText(_fromUtf8(""))
        self.bc2FCheck.setObjectName(_fromUtf8("bc2FCheck"))
        self.gridLayout.addWidget(self.bc2FCheck, 3, 12, 1, 1)
        self.bc2VCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.bc2VCheck.setText(_fromUtf8(""))
        self.bc2VCheck.setObjectName(_fromUtf8("bc2VCheck"))
        self.gridLayout.addWidget(self.bc2VCheck, 2, 12, 1, 1)
        self.bc2HCheck = QtGui.QCheckBox(self.magnetsGroup)
        self.bc2HCheck.setText(_fromUtf8(""))
        self.bc2HCheck.setObjectName(_fromUtf8("bc2HCheck"))
        self.gridLayout.addWidget(self.bc2HCheck, 1, 12, 1, 1)
        self.bc2HWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.bc2HWrite.setObjectName(_fromUtf8("bc2HWrite"))
        self.gridLayout.addWidget(self.bc2HWrite, 1, 10, 1, 1)
        self.bc2HRead = TaurusLabel(self.magnetsGroup)
        self.bc2HRead.setObjectName(_fromUtf8("bc2HRead"))
        self.gridLayout.addWidget(self.bc2HRead, 1, 9, 1, 1)
        self.bc2HLabel = QtGui.QLabel(self.magnetsGroup)
        self.bc2HLabel.setObjectName(_fromUtf8("bc2HLabel"))
        self.gridLayout.addWidget(self.bc2HLabel, 1, 7, 1, 1)
        self.bc2VLabel = QtGui.QLabel(self.magnetsGroup)
        self.bc2VLabel.setObjectName(_fromUtf8("bc2VLabel"))
        self.gridLayout.addWidget(self.bc2VLabel, 2, 7, 1, 1)
        self.bc2FLabel = QtGui.QLabel(self.magnetsGroup)
        self.bc2FLabel.setObjectName(_fromUtf8("bc2FLabel"))
        self.gridLayout.addWidget(self.bc2FLabel, 3, 7, 1, 1)
        self.bc2SwitchLabel = QtGui.QLabel(self.magnetsGroup)
        self.bc2SwitchLabel.setObjectName(_fromUtf8("bc2SwitchLabel"))
        self.gridLayout.addWidget(self.bc2SwitchLabel, 4, 7, 1, 1)
        self.bc2VRead = TaurusLabel(self.magnetsGroup)
        self.bc2VRead.setObjectName(_fromUtf8("bc2VRead"))
        self.gridLayout.addWidget(self.bc2VRead, 2, 9, 1, 1)
        self.bc2FRead = TaurusLabel(self.magnetsGroup)
        self.bc2FRead.setObjectName(_fromUtf8("bc2FRead"))
        self.gridLayout.addWidget(self.bc2FRead, 3, 9, 1, 1)
        self.bc2SwitchRead = TaurusLed(self.magnetsGroup)
        self.bc2SwitchRead.setMinimumSize(QtCore.QSize(15, 15))
        self.bc2SwitchRead.setMaximumSize(QtCore.QSize(15, 15))
        self.bc2SwitchRead.setObjectName(_fromUtf8("bc2SwitchRead"))
        self.gridLayout.addWidget(self.bc2SwitchRead, 4, 9, 1, 1)
        self.bc2VWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.bc2VWrite.setObjectName(_fromUtf8("bc2VWrite"))
        self.gridLayout.addWidget(self.bc2VWrite, 2, 10, 1, 1)
        self.bc2FWrite = QtGui.QDoubleSpinBox(self.magnetsGroup)
        self.bc2FWrite.setObjectName(_fromUtf8("bc2FWrite"))
        self.gridLayout.addWidget(self.bc2FWrite, 3, 10, 1, 1)
        self.bc2SwitchWrite = QtGui.QCheckBox(self.magnetsGroup)
        self.bc2SwitchWrite.setObjectName(_fromUtf8("bc2SwitchWrite"))
        self.gridLayout.addWidget(self.bc2SwitchWrite, 4, 10, 1, 1)
        self.line_3 = QtGui.QFrame(self.magnetsGroup)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 1, 11, 19, 1)
        self.gridLayout_2.addWidget(self.magnetsGroup, 0, 0, 1, 1)

        self.retranslateUi(magnetSnapshot)
        QtCore.QMetaObject.connectSlotsByName(magnetSnapshot)

    def retranslateUi(self, magnetSnapshot):
        magnetSnapshot.setWindowTitle(QtGui.QApplication.translate("magnetSnapshot", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.magnetsGroup.setTitle(QtGui.QApplication.translate("magnetSnapshot", "Magnets", None, QtGui.QApplication.UnicodeUTF8))
        self.ToApplyTitle.setText(QtGui.QApplication.translate("magnetSnapshot", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveRetrieveTitle.setText(QtGui.QApplication.translate("magnetSnapshot", "Save/Retrieve", None, QtGui.QApplication.UnicodeUTF8))
        self.glSwitchWrite.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.sl1SwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl1 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.as2SwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "AS2 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.as2SwitchWrite.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.sl4SwitchWrite.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.sl3SwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl3 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "bc1 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.sl3FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl3 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "bc1 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.sl1FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl1 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.PresentWriteTitle.setText(QtGui.QApplication.translate("magnetSnapshot", "Present value", None, QtGui.QApplication.UnicodeUTF8))
        self.sl1SwitchWrite.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1SwitchWrite.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.sl4SwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl4 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.sl2SwitchWrite.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.sl2SwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl2 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1SwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "bc1 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveRetrieveTitle_2.setText(QtGui.QApplication.translate("magnetSnapshot", "Save/Retrieve", None, QtGui.QApplication.UnicodeUTF8))
        self.sl2HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl2 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.sl3HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl3 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.sl2VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl2 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.sl4FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl4 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.sl4VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl4 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.sl4HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl4 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.sl2FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl2 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.PresentWriteTitle_2.setText(QtGui.QApplication.translate("magnetSnapshot", "Present value", None, QtGui.QApplication.UnicodeUTF8))
        self.qtSwitchWrite.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "bc1 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.sl3VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl3 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.as1SwitchWrite.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.sl1VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl1 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.sl1HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "sl1 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.sl3SwitchWrite.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.qtSwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "QT Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.qt2FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "QT2 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.as2HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "AS2 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.as2VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "AS2 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.qt1FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "QT1 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.qt1VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "QT1 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.qt1HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "QT1 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.as1SwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "AS1 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.as1VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "AS1 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.as1HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "AS1 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.glSwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "gl Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.glFLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "gl Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.glVLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "gl Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.glHLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "gl Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2HLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "bc2 Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2VLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "bc2 Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2FLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "bc2 Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2SwitchLabel.setText(QtGui.QApplication.translate("magnetSnapshot", "bc2 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2SwitchWrite.setText(QtGui.QApplication.translate("magnetSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusLabel, TaurusLed
from taurus.qt.qtgui.container import TaurusGroupBox
from taurus.qt.qtgui.panel import TaurusWidget
