# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/ui/snapshot_radiofrequency.ui'
#
# Created: Wed Mar 12 08:55:37 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_radioFrequencySnapshot(object):
    def setupUi(self, radioFrequencySnapshot):
        radioFrequencySnapshot.setObjectName(_fromUtf8("radioFrequencySnapshot"))
        radioFrequencySnapshot.resize(379, 326)
        self.gridLayout_2 = QtGui.QGridLayout(radioFrequencySnapshot)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.radioFrequencyGroup = TaurusGroupBox(radioFrequencySnapshot)
        self.radioFrequencyGroup.setObjectName(_fromUtf8("radioFrequencyGroup"))
        self.gridLayout = QtGui.QGridLayout(self.radioFrequencyGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.PresentValueTitle = QtGui.QLabel(self.radioFrequencyGroup)
        self.PresentValueTitle.setObjectName(_fromUtf8("PresentValueTitle"))
        self.gridLayout.addWidget(self.PresentValueTitle, 0, 1, 1, 1)
        self.SaveRetrieveTitle = QtGui.QLabel(self.radioFrequencyGroup)
        self.SaveRetrieveTitle.setObjectName(_fromUtf8("SaveRetrieveTitle"))
        self.gridLayout.addWidget(self.SaveRetrieveTitle, 0, 2, 1, 1)
        self.ToApplyTitle = QtGui.QCheckBox(self.radioFrequencyGroup)
        self.ToApplyTitle.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ToApplyTitle.setObjectName(_fromUtf8("ToApplyTitle"))
        self.gridLayout.addWidget(self.ToApplyTitle, 0, 4, 1, 1)
        self.TPS0PhaseLabel = QtGui.QLabel(self.radioFrequencyGroup)
        self.TPS0PhaseLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TPS0PhaseLabel.setObjectName(_fromUtf8("TPS0PhaseLabel"))
        self.gridLayout.addWidget(self.TPS0PhaseLabel, 1, 0, 1, 1)
        self.TPS2PhaseValue = QtGui.QDoubleSpinBox(self.radioFrequencyGroup)
        self.TPS2PhaseValue.setObjectName(_fromUtf8("TPS2PhaseValue"))
        self.gridLayout.addWidget(self.TPS2PhaseValue, 4, 2, 1, 1)
        self.PHS1Reading = TaurusLabel(self.radioFrequencyGroup)
        self.PHS1Reading.setObjectName(_fromUtf8("PHS1Reading"))
        self.gridLayout.addWidget(self.PHS1Reading, 8, 1, 1, 1)
        self.PHS2Reading = TaurusLabel(self.radioFrequencyGroup)
        self.PHS2Reading.setObjectName(_fromUtf8("PHS2Reading"))
        self.gridLayout.addWidget(self.PHS2Reading, 9, 1, 1, 1)
        self.A0OPValue = QtGui.QDoubleSpinBox(self.radioFrequencyGroup)
        self.A0OPValue.setObjectName(_fromUtf8("A0OPValue"))
        self.gridLayout.addWidget(self.A0OPValue, 5, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 1, 1, 1)
        self.PHS2Value = QtGui.QDoubleSpinBox(self.radioFrequencyGroup)
        self.PHS2Value.setObjectName(_fromUtf8("PHS2Value"))
        self.gridLayout.addWidget(self.PHS2Value, 9, 2, 1, 1)
        self.TPS0PhaseValue = QtGui.QDoubleSpinBox(self.radioFrequencyGroup)
        self.TPS0PhaseValue.setObjectName(_fromUtf8("TPS0PhaseValue"))
        self.gridLayout.addWidget(self.TPS0PhaseValue, 1, 2, 1, 1)
        self.TPS1PhaseValue = QtGui.QDoubleSpinBox(self.radioFrequencyGroup)
        self.TPS1PhaseValue.setObjectName(_fromUtf8("TPS1PhaseValue"))
        self.gridLayout.addWidget(self.TPS1PhaseValue, 3, 2, 1, 1)
        self.PHS1Value = QtGui.QDoubleSpinBox(self.radioFrequencyGroup)
        self.PHS1Value.setObjectName(_fromUtf8("PHS1Value"))
        self.gridLayout.addWidget(self.PHS1Value, 8, 2, 1, 1)
        self.ATT2Reading = TaurusLabel(self.radioFrequencyGroup)
        self.ATT2Reading.setObjectName(_fromUtf8("ATT2Reading"))
        self.gridLayout.addWidget(self.ATT2Reading, 7, 1, 1, 1)
        self.ATT2Value = QtGui.QDoubleSpinBox(self.radioFrequencyGroup)
        self.ATT2Value.setObjectName(_fromUtf8("ATT2Value"))
        self.gridLayout.addWidget(self.ATT2Value, 7, 2, 1, 1)
        self.A0OPReading = TaurusLabel(self.radioFrequencyGroup)
        self.A0OPReading.setObjectName(_fromUtf8("A0OPReading"))
        self.gridLayout.addWidget(self.A0OPReading, 5, 1, 1, 1)
        self.TPS2PhaseReading = TaurusLabel(self.radioFrequencyGroup)
        self.TPS2PhaseReading.setObjectName(_fromUtf8("TPS2PhaseReading"))
        self.gridLayout.addWidget(self.TPS2PhaseReading, 4, 1, 1, 1)
        self.TPSXPhaseReading = TaurusLabel(self.radioFrequencyGroup)
        self.TPSXPhaseReading.setObjectName(_fromUtf8("TPSXPhaseReading"))
        self.gridLayout.addWidget(self.TPSXPhaseReading, 2, 1, 1, 1)
        self.TPS1PhaseReading = TaurusLabel(self.radioFrequencyGroup)
        self.TPS1PhaseReading.setObjectName(_fromUtf8("TPS1PhaseReading"))
        self.gridLayout.addWidget(self.TPS1PhaseReading, 3, 1, 1, 1)
        self.TPS0PhaseCheck = QtGui.QCheckBox(self.radioFrequencyGroup)
        self.TPS0PhaseCheck.setText(_fromUtf8(""))
        self.TPS0PhaseCheck.setObjectName(_fromUtf8("TPS0PhaseCheck"))
        self.gridLayout.addWidget(self.TPS0PhaseCheck, 1, 4, 1, 1)
        self.PHS1Check = QtGui.QCheckBox(self.radioFrequencyGroup)
        self.PHS1Check.setText(_fromUtf8(""))
        self.PHS1Check.setObjectName(_fromUtf8("PHS1Check"))
        self.gridLayout.addWidget(self.PHS1Check, 8, 4, 1, 1)
        self.TPS1PhaseCheck = QtGui.QCheckBox(self.radioFrequencyGroup)
        self.TPS1PhaseCheck.setText(_fromUtf8(""))
        self.TPS1PhaseCheck.setObjectName(_fromUtf8("TPS1PhaseCheck"))
        self.gridLayout.addWidget(self.TPS1PhaseCheck, 3, 4, 1, 1)
        self.TPS0PhaseReading = TaurusLabel(self.radioFrequencyGroup)
        self.TPS0PhaseReading.setObjectName(_fromUtf8("TPS0PhaseReading"))
        self.gridLayout.addWidget(self.TPS0PhaseReading, 1, 1, 1, 1)
        self.TPSXPhaseValue = QtGui.QDoubleSpinBox(self.radioFrequencyGroup)
        self.TPSXPhaseValue.setObjectName(_fromUtf8("TPSXPhaseValue"))
        self.gridLayout.addWidget(self.TPSXPhaseValue, 2, 2, 1, 1)
        self.TPS2PhaseCheck = QtGui.QCheckBox(self.radioFrequencyGroup)
        self.TPS2PhaseCheck.setText(_fromUtf8(""))
        self.TPS2PhaseCheck.setObjectName(_fromUtf8("TPS2PhaseCheck"))
        self.gridLayout.addWidget(self.TPS2PhaseCheck, 4, 4, 1, 1)
        self.TPSXPhaseCheck = QtGui.QCheckBox(self.radioFrequencyGroup)
        self.TPSXPhaseCheck.setText(_fromUtf8(""))
        self.TPSXPhaseCheck.setObjectName(_fromUtf8("TPSXPhaseCheck"))
        self.gridLayout.addWidget(self.TPSXPhaseCheck, 2, 4, 1, 1)
        self.A0OPCheck = QtGui.QCheckBox(self.radioFrequencyGroup)
        self.A0OPCheck.setText(_fromUtf8(""))
        self.A0OPCheck.setObjectName(_fromUtf8("A0OPCheck"))
        self.gridLayout.addWidget(self.A0OPCheck, 5, 4, 1, 1)
        self.TPSXPhaseLabel = QtGui.QLabel(self.radioFrequencyGroup)
        self.TPSXPhaseLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TPSXPhaseLabel.setObjectName(_fromUtf8("TPSXPhaseLabel"))
        self.gridLayout.addWidget(self.TPSXPhaseLabel, 2, 0, 1, 1)
        self.TPS1PhaseLabel = QtGui.QLabel(self.radioFrequencyGroup)
        self.TPS1PhaseLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TPS1PhaseLabel.setObjectName(_fromUtf8("TPS1PhaseLabel"))
        self.gridLayout.addWidget(self.TPS1PhaseLabel, 3, 0, 1, 1)
        self.TPS2PhaseLabel = QtGui.QLabel(self.radioFrequencyGroup)
        self.TPS2PhaseLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TPS2PhaseLabel.setObjectName(_fromUtf8("TPS2PhaseLabel"))
        self.gridLayout.addWidget(self.TPS2PhaseLabel, 4, 0, 1, 1)
        self.A0OPLabel = QtGui.QLabel(self.radioFrequencyGroup)
        self.A0OPLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.A0OPLabel.setObjectName(_fromUtf8("A0OPLabel"))
        self.gridLayout.addWidget(self.A0OPLabel, 5, 0, 1, 1)
        self.PHS1Label = QtGui.QLabel(self.radioFrequencyGroup)
        self.PHS1Label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PHS1Label.setObjectName(_fromUtf8("PHS1Label"))
        self.gridLayout.addWidget(self.PHS1Label, 8, 0, 1, 1)
        self.ATT2Check = QtGui.QCheckBox(self.radioFrequencyGroup)
        self.ATT2Check.setText(_fromUtf8(""))
        self.ATT2Check.setObjectName(_fromUtf8("ATT2Check"))
        self.gridLayout.addWidget(self.ATT2Check, 7, 4, 1, 1)
        self.ATT2Label = QtGui.QLabel(self.radioFrequencyGroup)
        self.ATT2Label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ATT2Label.setObjectName(_fromUtf8("ATT2Label"))
        self.gridLayout.addWidget(self.ATT2Label, 7, 0, 1, 1)
        self.PHS2Label = QtGui.QLabel(self.radioFrequencyGroup)
        self.PHS2Label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PHS2Label.setObjectName(_fromUtf8("PHS2Label"))
        self.gridLayout.addWidget(self.PHS2Label, 9, 0, 1, 1)
        self.PHS2Check = QtGui.QCheckBox(self.radioFrequencyGroup)
        self.PHS2Check.setText(_fromUtf8(""))
        self.PHS2Check.setObjectName(_fromUtf8("PHS2Check"))
        self.gridLayout.addWidget(self.PHS2Check, 9, 4, 1, 1)
        self.line = QtGui.QFrame(self.radioFrequencyGroup)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 3, 9, 1)
        self.gridLayout_2.addWidget(self.radioFrequencyGroup, 0, 0, 1, 1)

        self.retranslateUi(radioFrequencySnapshot)
        QtCore.QMetaObject.connectSlotsByName(radioFrequencySnapshot)

    def retranslateUi(self, radioFrequencySnapshot):
        radioFrequencySnapshot.setWindowTitle(QtGui.QApplication.translate("radioFrequencySnapshot", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.radioFrequencyGroup.setTitle(QtGui.QApplication.translate("radioFrequencySnapshot", "Radio Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.PresentValueTitle.setText(QtGui.QApplication.translate("radioFrequencySnapshot", "Present value", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveRetrieveTitle.setText(QtGui.QApplication.translate("radioFrequencySnapshot", "Save/Retrieve", None, QtGui.QApplication.UnicodeUTF8))
        self.ToApplyTitle.setText(QtGui.QApplication.translate("radioFrequencySnapshot", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.TPS0PhaseLabel.setText(QtGui.QApplication.translate("radioFrequencySnapshot", "Time Phase Shifter 0", None, QtGui.QApplication.UnicodeUTF8))
        self.TPSXPhaseLabel.setText(QtGui.QApplication.translate("radioFrequencySnapshot", "Time Phase Shifter X", None, QtGui.QApplication.UnicodeUTF8))
        self.TPS1PhaseLabel.setText(QtGui.QApplication.translate("radioFrequencySnapshot", "Time Phase Shifter 1", None, QtGui.QApplication.UnicodeUTF8))
        self.TPS2PhaseLabel.setText(QtGui.QApplication.translate("radioFrequencySnapshot", "Time Phase Shifter 2", None, QtGui.QApplication.UnicodeUTF8))
        self.A0OPLabel.setText(QtGui.QApplication.translate("radioFrequencySnapshot", "A0 output power", None, QtGui.QApplication.UnicodeUTF8))
        self.PHS1Label.setText(QtGui.QApplication.translate("radioFrequencySnapshot", "Phase Shifter 1", None, QtGui.QApplication.UnicodeUTF8))
        self.ATT2Label.setText(QtGui.QApplication.translate("radioFrequencySnapshot", "Attenuator 2", None, QtGui.QApplication.UnicodeUTF8))
        self.PHS2Label.setText(QtGui.QApplication.translate("radioFrequencySnapshot", "Phase Shifter 2", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusLabel
from taurus.qt.qtgui.container import TaurusGroupBox
from taurus.qt.qtgui.panel import TaurusWidget
