# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/ui/snapshot_klystrons.ui'
#
# Created: Wed Mar 12 14:27:41 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_klystronSnapshot(object):
    def setupUi(self, klystronSnapshot):
        klystronSnapshot.setObjectName(_fromUtf8("klystronSnapshot"))
        klystronSnapshot.resize(325, 217)
        font = QtGui.QFont()
        font.setPointSize(7)
        klystronSnapshot.setFont(font)
        self.gridLayout_3 = QtGui.QGridLayout(klystronSnapshot)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.klystronGroup = TaurusGroupBox(klystronSnapshot)
        self.klystronGroup.setObjectName(_fromUtf8("klystronGroup"))
        self.gridLayout = QtGui.QGridLayout(self.klystronGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.ka2HVPSLabel = QtGui.QLabel(self.klystronGroup)
        self.ka2HVPSLabel.setObjectName(_fromUtf8("ka2HVPSLabel"))
        self.gridLayout.addWidget(self.ka2HVPSLabel, 5, 0, 1, 1)
        self.ka2LVSwitchLabel = QtGui.QLabel(self.klystronGroup)
        self.ka2LVSwitchLabel.setObjectName(_fromUtf8("ka2LVSwitchLabel"))
        self.gridLayout.addWidget(self.ka2LVSwitchLabel, 4, 0, 1, 1)
        self.ka1HVSwitchLabel = QtGui.QLabel(self.klystronGroup)
        self.ka1HVSwitchLabel.setObjectName(_fromUtf8("ka1HVSwitchLabel"))
        self.gridLayout.addWidget(self.ka1HVSwitchLabel, 3, 0, 1, 1)
        self.ka1HVPSLabel = QtGui.QLabel(self.klystronGroup)
        self.ka1HVPSLabel.setObjectName(_fromUtf8("ka1HVPSLabel"))
        self.gridLayout.addWidget(self.ka1HVPSLabel, 2, 0, 1, 1)
        self.ka1HVSwitchCheck = QtGui.QCheckBox(self.klystronGroup)
        self.ka1HVSwitchCheck.setText(_fromUtf8(""))
        self.ka1HVSwitchCheck.setObjectName(_fromUtf8("ka1HVSwitchCheck"))
        self.gridLayout.addWidget(self.ka1HVSwitchCheck, 3, 4, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.klystronGroup)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 0, 4, 1, 1)
        self.ka1HVSwitchRead = TaurusLed(self.klystronGroup)
        self.ka1HVSwitchRead.setMinimumSize(QtCore.QSize(15, 15))
        self.ka1HVSwitchRead.setMaximumSize(QtCore.QSize(15, 15))
        self.ka1HVSwitchRead.setObjectName(_fromUtf8("ka1HVSwitchRead"))
        self.gridLayout.addWidget(self.ka1HVSwitchRead, 3, 1, 1, 1)
        self.ka1HVSwitchWrite = QtGui.QCheckBox(self.klystronGroup)
        self.ka1HVSwitchWrite.setObjectName(_fromUtf8("ka1HVSwitchWrite"))
        self.gridLayout.addWidget(self.ka1HVSwitchWrite, 3, 2, 1, 1)
        self.PresentWriteTitle = QtGui.QLabel(self.klystronGroup)
        self.PresentWriteTitle.setObjectName(_fromUtf8("PresentWriteTitle"))
        self.gridLayout.addWidget(self.PresentWriteTitle, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 1, 1, 1)
        self.ka1LVSwitchLabel = QtGui.QLabel(self.klystronGroup)
        self.ka1LVSwitchLabel.setObjectName(_fromUtf8("ka1LVSwitchLabel"))
        self.gridLayout.addWidget(self.ka1LVSwitchLabel, 1, 0, 1, 1)
        self.ka1LVSwitchRead = TaurusLed(self.klystronGroup)
        self.ka1LVSwitchRead.setMinimumSize(QtCore.QSize(15, 15))
        self.ka1LVSwitchRead.setMaximumSize(QtCore.QSize(15, 15))
        self.ka1LVSwitchRead.setObjectName(_fromUtf8("ka1LVSwitchRead"))
        self.gridLayout.addWidget(self.ka1LVSwitchRead, 1, 1, 1, 1)
        self.ka1LVSwitchCheck = QtGui.QCheckBox(self.klystronGroup)
        self.ka1LVSwitchCheck.setText(_fromUtf8(""))
        self.ka1LVSwitchCheck.setObjectName(_fromUtf8("ka1LVSwitchCheck"))
        self.gridLayout.addWidget(self.ka1LVSwitchCheck, 1, 4, 1, 1)
        self.ka1HVPSCheck = QtGui.QCheckBox(self.klystronGroup)
        self.ka1HVPSCheck.setText(_fromUtf8(""))
        self.ka1HVPSCheck.setObjectName(_fromUtf8("ka1HVPSCheck"))
        self.gridLayout.addWidget(self.ka1HVPSCheck, 2, 4, 1, 1)
        self.ka1HVPSWrite = QtGui.QDoubleSpinBox(self.klystronGroup)
        self.ka1HVPSWrite.setObjectName(_fromUtf8("ka1HVPSWrite"))
        self.gridLayout.addWidget(self.ka1HVPSWrite, 2, 2, 1, 1)
        self.SaveRetrieveTitle = QtGui.QLabel(self.klystronGroup)
        self.SaveRetrieveTitle.setObjectName(_fromUtf8("SaveRetrieveTitle"))
        self.gridLayout.addWidget(self.SaveRetrieveTitle, 0, 2, 1, 1)
        self.ka1HVPSRead = TaurusLabel(self.klystronGroup)
        self.ka1HVPSRead.setObjectName(_fromUtf8("ka1HVPSRead"))
        self.gridLayout.addWidget(self.ka1HVPSRead, 2, 1, 1, 1)
        self.ka1LVSwitchWrite = QtGui.QCheckBox(self.klystronGroup)
        self.ka1LVSwitchWrite.setObjectName(_fromUtf8("ka1LVSwitchWrite"))
        self.gridLayout.addWidget(self.ka1LVSwitchWrite, 1, 2, 1, 1)
        self.ka2HVSwitchLabel = QtGui.QLabel(self.klystronGroup)
        self.ka2HVSwitchLabel.setObjectName(_fromUtf8("ka2HVSwitchLabel"))
        self.gridLayout.addWidget(self.ka2HVSwitchLabel, 6, 0, 1, 1)
        self.ka2LVSwitchRead = TaurusLed(self.klystronGroup)
        self.ka2LVSwitchRead.setMinimumSize(QtCore.QSize(15, 15))
        self.ka2LVSwitchRead.setMaximumSize(QtCore.QSize(15, 15))
        self.ka2LVSwitchRead.setObjectName(_fromUtf8("ka2LVSwitchRead"))
        self.gridLayout.addWidget(self.ka2LVSwitchRead, 4, 1, 1, 1)
        self.ka2HVPSRead = TaurusLabel(self.klystronGroup)
        self.ka2HVPSRead.setObjectName(_fromUtf8("ka2HVPSRead"))
        self.gridLayout.addWidget(self.ka2HVPSRead, 5, 1, 1, 1)
        self.ka2HVSwitchRead = TaurusLed(self.klystronGroup)
        self.ka2HVSwitchRead.setMinimumSize(QtCore.QSize(15, 15))
        self.ka2HVSwitchRead.setMaximumSize(QtCore.QSize(15, 15))
        self.ka2HVSwitchRead.setObjectName(_fromUtf8("ka2HVSwitchRead"))
        self.gridLayout.addWidget(self.ka2HVSwitchRead, 6, 1, 1, 1)
        self.ka2LVSwitchWrite = QtGui.QCheckBox(self.klystronGroup)
        self.ka2LVSwitchWrite.setObjectName(_fromUtf8("ka2LVSwitchWrite"))
        self.gridLayout.addWidget(self.ka2LVSwitchWrite, 4, 2, 1, 1)
        self.ka2HVPSWrite = QtGui.QDoubleSpinBox(self.klystronGroup)
        self.ka2HVPSWrite.setObjectName(_fromUtf8("ka2HVPSWrite"))
        self.gridLayout.addWidget(self.ka2HVPSWrite, 5, 2, 1, 1)
        self.ka2HVSwitchWrite = QtGui.QCheckBox(self.klystronGroup)
        self.ka2HVSwitchWrite.setObjectName(_fromUtf8("ka2HVSwitchWrite"))
        self.gridLayout.addWidget(self.ka2HVSwitchWrite, 6, 2, 1, 1)
        self.ka2LVSwitchCheck = QtGui.QCheckBox(self.klystronGroup)
        self.ka2LVSwitchCheck.setText(_fromUtf8(""))
        self.ka2LVSwitchCheck.setObjectName(_fromUtf8("ka2LVSwitchCheck"))
        self.gridLayout.addWidget(self.ka2LVSwitchCheck, 4, 4, 1, 1)
        self.ka2HVPSCheck = QtGui.QCheckBox(self.klystronGroup)
        self.ka2HVPSCheck.setText(_fromUtf8(""))
        self.ka2HVPSCheck.setObjectName(_fromUtf8("ka2HVPSCheck"))
        self.gridLayout.addWidget(self.ka2HVPSCheck, 5, 4, 1, 1)
        self.ka2HVSwitchCheck = QtGui.QCheckBox(self.klystronGroup)
        self.ka2HVSwitchCheck.setText(_fromUtf8(""))
        self.ka2HVSwitchCheck.setObjectName(_fromUtf8("ka2HVSwitchCheck"))
        self.gridLayout.addWidget(self.ka2HVSwitchCheck, 6, 4, 1, 1)
        self.line = QtGui.QFrame(self.klystronGroup)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 3, 6, 1)
        self.gridLayout_3.addWidget(self.klystronGroup, 0, 0, 1, 1)

        self.retranslateUi(klystronSnapshot)
        QtCore.QMetaObject.connectSlotsByName(klystronSnapshot)

    def retranslateUi(self, klystronSnapshot):
        klystronSnapshot.setWindowTitle(QtGui.QApplication.translate("klystronSnapshot", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.klystronGroup.setTitle(QtGui.QApplication.translate("klystronSnapshot", "Klystrons", None, QtGui.QApplication.UnicodeUTF8))
        self.ka2HVPSLabel.setText(QtGui.QApplication.translate("klystronSnapshot", "KA2 High Voltage PS", None, QtGui.QApplication.UnicodeUTF8))
        self.ka2LVSwitchLabel.setText(QtGui.QApplication.translate("klystronSnapshot", "KA2 Low Voltage Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.ka1HVSwitchLabel.setText(QtGui.QApplication.translate("klystronSnapshot", "KA1 HVPS Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.ka1HVPSLabel.setText(QtGui.QApplication.translate("klystronSnapshot", "KA1 High Voltage PS", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("klystronSnapshot", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.ka1HVSwitchWrite.setText(QtGui.QApplication.translate("klystronSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.PresentWriteTitle.setText(QtGui.QApplication.translate("klystronSnapshot", "Present value", None, QtGui.QApplication.UnicodeUTF8))
        self.ka1LVSwitchLabel.setText(QtGui.QApplication.translate("klystronSnapshot", "KA1 Low Voltage Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveRetrieveTitle.setText(QtGui.QApplication.translate("klystronSnapshot", "Save/Retrieve", None, QtGui.QApplication.UnicodeUTF8))
        self.ka1LVSwitchWrite.setText(QtGui.QApplication.translate("klystronSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.ka2HVSwitchLabel.setText(QtGui.QApplication.translate("klystronSnapshot", "KA2 HVPS Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.ka2LVSwitchWrite.setText(QtGui.QApplication.translate("klystronSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.ka2HVSwitchWrite.setText(QtGui.QApplication.translate("klystronSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusLabel, TaurusLed
from taurus.qt.qtgui.container import TaurusGroupBox
from taurus.qt.qtgui.panel import TaurusWidget
