# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/ui/snapshot_coolingloops.ui'
#
# Created: Wed Mar 12 08:57:24 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_coolingLoopSnapshot(object):
    def setupUi(self, coolingLoopSnapshot):
        coolingLoopSnapshot.setObjectName(_fromUtf8("coolingLoopSnapshot"))
        coolingLoopSnapshot.resize(363, 215)
        self.gridLayout = QtGui.QGridLayout(coolingLoopSnapshot)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.coolingLoopGroup = TaurusGroupBox(coolingLoopSnapshot)
        self.coolingLoopGroup.setObjectName(_fromUtf8("coolingLoopGroup"))
        self.gridLayout_2 = QtGui.QGridLayout(self.coolingLoopGroup)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.collingLoop1SwitchReading = TaurusLed(self.coolingLoopGroup)
        self.collingLoop1SwitchReading.setMinimumSize(QtCore.QSize(15, 15))
        self.collingLoop1SwitchReading.setMaximumSize(QtCore.QSize(15, 15))
        self.collingLoop1SwitchReading.setObjectName(_fromUtf8("collingLoop1SwitchReading"))
        self.gridLayout_2.addWidget(self.collingLoop1SwitchReading, 2, 1, 1, 1)
        self.coolingLoop1SetpointCheck = QtGui.QCheckBox(self.coolingLoopGroup)
        self.coolingLoop1SetpointCheck.setText(_fromUtf8(""))
        self.coolingLoop1SetpointCheck.setObjectName(_fromUtf8("coolingLoop1SetpointCheck"))
        self.gridLayout_2.addWidget(self.coolingLoop1SetpointCheck, 1, 4, 1, 1)
        self.coolingLoop1SetpointLabel = QtGui.QLabel(self.coolingLoopGroup)
        self.coolingLoop1SetpointLabel.setObjectName(_fromUtf8("coolingLoop1SetpointLabel"))
        self.gridLayout_2.addWidget(self.coolingLoop1SetpointLabel, 1, 0, 1, 1)
        self.collingLoop1SwitchLabel = QtGui.QLabel(self.coolingLoopGroup)
        self.collingLoop1SwitchLabel.setObjectName(_fromUtf8("collingLoop1SwitchLabel"))
        self.gridLayout_2.addWidget(self.collingLoop1SwitchLabel, 2, 0, 1, 1)
        self.collingLoop1SwitchValue = QtGui.QCheckBox(self.coolingLoopGroup)
        self.collingLoop1SwitchValue.setObjectName(_fromUtf8("collingLoop1SwitchValue"))
        self.gridLayout_2.addWidget(self.collingLoop1SwitchValue, 2, 2, 1, 1)
        self.coolingLoop1SetpointValue = QtGui.QDoubleSpinBox(self.coolingLoopGroup)
        self.coolingLoop1SetpointValue.setObjectName(_fromUtf8("coolingLoop1SetpointValue"))
        self.gridLayout_2.addWidget(self.coolingLoop1SetpointValue, 1, 2, 1, 1)
        self.coolingLoop1SetpointReading = TaurusLabel(self.coolingLoopGroup)
        self.coolingLoop1SetpointReading.setObjectName(_fromUtf8("coolingLoop1SetpointReading"))
        self.gridLayout_2.addWidget(self.coolingLoop1SetpointReading, 1, 1, 1, 1)
        self.collingLoop2SwitchLabel = QtGui.QLabel(self.coolingLoopGroup)
        self.collingLoop2SwitchLabel.setObjectName(_fromUtf8("collingLoop2SwitchLabel"))
        self.gridLayout_2.addWidget(self.collingLoop2SwitchLabel, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 7, 1, 1, 1)
        self.PresentValueTitle = QtGui.QLabel(self.coolingLoopGroup)
        self.PresentValueTitle.setObjectName(_fromUtf8("PresentValueTitle"))
        self.gridLayout_2.addWidget(self.PresentValueTitle, 0, 1, 1, 1)
        self.collingLoop1SwitchCheck = QtGui.QCheckBox(self.coolingLoopGroup)
        self.collingLoop1SwitchCheck.setText(_fromUtf8(""))
        self.collingLoop1SwitchCheck.setObjectName(_fromUtf8("collingLoop1SwitchCheck"))
        self.gridLayout_2.addWidget(self.collingLoop1SwitchCheck, 2, 4, 1, 1)
        self.SaveRetrieveTitle = QtGui.QLabel(self.coolingLoopGroup)
        self.SaveRetrieveTitle.setObjectName(_fromUtf8("SaveRetrieveTitle"))
        self.gridLayout_2.addWidget(self.SaveRetrieveTitle, 0, 2, 1, 1)
        self.coolingLoop3SetpointLabel = QtGui.QLabel(self.coolingLoopGroup)
        self.coolingLoop3SetpointLabel.setObjectName(_fromUtf8("coolingLoop3SetpointLabel"))
        self.gridLayout_2.addWidget(self.coolingLoop3SetpointLabel, 5, 0, 1, 1)
        self.coolingLoop2SetpointLabel = QtGui.QLabel(self.coolingLoopGroup)
        self.coolingLoop2SetpointLabel.setObjectName(_fromUtf8("coolingLoop2SetpointLabel"))
        self.gridLayout_2.addWidget(self.coolingLoop2SetpointLabel, 3, 0, 1, 1)
        self.collingLoop3SwitchLabel = QtGui.QLabel(self.coolingLoopGroup)
        self.collingLoop3SwitchLabel.setObjectName(_fromUtf8("collingLoop3SwitchLabel"))
        self.gridLayout_2.addWidget(self.collingLoop3SwitchLabel, 6, 0, 1, 1)
        self.coolingLoop2SetpointReading = TaurusLabel(self.coolingLoopGroup)
        self.coolingLoop2SetpointReading.setObjectName(_fromUtf8("coolingLoop2SetpointReading"))
        self.gridLayout_2.addWidget(self.coolingLoop2SetpointReading, 3, 1, 1, 1)
        self.collingLoop2SwitchReading = TaurusLed(self.coolingLoopGroup)
        self.collingLoop2SwitchReading.setMinimumSize(QtCore.QSize(15, 15))
        self.collingLoop2SwitchReading.setMaximumSize(QtCore.QSize(15, 15))
        self.collingLoop2SwitchReading.setObjectName(_fromUtf8("collingLoop2SwitchReading"))
        self.gridLayout_2.addWidget(self.collingLoop2SwitchReading, 4, 1, 1, 1)
        self.coolingLoop3SetpointReading = TaurusLabel(self.coolingLoopGroup)
        self.coolingLoop3SetpointReading.setObjectName(_fromUtf8("coolingLoop3SetpointReading"))
        self.gridLayout_2.addWidget(self.coolingLoop3SetpointReading, 5, 1, 1, 1)
        self.collingLoop3SwitchReading = TaurusLed(self.coolingLoopGroup)
        self.collingLoop3SwitchReading.setMinimumSize(QtCore.QSize(15, 15))
        self.collingLoop3SwitchReading.setMaximumSize(QtCore.QSize(15, 15))
        self.collingLoop3SwitchReading.setObjectName(_fromUtf8("collingLoop3SwitchReading"))
        self.gridLayout_2.addWidget(self.collingLoop3SwitchReading, 6, 1, 1, 1)
        self.coolingLoop2SetpointValue = QtGui.QDoubleSpinBox(self.coolingLoopGroup)
        self.coolingLoop2SetpointValue.setObjectName(_fromUtf8("coolingLoop2SetpointValue"))
        self.gridLayout_2.addWidget(self.coolingLoop2SetpointValue, 3, 2, 1, 1)
        self.collingLoop2SwitchValue = QtGui.QCheckBox(self.coolingLoopGroup)
        self.collingLoop2SwitchValue.setObjectName(_fromUtf8("collingLoop2SwitchValue"))
        self.gridLayout_2.addWidget(self.collingLoop2SwitchValue, 4, 2, 1, 1)
        self.coolingLoop3SetpointValue = QtGui.QDoubleSpinBox(self.coolingLoopGroup)
        self.coolingLoop3SetpointValue.setObjectName(_fromUtf8("coolingLoop3SetpointValue"))
        self.gridLayout_2.addWidget(self.coolingLoop3SetpointValue, 5, 2, 1, 1)
        self.collingLoop3SwitchValue = QtGui.QCheckBox(self.coolingLoopGroup)
        self.collingLoop3SwitchValue.setObjectName(_fromUtf8("collingLoop3SwitchValue"))
        self.gridLayout_2.addWidget(self.collingLoop3SwitchValue, 6, 2, 1, 1)
        self.coolingLoop2SetpointCheck = QtGui.QCheckBox(self.coolingLoopGroup)
        self.coolingLoop2SetpointCheck.setText(_fromUtf8(""))
        self.coolingLoop2SetpointCheck.setObjectName(_fromUtf8("coolingLoop2SetpointCheck"))
        self.gridLayout_2.addWidget(self.coolingLoop2SetpointCheck, 3, 4, 1, 1)
        self.collingLoop2SwitchCheck = QtGui.QCheckBox(self.coolingLoopGroup)
        self.collingLoop2SwitchCheck.setText(_fromUtf8(""))
        self.collingLoop2SwitchCheck.setObjectName(_fromUtf8("collingLoop2SwitchCheck"))
        self.gridLayout_2.addWidget(self.collingLoop2SwitchCheck, 4, 4, 1, 1)
        self.coolingLoop3SetpointCheck = QtGui.QCheckBox(self.coolingLoopGroup)
        self.coolingLoop3SetpointCheck.setText(_fromUtf8(""))
        self.coolingLoop3SetpointCheck.setObjectName(_fromUtf8("coolingLoop3SetpointCheck"))
        self.gridLayout_2.addWidget(self.coolingLoop3SetpointCheck, 5, 4, 1, 1)
        self.collingLoop3SwitchCheck = QtGui.QCheckBox(self.coolingLoopGroup)
        self.collingLoop3SwitchCheck.setText(_fromUtf8(""))
        self.collingLoop3SwitchCheck.setObjectName(_fromUtf8("collingLoop3SwitchCheck"))
        self.gridLayout_2.addWidget(self.collingLoop3SwitchCheck, 6, 4, 1, 1)
        self.line = QtGui.QFrame(self.coolingLoopGroup)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 1, 3, 6, 1)
        self.ToApplyTitle = QtGui.QCheckBox(self.coolingLoopGroup)
        self.ToApplyTitle.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ToApplyTitle.setObjectName(_fromUtf8("ToApplyTitle"))
        self.gridLayout_2.addWidget(self.ToApplyTitle, 0, 4, 1, 1)
        self.gridLayout.addWidget(self.coolingLoopGroup, 0, 0, 1, 1)

        self.retranslateUi(coolingLoopSnapshot)
        QtCore.QMetaObject.connectSlotsByName(coolingLoopSnapshot)

    def retranslateUi(self, coolingLoopSnapshot):
        coolingLoopSnapshot.setWindowTitle(QtGui.QApplication.translate("coolingLoopSnapshot", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.coolingLoopGroup.setTitle(QtGui.QApplication.translate("coolingLoopSnapshot", "Cooling Loops", None, QtGui.QApplication.UnicodeUTF8))
        self.coolingLoop1SetpointLabel.setText(QtGui.QApplication.translate("coolingLoopSnapshot", "cl1 Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.collingLoop1SwitchLabel.setText(QtGui.QApplication.translate("coolingLoopSnapshot", "cl1 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.collingLoop1SwitchValue.setText(QtGui.QApplication.translate("coolingLoopSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.collingLoop2SwitchLabel.setText(QtGui.QApplication.translate("coolingLoopSnapshot", "cl2 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.PresentValueTitle.setText(QtGui.QApplication.translate("coolingLoopSnapshot", "Present value", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveRetrieveTitle.setText(QtGui.QApplication.translate("coolingLoopSnapshot", "Save/Retrieve", None, QtGui.QApplication.UnicodeUTF8))
        self.coolingLoop3SetpointLabel.setText(QtGui.QApplication.translate("coolingLoopSnapshot", "cl3 Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.coolingLoop2SetpointLabel.setText(QtGui.QApplication.translate("coolingLoopSnapshot", "cl2 Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.collingLoop3SwitchLabel.setText(QtGui.QApplication.translate("coolingLoopSnapshot", "cl3 Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.collingLoop2SwitchValue.setText(QtGui.QApplication.translate("coolingLoopSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.collingLoop3SwitchValue.setText(QtGui.QApplication.translate("coolingLoopSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.ToApplyTitle.setText(QtGui.QApplication.translate("coolingLoopSnapshot", "All", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusLabel, TaurusLed
from taurus.qt.qtgui.container import TaurusGroupBox
from taurus.qt.qtgui.panel import TaurusWidget
