# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'snapshot_egun.ui'
#
# Created: Wed Mar 12 08:36:24 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_electronGunSnapshot(object):
    def setupUi(self, electronGunSnapshot):
        electronGunSnapshot.setObjectName(_fromUtf8("electronGunSnapshot"))
        electronGunSnapshot.resize(380, 200)
        self.gridLayout = QtGui.QGridLayout(electronGunSnapshot)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.electronGunGroup = TaurusGroupBox(electronGunSnapshot)
        self.electronGunGroup.setObjectName(_fromUtf8("electronGunGroup"))
        self.gridLayout_2 = QtGui.QGridLayout(self.electronGunGroup)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.PresentValueTitle = QtGui.QLabel(self.electronGunGroup)
        self.PresentValueTitle.setObjectName(_fromUtf8("PresentValueTitle"))
        self.gridLayout_2.addWidget(self.PresentValueTitle, 0, 1, 1, 1)
        self.SaveRetrieveTitle = QtGui.QLabel(self.electronGunGroup)
        self.SaveRetrieveTitle.setObjectName(_fromUtf8("SaveRetrieveTitle"))
        self.gridLayout_2.addWidget(self.SaveRetrieveTitle, 0, 2, 1, 1)
        self.GunFilamentLowVoltageLabel = QtGui.QLabel(self.electronGunGroup)
        self.GunFilamentLowVoltageLabel.setObjectName(_fromUtf8("GunFilamentLowVoltageLabel"))
        self.gridLayout_2.addWidget(self.GunFilamentLowVoltageLabel, 1, 0, 1, 1)
        self.GunFilamentLowVoltageReading = TaurusLabel(self.electronGunGroup)
        self.GunFilamentLowVoltageReading.setObjectName(_fromUtf8("GunFilamentLowVoltageReading"))
        self.gridLayout_2.addWidget(self.GunFilamentLowVoltageReading, 1, 1, 1, 1)
        self.GunFilamentLowVoltageValue = QtGui.QDoubleSpinBox(self.electronGunGroup)
        self.GunFilamentLowVoltageValue.setObjectName(_fromUtf8("GunFilamentLowVoltageValue"))
        self.gridLayout_2.addWidget(self.GunFilamentLowVoltageValue, 1, 2, 1, 1)
        self.line = QtGui.QFrame(self.electronGunGroup)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 1, 3, 7, 1)
        self.GunFilamentLowVoltageCheck = QtGui.QCheckBox(self.electronGunGroup)
        self.GunFilamentLowVoltageCheck.setText(_fromUtf8(""))
        self.GunFilamentLowVoltageCheck.setObjectName(_fromUtf8("GunFilamentLowVoltageCheck"))
        self.gridLayout_2.addWidget(self.GunFilamentLowVoltageCheck, 1, 4, 1, 1)
        self.GunKathodeLowVoltageReading = TaurusLabel(self.electronGunGroup)
        self.GunKathodeLowVoltageReading.setObjectName(_fromUtf8("GunKathodeLowVoltageReading"))
        self.gridLayout_2.addWidget(self.GunKathodeLowVoltageReading, 2, 1, 2, 1)
        self.GunKathodeLowVoltageValue = QtGui.QDoubleSpinBox(self.electronGunGroup)
        self.GunKathodeLowVoltageValue.setObjectName(_fromUtf8("GunKathodeLowVoltageValue"))
        self.gridLayout_2.addWidget(self.GunKathodeLowVoltageValue, 2, 2, 2, 1)
        self.GunKathodeLowVoltageLabel = QtGui.QLabel(self.electronGunGroup)
        self.GunKathodeLowVoltageLabel.setObjectName(_fromUtf8("GunKathodeLowVoltageLabel"))
        self.gridLayout_2.addWidget(self.GunKathodeLowVoltageLabel, 3, 0, 1, 1)
        self.GunKathodeLowVoltageCheck = QtGui.QCheckBox(self.electronGunGroup)
        self.GunKathodeLowVoltageCheck.setText(_fromUtf8(""))
        self.GunKathodeLowVoltageCheck.setObjectName(_fromUtf8("GunKathodeLowVoltageCheck"))
        self.gridLayout_2.addWidget(self.GunKathodeLowVoltageCheck, 3, 4, 1, 1)
        self.GunLowVoltageSwitchLabel = QtGui.QLabel(self.electronGunGroup)
        self.GunLowVoltageSwitchLabel.setObjectName(_fromUtf8("GunLowVoltageSwitchLabel"))
        self.gridLayout_2.addWidget(self.GunLowVoltageSwitchLabel, 4, 0, 1, 1)
        self.GunLowVoltageSwitchReading = TaurusLed(self.electronGunGroup)
        self.GunLowVoltageSwitchReading.setMinimumSize(QtCore.QSize(15, 15))
        self.GunLowVoltageSwitchReading.setMaximumSize(QtCore.QSize(15, 15))
        self.GunLowVoltageSwitchReading.setObjectName(_fromUtf8("GunLowVoltageSwitchReading"))
        self.gridLayout_2.addWidget(self.GunLowVoltageSwitchReading, 4, 1, 1, 1)
        self.GunLowVoltageSwitchValue = QtGui.QCheckBox(self.electronGunGroup)
        self.GunLowVoltageSwitchValue.setObjectName(_fromUtf8("GunLowVoltageSwitchValue"))
        self.gridLayout_2.addWidget(self.GunLowVoltageSwitchValue, 4, 2, 1, 1)
        self.GunLowVoltageSwitchCheck = QtGui.QCheckBox(self.electronGunGroup)
        self.GunLowVoltageSwitchCheck.setText(_fromUtf8(""))
        self.GunLowVoltageSwitchCheck.setObjectName(_fromUtf8("GunLowVoltageSwitchCheck"))
        self.gridLayout_2.addWidget(self.GunLowVoltageSwitchCheck, 4, 4, 1, 1)
        self.GunHighVoltagePowerSupplyLabel = QtGui.QLabel(self.electronGunGroup)
        self.GunHighVoltagePowerSupplyLabel.setObjectName(_fromUtf8("GunHighVoltagePowerSupplyLabel"))
        self.gridLayout_2.addWidget(self.GunHighVoltagePowerSupplyLabel, 5, 0, 1, 1)
        self.GunHighVoltagePowerSupplyReading = TaurusLabel(self.electronGunGroup)
        self.GunHighVoltagePowerSupplyReading.setObjectName(_fromUtf8("GunHighVoltagePowerSupplyReading"))
        self.gridLayout_2.addWidget(self.GunHighVoltagePowerSupplyReading, 5, 1, 1, 1)
        self.GunHighVoltagePowerSupplyValue = QtGui.QDoubleSpinBox(self.electronGunGroup)
        self.GunHighVoltagePowerSupplyValue.setObjectName(_fromUtf8("GunHighVoltagePowerSupplyValue"))
        self.gridLayout_2.addWidget(self.GunHighVoltagePowerSupplyValue, 5, 2, 1, 1)
        self.GunHighVoltagePowerSupplyCheck = QtGui.QCheckBox(self.electronGunGroup)
        self.GunHighVoltagePowerSupplyCheck.setText(_fromUtf8(""))
        self.GunHighVoltagePowerSupplyCheck.setObjectName(_fromUtf8("GunHighVoltagePowerSupplyCheck"))
        self.gridLayout_2.addWidget(self.GunHighVoltagePowerSupplyCheck, 5, 4, 1, 1)
        self.HighVoltageSwitchLabel = QtGui.QLabel(self.electronGunGroup)
        self.HighVoltageSwitchLabel.setObjectName(_fromUtf8("HighVoltageSwitchLabel"))
        self.gridLayout_2.addWidget(self.HighVoltageSwitchLabel, 6, 0, 1, 1)
        self.HighVoltageSwitchReading = TaurusLed(self.electronGunGroup)
        self.HighVoltageSwitchReading.setMinimumSize(QtCore.QSize(15, 15))
        self.HighVoltageSwitchReading.setMaximumSize(QtCore.QSize(15, 15))
        self.HighVoltageSwitchReading.setObjectName(_fromUtf8("HighVoltageSwitchReading"))
        self.gridLayout_2.addWidget(self.HighVoltageSwitchReading, 6, 1, 1, 1)
        self.HighVoltageSwitchValue = QtGui.QCheckBox(self.electronGunGroup)
        self.HighVoltageSwitchValue.setObjectName(_fromUtf8("HighVoltageSwitchValue"))
        self.gridLayout_2.addWidget(self.HighVoltageSwitchValue, 6, 2, 1, 1)
        self.HighVoltageSwitchCheck = QtGui.QCheckBox(self.electronGunGroup)
        self.HighVoltageSwitchCheck.setText(_fromUtf8(""))
        self.HighVoltageSwitchCheck.setObjectName(_fromUtf8("HighVoltageSwitchCheck"))
        self.gridLayout_2.addWidget(self.HighVoltageSwitchCheck, 6, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 7, 1, 1, 1)
        self.ToApplyTitle = QtGui.QCheckBox(self.electronGunGroup)
        self.ToApplyTitle.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ToApplyTitle.setObjectName(_fromUtf8("ToApplyTitle"))
        self.gridLayout_2.addWidget(self.ToApplyTitle, 0, 4, 1, 1)
        self.gridLayout.addWidget(self.electronGunGroup, 0, 0, 1, 1)

        self.retranslateUi(electronGunSnapshot)
        QtCore.QMetaObject.connectSlotsByName(electronGunSnapshot)

    def retranslateUi(self, electronGunSnapshot):
        electronGunSnapshot.setWindowTitle(QtGui.QApplication.translate("electronGunSnapshot", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.electronGunGroup.setTitle(QtGui.QApplication.translate("electronGunSnapshot", "Electron Gun", None, QtGui.QApplication.UnicodeUTF8))
        self.PresentValueTitle.setText(QtGui.QApplication.translate("electronGunSnapshot", "Present value", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveRetrieveTitle.setText(QtGui.QApplication.translate("electronGunSnapshot", "Save/Retrieve", None, QtGui.QApplication.UnicodeUTF8))
        self.GunFilamentLowVoltageLabel.setText(QtGui.QApplication.translate("electronGunSnapshot", "Filament Low Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.GunKathodeLowVoltageLabel.setText(QtGui.QApplication.translate("electronGunSnapshot", "Kathode Low Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.GunLowVoltageSwitchLabel.setText(QtGui.QApplication.translate("electronGunSnapshot", "Low Voltage Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.GunLowVoltageSwitchValue.setText(QtGui.QApplication.translate("electronGunSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.GunHighVoltagePowerSupplyLabel.setText(QtGui.QApplication.translate("electronGunSnapshot", "High Voltage PS", None, QtGui.QApplication.UnicodeUTF8))
        self.HighVoltageSwitchLabel.setText(QtGui.QApplication.translate("electronGunSnapshot", "High Voltage Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.HighVoltageSwitchValue.setText(QtGui.QApplication.translate("electronGunSnapshot", "on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.ToApplyTitle.setText(QtGui.QApplication.translate("electronGunSnapshot", "All", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusLabel, TaurusLed
from taurus.qt.qtgui.container import TaurusGroupBox
from taurus.qt.qtgui.panel import TaurusWidget
