# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/ui/snapshot_evr.ui'
#
# Created: Mon Nov 30 15:17:37 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_evrSnapshot(object):
    def setupUi(self, evrSnapshot):
        evrSnapshot.setObjectName(_fromUtf8("evrSnapshot"))
        evrSnapshot.resize(289, 383)
        font = QtGui.QFont()
        font.setPointSize(7)
        evrSnapshot.setFont(font)
        self.gridLayout_2 = QtGui.QGridLayout(evrSnapshot)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.evrGroup = TaurusGroupBox(evrSnapshot)
        self.evrGroup.setObjectName(_fromUtf8("evrGroup"))
        self.gridLayout = QtGui.QGridLayout(self.evrGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Fine2Read = TaurusLabel(self.evrGroup)
        self.Fine2Read.setObjectName(_fromUtf8("Fine2Read"))
        self.gridLayout.addWidget(self.Fine2Read, 9, 2, 1, 1)
        self.Delay2Read = TaurusLabel(self.evrGroup)
        self.Delay2Read.setObjectName(_fromUtf8("Delay2Read"))
        self.gridLayout.addWidget(self.Delay2Read, 7, 2, 1, 1)
        self.Width2Read = TaurusLabel(self.evrGroup)
        self.Width2Read.setObjectName(_fromUtf8("Width2Read"))
        self.gridLayout.addWidget(self.Width2Read, 8, 2, 1, 1)
        self.line = QtGui.QFrame(self.evrGroup)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 4, 14, 2)
        self.Delay0Read = TaurusLabel(self.evrGroup)
        self.Delay0Read.setObjectName(_fromUtf8("Delay0Read"))
        self.gridLayout.addWidget(self.Delay0Read, 1, 2, 1, 1)
        self.Fine1Read = TaurusLabel(self.evrGroup)
        self.Fine1Read.setObjectName(_fromUtf8("Fine1Read"))
        self.gridLayout.addWidget(self.Fine1Read, 6, 2, 1, 1)
        self.Delay3Read = TaurusLabel(self.evrGroup)
        self.Delay3Read.setObjectName(_fromUtf8("Delay3Read"))
        self.gridLayout.addWidget(self.Delay3Read, 10, 2, 1, 1)
        self.Width0Read = TaurusLabel(self.evrGroup)
        self.Width0Read.setObjectName(_fromUtf8("Width0Read"))
        self.gridLayout.addWidget(self.Width0Read, 2, 2, 1, 1)
        self.Fine0Read = TaurusLabel(self.evrGroup)
        self.Fine0Read.setObjectName(_fromUtf8("Fine0Read"))
        self.gridLayout.addWidget(self.Fine0Read, 3, 2, 1, 1)
        self.Delay1Read = TaurusLabel(self.evrGroup)
        self.Delay1Read.setObjectName(_fromUtf8("Delay1Read"))
        self.gridLayout.addWidget(self.Delay1Read, 4, 2, 1, 1)
        self.Width1Read = TaurusLabel(self.evrGroup)
        self.Width1Read.setObjectName(_fromUtf8("Width1Read"))
        self.gridLayout.addWidget(self.Width1Read, 5, 2, 1, 1)
        self.Width3Read = TaurusLabel(self.evrGroup)
        self.Width3Read.setObjectName(_fromUtf8("Width3Read"))
        self.gridLayout.addWidget(self.Width3Read, 11, 2, 1, 1)
        self.PresentWriteTitle = QtGui.QLabel(self.evrGroup)
        self.PresentWriteTitle.setObjectName(_fromUtf8("PresentWriteTitle"))
        self.gridLayout.addWidget(self.PresentWriteTitle, 0, 2, 1, 1)
        self.SaveRetrieveTitle = QtGui.QLabel(self.evrGroup)
        self.SaveRetrieveTitle.setObjectName(_fromUtf8("SaveRetrieveTitle"))
        self.gridLayout.addWidget(self.SaveRetrieveTitle, 0, 3, 1, 1)
        self.Delay0Label = QtGui.QLabel(self.evrGroup)
        self.Delay0Label.setObjectName(_fromUtf8("Delay0Label"))
        self.gridLayout.addWidget(self.Delay0Label, 1, 0, 1, 1)
        self.Delay0Write = QtGui.QDoubleSpinBox(self.evrGroup)
        self.Delay0Write.setObjectName(_fromUtf8("Delay0Write"))
        self.gridLayout.addWidget(self.Delay0Write, 1, 3, 1, 1)
        self.Delay0Check = QtGui.QCheckBox(self.evrGroup)
        self.Delay0Check.setText(_fromUtf8(""))
        self.Delay0Check.setObjectName(_fromUtf8("Delay0Check"))
        self.gridLayout.addWidget(self.Delay0Check, 1, 5, 1, 1)
        self.Width0Label = QtGui.QLabel(self.evrGroup)
        self.Width0Label.setObjectName(_fromUtf8("Width0Label"))
        self.gridLayout.addWidget(self.Width0Label, 2, 0, 1, 1)
        self.Width0Write = QtGui.QDoubleSpinBox(self.evrGroup)
        self.Width0Write.setObjectName(_fromUtf8("Width0Write"))
        self.gridLayout.addWidget(self.Width0Write, 2, 3, 1, 1)
        self.Width0Check = QtGui.QCheckBox(self.evrGroup)
        self.Width0Check.setText(_fromUtf8(""))
        self.Width0Check.setObjectName(_fromUtf8("Width0Check"))
        self.gridLayout.addWidget(self.Width0Check, 2, 5, 1, 1)
        self.Fine0Label = QtGui.QLabel(self.evrGroup)
        self.Fine0Label.setObjectName(_fromUtf8("Fine0Label"))
        self.gridLayout.addWidget(self.Fine0Label, 3, 0, 1, 1)
        self.Fine0Write = QtGui.QDoubleSpinBox(self.evrGroup)
        self.Fine0Write.setObjectName(_fromUtf8("Fine0Write"))
        self.gridLayout.addWidget(self.Fine0Write, 3, 3, 1, 1)
        self.Fine0Check = QtGui.QCheckBox(self.evrGroup)
        self.Fine0Check.setText(_fromUtf8(""))
        self.Fine0Check.setObjectName(_fromUtf8("Fine0Check"))
        self.gridLayout.addWidget(self.Fine0Check, 3, 5, 1, 1)
        self.Delay1Label = QtGui.QLabel(self.evrGroup)
        self.Delay1Label.setObjectName(_fromUtf8("Delay1Label"))
        self.gridLayout.addWidget(self.Delay1Label, 4, 0, 1, 1)
        self.Delay1Write = QtGui.QDoubleSpinBox(self.evrGroup)
        self.Delay1Write.setObjectName(_fromUtf8("Delay1Write"))
        self.gridLayout.addWidget(self.Delay1Write, 4, 3, 1, 1)
        self.Delay1Check = QtGui.QCheckBox(self.evrGroup)
        self.Delay1Check.setText(_fromUtf8(""))
        self.Delay1Check.setObjectName(_fromUtf8("Delay1Check"))
        self.gridLayout.addWidget(self.Delay1Check, 4, 5, 1, 1)
        self.Width1Label = QtGui.QLabel(self.evrGroup)
        self.Width1Label.setObjectName(_fromUtf8("Width1Label"))
        self.gridLayout.addWidget(self.Width1Label, 5, 0, 1, 1)
        self.Width1Write = QtGui.QDoubleSpinBox(self.evrGroup)
        self.Width1Write.setObjectName(_fromUtf8("Width1Write"))
        self.gridLayout.addWidget(self.Width1Write, 5, 3, 1, 1)
        self.Width1Check = QtGui.QCheckBox(self.evrGroup)
        self.Width1Check.setText(_fromUtf8(""))
        self.Width1Check.setObjectName(_fromUtf8("Width1Check"))
        self.gridLayout.addWidget(self.Width1Check, 5, 5, 1, 1)
        self.Fine1Label = QtGui.QLabel(self.evrGroup)
        self.Fine1Label.setObjectName(_fromUtf8("Fine1Label"))
        self.gridLayout.addWidget(self.Fine1Label, 6, 0, 1, 1)
        self.Fine1Write = QtGui.QDoubleSpinBox(self.evrGroup)
        self.Fine1Write.setObjectName(_fromUtf8("Fine1Write"))
        self.gridLayout.addWidget(self.Fine1Write, 6, 3, 1, 1)
        self.Fine1Check = QtGui.QCheckBox(self.evrGroup)
        self.Fine1Check.setText(_fromUtf8(""))
        self.Fine1Check.setObjectName(_fromUtf8("Fine1Check"))
        self.gridLayout.addWidget(self.Fine1Check, 6, 5, 1, 1)
        self.Delay2Label = QtGui.QLabel(self.evrGroup)
        self.Delay2Label.setObjectName(_fromUtf8("Delay2Label"))
        self.gridLayout.addWidget(self.Delay2Label, 7, 0, 1, 1)
        self.Delay2Write = QtGui.QDoubleSpinBox(self.evrGroup)
        self.Delay2Write.setObjectName(_fromUtf8("Delay2Write"))
        self.gridLayout.addWidget(self.Delay2Write, 7, 3, 1, 1)
        self.Delay2Check = QtGui.QCheckBox(self.evrGroup)
        self.Delay2Check.setText(_fromUtf8(""))
        self.Delay2Check.setObjectName(_fromUtf8("Delay2Check"))
        self.gridLayout.addWidget(self.Delay2Check, 7, 5, 1, 1)
        self.Width2Label = QtGui.QLabel(self.evrGroup)
        self.Width2Label.setObjectName(_fromUtf8("Width2Label"))
        self.gridLayout.addWidget(self.Width2Label, 8, 0, 1, 1)
        self.Width2Write = QtGui.QDoubleSpinBox(self.evrGroup)
        self.Width2Write.setObjectName(_fromUtf8("Width2Write"))
        self.gridLayout.addWidget(self.Width2Write, 8, 3, 1, 1)
        self.Width2Check = QtGui.QCheckBox(self.evrGroup)
        self.Width2Check.setText(_fromUtf8(""))
        self.Width2Check.setObjectName(_fromUtf8("Width2Check"))
        self.gridLayout.addWidget(self.Width2Check, 8, 5, 1, 1)
        self.Fine2Label = QtGui.QLabel(self.evrGroup)
        self.Fine2Label.setObjectName(_fromUtf8("Fine2Label"))
        self.gridLayout.addWidget(self.Fine2Label, 9, 0, 1, 1)
        self.Fine2Write = QtGui.QDoubleSpinBox(self.evrGroup)
        self.Fine2Write.setObjectName(_fromUtf8("Fine2Write"))
        self.gridLayout.addWidget(self.Fine2Write, 9, 3, 1, 1)
        self.Fine2Check = QtGui.QCheckBox(self.evrGroup)
        self.Fine2Check.setText(_fromUtf8(""))
        self.Fine2Check.setObjectName(_fromUtf8("Fine2Check"))
        self.gridLayout.addWidget(self.Fine2Check, 9, 5, 1, 1)
        self.Delay3Label = QtGui.QLabel(self.evrGroup)
        self.Delay3Label.setObjectName(_fromUtf8("Delay3Label"))
        self.gridLayout.addWidget(self.Delay3Label, 10, 0, 1, 1)
        self.Delay3Write = QtGui.QDoubleSpinBox(self.evrGroup)
        self.Delay3Write.setObjectName(_fromUtf8("Delay3Write"))
        self.gridLayout.addWidget(self.Delay3Write, 10, 3, 1, 1)
        self.Delay3Check = QtGui.QCheckBox(self.evrGroup)
        self.Delay3Check.setText(_fromUtf8(""))
        self.Delay3Check.setObjectName(_fromUtf8("Delay3Check"))
        self.gridLayout.addWidget(self.Delay3Check, 10, 5, 1, 1)
        self.Width3Label = QtGui.QLabel(self.evrGroup)
        self.Width3Label.setObjectName(_fromUtf8("Width3Label"))
        self.gridLayout.addWidget(self.Width3Label, 11, 0, 1, 1)
        self.Width3Write = QtGui.QDoubleSpinBox(self.evrGroup)
        self.Width3Write.setObjectName(_fromUtf8("Width3Write"))
        self.gridLayout.addWidget(self.Width3Write, 11, 3, 1, 1)
        self.Width3Check = QtGui.QCheckBox(self.evrGroup)
        self.Width3Check.setText(_fromUtf8(""))
        self.Width3Check.setObjectName(_fromUtf8("Width3Check"))
        self.gridLayout.addWidget(self.Width3Check, 11, 5, 1, 1)
        self.Fine3Label = QtGui.QLabel(self.evrGroup)
        self.Fine3Label.setObjectName(_fromUtf8("Fine3Label"))
        self.gridLayout.addWidget(self.Fine3Label, 12, 0, 1, 1)
        self.Fine3Write = QtGui.QDoubleSpinBox(self.evrGroup)
        self.Fine3Write.setObjectName(_fromUtf8("Fine3Write"))
        self.gridLayout.addWidget(self.Fine3Write, 12, 3, 1, 1)
        self.Fine3Check = QtGui.QCheckBox(self.evrGroup)
        self.Fine3Check.setText(_fromUtf8(""))
        self.Fine3Check.setObjectName(_fromUtf8("Fine3Check"))
        self.gridLayout.addWidget(self.Fine3Check, 12, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 13, 2, 1, 1)
        self.Fine3Read = TaurusLabel(self.evrGroup)
        self.Fine3Read.setObjectName(_fromUtf8("Fine3Read"))
        self.gridLayout.addWidget(self.Fine3Read, 12, 2, 1, 1)
        self.gridLayout_2.addWidget(self.evrGroup, 0, 0, 1, 1)

        self.retranslateUi(evrSnapshot)
        QtCore.QMetaObject.connectSlotsByName(evrSnapshot)

    def retranslateUi(self, evrSnapshot):
        evrSnapshot.setWindowTitle(_translate("evrSnapshot", "Form", None))
        self.evrGroup.setTitle(_translate("evrSnapshot", "EVR300", None))
        self.PresentWriteTitle.setText(_translate("evrSnapshot", "Present value", None))
        self.SaveRetrieveTitle.setText(_translate("evrSnapshot", "Save/Retrieve", None))
        self.Delay0Label.setText(_translate("evrSnapshot", "CH0 Delay", None))
        self.Width0Label.setText(_translate("evrSnapshot", "CH0 Width", None))
        self.Fine0Label.setText(_translate("evrSnapshot", "CH0 Fine tune", None))
        self.Delay1Label.setText(_translate("evrSnapshot", "CH1 Delay", None))
        self.Width1Label.setText(_translate("evrSnapshot", "CH1 Width", None))
        self.Fine1Label.setText(_translate("evrSnapshot", "CH1 Fine tune", None))
        self.Delay2Label.setText(_translate("evrSnapshot", "CH2 Delay", None))
        self.Width2Label.setText(_translate("evrSnapshot", "CH2 Width", None))
        self.Fine2Label.setText(_translate("evrSnapshot", "CH2 Fine tune", None))
        self.Delay3Label.setText(_translate("evrSnapshot", "CH3 Delay", None))
        self.Width3Label.setText(_translate("evrSnapshot", "CH3 Width", None))
        self.Fine3Label.setText(_translate("evrSnapshot", "CH3 Fine tune", None))

from taurus.qt.qtgui.display import TaurusLabel
from taurus.qt.qtgui.container import TaurusWidget, TaurusGroupBox
